### ISSUE TITLE
type extension for ethers signer for address property

### ISSUE THREAD

**Issue by thegostep** [nomiclabs/hardhat#1001]
> The signers returned by ethers.getSigners() have an address property now. No more await signer.getAddress() everywhere.

This does not seem to be currently accessible in typescript

**Comment by fvictorio** [comment]
Thanks @thegostep. There's a PR for that: https://github.com/nomiclabs/hardhat/pull/951 But it's not quite ready yet.

**Comment by alcuadrado** [comment]
Note that this is not ideal, but should work:

```ts
import { SignerWithAddress } from "@nomiclabs/hardhat-ethers/dist/src/signer-with-address";
import "@nomiclabs/hardhat-ethers";
import { task } from "hardhat/config";

task("accounts", "Prints the list of accounts", async (_, { ethers }) => {
  const signers = await ethers.getSigners();
  printSigners(signers);
});

function printSigners(signers: SignerWithAddress[]) {
  for (const signer of signers) {
    console.log(signer.address);
  }
}

export default {
  solidity: "0.7.3",
};
```

**Comment by mrosendin** [comment]
Hi @fvictorio,

I was having this issue. Fixed with 

```
import { SignerWithAddress } from "@nomiclabs/hardhat-ethers/dist/src/signer-with-address";
```

It seems that #951 was closed, was there a result for this yet, or is it still pending?

**Comment by fvictorio** [comment]
@mrosendin Notice that in the latest versions you can do:

```ts
import { SignerWithAddress } from "@nomiclabs/hardhat-ethers/signers";
```

I think the original issue can be closed, but please re-open if there's something left to do here.
