### ISSUE TITLE
forking xDAI to hardhat network doesn't work

### ISSUE THREAD

**Issue by pythonpete32** [nomiclabs/hardhat#1008]
```❯ npx hardhat node --fork https://rpc.xdaichain.com```
```
Error HH604: Error running JSON-RPC server: Chain with ID 100 not supported
```

**Comment by fvictorio** [comment]
This seems to be a problem with `ethereumjs-common` rejecting the chain id.

**Comment by sirbeefalot** [comment]
I'm having the same problem.

**Comment by pythonpete32** [comment]
> This seems to be a problem with `ethereumjs-common` rejecting the chain id.

so we have to wait for them to fix this?

**Comment by fvictorio** [comment]
Hey @pythonpete32 @sirbeefalot, `hardhat@2.0.9` now supports forking xDAI. Please try it out and let us know if it works for you!
