### ISSUE TITLE
'mixhash' is still missing in block fetched via JSON-RPC from NODE mode

### ISSUE THREAD

**Issue by vicnaum** [nomiclabs/hardhat#1011]
I assumed it was fixed in v2.0.1 (commit 55b8ee517e06770b531807283910961d61e55d83), but I've got a fresh hardhat install from npm (v2.0.3) just today into a new project - and the retrieved Block still doesn't have mixhash parameter.

I'm retrieving it by `web3.eth.getBlock(blocknumber)`

When using the same code with Ganache - everything is okay - block has mixhash.

![image](https://user-images.githubusercontent.com/5636644/98843080-c23eaf80-244a-11eb-8f23-534c28929743.png)

Left is `hardhat node`, right is `ganache`

**Comment by alcuadrado** [comment]
Hey @vicnaum, can you provide more info about what do you use the `minHash` for?

**Comment by vicnaum** [comment]
We're doing a project involving accessing information in blocks with help of blockheader RLPs (RLP is sent to the contract by the caller).
But to verify if block header RLP and data in it is valid, and haven't been tampered - we need to hash it and get the same hash as the block hash.

Without mixHash parameter in block header - we can't form the proper RLP and hash it. Even if it's 0 - it's better than "undefined".
