### ISSUE TITLE
Documentation output of contract artifacts can be very useful

### ISSUE THREAD

**Issue by cedoor** [nomiclabs/hardhat#1017]
Solidity `solc` compiler provides interesting information on the [NetSpec documentation](https://solidity.readthedocs.io/en/v0.7.4/natspec-format.html#documentation-output) of compiled contracts. `userdoc` and `devdoc` fields in the [`contractOutput`](https://github.com/nomiclabs/hardhat/blob/master/packages/hardhat-core/src/internal/artifacts.ts#L447) object could be easily included in the JSON build files, and be used, for example, to create a hardhat plugin to generate documentation similar to [solidity-docgen](https://github.com/OpenZeppelin/solidity-docgen) of OpenZeppelin.

**Comment by alcuadrado** [comment]
Hey @cedoor, this can already be done in hardhat. You just need to customize your compiler settings so that it includes the docs. Plugins can also do this for their users.

**Comment by cedoor** [comment]
You are right! I have only now seen the `settings` field to configure. Thank you very much @alcuadrado, Hardhat is a nice tool.
