### ISSUE TITLE
Is there a feature like "console.log" for the vyper plugin? 

### ISSUE THREAD

**Issue by Thrasymachus01** [nomiclabs/hardhat#1018]
Is there a feature like "console.log" for the vyper plugin? 

So you can do something like console.log("some info") while using vyper?

**Comment by alcuadrado** [comment]
I answered this on Discord already, but I'm repeating this here for any future reader.

There's nothing preventing `console.log` from working in Vyper, as it actually works at the Hardhat Network level. If you manage to the `staticcalls` that are done [here](https://github.com/nomiclabs/hardhat/blob/88ddd68f511653a9c00948a1ac2ddafbce683f24/packages/hardhat-core/console.sol), your logs will be printed.

The problem with Vyper is that there's no code reusing mechanisms, so we can't distribute the same helper methods (i.e. `console.log`) that we do in Solidity.

I'm closing this now, but feel free to ask any further questions.

**Comment by Thrasymachus01** [comment]
Considering how useful this feature is, I think it's at least worth considering collaborating with the Vyper team and adding the console.log function into the Vyper language itself at the compiler level - Maybe it can just be a compiler flag so its optional to include.

**Comment by alcuadrado** [comment]
Yes, I already sent this their way, @Thrasymachus01. Thanks.

**Comment by TeNNoX** [comment]
Relevant discussion in vyper repo:
https://github.com/vyperlang/vyper/discussions/2362
