### ISSUE TITLE
Plugins / tasks cannot dynamically set config.paths.artifacts

### ISSUE THREAD

**Issue by cgewecke** [nomiclabs/hardhat#1030]
(This issue was discovered and diagnosed by @wighawag in [solidity-coverage 573][1])

In the compile task, the location of sources is read from the config object. For example here:
https://github.com/nomiclabs/hardhat/blob/6ffb8baf0ede8c8c73b502bba826b0f8196604b2/packages/hardhat-core/src/builtin-tasks/compile.ts#L112

This allows a task to modify solidity files, store them in a temporary location, and direct the compiler to use them as inputs by changing the value of `config.paths.sources`.

However `paths.artifacts` does not seem configurable in the same way because it's set like this:  

https://github.com/nomiclabs/hardhat/blob/6ffb8baf0ede8c8c73b502bba826b0f8196604b2/packages/hardhat-core/src/internal/core/runtime-environment.ts#L77

This means a task can't write comp. artifacts to a temporary location and direct subsequent tasks to read from there.

solidity-coverage tries to set the sources, artifacts and cache paths, hoping these will be dynamically read.
 
[1]: https://github.com/sc-forks/solidity-coverage/issues/573

**Comment by cgewecke** [comment]
Fwiw, a work-around on my end would be to set the relevant private field on the global `artifacts` object, e.g
```js
artifacts._artifactsPath = tempArtifactsDir;
```

**Comment by fvictorio** [comment]
I guess this makes sense. Just having the same flexibility for the artifacts directory would be enough for your use case?

**Comment by cgewecke** [comment]
Yes. I also try not to corrupt the cache - not sure how that's handled.

 Tbh I only avoid over-writing the contents in these default directories because I worry about whether deleting them is ok - e.g people might have stuff in there they want to persist (or maybe put into source control). Is this the case or is it safe to view those more like temporary 'session' data? 

I realize deleting them slows things down for people but am less concerned about that than destroying something.

**Comment by fvictorio** [comment]
That's a good question. I think it makes sense to have a different, temporary artifacts directory _if that's the only way to do something_.

But I feel that, ideally, that shouldn't be necessary: if they are temporary, maybe the real problem is that there's not an easy way to use them in-memory for the duration of a task without writing them down to disk.

Put another way: do you see a different change that would let you do what you want to do _without_ having to rely on writing temporary artifacts to disk?

**Comment by cgewecke** [comment]
> maybe the real problem is that there's not an easy way to use them in-memory for the duration of a task without writing them down to disk.

Yes! This has occurred to me as well - perhaps there's a way to virtualize the artifacts and have an 'in-memory' mode. And some `save` methods. 

I would actually prefer to stop modifying contracts or saving artifacts at all. Ideally the way forward for coverage is to rely on the EVM tracing engine here for source location data, rather than injecting traceable statements into people's Solidity code. 

If #1035 can be resolved and it becomes clear that the stack trace can follow the execution path everywhere, I think it would make most sense to migrate coverage in that direction. It's a much simpler, faster design.

However, maybe there are other applications which would benefit from virtualized artifacts, not sure.

**Comment by cgewecke** [comment]
One application that has a legitimate reason for modifying Solidity files is a mutation tester. e.g 

https://github.com/JoranHonig/vertigo

**Comment by alcuadrado** [comment]
Now that Hardhat 2.0.4 was released, the cache is aware of file modifications, so there's no need to use a different artifacts folder. You can override this task and preprocess/instrument the files there.

**Comment by cgewecke** [comment]
Ok perfect, thanks @alcuadrado.

**Comment by wighawag** [comment]
Should we not leave that issue open ?
In my opinion, we should at least document which config are supposed to be dynamic (and that you can thus modify at any time by plugin) and which are supposed to be static, but ideally they should all behave the same.

Also for that particular case (artifacts var) there might be use case for updating the value later

**Comment by alcuadrado** [comment]
I created an issue about this, @wighawag
