### ISSUE TITLE
Is Hardhat support Contract at specific address?

### ISSUE THREAD

**Issue by shangpit** [nomiclabs/hardhat#1031]
```
contract("BitgamessToken", accounts => {
  it("Mainnet", async () => {
    const usdt = await USDT.at("0xdac17f958d2ee523a2206206994597c13d831ec7");
    const allowance = await usdt.allowance('0x428b2aBbc63f0F2fEb1D79b76f861a06a1bf7579', accounts[0])
  });
}
```

**Comment by fvictorio** [comment]
What plugins are you using? Where does `USDT` come from?

**Comment by shangpit** [comment]
Imagine, i want to debug mainnet USDT, and want to check balance of an address in real USDT ERC20...

**Comment by shangpit** [comment]
with truffle i can get the contract instance by USDT.at(address), or ERC20.at(address)

**Comment by alcuadrado** [comment]
If you use the `hardaht-truffle5` you can do it in the exact same way.

**Comment by fvictorio** [comment]
Preemptively closing this issue, but please re-open if that doesn't answer your question!
