### ISSUE TITLE
[hardhat-etherscan] Verify right after deployment results in : `Unable to locate ContractCode at ...`

### ISSUE THREAD

**Issue by krasi-georgiev** [nomiclabs/hardhat#1032]
The strange thing is that regardless of the error the contract is verified. I assume there needs to be some retry logic. I tried adding a delay of 5sec after the deployment(thinking it might need time to populate on the api) but didn't help

To replicate run the following on 
https://github.com/tellor-io/lens/tree/070a2495ce3919ac4cda15f1b1ef422ae29c0f61

```
hardhat deploy --master-address 0xfe41cb708cd98c5b20423433309e55b53f79134a
```

**Comment by fvictorio** [comment]
Maybe five seconds isn't long enough. Something you could try is:

```
await contract.deployTransaction.wait(2)
```

Which will wait for two confirmations. If that doesn't work, I would try with a way higher number, like 10. If that doesn't work either, then there might be a bug somewhere, I guess.

**Comment by krasi-georgiev** [comment]
yep all good, thanks for the pointer! appreciated!
