### ISSUE TITLE
Sample deploy script fails

### ISSUE THREAD

**Issue by fritzschoff** [nomiclabs/hardhat#1047]
Hey, if I want to deploy the Greeter contract to kovan I get the following error:
`ProviderError: The execution failed due to an exception.`
It fails when the contract calls the deploy function.
In my config I got that:
```
   kovan: {
      url: 'https://kovan.infura.io/v3/APIKEY',
      accounts: [`PRIVATE KEY`]
    }
```
Any idea what might be the issue? It could be the infura node?

**Comment by fvictorio** [comment]
Cannot reproduce, works for me. Do you mind posting your full `hardhat.config.js`, and also telling us if there's something else you changed after initializing the sample project?

**Comment by fritzschoff** [comment]
require("@nomiclabs/hardhat-waffle");

module.exports = {
  solidity: "0.6.6",
  networks: {
    kovan: {
      url: 'https://kovan.infura.io/v3/APIKEY',
      accounts: [`PRIVATE KEY`]
    }
  }
};

**Comment by fvictorio** [comment]
Not necessarily. If you modified the sample contract, you might have, for example, an error in the constructor that would cause this error.

Another thing you can check: run the deploy in the hardhat network (meaning: run your script without any `--network`) and see if you get the same error. If you do, it's probably an error in your contract.

**Comment by fritzschoff** [comment]
I didn't put the `--network` flag and it gave me a proper error what went wrong. Was something in the constructor. Thanks for the help!
