### ISSUE TITLE
Hardhat network can contain an url field, confusing the provider initialization

### ISSUE THREAD

**Issue by alcuadrado** [nomiclabs/hardhat#1051]
If an user adds an `url` field to the Hardhat Network config, we don't detect it during the config validation, but rather leave it there.

Then, when we initialize the network provider, Hardhat gets confused and treats it as an HTTP network config.

This should help reproduce it:

```js
networks: {
    hardhat: {
      url: "valid node url",
    },
  },
```

**Comment by shark0der** [comment]
I have to mention that the issue I was facing is that when passing `undefined` as the value, the impersionation feature would be broken but only, at the second call, first would work (very weird, I know).

I was literally passing this: ` url: process.env.TEST_ENV_FORK || undefined`, and the env var was missing.
