### ISSUE TITLE
View function is returning the entire tx hash instead of just the return

### ISSUE THREAD

**Issue by wschwab** [nomiclabs/hardhat#1060]
Hi! I'm testing a contract using Hardhat's Waffle implementation, and I'm running into something weird. The contract is an ERC20 contract, and inherits from the [OpenZeppelin Snapshot contract](https://docs.openzeppelin.com/contracts/3.x/api/token/erc20#ERC20Snapshot), among others. Here's part of a test I wrote to check the [`snapshot()`](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/ERC20Snapshot.sol#L81 function:
```javascript
it("Admin can snapshot", async () => {
          const id = await Contract.connect(admin).callStatic.snapshot();
          expect(await Contract.totalSupplyAt(id))
            .to.equal(0);
        });
```
Expected behavior would be that `id` would be the `uint256` returned by the [`snapshot`](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/ERC20Snapshot.sol#L81) function, and then the `expect` would work by passing in the id of the snapshot.

Here's the error I get:
```
ERC20:ERC20Snapshot
         functions
           snapshot()
             Admin can snapshot:
     Error: invalid BigNumber value (argument="value", value={"hash":"0xbead2cc40d8a9501bdc37ad07f9deb14bfdb0a6fcbaa54aa3406d926fe601a91","blockHash":"0xc53ebe68f8f6bc848dd999339a5c00093357cb5cda6129fb87be01d83734df41","blockNumber":172,"transactionIndex":0,"confirmations":1,"from":"0x70997970C51812dc3A010C7d01b50e0d17dc79C8","gasPrice":{"type":"BigNumber","hex":"0x01dcd65000"},"gasLimit":{"type":"BigNumber","hex":"0x820638"},"to":"0xBa3e08b4753E68952031102518379ED2fDADcA30","value":{"type":"BigNumber","hex":"0x00"},"nonce":49,"data":"0x9711715a","r":"0x11c5ec48b7adcc75b19b9404558585114242e468a9a668f9ef06c568b7584f45","s":"0xca9a526bab51dfda47ad1cce6123008f6b2f4aefceff26d4187a278a3deb5c58","v":62709,"creates":null,"chainId":31337}, code=INVALID_ARGUMENT, version=bignumber/5.0.8)
      at Logger.makeError (node_modules/@ethersproject/logger/src.ts/index.ts:205:28)
      at Logger.throwError (node_modules/@ethersproject/logger/src.ts/index.ts:217:20)
      at Logger.throwArgumentError (node_modules/@ethersproject/logger/src.ts/index.ts:221:21)
      at Function.BigNumber.from (node_modules/@ethersproject/bignumber/src.ts/bignumber.ts:268:23)
      at NumberCoder.encode (node_modules/@ethersproject/abi/src.ts/coders/number.ts:21:27)
      at node_modules/@ethersproject/abi/src.ts/coders/array.ts:71:19
      at Array.forEach (<anonymous>)
      at Object.pack (node_modules/@ethersproject/abi/src.ts/coders/array.ts:54:12)
      at TupleCoder.encode (node_modules/@ethersproject/abi/src.ts/coders/tuple.ts:23:16)
      at AbiCoder.encode (node_modules/@ethersproject/abi/src.ts/abi-coder.ts:106:15)
```
It would seem to me from this that `id` is in fact storing the entire tx object from calling `snapshot`, while `totalSupplyAt` is expecting a BigNumber. I don't know why this would be, though. 

Any ideas?

Thanks!

**Comment by wschwab** [comment]
So I've figured out a couple of issues with my code above: it shouldn't be making a `staticCall` to `snapshot`, as `snapshot` isn't a `view` or `pure` function, which apparently is also why it's returning the tx log instead of just the `uint`. If there was some way to decode the event out of the log, the `snapshot` function does emit an event.

Unfortunately, in Ethers an Interface is used to decode logs, and takes the ABI as an argument. I'm having trouble figuring out how to access the Interface from inside Hardhat, and having an equally hard time importing an ABI. In any event, I suppose a different way of trying to solve the above problem is how to decode a tx log the Hardhat way.

Thanks again!

**Comment by fvictorio** [comment]
Closing this since these are mostly ethers questions. I will try to answer what I can though.

> it shouldn't be making a `staticCall` to `snapshot`, as `snapshot` isn't a `view` or `pure` function

`staticCall` is precisely used when a function is not `view` or `pure` but you want to call it like it is. This is useful for example to obtain the value it returns, which you can't do if you call a non-view function without static (this calls the method and returns a tx object, which is what I suspect happened to you in the first error).

> I'm having trouble figuring out how to access the Interface from inside Hardhat

You can do this:

```
const { abi } = await artifacts.readArtifact("YourContractName")
```

**Comment by fvictorio** [comment]
You can join our [discord server](https://hardhat.org/discord) if you have more questions related to Hardhat. If you have questions related to ethers, I suggest you open an issue on their issue tracker (they don't have an official forum/chat, as far as I know).
