### ISSUE TITLE
non-deterministic test results

### ISSUE THREAD

**Issue by thegostep** [nomiclabs/hardhat#1079]
As mentioned in discord, I am getting non-deterministic test results on hardhat tests.

Codebase is private but here is a description of the setup:
- errors seem to always occur in tests that use `ethers.provider.send('evm_increaseTime', [seconds])` in the `beforeEach()` setup and are testing for time dependent logic (in the case below, testing for time based token vesting)
- test file is pretty massive (3000 lines)
- isolating tests with .only() does not improve accuracy

![image](https://user-images.githubusercontent.com/15959632/100896456-ec6e1500-34be-11eb-83d2-d29966c76cd2.png)
![image](https://user-images.githubusercontent.com/15959632/100896481-f09a3280-34be-11eb-8d5e-8222f81b8915.png)
![image](https://user-images.githubusercontent.com/15959632/100896837-57b7e700-34bf-11eb-85a6-06bd3787311d.png)
![image](https://user-images.githubusercontent.com/15959632/100897002-86ce5880-34bf-11eb-80da-ae1a2f272c89.png)

**Comment by fvictorio** [comment]
Thanks @thegostep. This might be enough to reproduce the issue, but I don't think we'll have time soon to look into it. If you can create a minimal working example that reproduces this problem, chances are we can work on it sooner.

**Comment by thegostep** [comment]
Here is a test file to reproduce
```ts
import { expect } from 'chai'
import { ethers } from 'hardhat'

describe('TimeTrial', async () => {
  async function getTimestamp() {
    return (await ethers.provider.getBlock('latest')).timestamp
  }

  async function increaseTime(seconds: number) {
    const startTime = await getTimestamp()

    await ethers.provider.send('evm_increaseTime', [seconds - 1])
    await ethers.provider.send('evm_mine', [])

    const endTime = await getTimestamp()
    if (startTime + seconds - 1 !== endTime) {
      expect(startTime + seconds - 1).to.be.eq(endTime)
    }
  }

  async function testTime(quantity: number) {
    for (let index = 0; index < quantity; index++) {
      it('should increase time correctly', async () => {
        const time = parseInt((Math.random() * 90 * 24 * 60 * 60).toString())
        await increaseTime(time)
      })
    }
  }
  await testTime(1000)
})
```

**Comment by gonzalpetraglia** [comment]
Hey guys. I am working on a plugin to manipulate time in tests and might have encountered the same issue, would love to send a PR but I would like to make sure the behaviour you are expecting is the same as I do.


IMO the correct behaviour for this should be that increaseTime sets the difference in the timestamp between the latest block and the next one.

This, for example results in the fact that if you call increaseTime multiple times before mining, only the last one matters, which might be undesirable, so I am a liitle bit dubious. BTW, I think ganache's description implies a different thing from what I am saying.

What do you think? @fvictorio

**Comment by fvictorio** [comment]
@gonzalpetraglia ideally, before doing anything around this, we should have a minimal reproduction example of this error, so that we understand what's going on before thinking about a fix. Do you think you could create one?

**Comment by gonzalpetraglia** [comment]
Yeah, but what do you think the correct behaviour should be? I haven't found unambiguous doc about it.

**Comment by fvictorio** [comment]
You mean the expected behavior if `increaseTime` is called multiple times? I'm not really sure. I think I would just use the latest one 

(cc @alcuadrado)

**Comment by gonzalpetraglia** [comment]
Yeah, thats what I was thinking but I think thats not case from what I saw in the code.

**Comment by fvictorio** [comment]
> Yeah, thats what I was thinking but I think thats not case from what I saw in the code.

Hmm, if that's the current behavior we should either document it (and add tests for that edge case, if there aren't already) or consider it a bug and fix it ([but people might be already using this "bug"](https://xkcd.com/1172/)).

**Comment by alcuadrado** [comment]
I think we should document it. Changing something like that would be too risky. Also, the name to me indicates that it increases the time further each time you call it.

To override a time increase you can use `hardhat_setNextBlockTimestamp`.

**Comment by gonzalpetraglia** [comment]
Ok, then I will test it, document it that and leave it as is. 

BTW, what do you think of adding a new feature to set that delta between the previous block and the next one?

**Comment by gonzalpetraglia** [comment]
Hopefully the previous PRs solved the 'issue'.


I will start a new issue with a new discussion for that other method, if you think thats OK.

**Comment by fvictorio** [comment]
> BTW, what do you think of adding a new feature to set that delta between the previous block and the next one?

I don't mind discussing the idea, but my first reaction is that that is trivially done with a combination of `getBlockByNumber("latest")` and `setNextBlockTimestamp`, so maybe it doesn't make sense to add another method for time manipulation.

**Comment by gpetraglia** [comment]
Yeah, but the thing is that IMO it is  more common to use increaseTime than setting an exact timestamp. Though, like you and I said, it probably would make more sense to have it on a lib. I would tag you when I upload it so you can have a look at it.

**Comment by gpetraglia** [comment]
There is still work to do, but here is an MVP https://github.com/atixlabs/hardhat-time-n-mine

**Comment by gpetraglia** [comment]
I think this can be closed now. What do you think @thegostep ?
