### ISSUE TITLE
Inconsistent behaviour during mainnet forking tests (Unspecified tx error)

### ISSUE THREAD

**Issue by alsco77** [nomiclabs/hardhat#1105]
### Issue description

I am running a test script using mainnet fork, and using alchemy as per instructions. However, I am getting inconsistent behaviour when running the same script multiple times. Given that it is pinned to a specific blockNumber, I can't see a reason for this happening. The failures happen when calling functions on the [mUSD contract](https://etherscan.io/address/0xe2f2a5C287993345a840Db3B0845fbC70f5935a5) which has a number of external dependencies (lending platforms etc).

Additional info: time has been increased 1 week.

**The error happens around 30% of the time and I cannot pin down any particular reproduction issues.. so just bringing this to the developers attention, not expecting a fix.**

#### Config

```
require("hardhat-gas-reporter");
require("@nomiclabs/hardhat-waffle");
require("@nomiclabs/hardhat-ethers");
require("@tenderly/hardhat-tenderly");
require("hardhat-typechain");

require("ts-node/register");

...

  hardhat: {
    forking: {
      url:
        "https://eth-mainnet.alchemyapi.io/v2/xxx",
      blockNumber: 11451451,
    },
  },
```

#### Error

```
Error: Transaction reverted without a reason
    at <UnrecognizedContract>.<unknown> (0x0...)
    at <UnrecognizedContract>.<unknown> (0x0...)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at EthModule._sendTransactionAndReturnHash (.../hardhat-network/provider/modules/eth.ts:1303:9)
    at HardhatNetworkProvider.request (.../hardhat-network/provider/provider.ts:102:18)
    at EthersProviderWrapper.send
    ```

**Comment by alcuadrado** [comment]
Hi @alsco77, thanks for opening this issue.

Can you tell us which version of Hardhat you are using.

**Comment by alsco77** [comment]
Hey @alcuadrado - i'm on `2.0.5`

**Comment by alcuadrado** [comment]
Can you try running those tests with `hardhat@rc`, please? We are releasing it this week.

**Comment by alsco77** [comment]
@alcuadrado I just upgraded to `rc` and ran the tests 5 times without fail, seems to have done the job :+1:

**Comment by fvictorio** [comment]
Glad to hear that, @alsco77! Please re-open if you run into this issue again.
