### ISSUE TITLE
signer.signTypedData is not defined.

### ISSUE THREAD

**Issue by Skyge** [nomiclabs/hardhat#1108]
I am trying to write a test case for `permit`, that is signing the typed data value with types data structure for domain using the EIP - 712 specification.

I am using like below:
```js
const [owner, ...accounts] = await ethers.getSigners();
const domain = {
    name: 'Ether Mail',
    version: '1',
    chainId: 1,
    verifyingContract: '0xCcCCccccCCCCcCCCCCCcCcCccCcCCCcCcccccccC'
};

// The named list of all type definitions
const types = {
    Person: [
        { name: 'name', type: 'string' },
        { name: 'wallet', type: 'address' }
    ],
    Mail: [
        { name: 'from', type: 'Person' },
        { name: 'to', type: 'Person' },
        { name: 'contents', type: 'string' }
    ]
};

// The data to sign
const value = {
    from: {
        name: 'Cow',
        wallet: '0xCD2a3d9F938E13CD947Ec05AbC7FE734Df8DD826'
    },
    to: {
        name: 'Bob',
        wallet: '0xbBbBBBBbbBBBbbbBbbBbbbbBBbBbbbbBbBbbBBbB'
    },
    contents: 'Hello, Bob!'
};

const signature = await owner.signTypedData(domain, types, value);
```

My ethers version is `5.0.21`, hardhat is `2.0.5`,  but I got the error:
```
TypeError: owner.signTypedData is not a function
```

**Comment by fvictorio** [comment]
Hey @Skyge, the method seems to be `_signTypedData` according to the [docs](https://docs.ethers.io/v5/single-page/#/v5/api/signer/-%23-Signer-signTypedData)

That being said, we don't expose that method in our wrapped signer. I'm not sure if we should do it or if we should wait until that method is stable.

As a workaround, you can access the underlying signer with `._signer`, so this should work:

```js
const signature = await owner._signer._signTypedData(domain, types, value);
```

**Comment by Skyge** [comment]
Sorry for replaying so late, just had a try, but got an error:
```js
MethodNotFoundError: Method eth_signTypedData_v4 not found
  at EthModule.processRequest (node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:275:11)
  at HardhatNetworkProvider._send (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:224:31)
  at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by fvictorio** [comment]
Oh, I see. This might be a problem on our side, but I'm not sure about the solution. We'll get back to you, thanks @Skyge!

**Comment by TimTinkers** [comment]
Any updates on this, @fvictorio? I'm experiencing the same issue when attempting to get access to `_signTypedData`.

**Comment by TimTinkers** [comment]
It looks like ethers uses `eth_signTypedData_v4`. Perhaps related? https://github.com/trufflesuite/ganache-core/pull/607

**Comment by scnale** [comment]
#1189 adds the missing method to Hardhat Network. That doesn't solve this issue entirely but I'm linking it here since it's related.

**Comment by scnale** [comment]
There's another workaround that I think is cleaner around this missing method:

```js
const signer = ethers.provider.getSigner(0);
await signer._signTypedData(...args);
```
