### ISSUE TITLE
Tests never exit if listeners are still listening

### ISSUE THREAD

**Issue by bohendo** [nomiclabs/hardhat#1110]
I have a test suite that runs to completion with no failures but never exits.

## Reproduction

NOT a minimal reproduction, I'm in the process of trimming out tests to figure out the smallest possible repro but this issue is kind of race-condition-ish so it's not super easy to isolate.

```
git clone https://github.com/connext/vector.git
cd vector
git checkout d36c5713
cd modules/contracts
npm install
npm run build
npm test
```

The *only* suite of our tests that appears to be affected is `modules/contracts/src.ts/services/ethService.spec.ts`.
I have the issue repro'd reliably at the above commit by running 4 relatively simple tests out of these suite.
It is not possible to repro this problem by running a single or pair of tests. 3 tests will repro the issue only intermittently.

## Problem

In the past, I've encountered this problem when the following code was run but the event was never detected:
```
    channelFactory.once(channelFactory.filters.ChannelCreation(), data => {
      this.log.info({ method, data: JSON.stringify(data) }, "Caught channel created event");
    });
```
In this case, we have a listener that hangs around indefinitely & this appears to prevent `hardhat test` from exiting.

In the current issue (see above repro instructions), I've checked all obvious `.on(` and `.once(` calls & haven't found any that are stuck listening. I'm stuck now & unsure how to get the debugging info I need.

## Solution

This problem isn't specific to hardhat, it appears that mocha needs to deal with it too. Mocha contains a flag:
```
  --exit                     Force Mocha to quit after tests complete  [boolean]
```
I've actually run into similar issues with mocha and this is a good way to get past it temporarily before doing a deeper dive into which listeners aren't getting cleaned up properly.

If it's possible to provide warnings re whether listeners or other background threads are preventing hardhat tests from exiting, that would be great.

If it's possible to provide into re *which* listeners are preventing hardhat tests from exiting, that would be even better.

**Comment by bohendo** [comment]
Update: I've refactored out all explicit `on` and `once` calls from our contracts code & this made no difference. Whatever's preventing hardhat tests from exiting must be an implicit/internal listener..

**Comment by bohendo** [comment]
Workaround: use mocha & pass it the `--exit` flag directly. The test script defined by our package.json is:
```
    "test": "mocha --exit --require ts-node/register --require hardhat/register --timeout 60000 'src.ts/**/*.spec.ts'"
```
This has the added bonus of also allowing us to provide `--forbid-only` in automated tests.

**Comment by fvictorio** [comment]
Hey @bohendo, I looked a little into this. I didn't find the problem, but maybe what I did can help you.

(First: your instructions have a little issue, there are two compiler errors, but I `any`ed them out. I don't think this is relevant though.)

I installed [wtfnode](https://www.npmjs.com/package/wtfnode) and then I created a `wtf.js` module with just `require("wtfnode")`. Then I changed the test script to include this module before anything else. That is, I added a `--register src.ts/wtf.js` at the beginning of the mocha command, before the other `--register`s.

Then in `src.ts/services/ethService.spec.ts` I imported `wtfnode` and in the test I added this:

```ts
  after(function () {
    setTimeout(() => {
      wtf.dump()
    }, 3000);
  })
```

Then I ran the tests and (after some tries) I got this:

```
- File descriptors: (note: stdio always exists)
  - fd 2 (tty) (stdio)
  - fd 1 (tty) (stdio)
- Timers:
  - (4000 ~ 4 s) (anonymous) @ /vector/modules/contracts/node_modules/ethers/node_modules/@ethersproject/providers/lib/base-provider.js:814
  - (3000 ~ 3 s) (anonymous) @ /vector/modules/contracts/src.ts/services/ethService.spec.ts:32
- Intervals:
  - (4000 ~ 4 s) bound  @ /vector/modules/contracts/node_modules/ethers/node_modules/@ethersproject/providers/lib/base-provider.js:808
```

The first two can be ignored, and the 3s one is the one I added, which doesn't matter either.

The other two are ethers providers that do some polling.

That's what I got! It's not much, but maybe it helps you investigate further.

**Comment by fvictorio** [comment]
I'm thinking about what to do with this issue. I don't think it's a bug in Hardhat: my guess is that it's something about your setup. That being said, I understand how this experience is not ideal. But I'm not sure if it's something on our side or on mocha's side.

> If it's possible to provide warnings re whether listeners or other background threads are preventing hardhat tests from exiting, that would be great.
> 
> If it's possible to provide into re which listeners are preventing hardhat tests from exiting, that would be even better.

I think this is technically possible but, again, I don't know if it's Hardhat's responsibility. I'm inclined to mark this as a feature request and, if more people run into this problem, evaluate what to do.

@alcuadrado what do you think?
