### ISSUE TITLE
hardhat_reset set custom gas and blockGasLimit

### ISSUE THREAD

**Issue by steffenix** [nomiclabs/hardhat#1115]
I am using coverage and  because of that I have  really big contracts.
I would like to be able to set the gas options on reset

**Comment by fvictorio** [comment]
Hi @steffenix. Why would you need it on reset? Can't you just set it in the config?

**Comment by cgewecke** [comment]
@fvictorio 

Do you know of a public repo using reset I could investigate this issue with? 

Think it's possible solidity-coverage does not handle resets correctly when Ethers is the provider.  

(Open question at [solidity-coverage 574][1])

[1]: https://github.com/sc-forks/solidity-coverage/issues/574

**Comment by steffenix** [comment]
I have set the limit to really high in the config and that's working. We could close this issue.

**Comment by cgewecke** [comment]
@steffenix 

Is this only necessary when you use hardhat reset? e.g after reset the config settings solidity-coverage starts with are lost?

**Comment by steffenix** [comment]
I have stopped using reset because it was also causing issues with coverage. I have used evm_snapshots instead.

**Comment by adjisb** [comment]
I'm having problems with reset and solidity-coverage too. 
Here an example: https://github.com/adjisb/hardhat-deploy-test/tree/6e4e1b1c9107bbd8396522f130345b3278dcae19

My problem with snapshots is how to take a snapshot of the initial state of the Evm ?
