### ISSUE TITLE
Using smart contracts from another NPM/Yarn project

### ISSUE THREAD

**Issue by vporton** [nomiclabs/hardhat#1129]
I have a Truffle project with some smart contracts and another project (I could use either Truffle or HardHat, now I use HardHat) than depends on it.

I want the second project to be able to compile and use (some of) smart contracts of the first project, as if they were contracts in the second projects itself.

How to do this?

Note: I do not want just to copy the `contracts/` folder from another project to make tracking changes (such as security audits) in the first project easier.

**Comment by fvictorio** [comment]
The easiest way is to publish it in npm, and then include it as a dependency in your project. Does that work for you?

**Comment by vporton** [comment]
> The easiest way is to publish it in npm, and then include it as a dependency in your project. Does that work for you?

It would not work, but additionally adding an `import.sol` file that just imports all the contracts I need seems to work.

**Comment by fvictorio** [comment]
@vporton glad to hear that. Closing this issue for now.
