### ISSUE TITLE
HardHat 2.0.6 does not compile legit contracts (not a Solidity bug)

### ISSUE THREAD

**Issue by vporton** [nomiclabs/hardhat#1130]
https://github.com/vporton/hardhat-solc-versions-bug

```
$ npx hardhat compile
Error HH606: The project cannot be compiled, see reasons below.

The Solidity version pragma statement in these files don't match any of the configured compilers in your config. Change the pragma or configure additional compiler versions in your hardhat config.

  * abdk-libraries-solidity/ABDKMath64x64.sol (^0.5.0)

These files import other files that use a different and incompatible version of Solidity:

  * contracts/import.sol (^0.7.5) imports abdk-libraries-solidity/ABDKMath64x64.sol (^0.5.0)

To learn more, run the command again with --verbose

Read about compiler configuration at https://hardhat.org/config


For more info go to https://hardhat.org/HH606 or run Hardhat with --show-stack-traces
```

**Comment by fvictorio** [comment]
Thanks @vporton. I think the underlying problem is https://github.com/nomiclabs/hardhat/issues/1089, since the imported contracts has a `pragma solidity ^0.5.0 || ^0.6.0 || ^0.7.0;`

**Comment by vporton** [comment]
Any workaround? or just use OpenZeppelin instead of HardHat?

**Comment by fvictorio** [comment]
A workaround that could be to use `>=0.5.0` instead of `^0.7.5` in the contract that imports that dependency. I *think* that should fix it. It's not a nice solution though, we'll try to release a proper fix for this as soon as possible.

**Comment by sisco0** [comment]
Have a good day, I have been doing some tests.
When using the `||` operator the tests seems to run correctly when added to
`packages/hardhat-core/test/internal/solidity/compiler/index.ts`
compilation tests, trying to replicate the error right now.

**Comment by sisco0** [comment]
I added my comments to the PR in order to ensure that `||` operators are properly parsed.
