### ISSUE TITLE
hardhat/console.sol v2.0.6 cannot work with Solidity 0.8.0

### ISSUE THREAD

**Issue by AuroraLantean** [nomiclabs/hardhat#1132]
The Solidity version pragma statement in these files don't match any of the configured compilers in your config. Change the pragma or configure additional compiler versions in your hardhat config.
hardhat/console.sol (>=0.4.22 <0.8.0)
Please help. Thank you

**Comment by sisco0** [comment]
I think that this issue is related to the `solc` (_SOLidity Compiler_) used, which version is defined statically as 0.7.3 at the line below
https://github.com/nomiclabs/hardhat/blob/97c5ee3815e9f5dc57171cea531f5669955486ab/packages/hardhat-core/package.json#L115

As it could be seen the package is currently at version 0.8.0 in the _NPM Repository_ https://www.npmjs.com/package/solc

**Comment by fvictorio** [comment]
Thanks @AuroraLantean. Yes, we need to make sure that `console.sol` works fine with solc 0.8 and change its pragma to use `<0.9.0` if that's the case.

**Comment by ksgebrekirstos98** [comment]
What is the status on this @fvictorio ? I'm still getting the same errors
`The Solidity version pragma statement in these files don't match any of the configured compilers in your config. Change the pragma or configure additional compiler versions in your hardhat config.`

I'm using Solidity v^0.8.0

**Comment by alcuadrado** [comment]
This was fixed long ago. Please make sure you are running the latest version of Hardhat and double check your compilers settings.

**Comment by ksgebrekirstos98** [comment]
Turns out I was using an older version of Hardhat:
"hardhat": "^2.0.4"

I upgraded to:
"hardhat": "^2.4.1"

and that solved it.

Thanks @alcuadrado :)

**Comment by cryptousic** [comment]
Getting the same error
I am using ^0.8.0 - this doesn't seem to be fixed because my hardhat version is ^2.8.3
 * contracts/TweetPortal.sol (^0.8.0)
  * hardhat/console.sol (>=0.4.22 <0.9.0)
  * contracts/users/UserStorage.sol (^0.8.0)
  * contracts/tweets/TweetStorage.sol (^0.8.0)

**Comment by cryptousic** [comment]
For anyone else wondering my solc compiler was ^0.8.0 and I fixed it by commenting console.log imports for all my Contracts, changed config and each solc file to 0.8.4 and then uncommenting console.log imports and compiling
