### ISSUE TITLE
Replace ethereumjs-account by Util.Account from ethereumjs-util

### ISSUE THREAD

**Issue by sisco0** [nomiclabs/hardhat#1136]
When running `yarn test` at the root folder, this warning appears:

```
 | npm WARN deprecated ethereumjs-account@3.0.0: Please use Util.Account class found on package ethereumjs-util@^7.0.6 https://github.com/ethereumjs/ethereumjs-util/releases/tag/v7.0.6
```

Maybe we should take into account this warning and replace by using `Util.Account`, the code should be replaced at all instances found at https://github.com/nomiclabs/hardhat/search?q=ethereumjs-account.

**Comment by fvictorio** [comment]
Closing this since I don't think we use `ethereumjs-account` directly anywhere?
