### ISSUE TITLE
Ethers module not found in hardhat but still compiles

### ISSUE THREAD

**Issue by platocrat** [nomiclabs/hardhat#1137]
After converting the provided `sample-test.js` to TypeScript, VSCode marks the `ethers` library as missing when importing it ES6-style from `hardhat`:

```
Module '"../node_modules/hardhat/internal/lib/hardhat-lib"' has no exported member 'ethers'.ts(2305)
```

This is what my `sample-test.ts` file looks like.
```ts
import { expect } from "chai"
import { ethers } from "hardhat"

describe("Greeter", function () {
  it("Should return the new greeting once it's changed", async function () {
    const Greeter = await ethers.getContractFactory("Greeter")
    const greeter = await Greeter.deploy("Hello, world!")

    await greeter.deployed()
    expect(await greeter.greet()).to.equal("Hello, world!")

    await greeter.setGreeting("Hola, mundo!")
    expect(await greeter.greet()).to.equal("Hola, mundo!")
  })
})

```

And here is how VSCode marks it red-as-missing:

<img width="798" alt="Screen Shot 2020-12-27 at 9 18 41 PM" src="https://user-images.githubusercontent.com/37757724/103187200-1a116880-4889-11eb-8dd8-c858cbef49cf.png">

Nonetheless, this sample script still compiles. 
So, I'm wondering what the issue is, and if this can be resolved so I don't have to write a note to myself about this red-underlined text 😅

**Comment by Tonyhaenn** [comment]
Same thing was happening for me — I added the following line to my `hardhat.config.ts`
`import "@nomiclabs/hardhat-ethers";` and that cleared up the error.
