### ISSUE TITLE
hardhat node task bug when defaultNetwork other than hardhat/empty

### ISSUE THREAD

**Issue by gitpusha** [nomiclabs/hardhat#1139]
I noticed the following bugs while using `hardhat-node`: 

- `npx hardhat node --network localhost` :

![image](https://user-images.githubusercontent.com/36712489/103292879-08e26c00-49ef-11eb-83a9-8087c5987388.png)

Weirdly the error changes when `localhost` is the `defaultNetwork` - I would have expected the same error. 

- defaultNetwork: "localhost" 
  - `npx hardhat node`

![image](https://user-images.githubusercontent.com/36712489/103292979-3e875500-49ef-11eb-8303-ce9a5b90a5c7.png)

==> It only seems to work if --network hardhat is passed or if defaultNetwork is empty / "hardhat"

Now the more serious bugs: 

- defaultNetwork: "ropsten" 
  - `npx hardhat node` 
  
![image](https://user-images.githubusercontent.com/36712489/103293223-bbb2ca00-49ef-11eb-827d-f3907609806b.png)

As you can see I am using `hardhat-deploy` which overrides the `hardhat node` task to run deploy scripts on start. I accidentally had my `defaultNetwork:` set to `ropsten` and somehow the `hardhat node` task did not fail and it deployed contracts to ropsten. 

**I would have expected `hardhat node` to fail with a Hardhat error similar to** `Error HH605: Unsupported network for JSON-RPC server.`

This works when `--network ropsten` is passed as a flag:

![image](https://user-images.githubusercontent.com/36712489/103293723-b3a75a00-49f0-11eb-8e3b-096810bee84c.png)

**But apparently not if the network is configured as defaultNetwork.**

**Comment by fvictorio** [comment]
Hi @gitpusha. Sorry for not responding before!

I can't reproduce this without `hardhat-deploy`, so I guess the issue is there? Please re-open if you think there's something we can do on our side.

**Comment by gitpusha** [comment]
I think this was an issue with hardhatNode that got fixed!
