### ISSUE TITLE
Invoking a method of a contract created by getContractAt returns "call revert exception"

### ISSUE THREAD

**Issue by aboutlo** [nomiclabs/hardhat#1142]
I'm trying to use in a task `getContractAt`

```ts
import Greeter from './artifacts/contracts/Greeter.sol/Greeter.json'

task('greet', "prints  a message")
  .setAction(async (args, {ethers}) => {
    const greeter = await ethers.getContractAt(Greeter.abi, GREETER)
    const message =  await greeter.greet()
    console.log({ message })
  })
```

this throws:
```
{ Error: call revert exception (method="greet()", errorSignature=null, errorArgs=[null], reason=null, code=CALL_EXCEPTION, version=abi/5.0.9)
    at Logger.makeError (node_modules/@ethersproject/logger/src.ts/index.ts:205:28)
    at Logger.throwError (node_modules/@ethersproject/logger/src.ts/index.ts:217:20)
    at Interface.decodeFunctionResult (node_modules/@ethersproject/abi/src.ts/interface.ts:326:23)
    at Contract.<anonymous> (node_modules/@ethersproject/contracts/src.ts/index.ts:309:44)
    at step (node_modules/@ethersproject/contracts/lib/index.js:46:23)
    at Object.next (node_modules/@ethersproject/contracts/lib/index.js:27:53)
    at fulfilled (node_modules/@ethersproject/contracts/lib/index.js:18:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  reason: null,
  code: 'CALL_EXCEPTION',
  method: 'greet()',
  errorSignature: null,
  errorArgs: [ null ],
  address: '0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0',
  args: [],
  transaction:
   { data: '0xcfae3217',
     to: '0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0',
     from: '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266',
     gasLimit: BigNumber { _hex: '0x820638', _isBigNumber: true } } }
 ```
 
 The same code works in a script where I deploy the smart contract:
 
 ```ts
 const Greeter = await ethers.getContractFactory('Greeter')
 const greeter = await Greeter.deploy('Hi')
  console.log(
    `Deployed contract Greeter on "${network.name}" as "${greeter.address}"`
  )
  const greeterInstance = await ethers.getContractAt('Greeter', greeter.address)
  const message  = await greeterInstance.greet()
  console.log({message})
 ```
 
Am I missing something?

**Comment by alcuadrado** [comment]
Hey @aboutlo, thanks for reporting this issue.

I'm afraid there's lots of info missing to be able to tell what's going on. Can you add the steps to reproduce it? Or ideally, a link to a repo to do it? Thanks!

**Comment by aboutlo** [comment]
Hey @alcuadrado, I figured out my issue. Basically, I was deploying using `npx hardhat run --network hardhat scripts/deployments/001_deploy.ts` rather than `npx hardhat run --network localhost scripts/deployments/001_deploy.ts` so the error was right the smart contract wasn't deployed on my local node, but it was temporarily available on the hardhat network during the deploy script execution.

I would change  https://hardhat.org/guides/deploying.html slightly to provide an example pointing to the localhost. 
e.g. including this config
https://hardhat.org/config/#default-networks-object 

and replace `npx hardhat run --network <your-network> scripts/sample-script.js` to  `npx hardhat run --network localhost scripts/deploy.js`

**Comment by alcuadrado** [comment]
Do you feel like sending a PR to update it? :) All the docs are in this same repo, written in markdown: https://github.com/nomiclabs/hardhat/blob/master/docs/guides/deploying.md

**Comment by aboutlo** [comment]
@alcuadrado https://github.com/nomiclabs/hardhat/issues/1142
