### ISSUE TITLE
Ethers.providers.jsonrpcprovider not connecting to Hardhat-network ?

### ISSUE THREAD

**Issue by Tonyhaenn** [nomiclabs/hardhat#1145]
My contract has some time related logic, so my test needs to send an `evm_mine`  message — I thought I could use 
`const JSONRPC = new ethers.providers.JsonRpcProvider();`

But that doesn’t seem to automatically connect to the internal Hardhat-network the way using the rest of the ethers library does. Do I have to run a node separately (npx Hardhat node) and then always make sure to initialize ethers the same way? 

Thanks for the pointer.

**Comment by fvictorio** [comment]
I'm not sure I understand.

If you want to send an `evm_mine`, you can do `hre.network.provider.send("evm_mine")`. If you are using `hardhat-ethers`, then you can use `ethers.provider`, that has an instance of a provider connected to the internal hardhat network. Does that work for you?

**Comment by alcuadrado** [comment]
`new ethers.providers.JsonRpcProvider();` creates a new `JsonRpcProvider`, which [by default connects to `localhost:8545`](https://docs.ethers.io/v5/api/providers/jsonrpc-provider/).

As @fvictorio mentioned, you should use the providers that are already available in the Hardhat Runtime Environment.

**Comment by Tonyhaenn** [comment]
I expected this test to pass:
```
import { ethers } from 'hardhat';
import { expect } from 'chai';

describe('Providers Testing', async ()=> {

    it('Should have the same chain id', async ()=>{
        const ethersProvider = ethers.getDefaultProvider();
        const jsonRPC = new ethers.providers.JsonRpcProvider();
        const ethersNetwork = await ethersProvider.getNetwork()
        const jsonRPCNetwork = await jsonRPC.getNetwork()
        
        expect(ethersNetwork.chainId).to.equal(jsonRPCNetwork.chainId);
    });
})
```

I got there after trying to write a small utility to advance the time on chain, but it wasn’t working as I expected

```import { ethers } from 'hardhat';

const provider = ethers.getDefaultProvider();
const JSONRPC = new ethers.providers.JsonRpcProvider();

const advanceTimeAndBlock = async (time: number) => {
    let blockNum: number = await provider.getBlockNumber()
    let block = await provider.getBlock(blockNum);
    let blockTime = block.timestamp;
    let forwardTime: number = blockTime + time;
    await JSONRPC.send('evm_mine', [forwardTime]).catch((err)=>{console.log(err)});
}

export default advanceTimeAndBlock;
```

**Comment by fvictorio** [comment]
@Tonyhaenn I'm not sure I understand your last message. As explained above, you shouldn't use `new ethers.providers.JsonRpcProvider()`. Use `hre.ethers.provider` instead.

**Comment by Tonyhaenn** [comment]
I think the root of the issue is as you explained; I'm using the wrong provider. I'll use `hre.ethers.provider` and see if I can get that to work as expected.

Thanks for the help
