### ISSUE TITLE
Waffle's calledOnContract is not supported by Hardhat

### ISSUE THREAD

**Issue by Mvii7** [nomiclabs/hardhat#1154]
Any ETA on when this will be supported?

**Comment by Dellybro** [comment]
Yes please! This will make testing even better!

**Comment by willhennessy** [comment]
Any tips on how to test mockERC20 transfers without this feature? For now I am checking my contracts' event emission and internal balance, but it feels unsafe to assume the ERC20 call worked.

```
      await expect(magnet.deposit(magnetId, amount, mockERC20.address))
        .to.emit(magnet, 'Deposited')
        .withArgs(owner.address, magnetId, mockERC20.address, amount);
      
      // Waffle's calledOnContractWith is not currently supported by Hardhat. (1/5/2021)
      // expect("transferFrom").to.be.calledOnContractWith(mockERC20, [expectedSender, expectedRecipient, amount]);

      expect((await magnet.vestingMagnets(magnetId)).balance).to.equal(expectedBalance);

```

**Comment by fvictorio** [comment]
> Any ETA on when this will be supported?

It's something we want to do, but I can't give an ETA right now.



> For now I am checking my contracts' event emission and internal balance, but it feels unsafe to assume the ERC20 call worked.

Not sure I understood this. Events are not emitted if the call fails, so checking them should be fine. (If you have more questions, please use the hardhat-waffle channel on [our discord server](https://discord.com/invite/uVgdpAb))

**Comment by fvictorio** [comment]
Closing this in favor of #1135.
