### ISSUE TITLE
Chai `lengthOf` matcher not compatible with ethers/waffle objects

### ISSUE THREAD

**Issue by ItsNickBarry** [nomiclabs/hardhat#1157]
```
let quorum = ethers.constants.One;
let signers = await ethers.getSigners();

expect(quorum).to.be.at.least(1);

expect(signers.length).to.be.at.least(quorum);
expect(signers).to.have.lengthOf.at.least(1);
expect([1]).to.have.lengthOf.at.least(quorum);
expect(signers).to.have.lengthOf.at.least(quorum);
```

All statements run successfully except for the last one.

The error message is not particularly helpful: `AssertionError: Expected "[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]" to be at least 1`

**Comment by alcuadrado** [comment]
I think this should be handled by Waffle rather than Hardhat. We don't define chai matchers ourselves.

**Comment by ItsNickBarry** [comment]
Wasn't sure because of the previous issue with `changeTokenBalance` and similar matchers.  I'll report it elsewhere.
