### ISSUE TITLE
Truffle Migrations not working with Hardhat

### ISSUE THREAD

**Issue by abhishekr700** [nomiclabs/hardhat#1160]
Hi, I have changed my truffle migrations to the fixture format like this
```js
const BucketFactory = artifacts.require("BucketFactory");

module.exports = async (deployer, network, accounts) => {
    let bf = await BucketFactory.new()
    BucketFactory.setAsDeployed(bf)
};

```
Then I started a hardhat network via `npx hardhat node`  
and ran tests with `npx hardhat test --network localhost`   
but I keep getting this error 
```
NomicLabsHardhatPluginError: Trying to get deployed instance of BucketFactory, but none was set.
```
This error pops up at this code segment `BucketFactory.deployed()` which is what I was using with truffle + ganache. What am I missing out here ?  

Here is my hardhat config
```js
/**
 * @type import('hardhat/config').HardhatUserConfig
 */

require("@nomiclabs/hardhat-truffle5");
require("@nomiclabs/hardhat-ethers");


module.exports = {
    solidity: "0.7.5",
    defaultNetwork: "hardhat",
    settings: {
        optimizer: {
            enabled: true,
            runs: 10
        }
    },
    mocha: {
        timeout: 100000
    },
    networks: {
        hardhat: {
            forking: {
                url: "my-json-rpc-endpoint-for-fork"
            },
            allowUnlimitedContractSize: true,
            blockGasLimit: 9999999999999
        }
    }
};

```

**Comment by zane-a-karl** [comment]
@abhishekr700 did you ever figure out how to get around this problem? I am running into the same thing. I also tried printing out the value of the `mbb.constructor._constructorMethods.isDeployed()` function immediately after having called `contract.setAsDeployed()` and I keep receiving `false`. Any advice?
