### ISSUE TITLE
Error in hardhat/etherscan verification

### ISSUE THREAD

**Issue by Aleione** [nomiclabs/hardhat#1161]
Hello,

i have migrated on Kovan some contracts using Hardhat and I am trying to verify them with Hardhat/etherscan. For some contracts i received this error:

Error in plugin @nomiclabs/hardhat-etherscan: Failed to send contract verification request.
Endpoint URL: https://api-kovan.etherscan.io/api
Reason: Source code exceeds max accepted (500k chars) length

How can i fix it?

**Comment by scnale** [comment]
Hi, are you using the [latest version of the plugin](https://github.com/nomiclabs/hardhat/releases/tag/hardhat-etherscan-v2.1.0)? We introduced a fix for this issue not long ago but if you're still experiencing it we would be interested in knowing how to reproduce it. Is your project hosted in a publicly available repository?

**Comment by fvictorio** [comment]
@Aleione Please re-open if the latest version doesn't fix your problem.

**Comment by econiche** [comment]
This problem also happened with my script

**Comment by fvictorio** [comment]
@econiche do you have some way for us to reproduce this problem?

Also, is it possible that your constructor receives a lot of string values? If so, you can try this (copying a message that someone left in our discord server):

> Guys if you ever get this kind of error:
`NomicLabsHardhatPluginError: constructor arguments exceeds max accepted (10k chars) length`
There is a way to solve this.
You just need to manually encode your constructor arguments. (In my case I've passed a very large array of  strings)
I use ethers.js to achieve this, so here is the way how i have done this.
`ethers.utils.defaultAbiCoder.encode([string[]], [[..., "my", "array", "of", "strings", ...]]`
After you have done this, try to verify your contract via etherscan and replace your encoded data with that one in Constructor Arguments field. (Dont forget to delete first 2 characters (0x))
