### ISSUE TITLE
Functions named `build` and `execute` don't appear as expected in ethers js-object.

### ISSUE THREAD

**Issue by LHerskind** [nomiclabs/hardhat#1168]
# Unexpected issues 

When working with [DSProxy](https://github.com/makerdao/developerguides/blob/master/devtools/working-with-dsproxy/working-with-dsproxy.md#setup-wipeproxysol) and hardhat, I run in to some quite strange errors. A repo that reproduces the issue is available at: https://github.com/LHerskind/dsproxy-hardhat-issue

## `Build`

**Expected behavior**:
- Running `build()` at the `DSProxyFactory` is expected to create a new proxy for `msg.sender`

**Actual behavior**:
- `dsproxyFactory.connect(...).build is not a function`

The issue seem to be that the js-object create from `ethers` don't create the methods `build()` and `build(address)` as we would expect them to. If we print the functions of the `DSProxyFactory` we have the following output:
```
{
  'isProxy(address)': [Function (anonymous)],
  'cache()': [Function (anonymous)],
  'build()': [Function (anonymous)],
  'build(address)': [Function (anonymous)],
  isProxy: [Function (anonymous)],
  cache: [Function (anonymous)]
}
```
Seems like we are hitting some keyword with build and it do not behave as expected. 

**Workaround**:   
Instead of accessing the functions directly, we can generate the `calldata` and execute the transaction ourselves as:
```
let fragmentCreate = DSProxyFactory.interface.fragments[2];
let calldataCreate = DSProxyFactory.interface.encodeFunctionData(fragmentCreate);
await addr1.sendTransaction({ to: dsproxyFactory.address, data: calldataCreate});
//await dsproxyFactory.connect(addr1).build(); // This will crash the program. 
```

Otherwise, we can rename the functions, but this would require additional contract to be uploaded as we could not just use the existing DSProxy. However, an showcase that this works is seen below: 
![ErRzdZeXYAADmdV](https://user-images.githubusercontent.com/16536249/104127754-3078f300-5364-11eb-8935-cf91eb97d6e8.png)

## `Execute`
We have the same issue with `execute` of the proxy itself. Again, we can work around it by creating the `calldata` ourselves.

**Comment by fvictorio** [comment]
The problem is that those functions are overloaded. So you have to use them like this:

```
dsproxyFactory.connect(addr1)['build()']
// or
dsproxyFactory.connect(addr1)['build(address)']
```

That is, you have to specify which function you are calling by giving the full signature. Since you can't access those properties using the dot, you need to use the brackets syntax.

This is an ethers decision. You can see an explanation for this behavior here: https://github.com/ethers-io/ethers.js/issues/407#issuecomment-458360013
