### ISSUE TITLE
Funding an impersonated contract to pay for gas.

### ISSUE THREAD

**Issue by dhadrien** [nomiclabs/hardhat#1171]
I'd like to impersonate a contract during a mainnet fork test, but it has no fund and no payable receive function.

It seems as of today that there is no way for the contract to receive ETH and thus pay for the gas when impersonating.

Am I correct? Would be a great feature, especially for testing governance systems that have proposal executors :)

**Comment by dhadrien** [comment]
Found a workaround, using selfdestructing contract: 

```
pragma solidity 0.6.12;

contract SelfdestructTransfer {
  function destroyAndTransfer(address payable to) external payable {
    selfdestruct(to);
  }
}
```

**Comment by fvictorio** [comment]
Yes, you need to use the selfdestruct trick to send eth to a contract that doesn't accept it. There's no other way right now as far as I know.
