### ISSUE TITLE
Enable EIPs for Hardhat Network

### ISSUE THREAD

**Issue by naddison36** [nomiclabs/hardhat#1178]
This is a feature request to have a way to enable Ethereum Improvement Proposals (EIPs) that are supported by [Ethereum-js](https://ethereumjs.github.io/) for the Hardhat Network.

The use case I have at the moment is to test the gas changes in [EIP-2929](https://eips.ethereum.org/EIPS/eip-2929) in the upcoming Berlin fork.

As per [EthereumJs](https://github.com/ethereumjs/ethereumjs-vm/blob/c9c76bb31f8fa7f5b746e8dca729e0fb8d6a0744/packages/common/README.md#eips) doco, the following EIPs are currently supported:
* EIP-2537: BLS precompiles
* EIP-2929: gas cost increases for state access opcodes

**Comment by fvictorio** [comment]
We don't support enabling/disabling _specific_ EIPs, but you can select which hard fork you want to use.

With respect to these EIPs, they are available if you use `"berlin"` as your hard fork, which is available starting from `hardhat@2.2.0`.

**Comment by sveitser** [comment]
If I understand correctly EIP-2537 has been pushed back and is now not included in any of the hardforks in ethereum-js. Is there a easier way to enable them other than overriding the chain config in the provider at https://github.com/nomiclabs/hardhat/blob/98b7548525080c91a45cc3d3971f2d0248f62695/packages/hardhat-core/src/internal/hardhat-network/provider/provider.ts#L216 ?

**Comment by fvictorio** [comment]
> Is there an easier way to enable them

Not that I'm aware of. But if ethereumjs supports this, maybe we could too?

@alcuadrado wdyt?

**Comment by alcuadrado** [comment]
No, not really. This is not supported. You may hack your way if you really want to, but it may not work well with the rest of hardhat.

**Comment by sveitser** [comment]
Thanks for the replies. If anyone else wants to try something in this direction modifying the return value of `Common.forCustomChain` from `ethereumjs` with following in `hardhat.config.js` seems to do the trick.

```js
require("@nomiclabs/hardhat-waffle");

const Common = require("@ethereumjs/common").default;
forCustomChain = Common.forCustomChain;
Common.forCustomChain = (...args) => {
  const common = forCustomChain(...args);
  common._eips = [2537];
  return common;
};
```
