### ISSUE TITLE
npx hardhat verify fails when more than one contract has the same bytecode

### ISSUE THREAD

**Issue by JSMITH10101** [nomiclabs/hardhat#1179]
I recently stared using OpenZeppelin with Hardhat. Created a very simple ERC20 contract and deployed it to Ropsten using Hardhat.

However, when running `npx verify` I get the following error:

![Capture](https://user-images.githubusercontent.com/77362075/104655793-23d30280-56b6-11eb-9fe7-c25218049dfd.png)

My local is using the latest plugin versions.

Thanks

**Comment by scnale** [comment]
@JSMITH10101 try using the [latest v2.1.1](https://github.com/nomiclabs/hardhat/releases/tag/hardhat-etherscan-v2.1.1) that we released a few days ago. You should be able to specify which contract you want to verify with the optional parameter `--contract` when the bytecode produced is identical.
