### ISSUE TITLE
Console.log feature gets crazy with numbers above 2**254 (for example "MAX_UINT = 2**256 - 1" is displayed as -1)

### ISSUE THREAD

**Issue by vicnaum** [nomiclabs/hardhat#1182]
Here's a simple to reproduce test showing how the error goes:

![image](https://user-images.githubusercontent.com/5636644/104739430-fda97300-5746-11eb-9495-71cc0740d1ae.png)

**Comment by fvictorio** [comment]
Thanks a lot for reporting this @vicnaum. We just released `hardhat@2.0.9` that fixes this.
