### ISSUE TITLE
Invalid left-hand side in assignment when using getSigners()

### ISSUE THREAD

**Issue by StillFantastic** [nomiclabs/hardhat#1184]
Hi nomiclabs!
I am writing test with `hardhat-waffle`, and found a weird behavior.
Here is the file(test.js) that cause the error:

```
const { ethers } = require("hardhat")

describe("ERC721", () => {
  let tokenFactory
  let owner, receiver, operator

  beforeEach(async () => {
    const TokenFactory = await ethers.getContractFactory("TokenFactory")
    tokenFactory = await TokenFactory.deploy()
    await tokenFactory.deployed()
    [owner, receiver, operator] = await ethers.getSigners()
  })
})
```
When I run `npx hardhat test test.js`, it says
> An unexpected error occurred:
/Users/billhsu/Desktop/work/github/AR-Factory/test/test.js:10
    await tokenFactory.deployed()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ReferenceError: Invalid left-hand side in assignment
    at new Script (vm.js:80:7)
    at createScript (vm.js:264:10)
    at Object.runInThisContext (vm.js:316:10)
    at Module._compile (internal/modules/cjs/loader.js:670:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)

But if I change the function order to:
```
  beforeEach(async () => {
    [owner, receiver, operator] = await ethers.getSigners()
    const TokenFactory = await ethers.getContractFactory("TokenFactory")
    tokenFactory = await TokenFactory.deploy()
    await tokenFactory.deployed()
  })
```
Then the error disappears!

The version I'm using:
* hardhat-ethers: 2.0.1
* hardhat-waffle: 2.0.1
* hardhat: 2.0.7

**Comment by scnale** [comment]
Hey @StillFantastic, could you try adding a semicolon to the tenth line in your script? Like this:
```js
...
    await tokenFactory.deployed();
    [owner, receiver, operator] = await ethers.getSigners()
...
```

I think it is being parsed as this instead:
```js
...
    await tokenFactory.deployed()[owner, receiver, operator] = await ethers.getSigners();
...
```

In general, I would recommend you add all semicolons where they correspond; there are other syntactic constructs where javascript doesn't automatically add semicolons at the end of a line.

This is not an issue in Hardhat though so I'm closing this.

**Comment by fvictorio** [comment]
In case anyone ends up here and wants to know more, the term you need to google is Automatic Semicolon Insertion (ASI).
