### ISSUE TITLE
Bytecode is not stored in artifact file for a simple library

### ISSUE THREAD

**Issue by filippetroviccc** [nomiclabs/hardhat#1191]
Hi,

I'm trying to port [tornado_cash](https://github.com/tornadocash/tornado-core) to hardhat but I had the following issue.

Library called `Hasher` that is located under `contracts/MerkleTreeWithHistory.sol` when compiled using hardhat doesn't output bytecode in [artifacts file](https://gist.github.com/filippetroviccc/5e3592168fa8945e20beef0fae09e6e5).

The same project, compiled with `truffle compile` has bytecode inside [build file](https://gist.github.com/filippetroviccc/27375660693962e995861136f72fe9b4).

### Steps to reproduce

1. Clone [tornado_cash](https://github.com/tornadocash/tornado-core)
2. Run `npx hardhat` -> create empty project.
3. Change compiler version to `0.5.17`
4. Run `npm install --save hardhat`
5. Run `npm install`
6. Run `npm run build:circuit`
7. Run `npx hardhat compile`

Check file located under `./artifacts/contracts/MerkleTreeWithHistory.sol/Hasher.json`

**Comment by kiyoptr** [comment]
Can confirm this. And the contract using libraries have their linkedReferences empty in artifacts

**Comment by fvictorio** [comment]
I don't think this is a bug in hardhat. They seem to have an [ad hoc script](https://github.com/tornadocash/tornado-core/blob/77af0c5bddfcf9d973efbc38278a249bb0173da3/compileHasher.js) for generating this artifact. This script is used [here](https://github.com/tornadocash/tornado-core/blob/77af0c5bddfcf9d973efbc38278a249bb0173da3/truffle-config.js#L99-L105).
