### ISSUE TITLE
is there any way to debug transaction

### ISSUE THREAD

**Issue by PipsqueakH** [nomiclabs/hardhat#1194]
in remix, a transaction can be easily debugged by the [debugger](https://remix-ide.readthedocs.io/en/latest/debugger.html), but in hardhat, it seems the only way to debug is using console.log(), is there a remix-like debugger?

**Comment by fvictorio** [comment]
Not right now. Btw, I recommend you use [our discord server](https://discord.com/invite/uVgdpAb) for questions like these, you'll probably get answers more quickly!
