### ISSUE TITLE
unable to obtain wallet with same address as test signers

### ISSUE THREAD

**Issue by thegostep** [nomiclabs/hardhat#1198]
```ts
export const getTestWallet = (nonce = 0) => {
  return Wallet.fromMnemonic(
    'test test test test test test test test test test test junk',
    `m/44'/60'/0'/${nonce}`,
  )
}
```

**Comment by fvictorio** [comment]
Hi @thegostep, sorry for not responding before. You have probably already figured this out, but in case someone else runs into this issue, the answer is that the snippet above is missing a `/0`, it should be:

```js
ethers.Wallet.fromMnemonic('test test test test test test test test test test test junk', `m/44'/60'/0'/0/0`)
```

and the last number can be incremented to obtain the other addresses.
