### ISSUE TITLE
No documentation to test events with ethers.js

### ISSUE THREAD

**Issue by kikoncuo** [nomiclabs/hardhat#1201]
The way the contract instance is generated is different from the traditional ethers.js, it doesn't expose the same functions, I can't find a way to catch events on my tests, I have to use the truffle+web3 version

**Comment by scnale** [comment]
Hey @kikoncuo, could you tell us what you are attempting to do? When you say "catch events", do you mean EVM contract events that happen in a transaction or a subscription to `ethers.js` events?

**Comment by cdesch** [comment]
I think @kikoncuo might be looking for this in waffle [emitting-events](https://ethereum-waffle.readthedocs.io/en/latest/matchers.html?highlight=events#emitting-events)

Here is an example:

My Contract:
```
pragma solidity ^0.7.0;
import "hardhat/console.sol";

contract Counter {

    event ValueChanged(uint oldValue, uint256 newValue);

    // Private variable of type unsigned int to keep the number of counts
    uint256 private count = 0;

    // Function that increments our counter
    function increment() public {
        count += 1;
        emit ValueChanged(count - 1, count);
    }

    // Getter to get the count value
    function getCount() public view returns (uint256) {
        return count;
    }
}
```

My Tests that capture the emitted event:

```
const { expect } = require("chai");

describe("Counter", function() {
  it("Should increment the values", async function() {
    const Counter = await ethers.getContractFactory("Counter");
    const counter = await Counter.deploy();

    await counter.deployed();
    expect(await counter.getCount()).to.equal(0);

    // The way to increment without observing the event
    // const receipt = await counter.increment();

    // Increment while observing the event
    await expect(counter.increment())
      .to.emit(counter, 'ValueChanged')
      .withArgs(0, );

    expect(await counter.getCount()).to.equal(1);

  });
});
```

**Comment by kikoncuo** [comment]
> Hey @kikoncuo, could you tell us what you are attempting to do? When you say "catch events", do you mean EVM contract events that happen in a transaction or a subscription to `ethers.js` provider events ?

Subscriptions, there is a section called inside of contract interaction, contract, events that mentions this can be done but it doesn't have any examples nor specifies the types inside of the functions, I got it to work with a little tinkering but it would be nice if there were examples for other people in the future.

**Comment by kikoncuo** [comment]
> I think @kikoncuo might be looking for this in [waffle](https://getwaffle.io/),  the chai matchers for [emitting events](https://ethereum-waffle.readthedocs.io/en/latest/matchers.html?highlight=events#emitting-events)
> 
> Here is an example:
> 
> My Contract:
> ```
> pragma solidity ^0.7.0;
> import "hardhat/console.sol";
> 
> contract Counter {
> 
>     event ValueChanged(uint oldValue, uint256 newValue);
> 
>     // Private variable of type unsigned int to keep the number of counts
>     uint256 private count = 0;
> 
>     // Function that increments our counter
>     function increment() public {
>         count += 1;
>         emit ValueChanged(count - 1, count);
>     }
> 
>     // Getter to get the count value
>     function getCount() public view returns (uint256) {
>         return count;
>     }
> }
> ```
> 
> My Tests that capture the emitted event:
> 
> ```
> const { expect } = require("chai");
> 
> describe("Counter", function() {
>   it("Should increment the values", async function() {
>     const Counter = await ethers.getContractFactory("Counter");
>     const counter = await Counter.deploy();
> 
>     await counter.deployed();
>     expect(await counter.getCount()).to.equal(0);
> 
>     // The way to increment without observing the event
>     // const receipt = await counter.increment();
> 
>     // Increment while observing the event
>     await expect(counter.increment())
>       .to.emit(counter, 'ValueChanged')
>       .withArgs(0, );
> 
>     expect(await counter.getCount()).to.equal(1);
> 
>   });
> });
> ```

This is exactly what I was trying to do, and this is a much better cleaner way of doing so, thanks.

**Comment by cdesch** [comment]
Thanks @kikoncuo Please consider closing the issue or perhaps making a contribution to the documentation 😄

**Comment by cdesch** [comment]
also, please note that I fixed the error in my comment by adding the missing second param  "1" in the `withArgs(0, );`

so it should now look like:

```
...
    await expect(counter.increment())
      .to.emit(counter, 'ValueChanged')
      .withArgs(0, 1);
...
```

**Comment by cdesch** [comment]
@fvictorio Recommend closing issue.

**Comment by alcuadrado** [comment]
Thanks for answering this, @cdesch!
