### ISSUE TITLE
Weird behavior for default hardhat account on mainnet fork

### ISSUE THREAD

**Issue by fvictorio** [nomiclabs/hardhat#1204]
Brace yourselves, this is a weird bug.

---

Reproduction steps:

1. Clone `https://github.com/NexusMutual/smart-contracts`
2. `git checkout e2326ecb9f448a42eef7ed31be016315c807b445`
3. `cp .env.sample .env` and fill `.env` with some valid private key and address (they aren't used for this, but are needed for validation)
4. `npm install`
5. Modify the forking config to use block `11727485`
6. Run `TEST_ENV_FORK=<some-archive-node> hh test test/fork/price-function --show-stack-traces`

A test will fail when trying to deploy a contract (`TwapOracle`).

There are three ways to make this test pass:

- Run the same command but add `HH_BUG_WORKAROUND=1`. This will make the test send two no-op transactions before deploying that contract, and then it will work.
- Change the fork block number to an older one. I used 11500685.
- Use a different mnemonic for the generated accounts.

This points towards a problem on how we handle the generated accounts. Since the first account has some mainnet activity, there might be something wrong on how we get our information about that account during a fork (it might be the nonce, the balance, or something else). Ideally we would completely ignore *everything* about the generated accounts on mainnet, so double checking that assumption seems like a good place to start.

cc @shark0der

**Comment by scnale** [comment]
I found this issue as well while testing out the fork mechanism on the Kovan testnet. Using the first account reverted the deploy transaction, so I tried with the third account and that did work.

**Comment by fvictorio** [comment]
Easier way to reproduce this:

1. Create the sample project
2. Fork kovan (when #1207 is ready, or in that branch). Block `23215000` reproduces the problem.
3. Run the sample script on that fork

**Comment by fvictorio** [comment]
Fixed in 2.0.10.This should be fixed on 2.0.10.
