### ISSUE TITLE
hardhat-waffle is a hidden dependency of hardhat-ethers

### ISSUE THREAD

**Issue by jtlacci** [nomiclabs/hardhat#1208]
Was trying to set up a simple deploy script so didn't install hardhat-waffle.

Received error: ReferenceError: ethers is not defined 

It appears that Hardhat runtime env will not inject ethers unless hardhat-waffle is installed

Steps to reproduce:
`npx hardhat`
`Create an empty hardhat.config.js`
`npm install @nomiclabs/hardhat-ethers ethers`
`npx hardhat accounts`
```js
//hardhat.config.js 
task('accounts', 'Prints the list of accounts', async () => {
  const accounts = await ethers.getSigners();

  for (const account of accounts) {
    console.log(account.address);
  }
});

/**
 * @type import('hardhat/config').HardhatUserConfig
 */
module.exports = {
  solidity: '0.7.3',
};
```

**Comment by fvictorio** [comment]
You are probably missing the `require("@nomiclabs/hardhat-ethers")` in your `hardhat.config.js`

**Comment by jtlacci** [comment]
you are correct, it is a little confusing that if you have `require('@nomiclabs/hardhat-waffle');` then you don't need to add `require("@nomiclabs/hardhat-ethers")`

**Comment by fvictorio** [comment]
Yes, you can add both if you want to be explicit abour your dependencies, it's just not necessary.
