### ISSUE TITLE
Parse Panic Solidity 0.8 revert data (as found in overflow)

### ISSUE THREAD

**Issue by frangio** [nomiclabs/hardhat#1209]
Solidity 0.8 introduced a new `Panic(uint256)` encoding for revert data, used in Solidity built-in errors such as overflow. This is a new alternative to the existing `Error(string)` encoding.

From a quick test using hardhat console and hardhat-ethers, triggering an overflow prints `Error: Transaction reverted for an unrecognized reason.`.

```solidity
// SPDX-License-Identifier: Unlicense
pragma solidity 0.8.0;

contract Panic {
    function test() public returns (uint) {
        return uint(0) - uint(1);
    }
}
```

This should produce an error with a message that identifies it as a panic, together with the corresponding error code. We want to extend `expectRevert` from OpenZeppelin Test Helpers to detect panics as well.

**Comment by frangio** [comment]
Any updates on this? :slightly_smiling_face:

**Comment by alcuadrado** [comment]
We'll probably start working on this after this week's release.

**Comment by fvictorio** [comment]
Hardhat [2.4.0](https://github.com/nomiclabs/hardhat/releases/tag/hardhat-core-v2.4.0) now supports panic codes :tada:
