### ISSUE TITLE
Multiple transactions in a block

### ISSUE THREAD

**Issue by CodeSandwich** [nomiclabs/hardhat#1214]
### Problem
Some edge case test scenarios require multiple transactions to be mined in a single block. Hardhat doesn't have any means of performing such tests.
### Solution
Add a way of putting multiple transactions in a single block. A good solution would be exposing `miner_stop` and `miner_start` in the RPC API.

**Comment by alcuadrado** [comment]
Thanks for opening this issue, @CodeSandwich. We are about to release this and other features, so I'm closing this issue.

**Comment by fvictorio** [comment]
This was added in `hardhat@2.1.0`: https://github.com/nomiclabs/hardhat/releases/tag/hardhat-core-v2.1.0
