### ISSUE TITLE
Existence of contract constructor call breaks revert messages

### ISSUE THREAD

**Issue by CodeSandwich** [nomiclabs/hardhat#1227]
I have a fully functional project: https://github.com/radicle-dev/radicle-contracts/commit/c83d7ecee75051f580cb419fb41ef7ade72486d8. You can run its tests with `yarn install && yarn test`, they are all passing.

But when I use the `RadicleToken` contract constructor inside `Phase0` contract, `RadicleToken` tests verifying a transaction revert message start breaking. Everything else is working including revert messages from other contracts: https://github.com/radicle-dev/radicle-contracts/commit/42c9132f4b28d8045e8781a477d44a8ca323bdcd.

```
      delegateBySig failed because of an unexpected reason
      + expected - actual

      -Transaction reverted and Hardhat couldn't infer the reason. Please report this to help us improve Hardhat.
      +RadicleToken::delegateBySig: invalid signature
```

The `Phase0` contract isn't used anywhere in the tests, it's never deployed or even referenced. It's a piece of dead code which breaks hardhat seemingly by just existing :thinking:

The project uses hardhat 2.0.6, but upgrade to 2.0.8 doesn't fix the issue.

**Comment by CodeSandwich** [comment]
I've found a very similar issue where a contract revert message is always `Transaction reverted: function was called with incorrect parameters` despite coming from a `require` with a different message. The issue goes away after importing and using `console.log` in the tested `.sol` file, the messages return to normal. Clearing caches doesn't help.

**Comment by moodysalem** [comment]
I'm seeing this all over the place when making completely unrelated changes

We are seeing it way more frequently after removing `pragma abicoder v2;` from certain files

`AssertionError: Expected transaction to be reverted with ___, but other exception was thrown: Error: Transaction reverted: function was called with incorrect parameters`

**Comment by jamesmorgan** [comment]
Yep also see both of these issues atm - not really sure how solve it.

**Comment by petejkim** [comment]
I am seeing `AssertionError: Expected transaction to be reverted with ___, but other exception was thrown: Error: Transaction reverted: function was called with incorrect parameter`  as well...

**Comment by moodysalem** [comment]
Another example of an unrelated change that broke hardhat's revert reasons:
https://github.com/Uniswap/uniswap-v3-core/pull/471/files#diff-b99eeb006763689ccc70c640210adcb1b62d207dea3943d520cbe1a18046af83R208-R209

**Comment by dkenw** [comment]
I've been seeing both `Transaction reverted and Hardhat couldn't infer the reason` and `function was called with incorrect parameters` as well. 
It goes off when I set a particularly low optimizer runs like 100 runs or when I disable the optimizer.

**Comment by sirpy** [comment]
for us this happened when adding some lines of code to the "initializer" method

**Comment by fvictorio** [comment]
Hi everyone. Hardhat [2.4.0](https://github.com/nomiclabs/hardhat/releases/tag/hardhat-core-v2.4.0) comes with an improved error detection mechanism that should fix problems like these. I'm going to tentatively close this issue, but please re-open if you are still getting the same results.

**Comment by StillFantastic** [comment]
We are seeing `function was called with incorrect parameters` after we added a `require` in the `receive` function.

**Comment by jflatow** [comment]
Seeing this as well after upgrading

**Comment by fvictorio** [comment]
@jflatow do you have the optimizer enabled? In general, the error detection mechanism works much better when the optimizer is disabled.
