### ISSUE TITLE
Customize outputSelection

### ISSUE THREAD

**Issue by antoinedc** [nomiclabs/hardhat#1232]
Hello! I'm trying to get Hardhat to put the ast in the artifact file. I've update the solidity object in hardhat.config.js, but that doesn't seem to change anything:
```
module.exports = {
    solidity: {
        version: "0.7.3",
        settings: {
            outputSelection: {
                "*": {
                    "": ["ast"]
                }
            }
        }
    }
};

```
Any idea what I'm doing wrong here? 
Thank you!

**Comment by alcuadrado** [comment]
It should be changing your [build info files](https://hardhat.org/guides/compile-contracts.html#build-info-files), not your artifacts.

**Comment by antoinedc** [comment]
Aah ok, got it! Thanks!

I was hoping to get it there to be able to retrieve it from `hre.artifacts.readArtifact` then

**Comment by alcuadrado** [comment]
You have `hre.artifacts.getBuildInfo(fullyQualifiedName: string): Promise<BuildInfo | undefined>`

**Comment by alcuadrado** [comment]
Note that the reason for not storing those things inside the artifacts is that they can get **HUGE**

**Comment by antoinedc** [comment]
> You have `hre.artifacts.getBuildInfo(fullyQualifiedName: string): Promise<BuildInfo | undefined>`
That's perfect, thanks! Just when I was done parsing through the dbg & build files ahah

> Note that the reason for not storing those things inside the artifacts is that they can get **HUGE**
True...Truffle artifacts are way too big because of that.
I'm using it to read variables data, I don't know if many projects do that or if it can be useful for something else, but having an option to put it in the artifact could be useful I think

**Comment by alcuadrado** [comment]
You can add them to the artifacts by overriding a subtask of `compile`, but I don't recommend doing it. Maybe you can store them in a separate file? like `Contract.variables.json`

**Comment by antoinedc** [comment]
I had looked into that a bit but I wasn't able to figure it out.
But actually, it's ok, I was able to get what I needed from the build-info file!
