### ISSUE TITLE
Deploying contracts on mainnet fork fails sometimes

### ISSUE THREAD

**Issue by tpscrpt** [nomiclabs/hardhat#1233]
Deploying contracts one after the other leads to an error on the first run, but succeeds on subsequent runs.
Happens independently of which forking url is used.

 - Create dummy contract
 - Configure hardhat to fork mainnet
 - Run hardhat node
 - Deploy 25x this dummy contract on localhost
 - Watch Transaction failed: revert error message

Minimal reproduction
https://github.com/tpscrpt/hardhat-deploy-repro
Readme has instructions
Adjusted gas so you can see the output in the node console

**Comment by chanhosuh** [comment]
In the repo you say it fails on the 13th deploy.  You sure you don't mean the 15th?  I think this may be related to this bug: https://github.com/nomiclabs/hardhat/issues/1231

**Comment by tpscrpt** [comment]
> I used your repo, and it failed after the 14th deploy. I think it's this bug: #1231. Basically, the test mnemonic's account 0 has a contract creation transaction with nonce 14, so the 15th attempted deploy will revert. After that however, the nonce has been incremented past the problematic number, so the subsequent creations work.

Yeah setting index to 1 fixed this

**Comment by alcuadrado** [comment]
Yes, it is that bug @chanhosuh. We are working on a fix.

**Comment by fvictorio** [comment]
This was fixed in 2.0.10. Please re-open if you run into this again.
