### ISSUE TITLE
is it possible to run test by mocha command?

### ISSUE THREAD

**Issue by PipsqueakH** [nomiclabs/hardhat#1234]
usually we run tests by 
`
yarn exec hardhat test
`
but can we  run test by the mocha command like
`
mocha test ...
`
as it is convenient to run single test in Intellij ides.

**Comment by alcuadrado** [comment]
Sure, just import `hardhat` explicitly in your tests. 

For example:

```js
const {ethers} = require("hardhat");
```

There's this guide for running them in vscode, it should also work for intellij.
