### ISSUE TITLE
bsc network ProviderError: missing trie node 02f51875869cc574b03cf7d12d586f1f74e8cac6011d84cb98fdae84c426a3aa (path )

### ISSUE THREAD

**Issue by jin10086** [nomiclabs/hardhat#1236]
```
hardhat: {
      forking: {
        url: "https://bsc-dataseed.binance.org",
        blockNumber: 4745245  
      },
```

**Comment by 5hanth** [comment]
what was the issue here?

**Comment by fvictorio** [comment]
@5hanth this error usually means that you are not forking from an archive node. When Hardhat asks data that is some blocks old (say, 15 or whatever) a non-archival node will consider that "historical" information and return that error.

**Comment by itoukaijiE** [comment]
it seems to be a problem only occurs in bsc, that the block forked is far behind the newest block even when block number is not pinned, which means if configured like this
```
hardhat: {
      forking: {
        url: "https://bsc-dataseed.binance.org"
      },
```
and try to get the block number in the beginning of some testing snippet code, the block number is quite far behind the newest block(it is more than 30 blocks for me), then the historical data cannot be viewed.

it is interesting that eth or heco mainnet do not have this problem. is there something to note in hardhat?

**Comment by fvictorio** [comment]
@itoukaijiE that has to do with reorg protection. When you don't specify a block number, the latest block number is used **minus** some number of blocks. For unsupported networks, like BSC, that value is 30. We don't have a way to circumvent that right now, but there's an ugly workaround that you can use: at the beginning of your script/test, you run something like this:

```js
  const bscProvider = new ethers.providers.JsonRpcProvider(BSC_URL);

  const latestBlock = await bscProvider.getBlockNumber();

  await network.provider.send("hardhat_reset", [{
    forking: {
      jsonRpcUrl: BSC_URL,
      blockNumber: latestBlock
    }
  }])
```

Again, it's not pretty, but maybe it can help you for the time being.

**Comment by codler** [comment]
@fvictorio Hmm, Im trying to make a generic fetching blockNumber but I don't manage to solve it. This is what I got so far. Maybe you can see what am missing in `hardhat.config.ts`? Url is `https://bsc-dataseed.binance.org/`
```ts
task("test", async (args, hre, runSuper) => {
  if ((hre.network.config as HardhatNetworkConfig).forking?.enabled) {
    const blockNumber = BigNumber.from(
      await hre.network.provider.send("eth_blockNumber")
    ).toNumber();
    const jsonRpcUrl = (hre.network.config as HardhatNetworkConfig).forking
      ?.url;

    await hre.network.provider.request({
      method: "hardhat_reset",
      params: [
        {
          forking: {
            jsonRpcUrl,
            blockNumber,
          },
        },
      ],
    });
  }

  return await runSuper(args);
});

**Comment by fvictorio** [comment]
@codler The problem is that you are doing this:

```js
await hre.network.provider.send("eth_blockNumber")
```

Which uses the already forked provider, and so it won't give you the latest block number of the remote network. That is, this reset it's pretty much a no-op. Instead you should do something like this:

```ts
    const jsonRpcUrl = (hre.network.config as HardhatNetworkConfig).forking
      ?.url;
    const remoteProvider = new ethers.providers.JsonRpcProvider(jsonRpcUrl)
    const blockNumber = (await remoteProvider.getBlockNumber()).toNumber();
```

If you have more questions, please use [our Discord server](https://hardhat.org/discord) or [GitHub's Discussions](https://github.com/nomiclabs/hardhat/discussions)

**Comment by npitsillos** [comment]
@fvictorio  As a newcomer to both blockchain technology and javascript I have a question after trying to use your answer.  Assuming I have the following hardhat.config.js
```javascript
const { task } = require("hardhat/config");
require("@nomiclabs/hardhat-waffle");

// BSC_URL = "https://bsc-dataseed.binance.org/"
// This is a sample Hardhat task. To learn how to create your own go to
// https://hardhat.org/guides/create-task.html
task("accounts", "Prints the list of accounts", async (taskArgs, hre) => {
  const accounts = await hre.ethers.getSigners();
  for (const account of accounts) {
    console.log(account.address);
  }
});

// You need to export an object to set up your config
// Go to https://hardhat.org/config/ to learn more

/**
 * @type import('hardhat/config').HardhatUserConfig
 */
module.exports = {
  networks: {
    hardhat: {
      chainId: 56
    }
  },
  solidity: "0.8.4",
};
```

I fork the mainnet BSC node using the following:
```npx hardhat node --fork https://bsc-dataseed.binance.org/```

To use your answer here

> @itoukaijiE that has to do with reorg protection. When you don't specify a block number, the latest block number is used **minus** some number of blocks. For unsupported networks, like BSC, that value is 30. We don't have a way to circumvent that right now, but there's an ugly workaround that you can use: at the beginning of your script/test, you run something like this:
> 
> ```js
>   const bscProvider = new ethers.providers.JsonRpcProvider(BSC_URL);
> 
>   const latestBlock = await bscProvider.getBlockNumber();
> 
>   await network.provider.send("hardhat_reset", [{
>     forking: {
>       jsonRpcUrl: BSC_URL,
>       blockNumber: latestBlock
>     }
>   }])
> ```
> 
> Again, it's not pretty, but maybe it can help you for the time being.

Should I add this to a script and call ```node <script>```?

Note that I have tried this and still get this error.  Hope I have been clear and provided enough information for the problem I am facing.

**Comment by fvictorio** [comment]
> Should I add this to a script and call `node <script>`?

My snippet was meant to be used inside the test task that @codler shared. It should work in a hardhat script too.

**Comment by npitsillos** [comment]
Thank you for your comment! I will try that but for completeness I have modified the `hardhat.config.js` file following this [site](https://www.binance.org/en/blog/using-hardhat-for-binance-smart-chain/).  I made a couple transactions with the public accounts provided from `npx hardhat node` and it worked fine

**Comment by cryptoinhero** [comment]
When fork BSC network, it occurred "ProviderError: missing trie node" issue.
It seems like hardhat config does not allow forking for bsc with block number.
If I remove blockNumber param, it works for me.
```
    hardhat: {
          accounts: { mnemonic},
          forking: {
            url: "https://bsc-dataseed.binance.org/",
          }
    }
```

> @fvictorio Hmm, Im trying to make a generic fetching blockNumber but I don't manage to solve it. This is what I got so far. Maybe you can see what am missing in `hardhat.config.ts`? Url is `https://bsc-dataseed.binance.org/`
> 
> ```ts
> task("test", async (args, hre, runSuper) => {
>   if ((hre.network.config as HardhatNetworkConfig).forking?.enabled) {
>     const blockNumber = BigNumber.from(
>       await hre.network.provider.send("eth_blockNumber")
>     ).toNumber();
>     const jsonRpcUrl = (hre.network.config as HardhatNetworkConfig).forking
>       ?.url;
> 
>     await hre.network.provider.request({
>       method: "hardhat_reset",
>       params: [
>         {
>           forking: {
>             jsonRpcUrl,
>             blockNumber,
>           },
>         },
>       ],
>     });
>   }
> 
>   return await runSuper(args);
> });
> ```

When fork BSC network, it occurred "ProviderError: missing trie node" issue.
It seems like hardhat config does not allow forking for bsc with block number.
If I remove blockNumber param, it works for me.
```
    hardhat: {
          accounts: { mnemonic},
          forking: {
            url: "https://bsc-dataseed.binance.org/",
          }
    }
```

**Comment by fvictorio** [comment]
@cryptoinhero please read [my previous comment](https://github.com/NomicFoundation/hardhat/issues/1236#issuecomment-904846041).
