### ISSUE TITLE
add evm_setTime JSON-RPC method

### ISSUE THREAD

**Issue by tjcloa** [nomiclabs/hardhat#1243]
It is used intensively for testing in Truffle. We need badly to keep this when transferring to Hardhat.

**Comment by alcuadrado** [comment]
@tjcloa thanks for moving this conversation here. Do you know of any documentation of `evm_setTime`? I don't think we'd implement it if it's undocumented, as that will most probably lead to fragmenting the JSON-RPC API even further.

**Comment by tjcloa** [comment]
thanks for your response, @alcuadrado!
here is all the info i have on the issue:
1. https://github.com/trufflesuite/ganache-core/search?q=evm_setTime
2. https://github.com/trufflesuite/ganache-core/pull/140/files

**Comment by fvictorio** [comment]
I still don't understand what can be done with this method that can't be done with `evm_increaseTime` and/or `evm_setNextBlockTimestamp`. I don't think we want to add a redundant method just for compatibility with ganache.

I'm tentatively closing this, but feel free to comment on this, we monitor closed issues too.
