### ISSUE TITLE
hardhat-ethers doesn't reset the provider when a snapshot is reverted

### ISSUE THREAD

**Issue by fvictorio** [nomiclabs/hardhat#1247]
We reset the provider when `hardhat_reset` is called, but not when `evm_revert` is called.

Related issue: https://github.com/ethers-io/ethers.js/issues/1155

**Comment by scnale** [comment]
Hey! As far as I can see, this should be fixed in the current source of `hardhat-ethers` but there was no release of the plugin itself since the fix. Is there something blocking it?

**Comment by pilagod** [comment]
Same here, I just ran into this problem.

@fvictorio Is there any release plan to include this fix? Thanks.

**Comment by fvictorio** [comment]
Oops, you are 100% right. This will be included in the next release.

**Comment by fvictorio** [comment]
Fixed in [`@nomiclabs/hardhat-ethers@2.0.3`](https://github.com/nomiclabs/hardhat/releases/tag/%40nomiclabs%2Fhardhat-ethers%402.0.3).
