### ISSUE TITLE
Hardhat-truffle5 test fixtures fail with: "{FixtureName} has no network configuration for its current network id (31337)."

### ISSUE THREAD

**Issue by lepidotteri** [nomiclabs/hardhat#1253]
After following the instructions outlined [here](https://hardhat.org/guides/truffle-migration.html#migrations-and-hardhat-truffle-fixtures) for adapting existing Truffle migrations referenced in original Truffle test suites I get the following error if I try to run the test files with the hardhat-truffle5 plugin, no matter what networks config is specified in either the hardhat-config or truffle-config files (is the latter still needed by the plugin?):

![image](https://user-images.githubusercontent.com/45174270/108060406-1ca56880-7057-11eb-8d5e-5f36f8bbf60c.png)

You can find the project here: https://github.com/lepidotteri/diamond-3/tree/feat/hardhat%2Bsolc-0.8

**Comment by fvictorio** [comment]
I don't know a lot about the truffle plugin, but I did some modifications to your `truffle-fixture.js` and now the tests at least run (but most fail). Here's the diff:

```diff
diff --git a/test/truffle-fixture.js b/test/truffle-fixture.js
index b12dd4a..e2f0cde 100644
--- a/test/truffle-fixture.js
+++ b/test/truffle-fixture.js
@@ -35,14 +35,16 @@ module.exports = async () => {
   DiamondCutFacet.setAsDeployed(cutFacet)
   const loupeFacet = await DiamondLoupeFacet.new()
   DiamondLoupeFacet.setAsDeployed(loupeFacet)
+  const ownershipFacet = await OwnershipFacet.new()
+  OwnershipFacet.setAsDeployed(ownershipFacet)
 
   const diamondCut = [
-    [DiamondCutFacet.address, FacetCutAction.Add, getSelectors(DiamondCutFacet)],
-    [DiamondLoupeFacet.address, FacetCutAction.Add, getSelectors(DiamondLoupeFacet)],
-    [OwnershipFacet.address, FacetCutAction.Add, getSelectors(OwnershipFacet)]
+    [cutFacet.address, FacetCutAction.Add, getSelectors(DiamondCutFacet)],
+    [loupeFacet.address, FacetCutAction.Add, getSelectors(DiamondLoupeFacet)],
+    [ownershipFacet.address, FacetCutAction.Add, getSelectors(OwnershipFacet)]
   ]
 
-  const diamond = await Diamond.new(diamondCut, admin)
+  const diamond = await Diamond.new(diamondCut, [admin.address])
   Diamond.setAsDeployed(diamond)
 
   const test1Facet = await Test1Facet.new()
```

Maybe this helps, but I'm playing it by ear here, so take it with a grain of salt.

**Comment by lepidotteri** [comment]
> Maybe this helps, but I'm playing it by ear here, so take it with a grain of salt.

Thank you very much for helping out with the fixture, I was able to fix most test suites here: https://github.com/mudgen/diamond-3/pull/21/commits/1b35d2a30eb2877fe42c5cd0c9e1a76022b55ab7

**Comment by fvictorio** [comment]
Glad to hear that. I don't know if there's something on our side to fix here, but I will leave the issue open because I think something could be improved on those docs.

**Comment by fvictorio** [comment]
Closing this since it's on our docs pipeline.
