### ISSUE TITLE
FR: add miner_start and miner_stop JSON-RPC

### ISSUE THREAD

**Issue by tjcloa** [nomiclabs/hardhat#1255]
Like https://github.com/trufflesuite/ganache-cli/releases/tag/v3.0.0
It is great for testing

**Comment by alcuadrado** [comment]
Hi @tjcloa, thanks for suggesting this. A superset of this is being worked on, and we'll be released in the near future. If you want to follow its progress, it's #1087 

I'm closing this issue now.

**Comment by fvictorio** [comment]
This was added in `hardhat@2.1.0`: https://github.com/nomiclabs/hardhat/releases/tag/hardhat-core-v2.1.0
