### ISSUE TITLE
v2.0.10 always compiles vyper contracts even no any change

### ISSUE THREAD

**Issue by bin-57blocks** [nomiclabs/hardhat#1258]
I installed hardhat v2.0.10 and hardhat-truffle5(2.0.0), hardhat-vyper(2.0.1). Solidity version is 0.6.8 and vyper version is 0.2.8.

I found it always compiling vyper contracts when I run npx hardhat test. Could you fix it to just compile after some code change. It will save test time.

**Comment by alcuadrado** [comment]
Hey @bin-57blocks

This is an unfortunate known limitation that will be fixed soon.

Sorry for the inconvinience.

**Comment by kesar** [comment]
+1 it makes it hard to use for vyper :(

**Comment by fvictorio** [comment]
@kesar There's no workaround that I'm aware of, sorry.

@alcuadrado maybe we could move the "remove obsolete artifacts" logic to a subtask, so vyper users could just override that subtask to make it a no-op as an easy, temporary fix?

**Comment by alcuadrado** [comment]
Sorry for the late answer. Isn't the actual fix rather trivial? We should only remove artifacts if they are inside a directory ending with `.sol`.

**Comment by fvictorio** [comment]
Oh yeah, that makes more sense.

**Comment by feuGeneA** [comment]
Released in [@nomiclabs/hardhat-vyper v3.0.0](https://github.com/nomiclabs/hardhat/releases/tag/%40nomiclabs%2Fhardhat-vyper%403.0.0)
