### ISSUE TITLE
Error HH903 when the artifacts already exists

### ISSUE THREAD

**Issue by AgusVelez5** [nomiclabs/hardhat#1259]
Hi, I have the error [HH903](https://hardhat.org/errors/#HH903) that says: "The inferred artifact path doesn't exist."
But I checked if the path is correct and the file exists, and both are correct.

The issue is with erc20 interface artifact:
```
HardhatError: HH903: The inferred artifact path for contract @openzeppelin\contracts\token\ERC20\IERC20.sol:IERC20
```

Any help?

**Comment by fvictorio** [comment]
Hey @AgusVelez5, are you still having this issue? Can you tell us how to reproduce it?
