### ISSUE TITLE
Is there a way to insert multiple transactions into one block?

### ISSUE THREAD

**Issue by bin-57blocks** [nomiclabs/hardhat#1262]
I wrote some tests depend on multiple transactions in one block. They work well in ganache with miner_stop and evm_mine methods. But they don't work when migrate to hardhat because no miner_stop method. Is there a way to insert multiple transactions into one block in hardhat? or any plan to support this?

It seems this [PR 1087](https://github.com/nomiclabs/hardhat/pull/1087) is related to what I want. Any plan when to release it?

**Comment by alcuadrado** [comment]
Hey @bin-57blocks, we are really excited about #1087 too :) It's even more powerful than just `miner_stop` and `evm_mine`.

The good news is that it's pretty close to being ready. I'm pretty confident that it will be released this month.

I'm closing this issue, but feel free to ask more things or drop by our discord https://hardhat.org/discord

**Comment by fvictorio** [comment]
This was added in `hardhat@2.1.0`: https://github.com/nomiclabs/hardhat/releases/tag/hardhat-core-v2.1.0

**Comment by computerphysicslab** [comment]
According to this issue, it is possible to stop mining, right?

What command should I use to do it?

I have tried unsuccessfully miner_stop() and minerStop():

async function minerStop() {
	return rpc({ method: "miner_stop" });
}

I am using:

npx hardhat --version
	2.2.1

Getting the error:
	ReferenceError: miner_stop is not defined

Any hint? Thx!
