### ISSUE TITLE
Error HH503

### ISSUE THREAD

**Issue by xbw1105** [nomiclabs/hardhat#1271]
I use docker to RUN npx hardhat compile from China.
However, it keep saying: error HH503. Couldn't download compiler version 0.4.24.
I have checked my internet, used several VPN and changed to a docker domestic mirror source.
I failed.
Can I get some suggestions?

**Comment by alcuadrado** [comment]
Can you try `npx hardhat clean --global`?

**Comment by sophiacodes** [comment]
@alcuadrado I'm having the same issue, but with compiler 0.5.3. `npx hardhat clean --global` doesn't work for me

**Comment by fvictorio** [comment]
This should be fixed in `hardhat@2.2.0`. If you get that message, you just need to run hardhat again; there's no need to use the `clean` task.

**Comment by fvictorio** [comment]
@sophiacodes do you still have that issue?
