### ISSUE TITLE
Use npx hardhat run with two different sets of arguments 

### ISSUE THREAD

**Issue by James-Sangalli** [nomiclabs/hardhat#1275]
Hi All,

I am using npx hardhat run to run a CLI script that has its own set of arguments

I know that I can use `npx hardhat run ./path/to/script` but I want to be able to do it so that I can also pass arguments to the script itself, like so:

`npx hardhat run src/CLI.js -arg1ForCLI.js xxx`

if I do this I will get the following error:

`Error HH308: Unrecognized positional argument`

Is there a way round this? Thank you for your time and for building an excellent tool for the community!

**Comment by alcuadrado** [comment]
You can run `node src/CLI.js` directly, as long as you import `hardhat` explicitly (e.g. `const {ethers} = require("ethers")`)  in your script, or require `hardhat/register` as its first line.

**Comment by James-Sangalli** [comment]
Thank you @alcuadrado

**Comment by LightMan** [comment]
Gracias @alcuadrado ,

Instead of the `const {ethers} = require("ethers")`
I used: `const hre = require("hardhat");`
And then `hre.ethers.getContractFactory(contractName);`
