### ISSUE TITLE
running the command runs hardhat twice

### ISSUE THREAD

**Issue by novaknole** [nomiclabs/hardhat#1276]
This is my `tsconfig.json`.

```js
{
    "compilerOptions": {
      "target": "es5",
      "module": "commonjs",
      "strict": true,
      "esModuleInterop": true,
      "moduleResolution": "node",
      "forceConsistentCasingInFileNames": true,
      "outDir": "dist"
    },
    "include": ["hardhat.config.ts", "./tasks", "./deploy", "./test"]
  }
```

This is my `hardhat config`.

```js
import { HardhatUserConfig } from 'hardhat/types'
import '@nomiclabs/hardhat-ethers'
import '@nomiclabs/hardhat-etherscan'
import '@nomiclabs/hardhat-waffle'
import 'hardhat-deploy'
import 'hardhat-typechain'
import 'solidity-coverage'

import { accounts } from './utils/network'

const config: HardhatUserConfig = {
  solidity: {
    version: '0.6.8',
    settings: {
      optimizer: {
        enabled: true,
        runs: 20000, // TODO: target average DAO use
      },
    },
  },
  etherscan: {
    apiKey: process.env.ETHERSCAN_KEY,
  },
  networks: {
    exampleHere: {
      url: "https://fasfasf.eth.aragon.network",
      accounts: accounts('mainnet123'),
    },
    rinkeby: {
      url: 'https://rinkeby.eth.aragon.network',
      accounts: accounts('rinkeby'),
    }
  },
}
```

In my package.json, I have this.

```js
"deploy": "hardhat deploy",
```

and I run `yarn deploy --network rinkeby`.

as you can see in the code, `accounts` is my function which just returns the private key for the according network. 

The problem is that `accounts` runs twice for `rinkeby` network and for also `exampleHere` . If I put `exampleHere` below `rinkeby` in the config, then it runs only twice.  

No idea what's going on..

**Comment by alcuadrado** [comment]
There's a few cases where Hardhat can be initialized more than once, for example `npx hardhat console` and `npx hardhat run <script>`. There's no guarantee that your config file will be evaluated just once.

**Comment by novaknole** [comment]
This gives a problem, because currently, I have the following config:

```js
networks: {
    mainnet: {
      url: "https://mainnet.network",
      accounts: accounts('mainnet'),
    },
    rinkeby: {
      url: 'https://rinkeby.network,
      accounts: accounts('rinkeby'),
    }
  },
```

When I run `yarn deploy --network rinkeby`, it runs both of the networks(`mainnet and rinkeby`) which results in an error `not enough gas to deploy contract` , because I don't have any money on the mainnet..

**Comment by novaknole** [comment]
I think, I understand now. It seems like `accounts` function gets run multiple times, but actual task gets run one time. 

Sounds good to me and thanks for the quick follow up

**Comment by novaknole** [comment]
@alcuadrado 

Sorry for asking questions here, This will be my last question and while you're here, maybe asking this in this thread makes more sense.

There's a function hardhat exposes such as :

```
await HRE.run(task, params)
```

I put it in a `try/catch` block. For my case, it goes into catch block with a reason: `Reason: Contract source code already verified`. Is there any way I can somehow import a type which would quickly let me know that it throws this error specifically ? I don't want to do `if(error == "Reason: Contract source code already verified")`.

Thanks a lot in advance.

**Comment by wighawag** [comment]
> Oh, that's not what I meant. The config file may be evaluated multiple times, but the task should be run once.
> 
> @wighawag does this sound familiar to you?
> 
> What does your `accounts` function do?

it is a utility function I have in my boilerplate : https://github.com/wighawag/template-ethereum-contracts/blob/8e72bef568fc317f524bfb3164a479bdc0d0ed4a/utils/network.ts#L41-L43

it help make you have different account per network using env variable if set, so you can have a generic env for all network or a specific one as you wish.

I did not know that `hardhat.config.js` would be called multiple time though. And so that would be the reason for the multiple call here.
