### ISSUE TITLE
Error in hardhat/etherscan verification

### ISSUE THREAD

**Issue by MLY0813** [nomiclabs/hardhat#1277]
Error in plugin @nomiclabs/hardhat-etherscan: Failed to send contract verification request.
Endpoint URL: https://api-ropsten.etherscan.io/api
Reason: request to https://api-ropsten.etherscan.io/api failed, reason: read ECONNRESET

"@nomiclabs/hardhat-etherscan": "^2.1.1"

Where is the problem?

**Comment by fvictorio** [comment]
It seems like a connection issue. Hard to know without more details.

Also, please use [our discord server](https://hardhat.org/discord) for questions like this.
