### ISSUE TITLE
No prompt for sample project or empty config.

### ISSUE THREAD

**Issue by cfsp4rk2** [nomiclabs/hardhat#1282]
After installing hardhat with:
`$ npm install --save-dev hardhat`

And attempting to start hardhat with:
`$ npx hardhat node`

Hardhat does not present the "What do you want to do?" prompt with options to create a sample project or empty config file. It simply presents:
```
Error HH1: You are not inside a Hardhat project.

For more info go to https://hardhat.org/HH1 or run Hardhat with --show-stack-traces
```

Tested on:
- OS: Windows 10 Pro
- Hardhat: v2.0.11
- Node: v14.11.0, v14.16.0, v10.24.0
- NPM: 6.14.4

It however worked as intended on newly created Ubuntu VM:
- OS: Ubuntu 20.04 LTS
- Hardhat: v2.0.11
- Node: v10.19.0
- NPM: 6.14.4

**Comment by shinaBR2** [comment]
+1 for the same problem

**Comment by fvictorio** [comment]
I think this is the same problem as #1408. The workaround is to use `cmd` for now.

Please re-open if you think this is a different issue.
