### ISSUE TITLE
`to.emit` can't figure out if the event was emitted from library.

### ISSUE THREAD

**Issue by novaknole** [nomiclabs/hardhat#1287]
I have a contract `contractA` which has the function `func1`. 

`func1` uses the library function `func2`.  

`funct2` emits the event, called `EventExample`.

In my test, I have the following:

```js
await expect(`contractA`.func1()).to.emit(`contractA`, 'EventExample')
```

The error says: 

> Expected event "EventExample" to be emitted, but it doesn't exist in the contract. Please make sure you've compiled its latest version before running the test.

It seems like the problem is because event gets thrown from library. How do I make this work ? I don't know the library address and will not know.

**Comment by alcuadrado** [comment]
hey @novaknole, try opening this issue in Waffle's repository, as it's not something hardhat specific.
