### ISSUE TITLE
Deployed address?

### ISSUE THREAD

**Issue by stoplion** [nomiclabs/hardhat#1290]
hello. I'm switching from Truffle, and one thing I can't figure out is how to get the deployed address?
In the artifacts from Truffle, you get the deployed address.

**Comment by fvictorio** [comment]
Hardhat doesn't manage deploys like Truffle does. You can try [`hardhat-deploy`](https://github.com/wighawag/hardhat-deploy/), which is a community plugin that could help you with this.
