### ISSUE TITLE
parseLog prints wrong output

### ISSUE THREAD

**Issue by novaknole** [nomiclabs/hardhat#1292]
My contract looks like this.

```js

struct test{
    Action[] actions;
}


struct Action {
    address to;
    uint256 value;
    bytes data;
}


event EventExample(test data);

function myFunction(test memory data) public {

   emit EventExample(data);

}

```

Then I want to test this, so I do the following:

```js

const data = {
    actions: [
      {
        to: 0x0000000000000000000000000000000000000000,
        value: 1000,
        data: 0x00
      }
    ],
}

let receipt :any= (await (await contract.myFunction(data)).wait())
let decodedArgs =  contract.interface.parseLog(receipt.events[0]).args;
```

If we log the `decodedArgs` , we get the following:

```js
[
    '0x0000000000000000000000000000000000000000',
    [BigNumber],
    '0x00',
    to: '0x0000000000000000000000000000000000000000',
    value: [BigNumber],
    data: '0x00'
]

```

The problem that I notice is why does the above contain `to` parameter two times ? `value` parameter 2 times and `data` parameter 2 times ? It doesn't make sense. It's an array, so how did both(key value pairs) and just values end up in there ? 

This brings me a problem, because when i test, I can't/don't pass the above object, because it's clueless, What I pass as expected argument is:

```js
[
    '0x0000000000000000000000000000000000000000',
    [BigNumber],
    '0x00',
]
```
 but for sure test fails, because the actual data contains also `to,value,data` .  

Question 1: Why does `parseLog` print such anomaly ?  my abi interface is correct.

Question 2: what do you advise for tests ? `ethereum-waffle` uses `withArgs`, which seems like I can't do `deep include` as `mocha` suggests.

**Comment by fvictorio** [comment]
As mentioned in the other issue, this issue tracker is not for questions. Plus, this seems like an ethers question unrelated to hardhat. You can try asking in the [crypto devs server](https://discord.gg/yExeTMpc). I also think that, unlike here, you can use [ethers.js repo](https://github.com/ethers-io/ethers.js) to ask questions, but I'm not sure.
