### ISSUE TITLE
hardhat coverage chainId is 1

### ISSUE THREAD

**Issue by novaknole** [nomiclabs/hardhat#1294]
```js
import { ethers, waffle} from 'hardhat'

chainId = (await ethers.provider.getNetwork()).chainId
```

I run the following:

```js
hardhat coverage --network coverage
```

It seems like `chainId` is 31337, but in the contract code, when I have this:

```js
 uint chainId;
  assembly {
      chainId := chainid()
  }
```

Now chainId is 1.  As we can see, running `hardhat coverage` is a problem, because in the contracts, chainId is 1, in the tests, it's 31337 and these cause my test fails to fail, because I am dependent on chainId.

If I run `hardhat test`, nothing like these happen. `chainId` in both contracts and tests are 31337.

Any ideas ?

This is my hardhat config.

```js
 coverage: {
      url: 'http://localhost:8555',
      allowUnlimitedContractSize: true,
    },
```

**Comment by cgewecke** [comment]
@novaknole When you use a coverage network and a url, coverage runs ganache by default. 

In the latest solidity-coverage it's possible to run your tests directly on the in-memory Hardhat network by omitting the `--network coverage` cli flag.
```
npx hardhat coverage 
```

It should inherit all your hardhat settings (and run faster as well).

If you'd like to continue using ganache, you can set the chainId via a `providerOptions` object in `.solcover.js`. The full set of [ganache-core options is here][1]

More info about all of this at the [solidity-coverage docs][2]

[1]: https://github.com/trufflesuite/ganache-core/tree/master#options
[2]: https://github.com/sc-forks/solidity-coverage#solidity-coverage

**Comment by novaknole** [comment]
Thanks a lot @cgewecke
