### ISSUE TITLE
hardhat HRE.run catch block check error

### ISSUE THREAD

**Issue by novaknole** [nomiclabs/hardhat#1301]
I am doing this:

```js
try {
    if (times) {
      await HRE.run('verify', params)
    } else {
      console.error(
        'Errors after all the retries, check the logs for more information.'
      )
    }
  } catch (error) {
    counter--
    console.error(error.message)
    await runTaskWithRetry(task, params, counter, msDelay, cleanup)
  }
```

This gets run when I want to verify contracts automatically. So far so good. 

The problem is that `try` catch block fails and it goes into the catch block where the error states: `Contract source code already verified`.  What I want to do is that if the error is `already verified`, I want it to stop, otherwise recursively call (maybe there's some other mistakes which running it again would fix).

The only workaround I have is that in the catch block, I do the following:

```js
if(error.message != "Contract source code already verified"){
   runTaskAgain();
}
```

Do we have any better alternatives ? One can use `error instanceof NomicLabsHardhatPluginError` , but I don't think this would be correct, because `NomicLabsHardhatPluginError` could be thrown in some other cases as well.

**Comment by fvictorio** [comment]
Checking the error message should be mostly fine, although we don't guarantee that that message won't change. You might do `/already verified/i.test(error.message)` instead and it would be a little more robust (but still: no guarantees).

---

In the future, please use our [discord server](https://discord.gg/bdxATfUx) to ask questions, the issue tracker here is for bug reports or feature requests.
