### ISSUE TITLE
Fail - Unable to verify: solc@0.8.2

### ISSUE THREAD

**Issue by Theo6890** [nomiclabs/hardhat#1308]
Same [bug](https://github.com/rkalis/truffle-plugin-verify/issues/65) with @nomiclabs/hardhat-etherscan due to etherscan failure

**Comment by fvictorio** [comment]
This seems like a problem on etherscan side, doesn't it? Have you reported it to them?

**Comment by Theo6890** [comment]
No I forgot to so but between the post and last days it has been fixed
