### ISSUE TITLE
Assert failing while compairing BigNumber

### ISSUE THREAD

**Issue by AbdulRafaySiddiqui** [nomiclabs/hardhat#1315]
Can anyone tell, why both of the following expects are failing

```const { expect } = require("chai");
const hre = require("hardhat");
const { ethers } = hre;
const { BigNumber, utils } = ethers;

describe("Deploy YDF token and check balance", function () {
    it("Deployer balance should be equal to 30K", async function () {
        
        expect(utils.parseEther("1.0")).to.equals(utils.parseEther("1.0"));
        expect(BigNumber.from("30000000000000000000000")).to.equals(BigNumber.from("30000000000000000000000"));
    });
});

**Comment by AbdulRafaySiddiqui** [comment]
![image](https://user-images.githubusercontent.com/46793902/110556829-1fc8db80-8161-11eb-814d-ff382eb4ff18.png)

**Comment by fvictorio** [comment]
My guess is that you are not importing `@nomiclabs/hardhat-waffle` in your config, or that you are using an outdated version of `ethereum-waffle`. Assuming you are using waffle at all.

If you are not using waffle, then this happens because `.to.equals` uses loose equality (i.e. it uses `==`), and `parseEther` returns a BigNumber object.

Please use our [discord server](https://hardhat.org/discord) if you have more questions.

**Comment by AbdulRafaySiddiqui** [comment]
I did import `require("@nomiclabs/hardhat-waffle");` in my hardhat config and I am using `"ethereum-waffle": "^3.3.0",` and `"@nomiclabs/hardhat-waffle": "^2.0.1",`
This is how I am using it with either importing solidity from the hardhat waffle or ethereum-waffle, both don't work..

```
const { ethers, waffle } = require("hardhat");
const { expect, use } = require("chai");
const { solidity } = waffle;
const { BigNumber, utils } = ethers;

use(solidity);

```

```
const { ethers } = require("hardhat");
const { expect, use } = require("chai");
const { solidity } = require('ethereum-waffle');
const { BigNumber, utils } = ethers;

use(solidity);
```

**Comment by fvictorio** [comment]
@AbdulRafaySiddiqui if you have a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), I can take a look.
