### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by rubydog** [nomiclabs/hardhat#1323]
Hi community, 

Is it just me or people here find hardhat's documentation very frustrating?

Great work @nomiclabs for such a great tool but it is very frustrating to read through documentation.

**Comment by alcuadrado** [comment]
Hey @rubydo, 

I'm sorry you are getting frustrated by our docs. Can you tell use by what parts of it and why so that we can improve them?

**Comment by fzeoli** [comment]
generally the feedback is the opposite, that the documentation is great, so I'm very curious to know what is it that you're finding so jarring?

**Comment by fzeoli** [comment]
generally the feedback is the opposite, that the documentation is great, so I'm very curious to know what is it that you're finding so jarring?

**Comment by RubyDo** [comment]
Hello! I think you meant to mention @rubydog  and not me :)

**Comment by rubydog** [comment]
@alcuadrado, it is generally very difficult the follow the flow, it feels like mix of how-to guides and workings of hardhat. There is no clear list of available api, its description and an example.

**Comment by fvictorio** [comment]
Closing this. We understand that the docs could be improved a lot, and we really want to invest more time on that as soon as we can. Please feel free to submit another issue if you have specific feedback, that would be very useful. Or you can just send it to us in [our discord server](https://hardhat.org/discord) if you prefer that.
