### ISSUE TITLE
Couldn't download compiler version 0.5.17

### ISSUE THREAD

**Issue by syuukawa** [nomiclabs/hardhat#1325]
npx hardhat compile
Downloading compiler 0.5.17
Error HH503: Couldn't download compiler version 0.5.17. Checksum verification failed. Please check your connection.

For more info go to https://hardhat.org/HH503 or run Hardhat with --show-stack-traces

**Comment by oszeleje** [comment]
I had similar issue today. Running `npx hardhat clean --global` helped.

**Comment by syuukawa** [comment]
> I had similar issue today. Running `npx hardhat clean --global` helped.

Thanks oszeleje, Just do as you said ,It is ok。
