### ISSUE TITLE
HH503 due to MacOS solc binaries having changed

### ISSUE THREAD

**Issue by rmi7** [nomiclabs/hardhat#1332]
```
Error HH503: Couldn't download compiler version 0.5.17. Checksum verification failed. Please check your connection.
```

Likely due to: https://github.com/ethereum/solc-bin/pull/76

Also see this PR https://github.com/crytic/echidna/pull/629

**Comment by rmi7** [comment]
see https://github.com/nomiclabs/hardhat/pull/1329

**Comment by rmi7** [comment]
Seems the `list.json` file is cached by hardhat. So simply updating an existing hardhat to use the new url `https://binaries.soliditylang.org/`, might not invalidate the old cached list. And since some solc version's hash did change this would cause problems.

**Comment by alcuadrado** [comment]
Thanks for reporting this, @rmi7. What we should do is remove the compilers list in `downloader.ts` if `verifyCompiler` fails.

**Comment by liamzebedee** [comment]
Bump on this issue. I've been running the aformentioned PR with a small change for a week or two now, though it's somewhat annoying to setup and maintain. Would heaps appreciate if it could be expedited! Cheers

**Comment by kingassune** [comment]
I've also run into this issue. This is killing my security environment currently.

**Comment by alcuadrado** [comment]
If you are experiencing this, please run `npx hardhat clean --global`

**Comment by zemse** [comment]
Experiencing the same issue

> npx hardhat clean --global

This doesn't solve for me. Is there any other hack that I can do on my side to quickly get this working for now?

**Comment by maldo-ctrl** [comment]
Thanks @zemse your hack is the only solution for me right now.

**Comment by alcuadrado** [comment]
@zemse, can you upload the `list.json` files that are in `~/Library/Caches/hardhat-nodejs/compilers/*/list.json`? Thanks!

**Comment by zemse** [comment]
[list.json.txt](https://github.com/nomiclabs/hardhat/files/6290512/list.json.txt)

I added `.txt` so that GitHub accepts the file upload.

**Comment by alcuadrado** [comment]
This should be fixed in `hardaht@rc`.
