### ISSUE TITLE
Vyper compiler support for CircleCI

### ISSUE THREAD

**Issue by ivanzhelyazkov** [nomiclabs/hardhat#1338]
I am using the hardhat vyper plugin to compile the CurveFi contract and it compiles successfully with running docker.

When using CircleCI with a Node image and enabled "Remote docker", the vyper compiler **cannot run** because it uses mounting to put the vyper contracts in the container with this command: 

`docker run -v $(pwd):/code vyperlang/vyper:0.1.0b17 -f combined_json /code/contracts/curve/CurveFi.vy
`

In CircleCI, mounting on a docker container is disabled and the workaround is the following:
```
    docker create -v /code --name code vyperlang/vyper:0.1.0b17 /bin/true
    docker cp $(pwd)/contracts/curve/CurveFi.vy code:/code
    docker run --volumes-from code vyperlang/vyper:0.1.0b17 -f combined_json /code/CurveFi.vy
```

For example, a flag can be put whether to avoid mounting or use the original way, or the command can be replaced by the above three commands. This way, all CircleCI Hardhat builds using Node images will be able to use the vyper compiler.

References:
https://circleci.com/docs/2.0/building-docker-images/#mounting-folders

**Comment by feuGeneA** [comment]
Released in [@nomiclabs/hardhat-vyper v3.0.0](https://github.com/nomiclabs/hardhat/releases/tag/%40nomiclabs%2Fhardhat-vyper%403.0.0)
