### ISSUE TITLE
HH903 err: In test, getContractAt does not work with ABI

### ISSUE THREAD

**Issue by shannonwells** [nomiclabs/hardhat#1340]
# Problem
I am writing a test to verify that abi used to create a contract and emitted as part of a log event can be used with (hardhat ethers plugin) `ethers.getContractAt`.  The example test shows that even though the ABI file exists and is readable, Hardhat fails when provided the ABI to `getContractAt`.  The source code implies that ABI is allowed, however it just tries to turn the ABI string into the contract name.
Here is a TypeScript test case that reproduces the error.  

```TypeScript
import { ethers } from "hardhat";
import chai from "chai";
import * as fs from "fs";
const { expect } = chai;

const parsedABI = (abiPath) => {
  const realPath = fs.realpathSync(abiPath);
  expect(fs.existsSync(realPath)).to.eq(true)
  const fileContent = fs.readFileSync(abiPath);
  const parsed = JSON.parse(fileContent.toString())
  return parsed.abi
}

  async function setup()  {
    const Contract = await ethers.getContractFactory("Migrations");
    const contract = await Contract.deploy();
    // await contract.deployed();
    return contract
  }
describe("Migrate", function () {

 it("can get the contract address and abi, and call getContractAt", async function() {
    const contract = await setup();

    const abiPath = "./artifacts/contracts/Announcer.sol/Announcer.json";
    let parsedabi = parsedABI(abiPath);
    const abiJSONStr = JSON.stringify(parsedabi)
    await ethers.getContractAt(abiJSONStr, contract.address);
  });
});

```
Here is the "Announcer" contract:
```solidity
//SPDX-License-Identifier: Unlicensed
pragma solidity ^0.7.3;

contract Announcer {
    event MyEvent(bytes32 hash, string someData);

    function batch(bytes32 hash, string calldata someData) external {
        emit MyEvent(hash, someData);
    }
}

```
is to include a [Minimal Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).
If you can't do that, then include a link to your repo, and the steps to reproduce the problem. The easiest it
is to reproduce your problem, the faster we are going to be able to fix it.

If you are submitting a feature request, please take the time to clearly describe your use case, and not only
your proposed solution.

**Comment by fvictorio** [comment]
`hre.ethers.getContractAt` receives a contract name, not an ABI. If you want to create a contract instance using an ABI and an address, you can use [`new ethers.Contract`](https://docs.ethers.io/v5/single-page/#/v5/api/contract/contract/-%23-Contract--creating) from core ethers. Keep in mind that in that case you also need to pass a signer, that you get from `hre.ethers.getSigners`.

Please use [our discord server](https://hardhat.org/discord) if you have more questions.

**Comment by wilwade** [comment]
@fvictorio I think then we might have a type bug. It does clearly say `nameOrAbi: string | any[]` in our type still.

https://github.com/nomiclabs/hardhat/blob/master/packages/hardhat-ethers/src/types/index.ts#L29
```typescript
export interface HardhatEthersHelpers {
  provider: ethers.providers.JsonRpcProvider;

  getContractFactory: typeof getContractFactory;
  getContractAt: (
    nameOrAbi: string | any[],
    address: string,
    signer?: ethers.Signer
  ) => Promise<ethers.Contract>;
  getSigner: (address: string) => Promise<SignerWithAddress>;
  getSigners: () => Promise<SignerWithAddress[]>;
}
```

**Comment by fvictorio** [comment]
Oh, sorry, you are right! In that case, the problem is that you are stringifying the ABI, try passing it as an object instead.
