### ISSUE TITLE
Artifact deployment and contract function calls doesn't mine when auto mining is off and interval is 0

### ISSUE THREAD

**Issue by notsegfault** [nomiclabs/hardhat#1343]
I am trying to use the latest Mining modes and I have an issue when using auto to false and interval to 0.

```javascript
[...]
mining: {
  auto: false,
  interval: 0
},
[...]
```

For example, creating a new contract like this:
```javascript
MyArtifact.new(...parameters);
```
stalls forever.

As a workaround I have been calling `hardhat_intervalMine` after some milliseconds, to manually mine a block before waiting for the contract deployment promise.

It's working but then all the functions of the contracts, when called are having the same issue and stall forever as well.

I tried to wrap all the contracts' function inside a wrapper that calls  `hardhat_intervalMine`  but it's not working very well and I feel that at this point it should be reported as an issue hence the current github issue.

```javascript
const promise = artifact.new(...parameters);
await new Promise(r => setTimeout(r, 500));
await triggerIntervalMine();
const contract = await promise;

Object.keys(contract).filter(key => {
  return typeof contract[key] === 'function' &&
  key !== "constructor"
}).forEach(fn => {
  const originalFn = contract[fn];
  contract[fn] = async (...parameters) => {
    console.log(`${fn.toString()} called... `);
    const promise = originalFn(...parameters);

    await new Promise(r => setTimeout(r, 500));
    await triggerIntervalMine();

    return promise;
  }
});

console.log('Deploying...');
return contract;
```

Am I missing something, I didn't see any mention of this in the documentation.

Thanks!

**Comment by alcuadrado** [comment]
That seems like the expected behavior to me. What were you expecting instead?

**Comment by x3devships** [comment]
> That seems like the expected behavior to me. What were you expecting instead?

I expect that if I create a new contract using the .new keyword, the test code continues running. If I await Contract.new(), it will hang the script forever. If i don't await Contract.new(), and then manually mine a block, the return value of Contract.new() is still an unfulfilled promise.

**Comment by x3devships** [comment]
Correction: it's not hanging forever, its just timing out after a very long time, like 700 seconds or something I think.

**Comment by alcuadrado** [comment]
Thanks for the explanation. I would also expect that promise to resolve onces the block is mined. I think this should be reported to truffle, as that's part of @truffle/contract.

**Comment by fvictorio** [comment]
Closing this. Please re-open if you think there's something we can do on our side.
