### ISSUE TITLE
Hardhat-etherscan - SO INTERESTING - says can't verify even if it's already verified.

### ISSUE THREAD

**Issue by novaknole** [nomiclabs/hardhat#1344]
This is one of the strangest errors I've encountered. I might be missing something for sure. There's no way to explain the behaviour without repo. So, here it is:  https://github.com/novaknole/hardhat-bug

* run `yarn` to install dependencies.
* go to `hardhat.config.ts`, find the `PUT HERE` string and replace it with the private key of  RINKEBY network.
* take a look at `./contracts/Test2.sol` and understand what it does. It just does nothing special.  `hardhat-deploy` just deploys `Test2` which deploys `Test` contract in the constructor. Seems all fine..
* Now, go again to `./contracts/Test2.sol` and find the line `uint x = 8282`. Just remember this, we are gonna change back and forth (you will know why soon).
* run `yarn deploy --network rinkeby`. This command deploys `Test2` contract with `DeterministicDeployment:true`.  After the command deploys it, verification starts. You can check what I am doing in `./deploy/verify.ts`. Basically,  I am trying to verify `Test` contract which was deployed from `Test2`'s contstructor. The `verify.ts` file should make sense. So basically, this step will deploy everything and verify `Test` just fine. (**STEP 5** for future reference)
* change `uint x = 8282` to any other number, let's do it together and change it to `uint x = 8283`, so after running `yarn deploy --network rinkeby` again, it starts to deploy from scratch and not uses the already deployed code(that's what `DeterministicDeployment:true` does). So, this will also deploy the new contracts and verify `Test` contract just fine.
* change `uint x = 8283` to `uint x = 8282` and run `yarn deploy --network rinkeby`. You will notice that this command isn't going to start deploying `Test2` which means `Test` won't also be deployed. All good. now, verification process of `Test` starts again.(NOTE: it was already deployed and verified in **STEP 5**, but we get an error:

> 
> The address provided as argument contains a contract, but its bytecode doesn't match any of your local contracts.
> 
> Possible causes are:
>   - Contract code changed after the deployment was executed. This includes code for seemingly unrelated contracts.
>   - A solidity file was added, moved, deleted or renamed after the deployment was executed. This includes files for seemingly unrelated contracts.
>   - Solidity compiler settings were modified after the deployment was executed (like the optimizer, target EVM, etc.).
>   - The given address is wrong.
>   - The selected network (rinkeby) is wrong.

So interesting. No idea what's going on, but I realized one thing.  

Let's go to `contracts/Test2` and comment the line `_registerStandard(type(ERC1271).interfaceId); `. As soon as you do this and repeat all the steps above, the error won't show up..

Hope you can take a look at this as fast as you can.. no idea what's going on..

**Comment by wighawag** [comment]
This was a bug in hardhat-deploy, you posted an issue there : https://github.com/wighawag/hardhat-deploy/issues/86
As mentioned there is is now fixed.

**Comment by novaknole** [comment]
Hi @fvictorio ,  I am closing this now , (Will test it though later) and if something is still wrong, Let's open it again.

Thanks a lot @wighawag
