### ISSUE TITLE
Issues with Hardhat's Impersonate Account

### ISSUE THREAD

**Issue by max-taylor** [nomiclabs/hardhat#1348]
Hi There,

I've just forked main-net on my machine and am using an Alchemy hosted node per the instructions. I was hoping to impersonate an account on my forked main-net but am having issues with the Signer that I would like to impersonate.

Attached is a code sample. I've created a function to simply print the total supply of a deployed contract. When I run that function on workingSigner it prints the expected totalSupply of the token, whereas when I run the same function with the second impersonated signer I get the error: "Error: contract not deployed (contractAddress="0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984", operation="getDeployed", code=UNSUPPORTED_OPERATION, version=contracts/5.0.12)"

Any help would be much appreciated. Thanks!

![image](https://user-images.githubusercontent.com/39660195/112234936-59353700-8c89-11eb-948a-eaa3ab17fab0.png)

**Comment by fvictorio** [comment]
This issue tracker is for bug reports and feature requests only. Use our [discord server](https://hardhat.org/discord) for questions like these.
