### ISSUE TITLE
hardhat-etherscan: verification fails using new compiler version

### ISSUE THREAD

**Issue by ItsNickBarry** [nomiclabs/hardhat#1349]
Solidity `0.8.3` was released today.  I attempted to verify a contract compiled with this Solidity version, but `hardhat-etherscan` returned a generic error:

```
Error in plugin @nomiclabs/hardhat-etherscan: The contract verification failed.
Reason: Fail - Unable to verify
```

The same code compiled with `0.8.2` was verified successfully.  It seems that Etherscan does not yet support version `0.8.3` because it doesn't appear on the web form dropdown.  If this is in fact the reason for the failure, and if it is possible for Hardhat to detect this situation, it would be helpful if the error message were more specific.

**Comment by ItsNickBarry** [comment]
Verification was successful, now that Etherscan supports `0.8.3`, so my theory has not been disproven.

**Comment by fvictorio** [comment]
That message we show is the verbatim response from etherscan, so I don't think we can detect it :disappointed: 

We could manually keep track of the solidity versions supported but... that's probably a bad idea. It would be extra work that's probably not worth it and, more important, it would mean that when etherscan adds support for a new version we need to release a new version of `hardhat-etherscan` and people need to upgrade.

I'll keep this open for a while in case there happens to be some way of doing this, but unless etherscan improves its error messages there's nothing we can do.

**Comment by villarode** [comment]
same error with 0.8.4

$ npx hardhat verify --network rinkeby 0x55845aEe1ee8A1d42d0554FfEfDED290312d8cfe "ipfs://Qma5F27Z2mVgM3uBX9eBDGKpHHXcrXDK82iN1a6ypyxCtt"
Nothing to compile
Compiling 1 file with 0.8.4
Successfully submitted source code for contract
contracts/NFTCollectible.sol:NFTCollectible at 0x55845aEe1ee8A1d42d0554FfEfDED290312d8cfe
for verification on Etherscan. Waiting for verification result...

We tried verifying your contract NFTCollectible without including any unrelated one, but it failed.
Trying again with the full solc input used to compile and deploy it.
This means that unrelated contracts may be displayed on Etherscan...

Successfully submitted source code for contract
contracts/NFTCollectible.sol:NFTCollectible at 0x55845aEe1ee8A1d42d0554FfEfDED290312d8cfe
for verification on Etherscan. Waiting for verification result...

Error in plugin @nomiclabs/hardhat-etherscan: The contract verification failed.
Reason: Fail - Unable to verify

**Comment by JohnChangUK** [comment]
I'm also getting the error
```
Error in plugin @nomiclabs/hardhat-etherscan: The contract verification failed.
Reason: Fail - Unable to verify
```

Has anyone faced this issue before?

**Comment by tercel** [comment]
same error with v0.8.2 
before is ok, but now is fail.

Creating Typechain artifacts in directory typechain for target ethers-v5
Successfully generated Typechain artifacts!
============Start verify contract.============
Nothing to compile
Creating Typechain artifacts in directory typechain for target ethers-v5
Successfully generated Typechain artifacts!
Compiling 1 file with 0.6.12
Compiling your contract excluding unrelated contracts did not produce identical bytecode.
Trying again with the full solc input used to compile and deploy it.
This means that unrelated contracts may be displayed on Etherscan...

Successfully submitted source code for contract
contracts/GamePool.sol:GamePool at 0x17573F56eA46B55843f60912bAc1C67122bc734D
for verification on Etherscan. Waiting for verification result...

(node:14386) UnhandledPromiseRejectionWarning: NomicLabsHardhatPluginError: The contract verification failed.
Reason: Fail - Unable to verify
    at SimpleTaskDefinition.verifySubtask [as action] (/protocol/node_modules/@nomiclabs/hardhat-etherscan/src/index.ts:330:9)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at Environment._runTaskDefinition (/protocol/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
    at Environment.run (/protocol/node_modules/hardhat/src/internal/core/runtime-environment.ts:129:14)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:14386) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:14386) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
✨  Done in 175.38s.

**Comment by ItsNickBarry** [comment]
@villarode @tercel These errors are unrelated, because your compiler versions are not new and are definitely supported by Etherscan.  You may have modified the source code after deploying, forgotten to compile before deploying (meaning old bytecode was deployed), or changed `runs` value.

Closing because @fvictorio says it's impractical to account for which versions are supported by Etherscan.

**Comment by villarode** [comment]
Actually in my particular case once I spelt the address for my metadata at
the end of verify command, all worked out fine)

**Comment by OliveBounty** [comment]
Hello~ I need some help.
I deployed smart contract using hardhat on Rinkeby test network.
after that, I need to verify the smart contract but, below command doesn't work!

npx hardhat etherscan-verify
Error HH303: Unrecognized task etherscan-verify

**Comment by ItsNickBarry** [comment]
The task is called `verify`, not `etherscan-verify`.  @OliveBounty Read the documentation before commenting, and in the future open a new issue rather than commenting on an unrelated issue.

**Comment by ezeamaka2** [comment]
> The task is called `verify`, not `etherscan-verify`. @OliveBounty Read the documentation before commenting, and in the future open a new issue rather than commenting on an unrelated issue.

Still doesn't work

**Comment by Remscar** [comment]
Getting this issue as well

```
We tried verifying your contract ZNSHub without including any unrelated one, but it failed.
Trying again with the full solc input used to compile and deploy it.
This means that unrelated contracts may be displayed on Etherscan...
```

Trying to verify on rinkeby with 0.8.3

**Comment by hahaashton1** [comment]
```
We tried verifying your contract TestContract without including any unrelated one, but it failed.
Trying again with the full solc input used to compile and deploy it.
This means that unrelated contracts may be displayed on Etherscan...
```

Getting the same problem too. I was still able to verify contracts more than 24 hours ago

**Comment by SciWalker** [comment]
I am also facing the same prob. It was working fine 24 hours before, but now it keeps giving unable to verify error. It happens on Rinkeby but I am not sure on the mainnet

**Comment by danj-O** [comment]
same :-(

**Comment by cj-l** [comment]
I was able to verify a few hours ago but can't now - same error as above, solc 0.8.9.

**Comment by digital-fak** [comment]
> 

Same here. solc 0.8.7

**Comment by 0xMoJo7** [comment]
Also having issues with solc 0.8.11

**Comment by BravoNatalie** [comment]
> I was able to verify a few hours ago but can't now - same error as above, solc 0.8.9.

same

**Comment by italosantana** [comment]
Also having issues with solc 0.8.9

**Comment by ItsNickBarry** [comment]
Any issues with compiler versions that have been out for a while and are already supported by Etherscan are unrelated to this issue.  Try `hardhat clean`.

**Comment by renope** [comment]
same

**Comment by NicoAcosta** [comment]
same. fails with multiple compiler versions

**Comment by cj-l** [comment]
I've found that verification fails on rinkeby, but works on ropsten and mainnet with the exact same contract/versions

**Comment by italosantana** [comment]
@cj-l I've tried with ropsten and rinkeby, but neither is working with multiple versions of compilers. Did anyone solve it?

**Comment by italosantana** [comment]
I managed to solve it by looking at the constructor in the contract and looking at the parameters being deployed. 👍🏻

**Comment by JetCyC** [comment]
Error in plugin @nomiclabs/hardhat-etherscan: Failed to send contract verification request.
Endpoint URL: https://api-rinkeby.etherscan.io/api
Reason: Connect Timeout Error

**Comment by fvictorio** [comment]
Locking this because there's nothing we can do on our side. If you think this is a problem with Hardhat (that is, that it's not a problem with Etherscan's API, or your connection, or between the keyboard and the chair), **and if you have minimal reproduction steps**, please open a new issue.
