### ISSUE TITLE
No way to get transaction hash of a failed transaction

### ISSUE THREAD

**Issue by BogdanHabic** [nomiclabs/hardhat#1351]
This is just a "transfer" of the issue listed [here](https://github.com/Tenderly/hardhat-tenderly/issues/12).

From the [Discord conversation](https://discord.com/channels/750408878008827925/774708962565292043/823942476817498162):
```
Ethers seems to support "unchecked" transactions, but since we use a subclassed signer we are not exposing it.
```

**Comment by Huge** [comment]
Does "unchecked" here mean to call https://docs.ethers.io/v5/api/utils/transactions/#utils-serializeTransaction , get the hash and then call `send` separately?

**Comment by Huge** [comment]
Anyway it seems the transactions are not even recorded to the provider as I tested this:
```> await hre.network.provider.request({ method: "eth_getBlockTransactionCountByNumber", params: ["0xba9fb0"]}) // returns '0x1' as this is the block where SC was deployed```
```> await hre.network.provider.request({ method: "eth_getBlockTransactionCountByNumber", params: ["0xba9fb1"]}) // returns null while here we have called a failed/reverted function of the deployed SC```

**Comment by fvictorio** [comment]
`hardhat@2.3.0` now returns the transaction hash of a failed transaction. Check the [release notes](https://github.com/nomiclabs/hardhat/releases/tag/hardhat-core-v2.3.0) to learn more.

If you consider that this doesn't fix this issue, please re-open!

**Comment by Huge** [comment]
I am quite sure it does not work for me.
  On one hand I would have to change the call from the neat and comfy `tx = await someContract.fun( arg1, arg2);` to call the RPC directly via `await hre.network.provider.request` I guess, but what is most suspicious is that `await ethers.provider.getBlock(await ethers.provider.getBlockNumber())` has only the last fine/non-reverting transaction and the reverted one seems nowhere to be queried.

**Comment by fvictorio** [comment]
@Huge My guess is that what's happening to you is that ethers.js first sends an `eth_estimateGas` call, and if that fails it won't send the transaction. If you want to "force" it to send the transaction that will revert, you need to set a fixed gas limit: `someContract.fun(arg1, arg2, { gasLimit: 1000000 })`

If you have more questions related to this, please use [our Discord server](https://hardhat.org/discord). And if you think there's some bug here, or if there's a feature you'd like to request, please submit a new issue.
