### ISSUE TITLE
run task in typescript hardhat config ts cause a HH9 error

### ISSUE THREAD

**Issue by zhouhanseng** [nomiclabs/hardhat#1353]
According to https://hardhat.org/guides/typescript.html I updated `hardhat.config.js` to `hardhat.config.ts`, then I encountered the HH9 error.

This is the js version: https://github.com/zhouhanseng/learn_hard_hat

This is ts version which broken: https://github.com/zhouhanseng/learn_hard_hat/tree/typescript_not_fine

I found it is the `run(task)` function cause the problem

```ts
// hardhat.config.ts
import { run } from "hardhat"
// ...
await run("test")
```

**Comment by rabib** [comment]
This was discussed in #1144.
