### ISSUE TITLE
Custom Network - Use Websocket connection

### ISSUE THREAD

**Issue by ngotchac** [nomiclabs/hardhat#1354]
Hi,

It seems that for [custom networks](https://hardhat.org/config/#json-rpc-based-networks) it is not possible to use a WebSocket connection. At least I couldn't get it working...

**Comment by fvictorio** [comment]
Hi @ngotchac, is it possible that your problem is the same as this issue? https://github.com/nomiclabs/hardhat/issues/588

**Comment by ngotchac** [comment]
Hey, sorry for the late answer. So the issue is, when I run
```bash
$ npx hardhat node --fork "wss://eth-mainnet.ws.alchemyapi.io/v2/<API_KEY>"
```

I get:
```
Error HH604: Error running JSON-RPC server: Only HTTP(S) protocols are supported
```

(while it works using the HTTPS endpoint). So I understand it's not supported yet, so maybe this can be a future feature?

**Comment by fvictorio** [comment]
Oh, I see. Can you tell us why you need that? I mean, that URL is used under the hood by the node, so you won't get any more features by setting a websocket URL. The only scenario where I see this making sense is if you *only* have a we URL, but that seems unlikely?

**Comment by ngotchac** [comment]
Yes you're right, it's actually not really needed, I just figured it would make concurrent requests a bit faster, but the cost of opening an HTTP connection is way lower than actually fetching data from an archive node. I'll close this one then, sorry for the noise
