### ISSUE TITLE
Hardhat Network Runs Slow When Using Solidity 0.8.1

### ISSUE THREAD

**Issue by mudgen** [nomiclabs/hardhat#1357]
I noticed that when using Solidity 0.8.1 to execute scripts using hardhat network the scripts run slower than when we were running earlier versions of Solidity.  

Are there plans to speed up smart contract execution when using Solidity 0.8.* ?

**Comment by fvictorio** [comment]
https://github.com/nomiclabs/hardhat/issues/1358#issuecomment-809408291
