### ISSUE TITLE
Compiled vyper contracts are not deployable

### ISSUE THREAD

**Issue by TeNNoX** [nomiclabs/hardhat#1365]
I'm trying to deploy contract compiled with **hardhat-vyper**, but they are missing their `.dbg.json` files. (the solidity ones have them) 
Which in turn choke the **hardhat-deploy** scripts failing to  `getBuildInfo` 
I need support in which part of it is expected and which part is wrong - and how to fix / work around it.

Deploy to local network works fine, but to goerli it does not.

I outlined the part of the issue which happens in the deployment process in the [hardhat-deploy issue](https://github.com/wighawag/hardhat-deploy/issues/94), but **I suppose the underlying issue is caused by the missing build-info of compiled vyper contracts**.

**Workaround:** set `saveDeployments: false` for the network

**Comment by wighawag** [comment]
It looks indeed like hardhat-vyper do not generate the dbg file that then link to the build-info file

Without it hardhat-deploy could continue with the deployment, but this would mean that source verification (and other features relying on extra build data (solc output)) would fails

**Comment by TeNNoX** [comment]
Please note that it's not only the link missing but the whole build-info. See my `build-info/5abc123.json`:
![Screenshot from 2021-04-02 14-38-44](https://user-images.githubusercontent.com/2084639/113416246-2eea2480-93c1-11eb-9284-125fec50fb34.png)
(see here that it only contains the build-info for the solidty contract, no the vyper ones)

**Comment by TeNNoX** [comment]
Posted a question to the Vyper team:
https://gitter.im/vyperlang/community?at=60671214db595f5599ceda9e

**Comment by alcuadrado** [comment]
> Without it hardhat-deploy could continue with the deployment, but this would mean that source verification (and other features relying on extra build data (solc output)) would fails

I'm confused about this. What do you mean? Vyper contracts are not compiled by solc.

**Comment by alcuadrado** [comment]
I just read this message of your on gitter, @wighawag 

> Ok, thanks fubuloubu i suppose the vyper compiler is deterministic and so i can use the input + compiler version info to verify source later

The answer there is yes. That info is enough.

Also note that the current build info format is tied to solc. If we were to introduce better debugging info for vyper we probably wont use build infos, but rather directly `.dbg.json` files with a different format, as vyper compiles files individually, so there's not need for build infos.

**Comment by wighawag** [comment]
@alcuadrado does hardhat-vyper at leats give me the vyper source and version used by the artifact ?
