### ISSUE TITLE
The timestamp of the genesis block can be in the future

### ISSUE THREAD

**Issue by fvictorio** [nomiclabs/hardhat#1389]
Easiest way to reproduce this is to initialize a hardhat project and run this script with `hh run`:

```js
async function main() {
  console.log(Date.now());

  const blockTimestamp = (await network.provider.send("eth_getBlockByNumber", ["0x0", false])).timestamp

  console.log(parseInt(blockTimestamp.slice(2), 16));
}

main()
  .then(() => process.exit(0))
  .catch(error => {
    console.error(error);
    process.exit(1);
  });
```

Some example results of running this:

```
$ hh run script.js
1617980772445
1617980773

$ hh run script.js
1617980775866
1617980777

$ hh run script.js
1617980778351
1617980779
```

Notice that the first line is the result of `Date.now()`, which is before the timestamp of the genesis block.

@iamdefinitelyahuman suggested that this could be a rounding thing since block timestamps are in seconds.

**Comment by alcuadrado** [comment]
Fixed in #1387
