### ISSUE TITLE
hardhat_reset is not properly cleaning the state

### ISSUE THREAD

**Issue by fvictorio** [nomiclabs/hardhat#1396]
As reported by @CodeForcer:

```
Error example:

1. Fork block 100
2. Run test
3. Fork block 200
4. Test fails as block chain has some of the state created in step (2)

Fix:

1. Fork block 100
2. Run test
3. Fork block 100
4. Evm mine one block
5. Fork block 200
6. Test works
```

**Comment by feuGeneA** [comment]
@fvictorio is reaching out to the original reporter (on Discord) for more information.

**Comment by fvictorio** [comment]
Nathan mentioned that he didn't run into this again, and I don't know how we can reproduce it without guessing, so let's just close this for now.
