### ISSUE TITLE
incorrect Error on typo in `console`

### ISSUE THREAD

**Issue by Huge** [nomiclabs/hardhat#1399]
```
await hre.network.provider.request({ method: "eth_getBlockTransactionCountByNumber", params: ["0xba9fb0"]}
await hre.network.provider.request({ method: "eth_getBlockTransactionCountByNumber", params: ["0xba9fb0"]}
^^^^^

Uncaught:
SyntaxError: await is only valid in async functions and the top level bodies of modules
``` 
while obviously the problem is the missing `)`.

(Found when investigating https://github.com/nomiclabs/hardhat/issues/1351 )

**Comment by alcuadrado** [comment]
This is a node.js error, not ours. Unfortunately, there's nothing we can do about it.

`npx hardhat console` is the same as running `node --require hardhat/register`, is not our own repl.
