### ISSUE TITLE
BUG Hard Hat Initial Install Failing (Error HH1 for project that ran npm install DevDependancy in package.json)

### ISSUE THREAD

**Issue by Leon-Africa** [nomiclabs/hardhat#1400]
Hard Hat initial install failing

Showing message "Error HH1: You are not inside a Hardhat project."

However already attached in package.json and available in node modules

````
$ npm install --save-dev hardhat

npm WARN deprecated ethereumjs-account@3.0.0: Please use Util.Account class found on package ethereumjs-util@^7.0.6 https://github.com/ethereumjs/ethereumjs-util/releases/tag/v7.0.6
npm WARN deprecated debug@3.2.6: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.1 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.1 (node_modules\mocha\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ hardhat@2.1.2
updated 1 package and audited 353 packages in 40.906s
found 0 vulnerabilities



---------------------------


$ npx hardhat
Error HH1: You are not inside a Hardhat project.

For more info go to https://hardhat.org/HH1 or run Hardhat with --show-stack-traces



-----------------------

$ npx hardhat --show-stack-traces
Error HH1: You are not inside a Hardhat project.

HardhatError: HH1: You are not inside a Hardhat project.
    at Object.getUserConfigPath (C:\Users\mrleo\Blocks\flashswap-hardhat\node_modules\hardhat\src\internal\core\project-structure.ts:27:11)
    at Object.resolveConfigPath (C:\Users\mrleo\Blocks\flashswap-hardhat\node_modules\hardhat\src\internal\core\config\config-loading.ts:26:18)
    at Object.willRunWithTypescript (C:\Users\mrleo\Blocks\flashswap-hardhat\node_modules\hardhat\src\internal\core\typescript-support.ts:15:18)
    at main (C:\Users\mrleo\Blocks\flashswap-hardhat\node_modules\hardhat\src\internal\cli\cli.ts:107:9)

----------------

Package.json
 "homepage": "my_github_url_here",
  "devDependencies": {
    "hardhat": "^2.1.2"
  }

--------------
````
Trace:
https://github.com/nomiclabs/hardhat/blob/ccc4d4d277df25020baaa5820f0a47e80b434bc3/packages/hardhat-core/src/internal/core/project-structure.ts#L19

https://github.com/nomiclabs/hardhat/blob/ccc4d4d277df25020baaa5820f0a47e80b434bc3/packages/hardhat-core/src/internal/core/config/config-loading.ts#L24

https://github.com/nomiclabs/hardhat/blob/ccc4d4d277df25020baaa5820f0a47e80b434bc3/packages/hardhat-core/src/internal/core/typescript-support.ts#L14

https://github.com/nomiclabs/hardhat/blob/ccc4d4d277df25020baaa5820f0a47e80b434bc3/packages/hardhat-core/src/internal/cli/cli.ts#L107

Attempted solution copying hardhat npm module package.json with npm install in local directory results in error:

````
$ npx hardhat

Error HH12: Trying to use a non-local installation of Hardhat, which is not supported.
Please install Hardhat locally using npm or Yarn, and try again.

For more info go to https://hardhat.org/HH12 or run Hardhat with --show-stack-traces
Error: EPERM: operation not permitted, unlink 'C:\Users\mrleo\AppData\Roaming\npm-cache\_npx\27860\node_modules\hardhat\node_modules\keccak\prebuilds\win32-x64\node.napi.node'
    at Object.unlinkSync (fs.js:1136:3)
    at fixWinEPERMSync (C:\Program Files\nodejs\node_modules\npm\node_modules\rimraf\rimraf.js:219:13)
    at rimrafSync (C:\Program Files\nodejs\node_modules\npm\node_modules\rimraf\rimraf.js:319:28)
    at C:\Program Files\nodejs\node_modules\npm\node_modules\rimraf\rimraf.js:350:5
    at Array.forEach (<anonymous>)
    at rmkidsSync (C:\Program Files\nodejs\node_modules\npm\node_modules\rimraf\rimraf.js:349:26)
    at rmdirSync (C:\Program Files\nodejs\node_modules\npm\node_modules\rimraf\rimraf.js:342:7)
    at fixWinEPERMSync (C:\Program Files\nodejs\node_modules\npm\node_modules\rimraf\rimraf.js:217:5)
    at rimrafSync (C:\Program Files\nodejs\node_modules\npm\node_modules\rimraf\rimraf.js:319:28)
    at C:\Program Files\nodejs\node_modules\npm\node_modules\rimraf\rimraf.js:350:5 {
  errno: -4048,
  syscall: 'unlink',
  code: 'EPERM',
  path: 'C:\\Users\\mrleo\\AppData\\Roaming\\npm-cache\\_npx\\27860\\node_modules\\hardhat\\node_modules\\keccak\\prebuilds\\win32-x64\\node.napi.node'
}
````

Am I missing something obvious - looking at the methods in trace I installed Typescript but doing that is not resolving the issue.

**Comment by fvictorio** [comment]
Hi @Leon-Africa. This looks like a setup problem, not a bug, and this issue tracker is not for support (you can use [our discord server](https://hardhat.org/discord) for that).

Please do this and give us that information in the support server:

1. Go to an **empty** directory and repeat those steps (installing hardhat and running `npx hardhat`)
2. If that works, then the problem is with the project where you are installing hardhat. To help with that we'll need to see the `package.json`. But something you can try is to remove the `node_modules` directory and the `package-lock.json` file (or `yarn.lock` if you are using `yarn`), install the dependencies again, and retry.
3. If installing in an empty directory doesn't work, then it might be a real bug, but it's unlikely. If that happens, please tell us your OS, node version and npm version.

**Comment by Leon-Africa** [comment]
Bug was found to be related to install of Hardhat when using Git Bash.

If you are on Windows using Git Bash to install hardhat will result in this issue.

Resolution in the interim is to use Windows CMD to perform the HardHat install with project creation.

After this using Git Bash for the project created via Windows CMD works smoothly.

**Comment by michael-fourie** [comment]
@Leon-Africa Thanks for that, was having this issue just now due to using Git Bash, but using CMD worked fine!

**Comment by mantasfam** [comment]
Hello,
I installed hardhad using Windows CMD. Now npx hardhat works in CMD, but in Git Bash I still get error "Error HH1: You are not inside a Hardhat project."

**Comment by fvictorio** [comment]
@mantasfam check the linked issue: https://github.com/nomiclabs/hardhat/issues/1408 This is a problem with git bash. Try using cmd, powershell or bash in WSL to initialize the project.

**Comment by mantasfam** [comment]
Try yarn instead npm

**Comment by vonwao** [comment]
> Same issue here on Win 10. Tried to install with yarn & nvm via cmd, bash, and powershell. Don't have it installed globally. Been dealing with this for a few days.

I finally got it to work after fiddling with it for many hours, and I'm not sure what caused it to work.  But basically I createad a new project that installed npm pacakges in my root user directory (because no package.json file), and then it works calling with npx.  

It seems like there are some non-standard things they are doing with hardhat since they seem to insist on using npx instead of any other way.   (if I'm wrong then someone please correct me), but I've used node and npm a lot in the past,  and I got so many unusal errors with hardhat that it makes me think there's something non-standard. 🤔 

Anyway, good luck @benjaminmbrown, just try with a new project and if it helps put your package.json a level above it (just wild speculation).  I did install packages with yarn I think.  And then try to run with "npx hardhat compile" and fingers crossed.   Another thing you could try is with a different version of node.

**Comment by iamjasonlevin** [comment]
How would I create the 10 fake ETH addresses if I downloaded someone else's code with the contract, src, etc?

I was following Nader Dabit's[ guide to full-stack ethereum development](https://dev.to/dabit3/the-complete-guide-to-full-stack-ethereum-development-3j13), but when I did **npx hardhat compile**, it said there is nothing to compile.  So, I downloaded his code, and now it is giving me the error listed above.

**Comment by alcuadrado** [comment]
@iamjasonlevin try asking on hardhat.org/discord

**Comment by mosinnik** [comment]
Faced with same issue with npx on windows gitbash with mingw. Solved by re-installing git with enabling support for pseudo consoles

**Comment by villarode** [comment]
> It works on Windows when you use Ubuntu in Windows or any Linux system for that matter. Here's the tutorial: https://ubuntu.com/tutorials/ubuntu-on-windows#1-overview

Isn't using Git Bash enough for replicating Linux on Windows (well, in most cases)?)

**Comment by manziEric** [comment]
any one knows how to solve this on linux terminal ?

**Comment by sdkosm** [comment]
I have also faced same error in npx hardhat....
![Command Prompt 28-12-2021 01_37_37 PM](https://user-images.githubusercontent.com/51430350/147545808-4cc62af4-404e-4c22-bc64-2588082730be.png)

**Comment by maaeyeng** [comment]
npm uninstall hardhat && npm install --save-dev hardhat

**Comment by gianlucajahn** [comment]
> Faced with same issue with npx on windows gitbash with mingw. Solved by re-installing git with enabling support for pseudo consoles

Worked for me, too.

**Comment by AIRCOM13** [comment]
Hello guys, I faced this issue 

hedi@MBP-de-Hedi Yes % npx hardhat                                                                                        
An unexpected error occurred:

Error: Cannot find module '@nomicfoundation/hardhat-toolbox'
Require stack:
- /Users/hedi/hardhat.config.js
- /Users/hedi/Desktop/Yo/Yes/node_modules/hardhat/internal/core/config/config-loading.js
- /Users/hedi/Desktop/Yo/Yes/node_modules/hardhat/internal/cli/cli.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:946:15)
    at Function.Module._load (node:internal/modules/cjs/loader:787:27)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/hedi/hardhat.config.js:1:1)
    at Module._compile (node:internal/modules/cjs/loader:1112:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Function.Module._load (node:internal/modules/cjs/loader:834:12)
    at Module.require (node:internal/modules/cjs/loader:1012:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/hedi/hardhat.config.js',
    '/Users/hedi/Desktop/Yo/Yes/node_modules/hardhat/internal/core/config/config-loading.js',
    '/Users/hedi/Desktop/Yo/Yes/node_modules/hardhat/internal/cli/cli.js'
  ]
}

do you have any advice ?

**Comment by Leon-Africa** [comment]
Hey @AIRCOM13 thanks for your contribution. The question is more fitting for stackoverflow or if github create a separate issue instead given it's different to this one ````Error HH1: You are not inside a Hardhat project````. 

I had a look at the error it seems to be looking for a package called ````@nomicfoundation/hardhat-toolbox````. My recommended solution would be to add ````'@nomicfoundation/hardhat-toolbox```` to your ````package.json```` and do a fresh ````npm install```` (Hardhat recommends using npm 7 or later i.e avoid using yarn in this case). This would resolve that issue.

**Comment by Leon-Africa** [comment]
May be more to the issue you are facing:

[1] https://github.com/NomicFoundation/hardhat/actions/runs/2469348271
[2] https://github.com/nomicfoundation/hardhat/tree/master/packages/hardhat-toolbox

Do you face the issue when running ````npx hardhat````?
