### ISSUE TITLE
eter

### ISSUE THREAD

**Issue by 78051301012** [nomiclabs/hardhat#1410]
Thank you for using Hardhat and taking the time to open an issue!

**Note that this issue tracker is not a support channel.**

- For help with Hardhat and Hardhat network, please use our [Discord server](https://hardhat.org/discord).
- For help with ethers.js, please go to [its Github Discussions](https://github.com/ethers-io/ethers.js/discussions).

If you are reporting a bug, please include reproduction steps. The best way to do this
is to include a [Minimal Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).
If you can't do that, then include a link to your repo, and the steps to reproduce the problem. The easiest it
is to reproduce your problem, the faster we are going to be able to fix it.

If you are submitting a feature request, please take the time to clearly describe your use case, and not only
your proposed solution.

**Comment by alcuadrado** [comment]
I assume this was accidentally submitted, so I'm closing it.
