### ISSUE TITLE
Smart contracts lose state when called by other contracts

### ISSUE THREAD

**Issue by MortenTobiasNielsen** [nomiclabs/hardhat#1411]
It seems like contracts loss state when they are called from other contracts (or maybe I am just doing it wrong)

I have created an example of the problem as simple as I could in this repo: [https://github.com/MortenTobiasNielsen/hardhat-bug-report](url)

1. Clone the repo
2. npm install
3. npx hardhat test

The value of a variable called test1 will then be printed for each step. It will be set for all calls made directly to "Token2", but when a call is made to "Token1" which then call "Token2" then the variable is no longer set. 

<img width="391" alt="Error" src="https://user-images.githubusercontent.com/48355480/115345956-d16f1980-a1af-11eb-805c-14f197aa784f.png">

**Comment by alcuadrado** [comment]
Hey @MortenTobiasNielsen, this is working as expected.

The address you hardcoded in `Token1.sol` (`0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512`) is only valid during the first test. In the second one, token2 ends up in a different address because the account that deploys it has a different nonce.

Let us know if you have any other problem.

**Comment by MortenTobiasNielsen** [comment]
Hey @alcuadrado, 

Thanks for the response. I can see that if I move the contract address check down into the transferFrom check, then it works. I am though a little in doubt as to why that happens. Is this correctly understood?:

- In the first test a smart contract for token2 is deployed with address "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512" and the check therefore succeed. 
- In the second test a smart contract for token2 is deployed with another address. Therefore no smart contract with the address "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512" is available when "interactWithToken2" is called and a new contract of token2 is silently being deployed to accommodate for this call to that address?

That got a little confusing, but I hope it is understandable. :)

**Comment by fvictorio** [comment]
@MortenTobiasNielsen I think what you are missing is the fact that `beforeEach` is called before each `it` test. So this is what is happening:

1. Your `beforeEach` is called. `token2` is deployed in the address that you expect
2. The first `it` is executed and it passes
3. `beforeEach` is called again, and token2 now points to a new deployed contract
4. The second `it` is called, and it assumes that `token2` is in certain address. But you are doing the `approve` call with the second deploy of `Token2`, and therefore the function fails.

Does that make sense?

**Comment by MortenTobiasNielsen** [comment]
Hey @fvictorio , 

Thanks for the elaboration. I thought that every `it` created a new environment and each run-through therefore were "clean" - but it seems like the environment stays the same. So in the second `it` `token1` is calling the first deployment of `token2` when `interactWithToken2` is called. 

I think I got it now - thanks a lot for your time @alcuadrado and @fvictorio 👍

**Comment by alcuadrado** [comment]
We don't do anything silently, Hardhat, in general, tries to be as transparent as possible with its users. 

What is happening is that the state of the network is shared between tests. Just like in normal unit tests, you need to keep that in mind to make your tests independent from each other. You can think of the network as a global variable that gets mutated with each tx.
