### ISSUE TITLE
Awful error when balance is a hex string

### ISSUE THREAD

**Issue by fvictorio** [nomiclabs/hardhat#1427]
If hardhat network is configured with an account with a balance like `"0x123"`, the node crashes with this error:

```
Error HH604: Error running JSON-RPC server: Invalid character
```

We should do something better here.

**Comment by Bidon15** [comment]
Two ideas in my mind:
1. Convert the hex to dec, so the node won't crash
2. Be more precise with the error message, as the current one is misleading

is it an expectation that hex type is not allowed to be passed as balance? 
If no, then I could drop a PR for the 1st option. Otherwise, 2nd

Would like to hear your thoughts

**Comment by alcuadrado** [comment]
I think a good way to solve this would be to extend the config validation logic so that it validates this using io-ts. 

I'd go with dec only, as relaxing that restriction can be done in a backwards-compatible way.

**Comment by fvictorio** [comment]
To expand on what @alcuadrado said: I think we should replace the `t.string` here:

https://github.com/nomiclabs/hardhat/blob/0b44fc42f9af05a0318be643808fea6f29c079c4/packages/hardhat-core/src/internal/core/config/config-validation.ts#L88

with a io-ts codec that checks that the value is a string with a proper decimal value. An example of something like that is this one:

https://github.com/nomiclabs/hardhat/blob/0b44fc42f9af05a0318be643808fea6f29c079c4/packages/hardhat-core/src/internal/core/config/config-validation.ts#L68-L81

`io-ts` is not very intuitive, and its documentation is... not very pedagogic, but it's not that hard to play it by ear.

This also needs tests. They are under the `test/internal/core/config/config-validation.ts` file.

**Comment by Bidon15** [comment]
Thanks for your thoughts, ideas and guides @fvictorio @alcuadrado ! 

https://github.com/nomiclabs/hardhat/pull/1458
