### ISSUE TITLE
 Error: Transaction reverted: trying to deploy a contract whose code is too large

### ISSUE THREAD

**Issue by sriharikapu** [nomiclabs/hardhat#1430]
https://github.com/ethereum-ts/TypeChain/issues/375

Solidity Version 0.7.1
Length of solidity file is 3000+ lines

Issue : Deployment isn't working when writing tests

**Comment by zemse** [comment]
You can see https://eips.ethereum.org/EIPS/eip-170, which specifies the deployment of a contract whose bytecode is more than 24 kb should fail.

**Comment by fvictorio** [comment]
Closing this since, as @zemse mentioned, this is expected behavior. Note that you have an `allowUnlimitedContractSize` option in the [config](https://hardhat.org/config/).

**Comment by dzmitry-lahoda** [comment]
https://hardhat.org/hardhat-network/reference#allowunlimitedcontractsize

**Comment by jmendiola222** [comment]
I can't make it work on `hardhat coverage`, it's still throwing the error and the test, that otherwise work, fail when on coverage. 
I tried both in the `hardhat.config` file:
```
networks: {
    hardhat: {
      ...
      allowUnlimitedContractSize: true,
    },
```
and in the `solcover` file:
```
providerOptions: {
    ....
    allowUnlimitedContractSize: true,
  },
```
Any idea how to make it work on coverage? Thanks

**Comment by solchef** [comment]
The following configuration on hardhat.config.ts works

`settings: {
      optimizer: {
        enabled: true,
        runs: 200,
        details: { yul: false },
      },
    },
`
**NB**

yul: true and stackAllocation: true are just defaults when the optimizer is enabled

**Comment by calmacfadden** [comment]
Assuming you already have the optimizer enabled then you need to add the allowUnlimitedContractSize: true config to the hardhat.config.js file, but start with enabling the optimizer first. 

```
require("@nomicfoundation/hardhat-toolbox");
require('solidity-coverage')
require('@openzeppelin/hardhat-upgrades');

/** @type import('hardhat/config').HardhatUserConfig */
module.exports = {
  networks: {
    hardhat: {
      allowUnlimitedContractSize: true
    }
  },
  solidity: {
    compilers: [
      {
        version: "0.8.7",
        settings: {
          optimizer: {
            enabled: true,
            runs: 200,
          },
        },
      },
      {
        version: "0.8.12",
        settings: {
          optimizer: {
            enabled: true,
            runs: 200,
          },
        },
      }
    ]
  },
};

```
