### ISSUE TITLE
Balance of msg.sender shouldn't be modified whan a view function is called

### ISSUE THREAD

**Issue by fvictorio** [nomiclabs/hardhat#1436]
Given this contract:

```solidity
contract Foo {
  function printBalance() public view returns(uint256) {
    return msg.sender.balance;
  }
}
```

Deploying it and doing this in Hardhat network:

```js
console.log((await ethers.provider.getBalance(signer.address)).toString());
console.log((await foo.printBalance()).toString());
```

prints two different numbers, while doing the same thing in Rinkeby prints the same number.

**Comment by alcuadrado** [comment]
I guess Rinkeby uses `gasPrice` 0 by default for calls. The intrinsic cost of the fake tx we run to implement `eth_call` is debited from the account before the EVM Message is executed.

**Comment by alcuadrado** [comment]
Does this still happen if you use an explicit gasPrice of 0? What if you use the same non-zero explicit gas price on both HH Network and Rinkeby?

**Comment by wiasliaw** [comment]
I'm testing other testnet, link below. It is wired that only hardhat network has the problem. Could this error happen in emv?

https://github.com/wiasliaw/bug-report-1436

**Comment by alcuadrado** [comment]
I've confirmed my theory by reading geth's code. It is because of the `gasPrice`.

**Comment by alcuadrado** [comment]
Adding this to the London project, as it forced us to reevaluate how we handle this, and fixing it.
