### ISSUE TITLE
Accept `null` in the "to" field of a transaction

### ISSUE THREAD

**Issue by fvictorio** [nomiclabs/hardhat#1441]
To deploy a contract in hardhat, you need to send a tx without the `to` field. But geth also accepts a `"to": null` field for the same thing, and its client uses that, so we probably should too.

**Comment by Bidon15** [comment]
Hey, I would like to help with this issue as much as have a more deep dive experience
 
Do you mean to add null into **to** for this interface? 
https://github.com/nomiclabs/hardhat/blob/7861f7b0290eaa23ccfc6171e7fdfc93c57252fe/packages/hardhat-core/src/internal/core/jsonrpc/types/input/transactionRequest.ts#L25-L33

I've also seen the transaction helper for tests. Guess it has to be edited accordingly 🧐

**Comment by fvictorio** [comment]
This is going to be a little harder than it seems. The problem is that geth supports `null` as a value in a bunch of places. Our guess is that _any_ value that is optional can also be null (again, in geth, but we try to be as compatible with it as we can). So the proper fix might be to modify the `optional` io-ts codec to accept both missing values and null values. But before doing that, we need to double-check that assumption about geth.
