### ISSUE TITLE
Print hardhat config path in verbose mode

### ISSUE THREAD

**Issue by fvictorio** [nomiclabs/hardhat#1443]
Sometimes users don't realize there is a `hardhat.config.js` in a parent directory, and complain about not getting the initialization prompt. The best way to quickly find out if that's the case would be to have a way to print the detected config file. The easiest way to do this is to just log it in verbose mode. That way we can ask them to just do `npx hardhat --verbose` and see where the file is located.

**Comment by Bidon15** [comment]
I guess, I am visiting this repo at the right moment 😁

https://github.com/nomiclabs/hardhat/pull/1454

**Comment by fvictorio** [comment]
Released in `hardhat@2.3.0`. Thanks @Bidon15!
