### ISSUE TITLE
Hardhat_reset resets to 0th block vs the block I specify

### ISSUE THREAD

**Issue by borseno** [nomiclabs/hardhat#1462]
Hi guys.

When I send a hardhat_reset, it suddenly reverts to the 0th block vs to the block I specify.
To reproduce, please visit this [repo](https://github.com/borseno/HardhatResetBug/) (includes the steps in readme)

By the way, I'm running this from Ubuntu 20.04.2 LTS.

**Comment by fvictorio** [comment]
Hi @borseno, thanks for reporting this. I don't have the necessary stuff installed to run an F# project. Could you please log the JSON object you are sending with the `hardhat_reset` call and share it here?

**Comment by borseno** [comment]
@fvictorio it looks like this:

{"forking":{"jsonRpcUrl":"https://eth-mainnet.alchemyapi.io/v2/5VaoQ3iNw3dVPD_PNwd5I69k3vMvdnNj","blockNumber":12330245}}

**Comment by fvictorio** [comment]
I can't reproduce this with plain calls. Please check this and see if it happens to you:

1. Run `npx hardhat node --url ALCHEMY_URL
2. In another terminal, run this sequence of commands:

```bash
curl -X POST --data '{"jsonrpc":"2.0","id":1,"method":"eth_blockNumber","params":[]}' -H 'Content-Type:application/json' http://localhost:8545
curl -X POST --data '{"jsonrpc":"2.0","id":1,"method":"hardhat_reset","params":[{"forking": {"jsonRpcUrl": "ALCHEMY_URL", "blockNumber": 12330245}}]}' -H 'Content-Type:application/json' http://localhost:8545
curl -X POST --data '{"jsonrpc":"2.0","id":1,"method":"eth_blockNumber","params":[]}' -H 'Content-Type:application/json' http://localhost:8545
```

The first command should return the current mainnet block number, the second one should return true, and the third one should return `0xbc2505`.

If this works for you, then you might have a problem with your code, or there might be an issue in the web3 library you are using.

**Comment by borseno** [comment]
Indeed it was an issue on my side. 

This is the update in F# code that made it work: https://github.com/borseno/HardhatResetBug/commit/3e6e10992eedaf6f905ccef0e6540144a0568c85
