### ISSUE TITLE
Error: Transaction reverted and Hardhat couldn't infer the reason

### ISSUE THREAD

**Issue by JoyCood** [nomiclabs/hardhat#1477]
error message:

> web3_clientVersion
eth_chainId
eth_accounts (2)
eth_chainId
eth_estimateGas
eth_gasPrice
eth_sendTransaction
  Contract call:       Diamond#<unrecognized-selector>
  Transaction:         0x683b56b9df884d7ce0a0db6dedabf806694a50e9aa94f23ac99a589ed08f0879
  From:                0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
  To:                  0xb7f8bc63bbcad18155201308c8f3540b07f84f5e
  Value:               0 ETH
  Gas used:            51257 of 51657
  Block #24:           0x89a308c60799d153e68bf3301d831853eb7cddfc2f9f6a702088b43c1555d344
  eth_chainId
    eth_getTransactionByHash
    eth_blockNumber
eth_chainId (2)
eth_estimateGas (2)
eth_call
  Contract call:       Diamond#<unrecognized-selector>
  From:                0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
  To:                  0x9a9f2ccfde556a7e9ff0848998aa4a0cfd8863ae
  eth_sendTransaction
  Contract call:       Diamond#<unrecognized-selector>
  Transaction:         0xe7a4ff2f211a7f3b7f64ca9456ea73c9d740b95ae1099f0e8c3898550ff011ef
  From:                0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
  To:                  0x9a9f2ccfde556a7e9ff0848998aa4a0cfd8863ae
  Value:               0 ETH
  Gas used:            388348 of 424755
  Block #25:           0xea27d937dffaa4f4dbb47114eb8fb55ab8cd97c9cb07d7d270a5edcc193d5df2

eth_sendTransaction
  Contract call:       Diamond#<unrecognized-selector>
  Transaction:         0x7dd650d6c9f77b33a262581fa36f4c891b5648578cfd3d9cb80b0be81b9fc820
  From:                0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
  To:                  0x9a9f2ccfde556a7e9ff0848998aa4a0cfd8863ae
  Value:               0 ETH
  Gas used:            418575 of 424755
  Block #26:           0x946474d9af3aee5a58a77c178af2c9588a443137df894d04aece06f26c36c05c

  Error: Transaction reverted and Hardhat couldn't infer the reason. Please report this to help us improve Hardhat.
      at ERC721MarketplaceFacet.addERC721ListingItem (contracts/marketplace/libraries/LibERC721Marketplace.sol:67)
      at ERC721MarketplaceFacet.addERC721Listing (contracts/marketplace/facets/ERC721MarketplaceFacet.sol:131)
      at ERC721MarketplaceFacet.addERC721Listing (contracts/marketplace/facets/ERC721MarketplaceFacet.sol:93)
      at Diamond.<fallback> (contracts/shared/Diamond.sol:27)
      at HardhatNode._mineBlockWithPendingTxs (/Users/knight/Projects/valuemaster/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:1154:23)
      at HardhatNode.mineBlock (/Users/knight/Projects/valuemaster/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:377:16)
      at EthModule._sendTransactionAndReturnHash (/Users/knight/Projects/valuemaster/node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:1376:18)
      at HardhatNetworkProvider._sendWithLogging (/Users/knight/Projects/valuemaster/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:119:22)
      at HardhatNetworkProvider.request (/Users/knight/Projects/valuemaster/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:99:18)
      at JsonRpcHandler._handleRequest (/Users/knight/Projects/valuemaster/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/handler.ts:188:20)
      at JsonRpcHandler._handleSingleRequest (/Users/knight/Projects/valuemaster/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/handler.ts:167:17)

javascript:
`
    const { meta } = require('./meta.js')
    const tokens = [
        {"id": 1, "price": "1"}, 
        {"id": 2, "price": "2"}, 
    ]

    async function main() {
        const metaVars = await meta()
        const slimeDiamond = metaVars.slimeDiamond
        const valuemasterDiamond = metaVars.valuemasterDiamond

        const erc721MarketplaceFacet = await ethers.getContractAt('ERC721MarketplaceFacet', valuemasterDiamond)
        const slimeFacet = await ethers.getContractAt('SlimeFacet', slimeDiamond)

        await slimeFacet.setApprovalForAll(valuemasterDiamond, true)

        await tokens.map(async token => {
            await erc721MarketplaceFacet.addERC721Listing(slimeDiamond, token.id, ethers.utils.parseEther(token.price))
        })
        let listings = await erc721MarketplaceFacet.getERC721Listings(0, "listed", 20)
        console.log("listings: ", listings)
    }

    if (require.main === module) {
        main()
	    .then(() => process.exit(0))
	    .catch(error => {
	        console.error(error)
	        process.exit(1)
	    })
    }`

**Comment by fvictorio** [comment]
@JoyCood is your repo public? If not, could you tell us how to reproduce this besides the script you shared?

**Comment by JoyCood** [comment]
> @JoyCood is your repo public? If not, could you tell us how to reproduce this besides the script you shared?

you can check this [repo](https://github.com/aavegotchi/aavegotchi-contracts/blob/master/contracts/Aavegotchi/libraries/LibERC721Marketplace.sol) on line 67, and call the contract function `addERC721ListingItem ` using `
const tokens = [
    {"id": 1, "price": "1"}, 
    {"id": 2, "price": "2"}, 
]
**// below two comment out lines work fine, but use the loop statement will failed**
  //await erc721MarketplaceFacet.addERC721Listing(slimeDiamond, tokens[0].id, ethers.utils.parseEther(tokens[0].price))
   // await erc721MarketplaceFacet.addERC721Listing(slimeDiamond, tokens[1].id, ethers.utils.parseEther(tokens[1].price))

    await tokens.map(async token => {
        await erc721MarketplaceFacet.addERC721Listing(slimeDiamond, token.id, ethers.utils.parseEther(token.price))
    })
` l

**Comment by sirpy** [comment]
we started having these issue when add/removing a single line from the contract
we are using solidity 8 though.
but it is still strange that revert reason works ok, but after adding a line of code in unrelated place, some revert reasons stop working. we validated that it reverts at the correct place

**Comment by fvictorio** [comment]
Hi, Hardhat [2.4.0](https://github.com/nomiclabs/hardhat/releases/tag/hardhat-core-v2.4.0) now has a better error detection mechanism that might fix this. Please try it out and feel free to re-open this issue if you are still having issues.
