### ISSUE TITLE
Error with tests - Hardhat Tutorial

### ISSUE THREAD

**Issue by damianlluch** [nomiclabs/hardhat#1479]
Hi, I'm following the official Hardhat tutorial, and I'm getting errors when running the tests.

![image](https://user-images.githubusercontent.com/1463804/119277343-5f12ae80-bc1f-11eb-96aa-6e9edfe2171c.png)
![image](https://user-images.githubusercontent.com/1463804/119277368-7e114080-bc1f-11eb-8a93-886114753dcd.png)

any suggestions?

thanks

**Comment by alcuadrado** [comment]
Hey, this is not the right place to ask for support. Please use hardhat.org/discord

BTW, I think you didn't installed the ethers plugin. Check your config.
