### ISSUE TITLE
Module not found: Can't resolve 'console'

### ISSUE THREAD

**Issue by grimelion** [nomiclabs/hardhat#1481]
After installing hardhat@2.3.0, the `Module not found: Can't resolve 'console' in '/Users/grimelion/ETH/metamask-3box-boilerplate/node_modules/@sentry/node/esm/integrations'` error appears when importing ethers:
`const { ethers } = require('hardhat');`

**Comment by alcuadrado** [comment]
Hey @grimelion, can you provide the full strack trace?

Also, are you using `"type": "module"` in your package.json?
