### ISSUE TITLE
Show a warning when the config is empty

### ISSUE THREAD

**Issue by fvictorio** [nomiclabs/hardhat#1490]
An user could make something like this in the config:

```ts
let config: HardhatUserConfig = {
  ...
}
```

and forget to do `export default config`. We should show a warning when that happens.

**Comment by alcuadrado** [comment]
I don't think this is feasible, as a file that doesn't export anything in node is equivalent to one exporting an empty object, and that's a valid config.

**Comment by fvictorio** [comment]
Oh, I know, but I think it's a good trade-off. We can just check `Object.keys(config).length` and I think it's way more likely that this helps someone than this annoys a user that explicitly wants an empty config (I don't see why anyone would do that).

**Comment by Endlessline** [comment]
I took a stab at this, is it something you all think would be useful? It sounds like it still may be up for debate.

**Comment by fvictorio** [comment]
Fixed in [`hardhat@2.8.1`](https://github.com/nomiclabs/hardhat/releases/tag/hardhat%402.8.1).
