### ISSUE TITLE
can't find mint function in test code

### ISSUE THREAD

**Issue by noobmaster19** [nomiclabs/hardhat#1495]
Hey guys, im trying to call the ERC20 mint function from the testing code but im met with an error

Here's the error message:
`Token.connect(...).mint is not a function`

Here's a skinned down version of my TESTing code:

```
describe("Token contract", function () {
    let TokenContract;
    let Token;
    beforeEach(async () => {
        TokenContract = await ethers.getContractFactory("Token");
        [owner, alice, bob, carol, fakeRouter] = await ethers.getSigners();
        Token = await Contract.deploy(); //sender is by default owner/first address
     });
    it('onlyOwner modifier', async () => {
        await expect(Token.connect(alice).mint(bob.address, 
        10)).to.be.revertedWith('operator: caller is not the operator')
    });
```
Here is the mint function residing in my smartcontract code:

```
/// @notice Creates `_amount` token to `_to`. Must only be called by the owner(MasterChef).
function mint(address _to, uint256 _amount) public onlyOwner {
    _mint(_to, _amount);
    _moveDelegates(address(0), _delegates[_to], _amount);
}
```
Here's a skinned down version of `console.log(Token)`

```
  'mint(address,uint256)': [Function (anonymous)],
  'mint(uint256)': [Function (anonymous)],
```

Any idea why the console might be telling me that .mint function cant be found?

**Comment by fvictorio** [comment]
@noobmaster19 did you read the commit template before submitting this issue? The issue tracker is only for bugs or feature requests. For questions, use our [discord server](https://hardhat.org/discord).
