### ISSUE TITLE
Vyper plugin not work when compiling smart contract

### ISSUE THREAD

**Issue by afeiluo** [nomiclabs/hardhat#1506]
![image](https://user-images.githubusercontent.com/6848479/120576971-3330cd80-c456-11eb-9227-7db050cdc147.png)
when I compiling it says "KeyError: 'combined_json", I cannot figure out what's wrong with it
https://vyper.readthedocs.io/en/v0.1.0-beta.10/compiling-a-contract.html  shows '-f' option can specify output format , how can i config  the same option in hardhat.config.js

**Comment by fvictorio** [comment]
Hi @afeiluo. I'm not sure where that error comes from, but just in case: this doesn't seem to happen with the latest vyper version (`0.2.12`). I'm not familiar with vyper so I don't know how old `0.1.0b4` is and if it makes sense for us to support it.
