### ISSUE TITLE
Error HH109: Network connection timed-out. Please check your internet connection and networks config

### ISSUE THREAD

**Issue by Agin-DropDisco** [nomiclabs/hardhat#1507]
[Sample Task  --> ] https://github.com/Agin-DropDisco/MT-Bg/blob/main/deploy.js

This Error only for NetworkID 1287;
```bash
        moonbase: {
            url:"https://rpc.testnet.moonbeam.network",
            accounts: [PK_1],
            network_id: 1287,
            gasPrice: 10000000,
            timeout: 100000
        },
 ```

**Comment by fvictorio** [comment]
Hi @Agin-DropDisco. This network works for me. Are you sure this isn't really a connection issue?

**Comment by Agin-DropDisco** [comment]
i guess not @fvictorio , cuz its work when i deployed it to Matic (NetworkId: 80001), Rinkeby or Ropsten.
Please see my Task

**Comment by alcuadrado** [comment]
Hey @Agin-DropDisco, 

That error can only be raised if we actually get a timeout when connecting to the node. The task can't influence that.

Are you behind a proxy or VPN? Are you sure that rpc endpoint is stable?

**Comment by fvictorio** [comment]
> I suspect this is an issue in moonbeam's rpc, and that you should report it there.

I was going to say the same thing. Also notice that JSON-RPC network have a `timeout` property that you can configure.

I'm going to close this since I'm pretty sure there's nothing we can do on our side, but please re-open if that's not the case.
