### ISSUE TITLE
Put a name field in the contract object

### ISSUE THREAD

**Issue by sshmaxime** [nomiclabs/hardhat#1513]
`contract.constructor.name` doesn't give the proper output when using template/generic (https://stackoverflow.com/questions/47312116/how-to-get-generic-classt-name-of-typescript) therefore it would be a good thing if a `name` field would be in a contract object

**Comment by fvictorio** [comment]
Hi @sshmaxime. I don't understand what this issue is about. Can you tell us what you are trying to do and what error are you getting?

**Comment by sshmaxime** [comment]
I'm trying to find a proper way to pass a contract to a function and, in it, get the name of the passed contract.

```
const basicDeploy: deployFct = async <C extends Contract>(toDeployContract: Promise<C>): Promise<C> => {
    const contract = await toDeployContract;
    console.log("ContractName: ", ***something***);
    return contract;
};
```

**Comment by fvictorio** [comment]
Hmm, I see. I don't know how we could do this without monkey-patching ethers even more, and we want to avoid that (in fact, we want to remove all our monkey-patching at some point).

@alcuadrado wdyt?

**Comment by sshmaxime** [comment]
Maybe I should redirect this feature to ethers directly ?

**Comment by alcuadrado** [comment]
Yeah, i think it's within the scope of ethers. 

We try to change ethers as little as possible. We did in a few occasions, and learned the hard way that it's the best thing we can do.

**Comment by sshmaxime** [comment]
make sense 👌
