### ISSUE TITLE
Feature: override `readArtifact` during `getContractFactory()`

### ISSUE THREAD

**Issue by heri16** [nomiclabs/hardhat#1515]
Certain plugins like `hardhat-deploy-ethers` would benefit from being able to override `readArtifact` during `getContractFactory()` from `packages/hardhat-ethers/src/internal/helpers.ts`.

`hardhat-deploy-ethers` currently does not extend from `@nomiclabs/hardhat-ethers`, even though it is mostly the same.

**Comment by heri16** [comment]
PR #1514

**Comment by heri16** [comment]
After analyzing third party plugin called `hardhat-deploy-ethers`, it looks like the features added to `@nomiclabs/hardhat-ethers` are `getNamedSigners`, `getUnnamedSigners`, and these lines below:

https://github.com/wighawag/hardhat-deploy-ethers/blob/main/src/helpers.ts#L237

https://github.com/wighawag/hardhat-deploy-ethers/blob/a6053c7ceb39bc17064b356b628dc381b9aacb9d/src/helpers.ts#L237

```typescript
async function _getArtifact(
  hre: HardhatRuntimeEnvironment,
  name: string
): Promise<Artifact> {
  const deployments = (hre as any).deployments;
  if (deployments !== undefined) {
    return deployments.getArtifact(name);
  }
  return hre.artifacts.readArtifact(name);
}

async function getContractFactoryByName<T extends ethers.ContractFactory>(
  hre: HardhatRuntimeEnvironment,
  contractName: string,
  signerOrOptions?: ethers.Signer | string | FactoryOptions
): Promise<T> {
  const artifact = await _getArtifact(hre, contractName);
  ...
}
```

This is a good first step to enable the reuse of `@nomiclabs/hardhat-ethers`, in such a third-party plugin.

**Comment by fvictorio** [comment]
Closing this in favor of #1040.

**Comment by heri16** [comment]
@fvictorio half a year with no progress on #1040 and we are closing this?
