### ISSUE TITLE
Due to gas limit Unrecognized deployment failure 

### ISSUE THREAD

**Issue by maxim-engr** [nomiclabs/hardhat#1521]
While running hardhat deployment with a fixed gas limit (lower than necessary to succeed) we found the error message.

**Comment by fvictorio** [comment]
Hi @maxim-engr. Can you tell me how to reproduce this? I tried deploying a contract with a low gas limit and I got a "TransactionExecutionError: Transaction ran out of gas" error, which IMO is the expected result.

**Comment by maxim-engr** [comment]
It was fixed on my side. Thanks!
