### ISSUE TITLE
Plugin type extensions are broken from v2.3.3

### ISSUE THREAD

**Issue by lbeder** [nomiclabs/hardhat#1539]
Hi,

I've tried to upgrade to v2.3.3, in order to resolve https://github.com/nomiclabs/hardhat/issues/1537, but it has broken all the plugin type extensions in `hardhat.config.ts` :(.

```sh
hardhat.config.ts:57:5 - error TS2322: Type '{ networks: any; solidity: { version: string; settings: { optimizer: { enabled: boolean; runs: number; }; metadata: { bytecodeHash: string; }; }; }; etherscan: { apiKey: any; }; contractSizer: { alphaSort: boolean; runOnCompile: boolean; disambiguatePaths: boolean; }; abiExporter: { ...; }; gasReporter: { ...; }; mo...' is not assignable to type 'HardhatUserConfig'.
  Object literal may only specify known properties, and 'etherscan' does not exist in type 'HardhatUserConfig'.

57     etherscan: {
       ~~~~~~~~~~~~
58         apiKey: loadAPIKey('etherscan')
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
59     },
   ~~~~~
```

Reverting back solves this, but then we get to #1537.

**Comment by alcuadrado** [comment]
Hey @lbeder,

Do you have a link to your project so that we can reproduce this?

**Comment by lbeder** [comment]
Unfortunately, it's current in a  private, but I'll create a public sample for testing soon.

**Comment by alcuadrado** [comment]
Can you try deleting your `node_modules` and installing everything again, using `v2.3.3`?

**Comment by lbeder** [comment]
Sorry, @alcuadrado - false alarm. I've tried to recreate it in a new project but wasn't able to, so I've went back to the original project and figured out that the root cause was some dependency issues between two Lerna packages using different hardhat versions (resulting in a wrong dependency resolution by npm).

**Comment by Simiyu40** [comment]
And how did you solve the dependency issue kindly..........?i got the same problem

**Comment by mjlescano** [comment]
| And how did you solve the dependency issue kindly..........?i got the same problem

For future reference, this can be fixed making sure the hardhat versions on all the `package.json` files are the same, e.g.: `"hardhat": "2.9.1",`

**Comment by aabertente** [comment]
I have this isseus, I ask you for help @mjlescano 

 Type '{ solidity: { version: string; settings: { optimizer: { enabled: boolean; runs: number; }; }; }; networks: { truffle: { url: string; }; }; gasReporter: { enabled: boolean; currency: string; coinmarketcap: string | undefined; }; etherscan: { ...; }; }' is not assignable 
to type 'HardhatUserConfig'.
  Object literal may only specify known properties, and 'gasReporter' does not exist in type 'HardhatUserConfig'.

**Comment by aabertente** [comment]
@mjlescano

**Comment by aabertente** [comment]
![image](https://user-images.githubusercontent.com/62211924/158492395-75fc3181-87ba-4cb3-9e0c-be29b066145e.png)

**Comment by aabertente** [comment]
@alcuadrado @lbeder

**Comment by MotykaTaras** [comment]
**Install dependency packages and everything will work.**

```
npm install --save-dev @typechain/hardhat
npm install --save-dev @nomiclabs/hardhat-waffle 'ethereum-waffle@^3.0.0'
npm install --save-dev @nomiclabs/hardhat-ethers 'ethers@^5.0.0'
npm install --save-dev @nomiclabs/hardhat-etherscan
npm install --save-dev hardhat-gas-reporter 
npm install --save-dev solidity-coverage
```

**Comment by MotykaTaras** [comment]
> Hi,
> 
> I've tried to upgrade to v2.3.3, in order to resolve #1537, but it has broken all the plugin type extensions in `hardhat.config.ts` :(.
> 
> ```shell
> hardhat.config.ts:57:5 - error TS2322: Type '{ networks: any; solidity: { version: string; settings: { optimizer: { enabled: boolean; runs: number; }; metadata: { bytecodeHash: string; }; }; }; etherscan: { apiKey: any; }; contractSizer: { alphaSort: boolean; runOnCompile: boolean; disambiguatePaths: boolean; }; abiExporter: { ...; }; gasReporter: { ...; }; mo...' is not assignable to type 'HardhatUserConfig'.
>   Object literal may only specify known properties, and 'etherscan' does not exist in type 'HardhatUserConfig'.
> 
> 57     etherscan: {
>        ~~~~~~~~~~~~
> 58         apiKey: loadAPIKey('etherscan')
>    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 59     },
>    ~~~~~
> ```
> 
> Reverting back solves this, but then we get to #1537.



> ![image](https://user-images.githubusercontent.com/62211924/158492395-75fc3181-87ba-4cb3-9e0c-be29b066145e.png)

**Install dependency packages and everything will work.**

```
npm install --save-dev @typechain/hardhat
npm install --save-dev @nomiclabs/hardhat-waffle 'ethereum-waffle@^3.0.0'
npm install --save-dev @nomiclabs/hardhat-ethers 'ethers@^5.0.0'
npm install --save-dev @nomiclabs/hardhat-etherscan
npm install --save-dev hardhat-gas-reporter 
npm install --save-dev solidity-coverage
```
