### ISSUE TITLE
Hardhat jsonRPC server shows Parse error

### ISSUE THREAD

**Issue by e74000** [nomiclabs/hardhat#1567]
When you run `curl 127.0.0.1:8545` when a hardhat node is running, you get the following: `{"jsonrpc":"2.0","id":null,"error":{"code":-32700,"message":"Parse error: Unexpected end of JSON input"}}` which I assume is an error.

It does not seem to impact anything AFAIK but It does prevent me from getting specific bits of information out of the jsonRPC server using curl.

**Comment by alcuadrado** [comment]
Hey @e74000. This is expected, as you aren't sending a valid JSON-RPC request.

Try this instead `curl localhost:8545 --data '{"jsonrpc": "2.0", "id": 1, "method": "eth_accounts"}'`
