### ISSUE TITLE
Hardhat won't initiate create project sequence

### ISSUE THREAD

**Issue by alexrmacleod** [nomiclabs/hardhat#1569]
https://stackoverflow.com/questions/68036433/hardhat-wont-initiate-create-project-sequence

following the docs https://hardhat.org/getting-started/#quick-start

```
npm init -y
npm install --save-dev hardhat
npx hardhat 
```
then i get the below response which just skips create project.

Why is hardhat cli skipping the start project sequence?

Was working before but just stopped working.

```
alex@HL072 test2 % npx hardhat
Hardhat version 2.4.0

Usage: hardhat [GLOBAL OPTIONS] <TASK> [TASK OPTIONS]

GLOBAL OPTIONS:

  --config              A Hardhat config file. 
  --emoji               Use emoji in messages. 
  --help                Shows this message, or a task's help if its name is provided 
  --max-memory          The maximum amount of memory that Hardhat can use. 
  --network             The network to connect to. 
  --show-stack-traces   Show stack traces. 
  --tsconfig            Reserved hardhat argument -- Has no effect. 
  --verbose             Enables Hardhat verbose logging 
  --version             Shows hardhat's version. 


AVAILABLE TASKS:

  check     Check whatever you need
  clean     Clears the cache and deletes all artifacts
  compile   Compiles the entire project, building all artifacts
  console   Opens a hardhat console
  flatten   Flattens and prints contracts and their dependencies
  help      Prints this message
  node      Starts a JSON-RPC server on top of Hardhat Network
  run       Runs a user-defined script after compiling the project
  test      Runs mocha tests

To get help for a specific task run: npx hardhat help [task]

alex@HL072 test2 % 
```

**Comment by fvictorio** [comment]
@alexrmacleod can you paste the output of `npx hardhat --verbose`?

**Comment by alexrmacleod** [comment]
@fvictorio 

`alex@HL072 test % npx hardhat --verbose
  hardhat:core:config Loading Hardhat config from /Users/alex/hardhat.config.js +0ms
  hardhat:core:global-dir Looking up Client Id at /Users/alex/Library/Application Support/hardhat-nodejs/analytics.json +0ms
  hardhat:core:global-dir Client Id found: 3f50c4af-8d25-402b-8ae4-e39d56ad8642 +1ms
  hardhat:core:analytics Sending hit for /task/builtin +0ms
  hardhat:core:analytics Hit payload: {"v":"1","t":"pageview","tid":"UA-117668706-3","cid":"3f50c4af-8d25-402b-8ae4-e39d56ad8642","dp":"/task/builtin","dh":"cli.hardhat.org","ua":"Node/v14.4.0 (Macintosh; Intel Mac OS X 10_13_6)","cs":"Developer","cm":"User Type","cd1":"hardhat-project","cd2":"Developer","cd3":"Hardhat 2.4.0"} +1ms
  hardhat:core:hre Creating HardhatRuntimeEnvironment +0ms
  hardhat:core:hre Running task help +1ms
Hardhat version 2.4.0

Usage: hardhat [GLOBAL OPTIONS] <TASK> [TASK OPTIONS]

GLOBAL OPTIONS:

  --config           	A Hardhat config file. 
  --emoji            	Use emoji in messages. 
  --help             	Shows this message, or a task's help if its name is provided 
  --max-memory       	The maximum amount of memory that Hardhat can use. 
  --network          	The network to connect to. 
  --show-stack-traces	Show stack traces. 
  --tsconfig         	Reserved hardhat argument -- Has no effect. 
  --verbose          	Enables Hardhat verbose logging 
  --version          	Shows hardhat's version. 


AVAILABLE TASKS:

  check  	Check whatever you need
  clean  	Clears the cache and deletes all artifacts
  compile	Compiles the entire project, building all artifacts
  console	Opens a hardhat console
  flatten	Flattens and prints contracts and their dependencies
  help   	Prints this message
  node   	Starts a JSON-RPC server on top of Hardhat Network
  run    	Runs a user-defined script after compiling the project
  test   	Runs mocha tests

To get help for a specific task run: npx hardhat help [task]

  hardhat:core:analytics Aborting hit for "/task/builtin" +24ms
  hardhat:core:cli Killing Hardhat after successfully running task help +0ms
alex@HL072 test % `

**Comment by alcuadrado** [comment]
Hey, @alexrmacleod 

You do have a hardhat config file in `/Users/alex/hardhat.config.js`, so Hardhat is using it.

Delete it and try initializing the project again, and you'll see the project initialization options.

I'm closing this issue, but feel free to reopen it if the problem persists.

**Comment by THRUSTDeltaV** [comment]
Thank you. Had the same problem. deleting hardhat.config.js from global user is the solution.
