### ISSUE TITLE
Remove custom state manager and update the one used when forking

### ISSUE THREAD

**Issue by fvictorio** [nomiclabs/hardhat#1590]
We added a custom (non-fork) state manager to work around a bug in EthereumJS. That bug has been allegedly fixed, so we should remove this workaround and see if it works now.

**Comment by fvictorio** [comment]
We should keep [this PR](https://github.com/ethereumjs/ethereumjs-monorepo/pull/1548) in mind for this issue.

That will probably not be merged soon, but maybe we can give it a try locally when it's ready to be tested.

cc @holgerd77, would that be useful for you?

**Comment by holgerd77** [comment]
PR is ready to be tested - yes - that would definitely useful for us (and hopefully for you guys as well)! 😄

**Comment by feuGeneA** [comment]
Regarding the "and update the one used when forking" part of the Issue title, is that really necessary? Or was it just a guess/assumption as to what needed to be done?

As far as I can tell, [ForkStateManager](https://github.com/nomiclabs/hardhat/blob/master/packages/hardhat-core/src/internal/hardhat-network/provider/fork/ForkStateManager.ts) is already importing and encapsulating `DefaultStateManager` from `@ethereumjs/vm/dist/state`.

**Comment by fvictorio** [comment]
Yeah, I'm not sure what I meant with that. Maybe I was talking about updating the dependency.

**Comment by feuGeneA** [comment]
Released in hardhat 2.8.1
