### ISSUE TITLE
Replace `no-return-await` with `@typescript-eslint/return-await`

### ISSUE THREAD

**Issue by fvictorio** [nomiclabs/hardhat#1596]
We are using `"no-return-wait": "error"`, but it would've be better to do the opposite and to actually enforce `return await` everywhere, so that we have better async stack traces. See [this comment](https://github.com/nomiclabs/hardhat/pull/1587#discussion_r658937143).

Links:

- [`no-return-await`](https://eslint.org/docs/rules/no-return-await)
- [`@typescript-eslint/return-await`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/return-await.md)

**Comment by alcuadrado** [comment]
Closed by #1835
