### ISSUE TITLE
[hardhat-etherscan] unable to verify on kovan

### ISSUE THREAD

**Issue by sirpy** [nomiclabs/hardhat#1597]
I'm unable to verify on etherscan kovan with the plugin but also manually with the single file format.
I was able to verify using https://github.com/rkalis/truffle-plugin-verify which uses the json-standard-format
can this be adapted to hardhat?

**Comment by fvictorio** [comment]
@sirpy there's nothing we can do with that information. Please re-open if you can provide reproduction steps.
