### ISSUE TITLE
Implement `hardhat_setBaseFeePerGas`

### ISSUE THREAD

**Issue by alcuadrado** [nomiclabs/hardhat#1607]
We need a method to manipulate the base fee. Should we include a "fixed" mode that prevents the base fee from being updated after setting it?

**Comment by alcuadrado** [comment]
We should make sure that this is preserved by the snapshots.

**Comment by fvictorio** [comment]
I think the two alternatives we have is to add two methods (`hardhat_setNextBaseFeePerGas` and `hardhat_setBaseFeePerGas`, for example) or having a parameter:

```js
send("hardhat_setBaseFeePerGas", [{
  fixed: true
}])
```

I have a weak preference for the first option, but I think both are fine.

**Comment by alcuadrado** [comment]
We can implement `hardhat_setNextBlockBaseFeePerGas` and see if the fixed version is a common request.
