### ISSUE TITLE
Update the forking functionality to support London

### ISSUE THREAD

**Issue by alcuadrado** [nomiclabs/hardhat#1612]
As always, the tricky part of this is when the remote network is running a different hardfork than the local one. Here's a description of the different cases:

- London Hardhat forking a London Network
    - Same behavior as a local network with London, except remote blocks before the hardfork don't have the `baseFeePerGas` field.
    - The base fee is respected. That is, the first local block after forking has the correct base `baseFeePerGas`
- Non-London Hardhat forking a Non-London network
    - Same behavior as a local network using a pre-London hardfork.
- Non-London Hardhat forking a London network
    - New blocks, or remote blocks before the hardfork don't have the `baseFeePerGas`. EIP-1559 transactions are not accepted.
- London Hardhat forking a Non-London Network
    - New blocks have the London behavior. The initial base fee is the configured one.

**Comment by yuetloo** [comment]
Recently, our test cases that use forking functionality are failing with error `Unknown transaction type 2` coming from the following line.

https://github.com/nomiclabs/hardhat/blob/master/packages/hardhat-core/src/internal/hardhat-network/provider/fork/ForkBlockchain.ts#L290

Looks like it's related to this ticket. Any update on this issue? Or, workaround?

**Comment by fvictorio** [comment]
@yuetloo transaction type 2 is an EIP-1559 transaction, which we don't support yet.

**Comment by ajb413** [comment]
> Recently, our test cases that use forking functionality are failing with error `Unknown transaction type 2` coming from the following line.
> 
> https://github.com/nomiclabs/hardhat/blob/master/packages/hardhat-core/src/internal/hardhat-network/provider/fork/ForkBlockchain.ts#L290
> 
> Looks like it's related to this ticket. Any update on this issue? Or, workaround?

You can try this (learned from https://yuichiroaoki.medium.com/internalerror-unknown-transaction-type-2-hardhat-403031bb0c11). It fixed this error for me:

```
npm update
## or if you use yarn
yarn upgrade 
```

**Comment by fvictorio** [comment]
Yes, if someone runs into this: Hardhat 2.5.0 supports London (but you need to enable it by setting `hardfork: "london"` in the hardhat network config). Hardhat 2.6.0 enables London by default.
