### ISSUE TITLE
Hardhat has no exported member ethers

### ISSUE THREAD

**Issue by pizzarob** [nomiclabs/hardhat#1627]
Hi I am writing a script using typescript. I run with the hardhat runtime and it works as expected however typescript is saying that ethers is not exported from hardhat. How can I fix this?

![image](https://user-images.githubusercontent.com/5282495/124222288-4f0bab80-dab6-11eb-82b3-c7af2b7d4888.png)

**Comment by pizzarob** [comment]
I had to specify the scripts folder in the include field in tsconfig

```
{
  "compilerOptions": {
    "target": "ES2017",
    "module": "commonjs",
    "declaration": true,
    "declarationMap": true,
    "sourceMap": true,
    "outDir": "./dist",
    "strict": true,
    "rootDirs": ["./src", "./scripts", "./test"],
    "esModuleInterop": true
  },
  "exclude": ["dist", "node_modules"],
  "include": ["./test", "./src", "./scripts"],
  "files": ["./hardhat.config.ts"]
}
```

**Comment by supafreq** [comment]
Glad you figured it out and shared the solution before [the maintainers blamed your setup was wrong and instantly closed / locked your issue.](1640)

**Comment by fvictorio** [comment]
@supafreq You are right I shouldn't have locked that issue. To be honest I don't remember why I did it (I guess I wanted to move the discussion to Discord, but it was not a good idea in retrospect). With respect to closing it, we err on the side of closing issues instead of keeping them open for bookkeeping reasons. But again, that only makes sense if they can still be commented on, so my bad :slightly_smiling_face:

**Comment by BrennerSpear** [comment]
I'm seeming to still have this problem when I run `npx ts-node scripts/deploy.ts ../NFTs/myFirstNFT.ts`

```
// #tsconfig.json
{
  "compilerOptions": {
    "outDir": "./dist",
    "allowJs": true,
    "target": "es2018",
    "module": "CommonJS",
    "strict": true,
    "esModuleInterop": true,
    "rootDirs": ["./src", "./scripts", "./test"]
    // "types": ["chai", "mocha", "node"]
  },
  "include": ["./src/**/*", "./scripts", "./test", "./test/**/*"],
  "files": ["./hardhat.config.ts"]

```


```
// # hardhat.config.ts

/**
* @type import('hardhat/config').HardhatUserConfig
*/
import * as dotenv from 'dotenv';
import 'hardhat-contract-sizer';
import '@nomiclabs/hardhat-etherscan';
import '@nomiclabs/hardhat-waffle';
import '@nomiclabs/hardhat-ethers';

dotenv.config();

const { ROPSTEN_INFURA_URL, RINKEBY_INFURA_URL, GOERLI_INFURA_URL, PRIVATE_KEY, ETHERSCAN_API_KEY } = process.env;

export default {
  solidity: {

```
![Screen Shot 2021-09-12 at 10 56 14 PM](https://user-images.githubusercontent.com/12127609/133021717-fe59671d-5050-48ec-a62d-16960f734983.png)

**Comment by fvictorio** [comment]
@BrennerSpear do you have a public repo that reproduces the problem?

**Comment by BrennerSpear** [comment]
Fixed it - I had to import `hre` explicitly since I'm using `ts-node` instead of `hardhat run`

**Comment by AuroraLantean** [comment]
Fixed it: have to install @nomiclabs/hardhat-ethers

**Comment by jogamod** [comment]
@BrennerSpear did you figure out how to run with `ts-node` instead of `hardat run` ?

**Comment by gebob19** [comment]
adding `import "@nomiclabs/hardhat-waffle";` to `hardhat.config.ts` fixed it for me

**Comment by velsa** [comment]
Tried everything that's been suggested here and still Typescript was complaining.

But adding just one ts-node flag solved the issue for me :)

```
TS_NODE_FILES=true ts-node ./scripts/deploy-my-contract.ts
```

**Comment by DedicatedDev** [comment]
it is happening when tried to debug with viscose. 
normal command is working but if I config debugger, without import {ether} form 'hardhat', it is working well, but if I add this, it shows this message. 

test/index.ts:4:10 - error TS2305: Module '"hardhat"' has no exported member 'ethers'.

**Comment by Palmatum** [comment]
Installing ` npm install --save-dev @nomiclabs/hardhat-ethers 'ethers@^5.0.0'` 
and adding `import "@nomiclabs/hardhat-ethers";` in _deploy.ts_ fixed it for me.

**Comment by ricardo-passos** [comment]
@Palmatum For me, I had to `import '@nomiclabs/hardhat-ethers'` inside `hardhat.config.ts` and then `import { ethers } from 'hardhat'` in my `deploy.ts` file.

`hardhat.config.ts`:
```ts
import '@nomiclabs/hardhat-waffle'
import '@nomiclabs/hardhat-ethers'

// types
import type { HardhatUserConfig } from 'hardhat/config'

const config: HardhatUserConfig = {
  solidity: '0.8.0',
  networks: {
    ropsten: {
      
    },
    hardhat: {

    }
  }
}

export default config
```


`deploy.ts`:

```ts
import { ethers } from 'hardhat'

async function main() {
  const Greeter = await ethers.getContractFactory('Greeter')
  const greeter = await Greeter.deploy('Hello, Hardhat!')

  await greeter.deployed()

  console.log('Greeter deployed to:', greeter.address)
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error)
    process.exit(1)
  })
```

**Comment by nascimento-cesar** [comment]
> I had to specify the scripts folder in the include field in tsconfig
> 
> ```
> {
>   "compilerOptions": {
>     "target": "ES2017",
>     "module": "commonjs",
>     "declaration": true,
>     "declarationMap": true,
>     "sourceMap": true,
>     "outDir": "./dist",
>     "strict": true,
>     "rootDirs": ["./src", "./scripts", "./test"],
>     "esModuleInterop": true
>   },
>   "exclude": ["dist", "node_modules"],
>   "include": ["./test", "./src", "./scripts"],
>   "files": ["./hardhat.config.ts"]
> }
> ```

Thank you very much for your answer! It helped me.

**Comment by sanderpick** [comment]
> Installing ` npm install --save-dev @nomiclabs/hardhat-ethers 'ethers@^5.0.0'` and adding `import "@nomiclabs/hardhat-ethers";` in _deploy.ts_ fixed it for me.

this works, note that `ethers` needs to be in `devDependencies`, which the above will do

**Comment by sanjayojha** [comment]
Thanks, its helped.
But `hardhat.config.ts` is compiling into dist folder along with others. How to compile it exclusively in project root?

**Comment by Wwjian-lab** [comment]
Add `import "@nomicfoundation/hardhat-toolbox"` or `import "@nomiclabs/hardhat-ethers"` to `hardhat.config.ts`.

**Comment by ackvf** [comment]
This is enough:

```
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", "**/*.js",],
  "exclude": ["node_modules"]
```
