### ISSUE TITLE
Forking with WSS endpoints

### ISSUE THREAD

**Issue by EtDu** [nomiclabs/hardhat#1634]
I'm using a WSS endpoint for a BSC archive node. When I try to fork it with `hardhat node`:

`Error HH604: Error running JSON-RPC server: Only HTTP(S) protocols are supported`

Are there any plans to support WSS for forking in the future?

**Comment by fvictorio** [comment]
@EtDu can you explain your use case a bit more? You have a node that exposes a ws endpoint but not an http one?

**Comment by EtDu** [comment]
The node I was using exposes both but the https wasn't working properly. After you reminded me about getBlock however, my problem has been solved. They seem to work pretty well. We can close this, unless you want to keep as a low priority issue. Thanks!

**Comment by fvictorio** [comment]
Hmm, yeah, I think I'm going to close it. I don't see us working on this soon, since it's not an easy change and my guess is that it's only useful in really unlikely scenarios (like the one you mentioned).

If someone reads this and thinks otherwise, please let us know!
