### ISSUE TITLE
Improve error message for invalid private key

### ISSUE THREAD

**Issue by fvictorio** [nomiclabs/hardhat#1635]
This is a valid config:

```js
module.exports = {
  solidity: "0.7.3",
  networks: {
    rinkeby: {
      url: "https://rinkeby.infura.io/v3/",
      accounts: ["0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"]
    }
  }
};
```

But adding or removing a single character to the private key (or changing an `a` to a `g`) results in this error message:

```
Error HH8: There's one or more errors in your config file:

  * Invalid value {"url":"https://rinkeby.infura.io/v3/","accounts":["0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"]} for HardhatConfig.networks.rinkeby - Expected a value of type HttpNetworkConfig.
```

There is a bigger issue here about our config validation being awful in general, but I think we should handle this particular case right now, since it shows up **a lot** in the discord server, and it's a really bad experience for users.

**Comment by fvictorio** [comment]
This is not a hard issue to tackle, but it's not trivial either. If someone wants to give it a try, please let us know here first.

**Comment by Rishabhraghwendra18** [comment]
May I work on this issue ?

**Comment by alcuadrado** [comment]
Sure! Take a look at the `config-validation.ts` file. It uses `io-ts`, but we also have some manual validations.
