### ISSUE TITLE
.env security vulnerability

### ISSUE THREAD

**Issue by InvokerMaster** [nomiclabs/hardhat#1636]
Yesterday I experienced a really bad issue. I created a project using npm hardhat init and it seemed that hardhat created .gitignore file.
I was thinking that .env is added to this file already, and added my private key, tested deployment on testnet and made it public repository.
After 1 hour, when I noticed that .env file is exposed, it was already late.
So I would to add .env file to .gitignore as default.
Thank you for the hard work

**Comment by fvictorio** [comment]
Hi @InvokerMaster. I'm really sorry to hear that. I guess we tried to make the `.gitignore` as minimal as possible, and since we don't include `dotenv` in the sample project, we don't add `.env` to the `.gitignore` either. But it's a fairly common pattern, so I think it doesn't hurt at all to add it.

**Comment by Rishabhraghwendra18** [comment]
Hi @fvictorio . First timer this side . May I work on this

**Comment by fvictorio** [comment]
@Rishabhraghwendra18 sure! I think you just need to update this file: https://github.com/nomiclabs/hardhat/blob/master/packages/hardhat-core/recommended-gitignore.txt

**Comment by InvokerMaster** [comment]
Awesome Thanks @Rishabhraghwendra18 , @fvictorio

**Comment by Rishabhraghwendra18** [comment]
@InvokerMaster No problem

**Comment by Rishabhraghwendra18** [comment]
@fvictorio I think the above PR has solved the issue . We may close the issue now

**Comment by fvictorio** [comment]
Thanks @Rishabhraghwendra18!
