### ISSUE TITLE
hardhat has no exported member 'ethers' in v2.0.2

### ISSUE THREAD

**Issue by ClusterH** [nomiclabs/hardhat#1640]
when I use v2.0.1,  `import { ethers } from 'hardhat'`  in deploy.ts file and others is worked as well, after upgrade to v2.0.2, it is not work and show error in VSCode like that: **hardhat has no exported member 'ethers'**.

**Comment by fvictorio** [comment]
This is unlikely to be a bug in Hardhat. It seems more like a problem with your setup. Try resetting VS Code, reinstalling your dependencies, or check the [typescript guide](https://hardhat.org/guides/typescript.html).

Please use [our Discord server](https://hardhat.org/discord) if you have more questions like this one.

**Comment by elmariachi111** [comment]
@ClusterH it'll disappear once you put 
```
  "files": [
    "./hardhat.config.ts"
  ]
  ``` 
in your `tsconfig`

**Comment by feuGeneA** [comment]
> @ClusterH it'll disappear once you put
> 
> ```
>   "files": [
>     "./hardhat.config.ts"
>   ]
> ```
> 
> in your `tsconfig`

@ClusterH @elmariachi111 Also, if you happen to be invoking the script via `ts-node` rather than via `hardhat`, be sure to use `TS_NODE_FILES=1` or `--files`; see https://hardhat.org/guides/typescript.html#running-your-tests-and-scripts-directly-with-ts-node
