### ISSUE TITLE
In Quick Start, there is a `require` missing?

### ISSUE THREAD

**Issue by kvutien** [nomiclabs/hardhat#1652]
_If you are reporting a bug, please include reproduction steps._

At step [https://hardhat.org/getting-started/#testing-your-contracts](https://hardhat.org/getting-started/#testing-your-contracts), the test failed with this error message
```bash
Greeter
    1) Should return the new greeting once it's changed

  0 passing (11ms)
  1 failing

  1) Greeter
       Should return the new greeting once it's changed:
     *ReferenceError: ethers is not defined*
      *at Context.<anonymous> (test/sample-test.js:5:21)*
      at processImmediate (internal/timers.js:456:21)

``` 
I understood that `ethers` is added automatically by hardhat?

My installed versions
```bash
+ chai@4.3.4
+ ethers@5.4.1
+ ethereum-waffle@3.4.0
+ @nomiclabs/hardhat-waffle@2.0.1
+ @nomiclabs/hardhat-ethers@2.0.2

```

**Comment by alcuadrado** [comment]
Thanks for reporting this, @kvutien!

Did you require the waffle plugin in your config?

**Comment by kvutien** [comment]
Wow, you are quick. And your hint hit the spot
```bash
kvutien@VTKT5 hardhat-trial % npx hardhat test

  Greeter
Deploying a Greeter with greeting: Hello, world!
Changing greeting from 'Hello, world!' to 'Hola, mundo!'
    ✓ Should return the new greeting once it's changed (944ms)


  1 passing (953ms)

```


No I didn't. It was not mentioned in the test chapter. Now that I read again the tutorial, it was indeed mentioned at the beginning but I disregarded this first config line because I considered it as a side note explaining the plug-ins.

Maybe I'll fork your tuto, propose a reminder change in the text of the test chapter and do a PR?

**Comment by kvutien** [comment]
Awesome tutorial. I've also finished deploying the smart contract on the local node. Very good tuto.

Maybe one suggestion: remove the [note about plug-ins](https://hardhat.org/getting-started/#running-tasks) off the mainstream logic, for example into an annex. Focus the beginner on the main actions. Specially because at this moment of the tuto, the beginner is still expecting only the most important topics.
```bash
kvutien@VTKT5 hardhat-trial % npx hardhat run scripts/sample-script.js --network localhost
web3_clientVersion (2)
eth_chainId
eth_accounts
eth_blockNumber
eth_chainId (2)
eth_estimateGas
eth_gasPrice
eth_sendTransaction
  Contract deployment: Greeter
  Contract address:    0x5fbdb2315678afecb367f032d93f642f64180aa3
  Transaction:         0x8a13cd0caabb1b116b69213ae6e2a96a36dcb1c48982a848e809e91603b307a2
  From:                0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
  Value:               0 ETH
  Gas used:            488014 of 488014
  Block #1:            0x7990c257fc619c5c66c25c964000bd5141fcc2b29cbb6c8f42540fe967963d6b

  console.log:
    Deploying a Greeter with greeting: Hello, Hardhat!

eth_chainId
eth_getTransactionByHash
eth_chainId
eth_getTransactionReceipt
Greeter deployed to: 0x5FbDB2315678afecb367f032d93F642f64180aa3
```
