### ISSUE TITLE
Implement eth_maxPriorityFeePerGas

### ISSUE THREAD

**Issue by alcuadrado** [nomiclabs/hardhat#1664]
We need to implement this RPC method.

We can probably just hardcode a value.

**Comment by alcuadrado** [comment]
This isn't going to be implemented. `eth_feeHistory` should be used instead.

**Comment by ilya-korotya** [comment]
@alcuadrado hi. Why did you refuse to implement `eth_maxPriorityFeePerGas` endpoint? I saw discussion on `ethereum/web3.py`.
ETH golang library has `SuggestGasTipCap` method. This method call `eth_maxPriorityFeePerGas` endpoint to get tips value. It is working with geth node, but it doesn't work with hardhat. And I can't emulate transaction flow in hardhat.
