### ISSUE TITLE
When forking a remote network, `eth_call` and `eth_estimateGas` can be run with an incorrect hardfork

### ISSUE THREAD

**Issue by alcuadrado** [nomiclabs/hardhat#1666]
If you fork a remote chain, and call `eth_call`, `eth_estimateGas`, or any other rpc method that requires (re)executing a tx, with a block tag pointing to a remote block, we may use the wrong hardfork, and hence get different results.

The reason for this is that we always use the currently active hardfork, while Geth derives the hardfork from the block tag.

This can only affect you if you are forking a remote chain, as otherwise all the blocks will be mined using the same hardfork.

Fixing this can be trickier than expected, as the forking functionality should support any chain, not just the ones natively supported by ethereumjs. I think we have two options for non-native chains:

(1) Keep doing what we do now, risking to give incorrect results.
(2) Fail when a remote block tag is used. Indicating how to ask for support for it.

**Comment by feuGeneA** [comment]
Backlink: https://github.com/nomiclabs/hardhat/blob/854a149835ed0763bb7396189f299fd094409f61/packages/hardhat-core/src/internal/hardhat-network/provider/node.ts#L2135

**Comment by feuGeneA** [comment]
Released in 2.8.0.
