### ISSUE TITLE
Enable dependencies caching in our CI jobs

### ISSUE THREAD

**Issue by alcuadrado** [nomiclabs/hardhat#1715]
A [new version](https://github.com/actions/setup-node/releases/tag/v2.2.0) of the `setup-node` github action makes caching npm/yarn dependencies really easy.

We should enable that caching, as yarn timing out is one of the most common failures we have on our CI.

**Comment by Rishabhraghwendra18** [comment]
I am on it !!

**Comment by alcuadrado** [comment]
That's right. I added it and forgot about this issue. Thanks!
