### ISSUE TITLE
[hardhat-ethers] `getContractFactory` and `getContractAt` should have an overload that take an `Artifact`

### ISSUE THREAD

**Issue by alcuadrado** [nomiclabs/hardhat#1716]
_This was reported by @nventuro_

If you have your own artifacts-loading logic, and have a contract that needs to be linked, our plugin doesn't help you. You'd have to link the libraries manually.

We should have overloads that take an `Artifact`, and take care of the library linking.

`getContractAt` doesn't really need this overload, but it would be great to be consistent.

**Comment by Rishabhraghwendra18** [comment]
is this issue still open ?

**Comment by alcuadrado** [comment]
Yes, do you want to implement it?

**Comment by Rishabhraghwendra18** [comment]
Ya... I want to give it a try since it's a good first issue . So I think I can do this

**Comment by alcuadrado** [comment]
This is a good first issue for you, @Rishabhraghwendra18

**Comment by kanej** [comment]
This will get closed when the release goes out.

**Comment by fvictorio** [comment]
Done in [`@nomiclabs/hardhat-ethers@2.0.4`](https://github.com/nomiclabs/hardhat/releases/tag/%40nomiclabs%2Fhardhat-ethers%402.0.4).
