### ISSUE TITLE
Changes after London is activated

### ISSUE THREAD

**Issue by fvictorio** [nomiclabs/hardhat#1722]
When London is activated mainnet, we need to release a new minor version that changes some things:

- [x] (FV) Change the default hardfork to london
- [x] (FV) Change the default gasPrice to auto
- [x] (FV) Change the default blockGasLimit to 30M (approx twice current mainnet value)
- [x] (PP) Drop support for node 10
- [x] (PP) Upgrade ethereumjs/vm to latest version

**Comment by alcuadrado** [comment]
All the changes listed here have been implemented 🚀
