### ISSUE TITLE
Unable to verify ovm-compiled contract

### ISSUE THREAD

**Issue by ZumZoom** [nomiclabs/hardhat#1730]
When deploying to kovan-optimistic and compiling with ovm compiler 0.7.6+commit.3b061308. Verify task fails with the following error:

`NomicLabsHardhatPluginError: The contract you want to verify was compiled with solidity <0.4.7, but your configured compiler version is: 0.7.6.`

Probably it happens because ovm compiler does not inject required metadata to the bytecode.

**Comment by fvictorio** [comment]
Ugh, that sucks. There might be an assumption in the plugin that "no metadata" means "solidity <0.4.7", which is of course totally wrong.

@ZumZoom could you please share the bytecode and the source with us, assuming it's public? Or, if it's not public, maybe just the bytecode would be enough.

**Comment by ZumZoom** [comment]
Here is the [example repo](https://github.com/ZumZoom/ovm-hardhat-etherscan-example) and its [deployed bytecode](https://kovan-optimistic.etherscan.io/address/0x4826E07AE9110004762Ed032258D17E9c5768469).

**Comment by mds1** [comment]
Hey! I was having the same issue and started looking into this.

> There might be an assumption in the plugin that "no metadata" means "solidity <0.4.7", which is of course totally wrong.

This is correct. The assumption is made here: https://github.com/nomiclabs/hardhat/blob/27b3842d6e270fc516cc7fec8266746deb6c2b7b/packages/hardhat-etherscan/src/solc/metadata.ts#L31-L44

Aside from that, you can see from the error message that it thinks @ZumZoom is compiling with `0.7.6`, but if you look at the Hardhat config linked, it's really compiling with `0.7.6+commit.3b061308`. There are multiple versions of the OVM compiler for a given solc version, as seen here where there are two different 0.7.6's:

<img src="https://user-images.githubusercontent.com/17163988/127240864-fe36c8e4-4896-4533-a98c-42bb5ccfa404.png" width=500px />


Therefore I think a change also needs to be made in the [`TASK_VERIFY_GET_COMPILER_VERSIONS`](https://github.com/nomiclabs/hardhat/blob/27b3842d6e270fc516cc7fec8266746deb6c2b7b/packages/hardhat-etherscan/src/index.ts#L540-L566) method. It seems this method is only looking in the ordinary `hardhatConfig.ovm.solcVersion` field to find the compiler version, but with the `@eth-optimism/hardhat-ovm` plugin the compiler version is specified in a different field as you can see in @ZumZoom's code [here](https://github.com/ZumZoom/ovm-hardhat-etherscan-example/blob/6c9f7d9581e0821b2f09e7114132d83f05267516/hardhat.config.js#L7-L9).

I'm happy to get in a PR for this, but any additional guidance on the changes required would be appreciated!

**Comment by mds1** [comment]
Fix for the original error described here can be found here: https://github.com/mds1/hardhat/commit/dcba65f396ca64346a8228db679594c91fbe8063. @ZumZoom feel free to give that a shot and see where it gets you

After implementing that I get the following error, which I'll take a closer look at tomorrow

```
Error in plugin @nomiclabs/hardhat-etherscan: The address provided as argument contains a contract, but its bytecode doesn't match any of your local contracts.
Possible causes are:
  - Contract code changed after the deployment was executed. This includes code for seemingly unrelated contracts.
  - A solidity file was added, moved, deleted or renamed after the deployment was executed. This includes files for seemingly unrelated contracts.
  - Solidity compiler settings were modified after the deployment was executed (like the optimizer, target EVM, etc.).
  - The given address is wrong.
  - The selected network (optimism) is wrong.
 ```

**Comment by fvictorio** [comment]
Thanks, @mds1, that's very useful. I don't think we'll be able to work on this soon (at least not this week), but I'll bring this up at our next planning meeting.

**Comment by ZumZoom** [comment]
After applying the patch I face the same issue:
`The address provided as argument contains a contract, but its bytecode doesn't match any of your local contracts.
Possible causes are:`

**Comment by fvictorio** [comment]
We just published `@nomiclabs/hardhat-etherscan@2.1.5`, which fixes this issue.

**Comment by TransmissionsDev** [comment]
yayyyy!!!!

**Comment by trnhgquan** [comment]
I still got these issues, how to fix them?

**Comment by fvictorio** [comment]
@trnhgquan are you using the latest version of `hardhat-etherscan`?
