### ISSUE TITLE
invalid opcode when use @nomiclabs/hardhat-ganache

### ISSUE THREAD

**Issue by sc0Vu** [nomiclabs/hardhat#1736]
Thank you for using Hardhat and taking the time to open an issue!

**Note that this issue tracker is not a support channel.**

- For help with Hardhat and Hardhat network, please use our [Discord server](https://hardhat.org/discord).
- For help with ethers.js, please go to [its Github Discussions](https://github.com/ethers-io/ethers.js/discussions).

If you are reporting a bug, please include reproduction steps. The best way to do this is to include a [Minimal Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example). If you can't do that, then include a link to your repo, and the steps to reproduce the problem. The easiest it is to reproduce your problem, the faster we are going to be able to fix it.

If you are submitting a feature request, please take the time to clearly describe your use case, and not only your proposed solution.

Description:

When I try to use `abi.encode` in my smart contract, it always throw invalid opcode error. After trace source code from hardhat-ganache and issues, I found this might be related: #952 and the fix commit: https://github.com/nomiclabs/hardhat/commit/71f268477bcd68afcf347d2700d2bf9253bbea3d#diff-f061864276d864bd266a85a7e2c9d97152e26740d2c770bffee605895d87c956

I tried 2.0.0-rc.1, it didn't work. Anyway, I didn't see bump version commit after that commit, is this possible to release a new version of @nomiclabs/hardhat-ganache?

**Comment by fvictorio** [comment]
@sc0Vu thanks for bringing this up. Yes, it seems like we need to do a new release.

**Comment by fvictorio** [comment]
@sc0Vu We just published `@nomiclabs/hardhat-ganache@2.0.1`. I'm going to close this issue now, but please reopen if this new version doesn't fix your problem.

**Comment by sc0Vu** [comment]
@fvictorio It works, thanks!
