### ISSUE TITLE
evm_mine is undefined

### ISSUE THREAD

**Issue by fulldecent** [nomiclabs/hardhat#1742]
evm_mine is defined at https://github.com/nomiclabs/hardhat/edit/website/docs/hardhat-network/reference/README.md as:

> Same as Ganache

But Ganache does not document this either:

https://www.trufflesuite.com/docs/search?query=evm_mine

Please link to authoritative documentation for this feature.

**Comment by fvictorio** [comment]
Hi @fulldecent, thanks for pointing this out. We already have a note in our documentation board to remove the Ganache references, and we're probably going to fix that soon, so I'm going to close this issue to avoid duplication.

**Comment by fulldecent** [comment]
Got it, thank you for the peek into that
