### ISSUE TITLE
Feature : Typescript Sample project through CLI

### ISSUE THREAD

**Issue by sachushaji** [nomiclabs/hardhat#1755]
Currently the hardhat cli creates a js sample project if we choose to create one from cli. If we need to make use of typescript, then we have to follow a set of manual steps to set it up as described [here](https://hardhat.org/guides/typescript.html). I was wondering whether we could have a feature introduced to have a typescript project created from cli itself by giving it as a choice in the cli while creating the sample project.
 
![image](https://user-images.githubusercontent.com/15767732/128110189-6910b044-996f-4edf-ac23-ffa6ff5c1452.png)

Add an option here like : Do you need typescript?

I can do a PR for this if needed.

**Comment by farreldarian** [comment]
Hi! I was also experiencing this issue before, to set up Typescript, Typechain, and many plugins take a lot of time. Therefore, I made this [create-hardhat-dapp](https://github.com/farreldarian/create-hardhat-dapp) CLI, an opinionated hardhat project scaffolder with useful default configurations. Feel free to use, suggest, and contribute.

**Comment by alcuadrado** [comment]
Hey, we are already working on this, so I'll close this issue to avoid duplicates.

Nice project @farreldarian !

**Comment by alcuadrado** [comment]
Reopening this issue to keep track of this. While we are working on it, there was no previous issue about it.

**Comment by feuGeneA** [comment]
Note that we are introducing an "Advanced" project type to that menu, with an opinionated set of tools (those observed to be commonly used alongside Hardhat in the wild) and configurations for them, in #1632 .  Once that is merged,  we will be creating yet another entry in that menu, for a TypeScript version of the Advanced project.

**Comment by fvictorio** [comment]
Released in `hardhat@2.6.5` :tada:
