### ISSUE TITLE
error when using hardhat node --watch, "sender doesn't have enough funds to send tx "

### ISSUE THREAD

**Issue by rjchow** [nomiclabs/hardhat#1764]
There seems to be an issue with hardhat 2.5.0 when using `hardhat node --watch`, when a redeploy is triggered an error about sender not having enough funds comes up

I've created a minimal repo to reproduce this at https://github.com/rjchow/hardhat-deploy-watch-repro

To reproduce, 

1. npm install
2. npx hardhat node --watch
3. wait for it to run
4. modify greeter.sol to trigger a recompile and redeploy
5. error manifests

![image](https://user-images.githubusercontent.com/27843274/128367582-3d069227-4a8e-4158-ae09-6b36f65c942d.png)

**Comment by alcuadrado** [comment]
Hey @rjchow!

This functionality is part of `hardhat-deploy`, not Hardhat itself. Please open an issue [here](https://github.com/wighawag/hardhat-deploy) instead.

**Comment by rjchow** [comment]
🤦🏻‍♂️ sorry i had too many tabs open and got the wrong repo, sorry!
