### ISSUE TITLE
OPCODE chainid returns wrong value.

### ISSUE THREAD

**Issue by drortirosh** [nomiclabs/hardhat#1785]
When running `hardhat node`, it exposes itself as "chainId 31337", but the assembly OPCODE `chainid` returns value "1"

Any code that uses EIP712 validates the chainId in a contract, and thus all signature checks are broken.

This is probably related to the same [bug in ganache](https://github.com/trufflesuite/ganache-core/issues/515) (though in ganache, it was already fixed, so that when specifying `--chainId xxx`, the same value will get returned by both RPC call and opcode `chainid`)

(Note that back then in ganache I could workaround by adding "--chainId 1", but with hardhat, I can't pass this option, so we can't use it)

**Comment by fvictorio** [comment]
> (Note that back then in ganache I could workaround by adding "--chainId 1", but with hardhat, I can't pass this option, so we can't use it)

You can configure the `chainId` in the Hardhat Network part of the configuration:

```js
module.exports = {
  networks: {
    hardhat: {
      chainId: 1
    }
  }
}
```

But agree that the opcode should match the configured value.

**Comment by alcuadrado** [comment]
@drortirosh are you forking another network?

**Comment by alcuadrado** [comment]
I just tried getting the chain id with the json rpc method `eth_chainId` and with a contract with this method

```solidity
  function getChainID() external view returns (uint256) {
      uint256 id;
      assembly {
          id := chainid()
      }
      return id;
  }
```

it returned the right value in all the cases, including with an empty config, forking mainnet, and with a `chainId` in the config.

**Comment by drortirosh** [comment]
my bad.. it was a local port configuration.. had another instance running with different chaind..
