### ISSUE TITLE
[hardhat-etherscan]: Different config field for PolygonScan API key

### ISSUE THREAD

**Issue by paulrberg** [nomiclabs/hardhat#1795]
## Use Case

When using the `hardhat-etherscan` plugin in a Hardhat project that deploys both to an Etherscan website (like Ethereum Mainnet or Rinkeby testnet) and PolygonScan, I am often running into the following error:

> Invalid API key.

The reason is that the API keys for [etherscan.io](https://etherscan.io) and [polygonscan.com](https://polygonscan.com) are not interchangeable.

## Solution

Add a `polygonApiKey` or `polygonScanApiKey` field to the `etherscan` configuration object.

**Comment by shresthagrawal** [comment]
I am facing similar issues as well. I have to keep on changing the keys before deployment

**Comment by paulrberg** [comment]
Closing this, duplicate of #1448.
