### ISSUE TITLE
`traceTransaction` doesn't work for FakeSender transactions

### ISSUE THREAD

**Issue by shuklaayush** [nomiclabs/hardhat#1799]
The [traceTransaction(...)](https://github.com/nomiclabs/hardhat/blob/master/packages/hardhat-core/src/internal/hardhat-network/provider/node.ts#L1235-L1256) function takes an incoming `tx`, and converts it into either @ethereumjs' Transaction (legacy), EIP1559Transaction or EIP2930Transaction object without considering the type of `tx`. This `txWithCommon` value is forwarded to the vm (see relevant code below).

```js
public async traceTransaction(hash: Buffer, config: RpcDebugTracingConfig) {
  ...
      for (const tx of block.transactions) {
        let txWithCommon: TypedTransaction;
        if (tx.type === 0) {
          txWithCommon = new Transaction(tx, {
            common: vm._common,
          });
        } else if (tx.type === 1) {
          txWithCommon = new AccessListEIP2930Transaction(tx, {
            common: vm._common,
          });
        } else if (tx.type === 2) {
          txWithCommon = new FeeMarketEIP1559Transaction(
            { ...tx, gasPrice: undefined },
            {
              common: vm._common,
            }
          );
        } else {
          throw new InternalError(
            "Only legacy, EIP2930, and EIP1559 txs are supported"
          );
        }
  ...
}
```

If `tx` is of type FakeSenderTransaction, then it gets converted to type Transaction and we lose the sender information. This results in weird errors downstream since `getSenderAddress()` of the new Transaction now returns a garbage address. I noticed this when using hardhat with [brownie](https://github.com/eth-brownie/brownie) where a call to `debug_traceTransaction` results in `Error: the tx doesn't have the correct nonce. account has nonce of: 0 tx has nonce of: xxx`. This is because of the garbage sender address.

We should use the same transaction type when copying `tx` to `txWithCommon`. I tested this by tweaking the code a bit, and it seemed to work. I'd be happy to create a PR for this.

```js
if (tx.type === 0) {
  if (tx instanceof FakeSenderTransaction) {
    txWithCommon = new FakeSenderTransaction(
      tx.getSenderAddress(),
      tx,
      {
        common: vm._common,
      }
    );
  } else {
    txWithCommon = new Transaction(tx, {
      common: vm._common,
    });
  }
}
```

## Steps to reproduce
1. Launch [brownie](https://github.com/eth-brownie/brownie) (>= 1.16.0) with hardhat-fork 
`brownie console --network hardhat-fork` 

2. Transact using a random account
```python
deployer = "0x9C33eaCc2F50E39940D3AfaF2c7B8246B681A374"
router = Contract.from_explorer("0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D")

tx = router.WETH.transact({'from': deployer})
```

3. Do a `debug_traceTransaction` call
```
tx.return_value
# See error
RPCRequestError: Error: the tx doesn't have the correct nonce. account has nonce of: 0 tx has nonce of: 5
```

**Comment by alcuadrado** [comment]
Fixed by #1586
