### ISSUE TITLE
Hardhat compile - "Cannot use import statement outside a module" / tsconfig.json esnext

### ISSUE THREAD

**Issue by martinoss** [nomiclabs/hardhat#1808]
I wanted to create a combined project with Hardhat and a React frontend, both configured to use typescript.

My plan was to share the same tsconfig.json, but Hardhat forces me to use "module": "commonjs" and React automatically changes the setting back to "esnext" when starting the application.

When I run "npx hardhat compile" for example, I get the error "Cannot use import statement outside a module"

The exception is thrown here, caused by require():

https://github.com/nomiclabs/hardhat/blob/ee4969a0a8f746f4775d4018326056d161066869/packages/hardhat-core/src/internal/core/config/config-loading.ts#L23

Is it required to configure commonjs when working with hardhat?

**Comment by alcuadrado** [comment]
Hey @martinoss,

Sorry for the late answer. Unfortunately, Hardhat doesn't support ESM yet.

We'll make an announcement once once we support it.

**Comment by Sceat** [comment]
for anyone finding this issue, know that it has been partly fixed in https://github.com/NomicFoundation/hardhat/issues/957#issuecomment-1256094430
