### ISSUE TITLE
Cannot test emitted event during contract deploy

### ISSUE THREAD

**Issue by MoMannn** [nomiclabs/hardhat#1809]
I want to check if an event was emitted during contract deployment. Since deploy is handled differently I cannot find any way to check this.

To reproduce you just need a contract that emits an event in constructor. That is all.

**Comment by fvictorio** [comment]
Hey @MoMannn, this is possible although not documented by Waffle:

```solidity
pragma solidity ^0.8.0;

contract Foo {
  event Event();

  constructor() {
    emit Event();
  }
}
```

```js
const { expect } = require("chai");
const { ethers } = require("hardhat");

it("Should emit an event in the constructor", async function () {
  const Foo = await ethers.getContractFactory("Foo");
  const foo = await Foo.deploy();
  await foo.deployed();

  await expect(foo.deployTransaction).to.emit(foo, "Event");
});
```

Please use [our Discord server](https://hardhat.org/discord) if you have more questions!
