### ISSUE TITLE
Hardhat reset not fetching relevant data

### ISSUE THREAD

**Issue by projectacode** [nomiclabs/hardhat#1819]
Hi, I was under the impression that calling Hardhat's reset method with a new fork number will allow me to interact with contracts deployed at or after that block number, unfortunately, this is not the case. I tested this a couple of times and below is the steps if ya'll would like to take a look.

Attached below are the only two files required to reproduce this issue. 

To reproduce:
The test involves interacting with Uniswap's V2 router which was deployed at [block 10207858](https://etherscan.io/tx/0x4fc1580e7f66c58b7c26881cce0aab9c3509afe6e507527f30566fbf8039bcd0).

- Insert your API key in the forking URL for both files. 
- Install dependencies.
- Run npx hardhat node in a terminal window in project directory.
- npm run start

A `CALL_EXCEPTION`  should be seen, Hardhat will also note `WARNING: Calling an account which is not a contract`.

Setting the blockNumber in hardhat.config.js to `10207858` directly then stopping and starting `npx hardhat node` fixes this.

When initially building around Hardhat I was under the impression that calling Hardhat to reset with the url and blockNumber would 'fetch' the relevant information at that block.

I've had to manually use NodeJS child processes with the fork and blocknumber flags from the command line, and remove the forking object from hardhats config. It's a workaround but complicates things quite a bit.

I wonder if this behaviour is normal and expected and that Hardhat does reset the chain but does not fetch externally again, only fetching relevant data on startup, this makes sense but adding a flag that can be passed in, to 'force' fetching when calling reset and forking again as it does on start would be very useful, cheers!

hardhat.config.js
```
module.exports = {
    networks: {
        hardhat: {
            accounts: {
                count: 2,
            },
            forking: {
                url: 'https://eth-mainnet.alchemyapi.io/v2/<API-KEY>',
                blockNumber: 10207600
            },
            chainId: 1,
            loggingEnabled: false,
            throwOnCallFailures: false,
            throwOnTransactionFailures: false,
        },
    }
}
```

index.js
```
const hardhat = require("hardhat");
const ethers = require("ethers");

async function resetHardHat(blockNumber) {
    return hardhat.network.provider.request({
        method: "hardhat_reset",
        params: [
            {
                forking: {
                    jsonRpcUrl: 'https://eth-mainnet.alchemyapi.io/v2/<API-KEY>',
                    blockNumber,
                },
            },
        ],
    });
}

async function callUniswapV2Router() {
    const factoryABI = ['function factory() external pure returns (address)'];

    const hardHatSigner = new ethers.Wallet('0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d', new ethers.providers.JsonRpcProvider(`http://127.0.0.1:8545/`));

    const uniswap = new ethers.Contract('0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D', factoryABI, hardHatSigner);

    console.log(await uniswap.factory());
}


// Reset Hardhat from the block it started with --> V2 router deploy block
resetHardHat(10207858).then(() => {
    return callUniswapV2Router();
})
```

package.json
```
{
  "scripts": {
    "start": "node index.js"
  },
  "dependencies": {
    "ethers": "^5.4.5",
    "hardhat": "^2.6.1"
  }
}
```

**Comment by fvictorio** [comment]
@projectacode you are mixing providers. This line:

```
    return hardhat.network.provider.request({
```

is using the provider of the current network which, since you are running the script just as `node index.js`, is the in-process hardhat network. But in this line:

```
    const hardHatSigner = new ethers.Wallet('0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d', new ethers.providers.JsonRpcProvider(`http://127.0.0.1:8545/`));
```

You are connecting to a local network. These are different networks, therefore the problem you see. I have a somewhat in-depth explainer about this [here](https://hackmd.io/@fvictorio/hardhat-networks-and-providers) if you are interested.

Please use [our Discord server](https://hardhat.org/discord) if you have more questions.

---

Unrelated, but the private key you are using seems to correspond to [an account](https://etherscan.io/address/0x70997970C51812dc3A010C7d01b50e0d17dc79C8) that is compromised (and if it wasn't before, it surely is now that you posted it here). Don't send funds to it.
