### ISSUE TITLE
Hardhat version changed from 2.6.1 to 2.1.2 after running "npm install" command

### ISSUE THREAD

**Issue by changzhi1990** [nomiclabs/hardhat#1840]
Hi, all

Recently, I encounter a problem when running "npm hardhat compile". Here are the detailed steps:

    ➜  amm-arbitrageur git:(master) npx hardhat --version
    2.6.1
    ➜  amm-arbitrageur git:(master) npm install --save-dev ts-node typescript

    added 1282 packages in 1m

    85 packages are looking for funding
    run `npm fund` for details
    ➜  amm-arbitrageur git:(master) ✗ npx hardhat --version
    2.1.2
  
Why the version of hardhat has been changed from **2.6.1** to **2.1.2**?

Actually, I encounter the [same issue here](https://github.com/nomiclabs/hardhat/issues/1280). The terminal was stuck when downloading the compiler. After some investigation, I find the fix of [this issue](https://github.com/nomiclabs/hardhat/issues/1280) has been merged. So I want to use the latest hardhat version.

I have no idea when the hardhat version has been changed.

Could someone give me some advice? BTW, my OS is macOS.

Thanks.

**Comment by fvictorio** [comment]
This seems to be related to how you are using npm or yarn. My guess is that you have a lock file that uses that version, or maybe just your `package.json` has that version.

The issue tracker is only for bug reports and feature requests. Please use [our Discord server](https://hardhat.org/discord) if you have more questions.

**Comment by changzhi1990** [comment]
> This seems to be related to how you are using npm or yarn. My guess is that you have a lock file that uses that version, or maybe just your `package.json` has that version.
> 
> The issue tracker is only for bug reports and feature requests. Please use [our Discord server](https://hardhat.org/discord) if you have more questions.

Thanks
