### ISSUE TITLE
Support for Deno?

### ISSUE THREAD

**Issue by sjmueller** [nomiclabs/hardhat#1858]
[Deno](https://deno.land) is the next-gen version of nodejs, built specifically for TypeScript. Hardhat is a modern TypeScript project that could fit very well with deno.

Here are some tools that can help:
- [Denoify](https://github.com/garronej/denoify) is a library that can aid in supporting deno with minimal changes to Hardhat's codebase
- [dpx](https://github.com/denorg/dpx) is analogous to node's npx, could it be used to execute the cli?
- Some services attempt to provide deno support automatically (Skypack: https://cdn.skypack.dev/hardhat?dts JSPM: https://dev.jspm.io/hardhat) but don't seem to work out of the box
- Ethers.js is also a modern Typescript repo that's often paired with Hardhat -- for reference, here's the corresponding deno issue: ethers-io/ethers.js#2009

Are there any plans to support deno?

**Comment by alcuadrado** [comment]
Hey @sjmueller,

We don't have any plan to support Deno for now. The reason for this is that Hardhat is currently very tied to node and npm, both directly and through its dependencies. This will partially change in the future, as we are moving some parts of it to Rust.

I'll close this for now, as it's not actionable. Feel free to open another issue in ~6 months.

**Comment by sjmueller** [comment]
Thanks for the quick reply @alcuadrado, will keep an eye on developments and check back in '22!

**Comment by eivindingebrigtsen** [comment]
Any new thoughts on this?

**Comment by alcuadrado** [comment]
Same status as my previous answer, @eivindingebrigtsen
