### ISSUE TITLE
hardhat-etherscan Verfication hangs

### ISSUE THREAD

**Issue by nickjuntilla** [nomiclabs/hardhat#1860]
These calls were working yesterday. Has something changed?

They just hang now or give back:

Reason: The HTTP server response is not ok. Status code: 503 Response text: The service is unavailable.

npx hardhat verify --network main CONTACT_ADDRESS
npx hardhat verify --network rinkeby CONTACT_ADDRESS

**Comment by keepitsane** [comment]
Just wanted to add that I am also experiencing the same issue as well across both Rinkeby and Ropsten testnets.

**Comment by trungnq1510** [comment]
Still hang in bsc testnet.

**Comment by nickjuntilla** [comment]
Just in case anyone needs help I was able to use this library solpp and verify my contracts. Saved my life! Thanks solpp people! Get all your contracts in one file and then use "no optimization". That worked for me. Good luck! I hope Etherscan get's its act together. 

https://github.com/merklejerk/solpp#example

**Comment by rafinskipg** [comment]
It's happening to me too

**Comment by trungnq1510** [comment]
Kk, it's worked.

**Comment by alcuadrado** [comment]
FYI: There was an issue on etherscan side which was fixed.
