### ISSUE TITLE
Function overloading kills hardhat tests.

### ISSUE THREAD

**Issue by grapevinegizmos** [nomiclabs/hardhat#1869]
Perhaps this is not a bug in hardhat but a shortcoming of ethers' apparent inability to handle overloaded functions (functions with same name, different set of parameters) results in tests which fail in test with the error `TypeError: myContract.foo is not a function`.  

Here's an example from my strings handling library.
Main function:
```
function getSlice(string memory source, uint startPos, uint numChars) public pure returns (string memory) {
       uint ustartPos = uint(startPos -1);
       uint _numChars = uint(numChars);
        bytes memory sourcebytes = bytes(source);
       if (_numChars==0) {
           _numChars = ((sourcebytes.length - ustartPos) + 1);
       }
      bytes memory result = new bytes(_numChars);     
      for (uint i = 0; i<_numChars; i++) {
          result[i] = sourcebytes[i + ustartPos];
      }
      return string(result);
    }
```

Convenience version to get a slice from startPos to end of string:
```
function getSlice(string memory source, uint startPos) public pure returns (string memory) {
       return getSlice(source, startPos, 0);
}
```

If the second form of getSlice exists in the library, getSlice causes the error "not a function" whichever form is used in the test.  Only by eliminating the function with the same name can I get the function work.  That means, practically speaking, I simply need to avoid overloaded functions entirely if I want to use hardhat, since I won't be able to write unit tests.  The tests work as expected in truffle or remix, and it seems suboptimal to have to eliminate an entire language feature of solidity in order to use hardhat as the development environment.  Can something be done about this?  I'm guessing using web3.js might fix the problem, but I'm hoping there is a better solution somehow. . .

**Comment by fvictorio** [comment]
Yes, there's nothing we can do about this, sorry.

This will probably be improved by ethers in the next major version, see [this comment](https://github.com/ethers-io/ethers.js/issues/119#issuecomment-861024418).
