### ISSUE TITLE
[Dev exp] Lazy load the config file

### ISSUE THREAD

**Issue by nathandem** [nomiclabs/hardhat#1872]
[Issue]

Hardhat fails to run when the configuration file (`hardhat.config.js`) is invalid because of missing values.

[Minimal Reproducible Example]
```
# hardhat.config.js
require("@nomiclabs/hardhat-waffle");

// For deployment
const ALCHEMY_KOVAN_API_KEY = process.env.ALCHEMY_KOVAN_API_KEY;
const DEPLOYMENT_PK = process.env.DEPLOYMENT_PK;

module.exports = {
    solidity: "0.8.4",
    networks: {
        hardhat: {
            chainId: 1337,
        },
        kovan: {
            url: `https://eth-kovan.alchemyapi.io/v2/${ALCHEMY_KOVAN_API_KEY}`,
            accounts: [`0x${DEPLOYMENT_PK}`],
        },
    },
};
```
In this minimal example, hardhat will fail to run any command until it is able to get the values of `ALCHEMY_KOVAN_API_KEY` and `DEPLOYMENT_PK`.

The thing is these 2 environment variables are only needed when deploying the contract, not the rest of the time. Hardhat doesn't need to load this part of the configuration file when running tests, when testing locally with the hardhat chain, etc.

In short, I'm asking for a lazy load of the configuration depending on what segment of the configuration hardhat needs (instead of eagerly loading it to satisfy the type `HttpNetworkConfig`). For example, when running tests, hardhat only needs to know about the hardhat network (`networks.hardhat`), not the kovan one (`networks.kovan`).

[Benefits]

Not having to load environment variables unless needed, especially useful when working with different developers with a env file not checked out. It's also better for developer experience, especially when using a tool like `env-cmd` to pull env vars from a local file. It avoids having to prefix all hardhat commands to pull env variables which are not needed.

_PS: in the meantime, I set default values when these environment variables are not defined (like below), it'd be better not to have to._
```
const ALCHEMY_KOVAN_API_KEY = process.env.ALCHEMY_KOVAN_API_KEY || 'dummy';
const DEPLOYMENT_PK = process.env.DEPLOYMENT_PK || '0000000000';
```

**Comment by fvictorio** [comment]
Hi @nathandem, thanks for the feedback. Sadly, doing something like this would mean a huge change in how Hardhat works, so it's very unlikely we'll implement it.

As you mention, the workaround right now is to use default values like that. We want to add better support for handling these kinds of secret parameters in the future, and maybe that would make this problem less annoying. But lazy loading probably won't happen.

I'm going to close this, but we read comments in closed issues, so anyone feel free to comment here. Maybe we re-consider this in the long term.
