### ISSUE TITLE
Print a warning when a user tries to use a solc remapping

### ISSUE THREAD

**Issue by alcuadrado** [nomiclabs/hardhat#1877]
Hardhat doesn't support solc remappings. 
We should print a warning if we detect that a user is trying to use them via their config.

**Comment by Rishabhraghwendra18** [comment]
Hi @alcuadrado . First timer this side . I am new to this repo . May you guide me in which file I have to make changes & what to do ?

**Comment by fvictorio** [comment]
@Rishabhraghwendra18 probably the easiest way is to add something here:

https://github.com/nomiclabs/hardhat/blob/770c50911c85a8743428ff090067d8031c75125f/packages/hardhat-core/src/internal/core/config/config-loading.ts#L93-L96

I guess just adding a `checkNoSolcRemappings` function and calling it there might be enough.

**Comment by Rishabhraghwendra18** [comment]
Ok... May you guide me what logic I have to write in this `checkNoSolcRemappings` function ?

**Comment by alcuadrado** [comment]
Hey @Rishabhraghwendra18, there was some miscommunication on our side, but @morgansliman is already working on this. I can point you to another good first issue if you want. Thanks for collaborating!

**Comment by Rishabhraghwendra18** [comment]
ok.. no problem @alcuadrado . May you guide me to other good first issues . I will like to make a PR for them
