### ISSUE TITLE
hardhat-linter marks free functions require visibility

### ISSUE THREAD

**Issue by grapevinegizmos** [nomiclabs/hardhat#1880]
Can't get rid of linter message on free function:

If i put 
`function roleValue(Role role)   pure returns(bytes32) {...}`

before the contract (free function), I get an  linter warning `Explicity mark visibility in function [func-visiblity] [7,1]` which of course is unavoidable since you can't mark visibility on a free function.

**Comment by fvictorio** [comment]
That seems like a [solhint](https://github.com/protofire/solhint/) issue.

**Comment by grapevinegizmos** [comment]
Well, I guess except I loaded it from npm install hardhat-solhint.  So your name is on it.
