### ISSUE TITLE
npx hardhat dont work

### ISSUE THREAD

**Issue by vikingdev92** [nomiclabs/hardhat#1890]
Hello.

I have tried fix a problem with using hardhat, i have tried use VS and CMD, only with CMD it seems to work better, with VS i come nowhere

I had made a simple project earlier today, but deleted it to upload my own file and started getting a lot of errors, now i uninstalled node.js and installed it from the website, also upgraded npm to latest version, but when i make a new folder, mkdir name, cd name, npm init, use npm install --save-dev hardhat and run npx hardhat. it comes up wrong and dont let me start the hardhat project or give me the option.

In the folder now i have folder node_modules and 2 files package.json and package-lock.json

i cant install @nomiclabs/hardhat-waffle cos i dont have hardhat.config.js and cant install that before using npx hardhat to create this file

here is the whole CMD console

C:\Users\34671>mkdir testviking

C:\Users\34671>cd testviking

C:\Users\34671\testviking>npm init -y
Wrote to C:\Users\34671\testviking\package.json:

{
  "name": "testviking",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}

C:\Users\34671\testviking>npm install --save-dev hardhat
npm WARN deprecated debug@3.2.6: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

added 332 packages, and audited 333 packages in 1m

59 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

C:\Users\34671\testviking>npx hardhat
An unexpected error occurred:

Error: Cannot find module '@nomiclabs/hardhat-waffle'
Require stack:
- C:\Users\34671\hardhat.config.js
- C:\Users\34671\testviking\node_modules\hardhat\internal\core\config\config-loading.js
- C:\Users\34671\testviking\node_modules\hardhat\internal\cli\cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (C:\Users\34671\hardhat.config.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\34671\\hardhat.config.js',
    'C:\\Users\\34671\\testviking\\node_modules\\hardhat\\internal\\core\\config\\config-loading.js',
    'C:\\Users\\34671\\testviking\\node_modules\\hardhat\\internal\\cli\\cli.js'
  ]
}

C:\Users\34671\testviking>node -v
v14.17.6

C:\Users\34671\testviking>npm -v
7.24.0

C:\Users\34671\testviking> npm install --save-dev @nomiclabs/hardhat-waffle
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated testrpc@0.0.1: testrpc has been renamed to ganache-cli, please use this package from now on.
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated @ensdomains/ens@0.4.5: Please use @ensdomains/ens-contracts
npm WARN deprecated @ensdomains/resolver@0.2.4: Please use @ensdomains/ens-contracts

added 1114 packages, and audited 1450 packages in 3m

114 packages are looking for funding
  run `npm fund` for details

44 vulnerabilities (11 low, 4 moderate, 29 high)

To address issues that do not require attention, run:
  npm audit fix

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.

C:\Users\34671\testviking>npx hardhat
An unexpected error occurred:

Error: Cannot find module '@nomiclabs/hardhat-waffle'
Require stack:
- C:\Users\34671\hardhat.config.js
- C:\Users\34671\testviking\node_modules\hardhat\internal\core\config\config-loading.js
- C:\Users\34671\testviking\node_modules\hardhat\internal\cli\cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (C:\Users\34671\hardhat.config.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\34671\\hardhat.config.js',
    'C:\\Users\\34671\\testviking\\node_modules\\hardhat\\internal\\core\\config\\config-loading.js',
    'C:\\Users\\34671\\testviking\\node_modules\\hardhat\\internal\\cli\\cli.js'
  ]
}

**Comment by fvictorio** [comment]
@vikingdev92 that probably means that you have a `hardhat.config.js` file in an upper directory. Run `npx hardhat --verbose` and look for a line like this:

```
  hardhat:core:config Loading Hardhat config from /path/to/some/hardhat.config.js +0ms
```

That will tell you where the file is located. You can either remove it (assuming it's not important), or create your project directory in a directory that is not under the one that has the config file.

Please use [our Discord server](https://hardhat.org/discord) if you have more questions like this.

**Comment by webst2r** [comment]
I too had this issue & had been searching for too long. It so happens that i had a hardhat.config.js file in my Home directory. Just delete it.

**Comment by Boyjerbz** [comment]
didnt work
