### ISSUE TITLE
Concurrent solc downloads fail

### ISSUE THREAD

**Issue by roderik** [nomiclabs/hardhat#1925]
We use a NX (nx.dev) mono repo setup where we run tests, typechain builds, etc concurrently for a bunch of hardhat projects. When it decides to run any of these tasks for more than one project, it fails with the following error

```
There was an unexpected problem downloading the compiler: ENOENT: no such file or directory, open '/home/runner/.cache/hardhat-nodejs/compilers/linux-amd64/solc-linux-amd64-v0.8.4+commit.c7e474f2'
41
```

One of the other ones will work and all the rest also since the cache file is there.

**Comment by fvictorio** [comment]
@roderik do you think you could make a minimal reproduction example that triggers this issue? Even if the reproduction steps include "run this command 100 times and 1 of those will fail".
