### ISSUE TITLE
Add an RPC call to get the current status of automine

### ISSUE THREAD

**Issue by jrmsayag** [nomiclabs/hardhat#2010]
Hardhat provides the `evm_setAutomine` call which is very convenient to programmatically change the status of the automine mode, but I can't find a call to get the current status (e.g. `evm_getAutomine`). This would be very convenient for some usecases (e.g. I need to make sure automine is disabled at some point to perform some actions, but I want to restore automine to its previous status after I'm done).

Is there such a call or would it be hard to implement?

**Comment by alcuadrado** [comment]
This is a good idea. It doesn't exist, but it should be pretty straightforward to implement. I would implement it as `hardhat_getAutomine` or something like that though. We try not to add non-standard json-rpc calls to the other modules.

**Comment by fvictorio** [comment]
Added in `hardhat@2.6.8`
