### ISSUE TITLE
eth_feeHistory gives error when calling it from web3 (with hardhat local fork)

### ISSUE THREAD

**Issue by gndelia** [nomiclabs/hardhat#2014]
When calling getFeeHistory in my app, using a local fork with hardhat, I get the following error

```
Error: Internal JSON-RPC error.
{
  "code": -32602,
  "message": "Errors encountered in param 0: Invalid value 1 supplied to : QUANTITY"
}
```

### Expected Behavior

I expect the proper response of eth_feeHistory, something like

```json
{
        "oldestBlock": "0xce1806",
        "baseFeePerGas": [
            "0x26a51093d0",
            "0x2532e26b6d"
        ],
        "gasUsedRatio": [
            0.35032733868710536
        ]
}
```

### Steps to Reproduce

fork a hardhat node with 
```sh
npx hardhat node \
  --fork "$BASE_NODE_URL" \
  --verbose
```

This is the very basic config I've used

```js
'use strict'
require('dotenv').config()

module.exports = {
  defaultNetwork: 'hardhat',
  networks: {
    hardhat: {
      accounts: {
        accountsBalance: process.env.WEI_BALANCE || '10000000000000000000000',
        mnemonic: process.env.MNEMONIC
      },
      forking: {
        url: process.env.BASE_NODE_URL,
        blockNumber: process.env.BLOCK_NUMBER
          ? parseInt(process.env.BLOCK_NUMBER)
          : undefined
      }
    },
    mainnet: {
      url: process.env.BASE_NODE_URL,
      chainId: 1
    }
  }
}

```

`BASE_NODE_URL` contains an HTTPS URL of a node that supports `eth_feeHistory`.

Then, from JS, I just do

```js
const web3 = new Web3(new Web3.providers.HttpProvider('local-fork-url'))
web3.eth.getFeeHistory(1, 'latest', []).then(console.log).catch(console.error)
// same problem with
// web3.eth.getFeeHistory('0x1', 'latest', []).then(console.log).catch(console.error)
```

and I get the above-mentioned error. If instead of pointing out to a local fork I point out to the HTTPS URL directly (without any local fork), it works.

### Environment

- Web3.js Version: 1.5.3 (which supports EIP-1559)
- Operating System: Mac OS 11.6
- Browser: Brave
- Node.js Version: 14.16.1
- NPM Version: 6.14.32

There's a counterpart of this issue in web3js repo https://github.com/ChainSafe/web3.js/issues/4510 but it seems they believe the problem is within hardhat

**Comment by fvictorio** [comment]
Hey @gndelia, thanks for reporting this! I'm pretty sure this is a problem in web3; see my comment in the issue you opened there. I'm going to tentatively close this, but I'll re-open it if I was wrong and this is actually a problem on our side.

**Comment by gndelia** [comment]
Thanks for your response @fvictorio  ! I tried to find the spec before opening the tickets in both repos but I failed to find them. Thanks for the help! 🚀

**Comment by fvictorio** [comment]
Yes, those specs are fairly new and not that well-known (yet!), but it's what we are following (and hopefully the rest of the ecosystem too :sweat_smile:)
