### ISSUE TITLE
Add chai-bignumber by default to hardhat

### ISSUE THREAD

**Issue by pedrohba1** [nomiclabs/hardhat#2018]
So, bigNumber is a common way to represent values from solidity smart contracts. However, I can't use BigNubmer comparisons as stated here by default: https://www.chaijs.com/plugins/chai-bignumber/ 

I would like to be able to do something like:
```js
expect(afterBalance).to.be.bignumber.greaterThan(beforeBalance);
```
without having to add `chai-bignumber` to a hardhat project and set it up. Given that BigNumber is so common, it does not make sense to me for comparisons between this type not coming out of the box in hardhat.

At least some documentation regarding on how to set it up should be added.

**Comment by alcuadrado** [comment]
Hey @pedrohba1, thanks for adding this suggestions.

This would be out of scope for hardhat tbh, but maybe for a plugin.

Which one do you think should have this?

**Comment by pedrohba1** [comment]
> Hey @pedrohba1, thanks for adding this suggestions.
> 
> This would be out of scope for hardhat tbh, but maybe for a plugin.
> 
> Which one do you think should have this?

I think it would be best to add it to @nomiclabs/hardhat-waffle?
Since it's the one that has chai macthers. 

It is a simple implementation I guess, just add:
```js
var chai = require('chai');
//use default BigNumber
chai.use(require('chai-bignumber')());
```

Wherever chai comes from.
Probably easier said than done, but it might me something like this;

**Comment by alcuadrado** [comment]
Are you sure that works with ethers' big numbers?

**Comment by pedrohba1** [comment]
> Are you sure that works with ethers' big numbers?

You can add `Ethers.BigNumber` specifically, if it is not the same as the version that chai uses by default. `chai-bignumber` does support that:

```js
chai.use(require('chai-bignumber')(BigNumber));
```

**Comment by alcuadrado** [comment]
I don't think that works. Note that `chai-bignumber` is built for `bignumber.js`, and ethers has its custom big number class with a different api.

For example, this

```js
const chai = require("chai");
const ethers = require("ethers");
chai.use(require('chai-bignumber')(ethers.BigNumber));

chai.expect(ethers.constants.One).to.be.equal(ethers.BigNumber.from(1));
```

Throws this

```
node index.js

/private/tmp/npmproject-0/node_modules/chai/lib/chai/assertion.js:152
      throw new AssertionError(
      ^
AssertionError: expected { Object (_hex, _isBigNumber) } to equal { Object (_hex, _isBigNumber) }
    at Object.<anonymous> (/private/tmp/npmproject-0/index.js:5:41)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47 {
  showDiff: true,
  actual: BigNumber { _hex: '0x01', _isBigNumber: true },
  expected: BigNumber { _hex: '0x01', _isBigNumber: true },
  operator: 'deepStrictEqual'
}
```

**Comment by pedrohba1** [comment]
oh well. 
Any other idea on how to make it easier to compare BigNumbers?

**Comment by alcuadrado** [comment]
Yes, that can be done. I'm not sure how challenging it would be.

**Comment by alcuadrado** [comment]
I'm closing this issue as it's not something that we want to execute for now. Feel free to open a thread in our discussion section.

**Comment by davidlondono** [comment]
please add support

**Comment by alcuadrado** [comment]
We are currently exploring adding something like this.

**Comment by jamesmcc-design** [comment]
I also found this awkward to get.. ended up using this and it seems to be working fine.
```(A.gt(B)).equal(true)```
Where A and B are BigNumber

**Comment by alcuadrado** [comment]
You can take a look at #2428 @pedrohba1

**Comment by jdnichollsc** [comment]
Hello folks, can I use this approach in the meantime?
```js
const beforeBalance = ethers.utils.formatEther(await ethers.provider.getBalance(contract.address));
// Run transaction to change balance
const afterBalance = ethers.utils.formatEther(await ethers.provider.getBalance(contract.address));

expect(Number(afterBalance)).to.be.lessThanOrEqual(Number(beforeBalance));
```

Please let me know and thanks for your support! <3

**Comment by jdnichollsc** [comment]
Ok, there's another better alternative:
```js
const { expect, use } = require('chai');
const { solidity } = require('ethereum-waffle');
use(solidity);

it('shuld reduce the health of the boss when attacked by a player', async function () {
  const contract = await deployContract();
  const { health: prevBigBossHealth } = await contract.bigBoss();
  await contract.attackBoss();
  const { health: newBigBossHealth } = await contract.bigBoss();

  expect(newBigBossHealth).to.be.lt(prevBigBossHealth);
});
```

More details [here](https://ethereum-waffle.readthedocs.io/en/latest/matchers.html#bignumbers)

**Comment by lukehutch** [comment]
Ethers uses BN.js internally for its BigNumber implementation:

https://docs.ethers.io/v5/api/utils/bignumber/
