### ISSUE TITLE
Transaction reverted and Hardhat couldn't infer the reason.

### ISSUE THREAD

**Issue by TJakubek** [nomiclabs/hardhat#2022]
Hi everyone. 

I am getting the above error during one of my contract calls when running a local node. The weird thing is sometimes the call works correctly, while others it will throw weird errors in numerous different places. 

In one instance, the error stack suggests a method is called which has nothing at all to do with the one I am running. 

Does anyone have any idea what can be the cause of such behaviour? Is there any additional info I can post to help with debug? 
Thanks in advance for any help

**Comment by fvictorio** [comment]
These errors are really hard to debug without a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). If you can create one, we'll take a look.

The easiest way to do this when you don't know why the error happens is to take your project and create a branch where you remove everything that is not relevant to reproduce the problem. But I understand that even that could be very time-consuming.

**Comment by saicharanpogul** [comment]
Same here.
```
...
   mapping(address => mapping(uint => Person)) private people;
   mapping(address => uint[]) private indexes;
...
   function addPerson(Person memory _person, uint8 _isPersonActive) public {
        // requires
        people[msg.sender][_person.personId] = _person;
        if(_isPersonActive == 2) { // some condition

            // indexes[msg.sender].push(_person.personId); // <-- 1
            
            uint length = indexes[msg.sender].length; // <-- 2
            indexes[msg.sender][length - 1] = _person.personId;
        }
    }
...
```
I tried the commented line then I got the following error: ``` AssertionError: Returned error: Error: Transaction reverted and Hardhat couldn't infer the reason. Please report this to help us improve Hardhat.```
The confusing part is I have some logic in another function that has almost similar functionality that worked, but in this function, it didn’t work. 
So I tried in another way then I got the following error: ``` AssertionError: Returned error: Error: VM Exception while processing transaction: reverted with panic code 0x11 (Arithmetic operation underflowed or overflowed outside of an unchecked block)``` (It is just a similar example to my code)

**Comment by fvictorio** [comment]
@saicharanpogul same comment: we need a minimal example with clear reproduction steps. Otherwise trying to guess how to reproduce the problem from a snippet is really time-consuming for us.

**Comment by saicharanpogul** [comment]
@fvictorio I have solved it and added the issue for which I was getting that error. #2045

**Comment by TJakubek** [comment]
hey guys, thanks for answering. I finally figured it out as well. 
Metamask was at times incorrectly estimating the amount of gas needed, so sometimes it would succeed while other times it failed. 

The misleading part was that in the node logs it would always state that the gas used was below the gas sent, so it didn't help in debugging. So exactly as @saicharanpogul explained in his issue. The other misleading part was the weird stack trace I mentioned, but I guess thats not relevant. 

Anyways glad we both got it working!
