### ISSUE TITLE
Add Avalanche support to hardhat-etherscan

### ISSUE THREAD

**Issue by MrHell0** [nomiclabs/hardhat#2033]
hardhat-etherscan doesn't work w/ Avalanche. It would be awesome if it did.

**Comment by DenisGorbachev** [comment]
Any chance to merge this non-breaking PR?

**Comment by alcuadrado** [comment]
This has already been released. Take a look at the [docs of the new version](https://hardhat.org/plugins/nomiclabs-hardhat-etherscan.html#multiple-api-keys-and-alternative-block-explorers).
