### ISSUE TITLE
Feature request: compile contracts dynamically

### ISSUE THREAD

**Issue by dancju** [nomiclabs/hardhat#2047]
**Scenario:** I am building an API that takes a Solidity contract as input and runs tests with Hardhat. However, in the current Hardhat, we can only compile contracts in `contracts/`.

**Feature Request:** I hope Hardhat could support compiling a contract through a js function call.

**Comment by alcuadrado** [comment]
Hey @dancju!

You can do that by overriding a subtask of `compile`. Take a look at [this one](https://github.com/nomiclabs/hardhat/blob/master/packages/hardhat-core/src/builtin-tasks/compile.ts#L104-L119) in particular, and read [this section](https://hardhat.org/guides/create-task.html#overriding-tasks) of the docs.
