### ISSUE TITLE
Add verbose debugging for requests

### ISSUE THREAD

**Issue by Pet3ris** [nomiclabs/hardhat#2056]
Hi There,

I'm running into a `ProviderError` while doing a kovan deployment and struggling to understand what the detailed response is from the RPC node:

- `verbose` logging does not currently report RPC requests
- `yarn link` does not seem to work well with hardhat (see here: https://github.com/nomiclabs/hardhat/issues/1222). By linking `hardhat-core`, I'm running into an error `Cannot find module 'debug'`.

**Potential solutions**

The ideal solution would be to enable a logging option for RPC requests especially in light of provider errors that are not easily interpretable.

A workaround solution would be to document a workflow to use `hardhat` with `yarn link`.

**Comment by fvictorio** [comment]
> A workaround solution would be to document a workflow to use `hardhat` with `yarn link`.

Hey @Pet3ris, have you checked our [contributing](https://github.com/nomiclabs/hardhat/blob/master/CONTRIBUTING.md) doc? There's an explanation there on how to link the project locally.

**Comment by Pet3ris** [comment]
Thanks @fvictorio - didn't realize that's where the info was. Super helpful thanks!
