### ISSUE TITLE
Hardhat test command poor performance when there are large number of tests

### ISSUE THREAD

**Issue by Siegrift** [nomiclabs/hardhat#2076]
Hi,

on our project (https://github.com/api3dao/airnode) hardhat tests run way too slowly (nearly ~30 minutes, see screenshot).
I've figured out that the performance penalty is due to large number of test files. I am not sure what causes this performance penalty but my fix for now is to run `hardhat test` with each test file separately.

![image](https://user-images.githubusercontent.com/22679154/142464992-b6ee48a0-3a35-469f-8bac-4bd9f8b90a52.png)

This penalty also happens if I run only a subset of tests (using `.only`)

## To reproduce

You can take a look at our project in the protocol tests - https://github.com/api3dao/airnode/tree/master/packages/airnode-protocol/test and run `hardhat test` there. But I think this is reproducible just by creating a large number of test files.

## Versions

"hardhat": "^2.6.0",

**Comment by alcuadrado** [comment]
Thanks for submitting this issue, @Siegrift 

Your description makes me think that this is unrelated to Hardhat, and more to mocha.

I only see a few test files in the project you linked. Have you modified the codebase lately? Can you link us to a commit instead?

Thanks

**Comment by Siegrift** [comment]
Yeah, sorry that was a poor link from me.

These are the tests: https://github.com/api3dao/airnode/tree/master/packages/airnode-protocol/test
This is the script I have implemented to reduce the execution speed: https://github.com/api3dao/airnode/blob/master/packages/airnode-protocol/scripts/run-hardhat-tests.ts

**Comment by alcuadrado** [comment]
But I only see ~15 test files there, is that the number you had in mind?

**Comment by Siegrift** [comment]
Yeah, but the actualy number of tests is rather large. For example, take a look at https://github.com/api3dao/airnode/blob/master/packages/airnode-protocol/test/rrp/AirnodeRrp.sol.js

When the tests are run using `hardhat test` they take around 27 minutes (as in the screenshot) and it seems that the bottleneck is just the number of tests, because when I test file by file (using the linked script) the execution is 9 minutes (see screenshot from current master).

![image](https://user-images.githubusercontent.com/22679154/144275200-6949a674-a546-40a6-95aa-9d316d874e8b.png)

**Comment by alcuadrado** [comment]
@Siegrift I think one reason this is happening is that you are defining top-level `beforeEach`s in each file. Mocha calls these [root-level hooks](https://mochajs.org/#root-level-hooks) and are now discouraged.

root-level hooks are not scoped to the file where they are declared, but global. This means that you are running every top-level `beforeEach` for every test. When you run a single file, the unrelated `beforeEach`s are never registered.

**Comment by Siegrift** [comment]
Thanks, I didn't know about this behaviour but it makes sense.

An easy way is to not use these root level hooks and make sure the tests are wrapped inside a `describe` statement.
Is there a better way? (This seems like it's very easy to forget about)

**Comment by alcuadrado** [comment]
I don't think there's a better alternative. IMO you should always place things inside a describe/context. 

Maybe you can add a linter rule to forbid top-level before each calls.

I'm closing this issue as I couldn't find any other reason for the slow down. Feel free to open a new one if you find something else.
