### ISSUE TITLE
Revamp vyper plugin

### ISSUE THREAD

**Issue by alcuadrado** [nomiclabs/hardhat#2082]
Things that need to change:

* Do not recompile every time
* Split the compilation pipeline into sensible subtasks
* Use the compiler binaries instead of docker

**Comment by feuGeneA** [comment]
Released in [@nomiclabs/hardhat-vyper v3.0.0](https://github.com/nomiclabs/hardhat/releases/tag/%40nomiclabs%2Fhardhat-vyper%403.0.0)
