### ISSUE TITLE
RSK explorer support for hardhat-etherscan

### ISSUE THREAD

**Issue by gpetraglia** [nomiclabs/hardhat#2087]
I am planning to add support for the RSK explorer. Sadly, the RSK explorer works quite differently from other explorers like etherscan, which would imply a little bit more of work than just adding the url. Instead, I would have to add another dependency (https://github.com/rsksmart/rsk-verify-tools). Would you think it is good to do create this PR or do you prefer that I create a new plugin that works exclusively for RSK?

Anyother feedback is appreciated

**Comment by alcuadrado** [comment]
Hey @gpetraglia! Thanks for opening this issue.

While the etherscan plugin supports other chains apart from Ethereum mainnet, we are not really open to add RSK at the moment. Our policy is to support every chain that has an official etherscan alternative. Official here means "coming from the etherscan team". The reason for this is that it's almost free for us to do it and maintain it.

Verification is a complex and extremely fragile problem, and we don't have the bandwidth to create custom solutions for other chains. Still, if you want to smooth out the process of verifying RSK smart contracts with Hardhat, making a new community plugin for this would be great!

I'm closing this issue as it's not actionable at the moment, but feel free to open a new one.

**Comment by gpetraglia** [comment]
Completely agree. I will create the plugin
