### ISSUE TITLE
Transactions/calls in "Forking" is too slowly

### ISSUE THREAD

**Issue by Vorh** [nomiclabs/hardhat#2094]
Hello! 
I picked up a local node and forked  `Polygon` across `Infura`.
Blockchain requests and transactions take a very long time.
* Сalls on average 30 seconds.
* Transactions from a minute to an error with a timeout. 

I do not know what this problem is related to. 
Sometimes calls to the blockchain occur without delay, but most often there is a timeout .
Tried increase memory with command:  `--max-memory 8096` but it didn't speed up. 

I run it with the command:  `npx hardhat  node --max-memory 8096`

Versions:
```
node: v16
hardhat: 2.6.8
web3: 1.5.2
Linux: 5.15.3-arch1-1
```

**Comment by fvictorio** [comment]
Have you read [this](https://hardhat.org/hardhat-network/guides/mainnet-forking.html#pinning-a-block)?

**Comment by rafehi** [comment]
I've got a similar issue with the bsc. Pinning doesn't work for me as my use-case is based around the current state of the blockchain.

Ideally, I'd like to automatically reset hardhat to the latest block every 5 minutes, and try run transactions against existing contracts. The issue I have is that certain contracts timeout, making the solution unfeasible.

Are there any workarounds here, or is the limitation the nodes themselves, and the amount of data they have to fetch?

**Comment by rafehi** [comment]
I've got a similar issue with the bsc. Pinning doesn't work for me as my use-case is based around the current state of the blockchain.

Ideally, I'd like to automatically reset hardhat to the latest block every 5 minutes, and try run transactions against existing contracts. The issue I have is that certain contracts timeout, making the solution unfeasible.

Are there any workarounds here, or is the limitation the nodes themselves, and the amount of data they have to fetch?

**Comment by fvictorio** [comment]
> Are there any workarounds here, or is the limitation the nodes themselves, and the amount of data they have to fetch?

Another way of speeding up forking is to reduce the distance (like, the physical distance) to the node you're forking from. This means either having a node running in your LAN, or running your code "closer to the remote node", if that's possible at all. For example, I'm in the southern hemisphere, so running our forking tests in my machine against Alchemy takes way longer than doing the same in GithHub's CI, which is surely much closer to wherever Alchemy's nodes are located.

**Comment by rafehi** [comment]
Thanks @fvictorio , that's sped it up enough to no longer timeout.
