### ISSUE TITLE
Allow metadata on hardhat network config

### ISSUE THREAD

**Issue by hamishjohnson** [nomiclabs/hardhat#2110]
I like to attach metadata to hardhat network config, for example:

```
    bsc: {
      url: "https://bsc-dataseed.binance.org/",
      accounts: [process.env.SECRET_1, process.env.SECRET_2],
      swapRouter: "0x10ED43C718714eb63d5aA57B78B54704E256024E",
      swapFactory: "0xcA143Ce32Fe78f1f7019d7d551a6402fC5350c73",
    },
    bscTestnet: {
      url: "xxx",
      accounts: [process.env.SECRET_1, process.env.SECRET_2],
      swapRouter: "0xD99D1c33F9fC3444f8101754aBC46c52416550D1",
      swapFactory: "0x6725F303b657a9451d8BA641348b6761A6CC7a17",
    },
```

This allows me to easily pass in values that belong to specific networks to particular scripts or tests.

Perhaps adding a metadata field like so to make this official:

```
export interface HardhatNetworkUserConfig {
  chainId?: number;
  from?: string;
  gas?: "auto" | number;
  gasPrice?: "auto" | number;
  gasMultiplier?: number;
  initialBaseFeePerGas?: number;
  hardfork?: string;
  mining?: HardhatNetworkMiningUserConfig;
  accounts?: HardhatNetworkAccountsUserConfig;
  blockGasLimit?: number;
  minGasPrice?: number | string;
  throwOnTransactionFailures?: boolean;
  throwOnCallFailures?: boolean;
  allowUnlimitedContractSize?: boolean;
  initialDate?: string;
  loggingEnabled?: boolean;
  forking?: HardhatNetworkForkingUserConfig;
  coinbase?: string;
  metadata?: any;
}
```

**Comment by Lopol2010** [comment]
Sounds good. Especially when you have big configs, you would just assign such config file to this field.

Though you already can have custom fields and get them like this `hre.network.config.metadata` where metadata is your custom field name. 

I wonder if it's possible to have this metadata field on Hardhat Network correspond to the current fork URL without writing my own utility scripts for this. One solution is to just allow multiple Hardhat Network entries, for example, if an entry has `forking` property set, we treat this network as Hardhat with forking.

**Comment by feuGeneA** [comment]
I can't see us doing this in the core of Hardhat, but please feel free to create a plugin that extends the configuration however you see fit.

**Comment by krruzic** [comment]
I implemented this as a plugin, might not be exactly what you want but I had a similar usecase and solved it.

https://www.npmjs.com/package/hardhat-network-metadata
https://github.com/krruzic/hardhat-network-metadata
