### ISSUE TITLE
The tsconfig.json in hardhat-ethers can't find referenced path "../../hardhat-core/src"

### ISSUE THREAD

**Issue by JakobLopez** [nomiclabs/hardhat#2129]

**Comment by feuGeneA** [comment]
If you believe this is a bug in Hardhat, please re-open and explain more what you are trying to accomplish and how you have arrived at this situation. As it stands, there is not enough information here for us to act on. If you need help, please use Discord.

**Comment by AlimByWater** [comment]
Same problem
