### ISSUE TITLE
hardhat network cannot report correct location of failure in the solidity file

### ISSUE THREAD

**Issue by kl456123** [nomiclabs/hardhat#2132]
<img width="788" alt="Screen Shot 2021-12-07 at 12 45 08" src="https://user-images.githubusercontent.com/10957718/144971610-f038b237-d8d5-4fcc-a479-5fafa6fa03b0.png">

the source code is in here https://rinkeby.etherscan.io/address/0x075b36de1bd11cb361c5b3b1e80a9ab0e7aa8a60#code
first I deploy it and run it in my fork network.
then I call `multicall(uint256 deadline, bytes[]data)`, the stacktrace displayed is wrong. in fact the `exactInputSingle` can never be called. you can check that the `STF` error in not in that function  very easily

**Comment by alcuadrado** [comment]
Hey, thanks for reporting this issue!

Unfortunately, this is a known limitation that we won't fix in the near future.

It's documented here: https://hardhat.org/hardhat-network/reference/#solidity-optimizer-support
