### ISSUE TITLE
Issues with time synchronization for Avalanche C-chain fork

### ISSUE THREAD

**Issue by mbare0** [nomiclabs/hardhat#2133]
Hello everyone :)

First of all thank you for delivering such useful tools for blockchain development!

I've been recently working with hardhat forking the Avalanche C-chain and found some issues with time synchronization. My tests are time dependent so having pretty accurate time is important. 

I try printing time difference between JS time and current block in my tests:
```
describe('Smart loan',  () => {
  before("Synchronize blockchain time", async () => {
    await checkTimeDifference();
  });
  
      it("example test", async () => {
      await checkTimeDifference();

      await contract.method(toWei("100"));
      await checkTimeDifference();
      });
});
```      
where:
```
async function checkTimeDifference() {
    let blockNumber = await provider.getBlockNumber();
    let block = await provider.getBlock(blockNumber);
    let timestamp = block.timestamp * 1000;
    console.log(`Difference ${(Date.now() - timestamp)/1000}s`);
}
```

When I start it just after running a fork, it prints a positive value (e.g. 40s). After performing some actions causing mining of new blocks, time difference is let's say 10-15s (ofc it's pretty random).
It becomes more weird when I do it again, because often time difference can becomes negative, meaning a block can have a timestamp in the future.

Normally I would just try synchronizing block timestamp before a test:
`await provider.send('evm_setNextBlockTimestamp', [Math.ceil(new Date().getTime() / 1000)]);`. 

But firstly, it is not enough to synchronize fork once at the beginning, because after some actions time difference diverges and I have to synchronize again.
Secondly when `block.timestamp` is in the future, it makes it more complicated because I can't set a block.timestamp before a previous one (my workaround is to `hardhat_reset` fork  and try to synchronize again).

Maybe it's related to the fact that I use Avalanche fork that has different average mining times than Ethereum chains?

Thanks for any help,
mbare

**Comment by fvictorio** [comment]
Hey @mbare0, there are several things to point out here.

First, by default Hardhat automines blocks, which means that a new block is created when a tx is received. So there are no guarantees that a new block will be mined every N seconds. If you want that behavior, you need to disable automining and enable interval mining (see [here](https://hardhat.org/hardhat-network/reference/#mining-modes)).

Second, Hardhat guarantees that each new block has a different timestamp. In practice, this means that if you mine 10 blocks in less than 1 second (which is entirely possible with automining), then each one will have a timestamp that is one second later than the previous one. If you are comparing with `Date.now()`, then you'll have that problem of having blocks "in the future".

Hope that helps! And feel free to re-open if you still think there's a bug (or feature request) here.
