### ISSUE TITLE
HardhatError: HH700??

### ISSUE THREAD

**Issue by herumet** [nomiclabs/hardhat#2135]
npx hardhat run scripts/run.js
HardhatError: HH700: Artifact for contract "WavePortal" not found.

**Comment by feuGeneA** [comment]
From CONTRIBUTING.md: "If you find a bug or want to propose a new feature, please open an issue."

HardhatErrors are in most cases problems reflective of problems in your own code, not Hardhat's. If you need help, please ask in Discord rather than raising an Issue here.
