### ISSUE TITLE
Problem with apiKey when adding trailing comma on hardhat config

### ISSUE THREAD

**Issue by fmonpelat** [nomiclabs/hardhat#2139]
Hi, im unable to verify the contract  always getting:
`Error in plugin @nomiclabs/hardhat-etherscan: Invalid API Key`

my hardhat config is:
```
require('@nomiclabs/hardhat-ethers');
require('@nomiclabs/hardhat-etherscan');

module.exports = {
  solidity: '0.8.4',
  defaultNetwork: 'ropsten',
  networks: {
    hardhat: {},
    ropsten: {
      url: process.env.ROPSTEN_NETWORK_URL,
      accounts: [process.env.WALLET_PRIVATE_KEY],
    },
  },
  etherscan: {
    apiKey: process.env.ETHERSCAN_API_KEY,
  },
};
```
but when removing the trailing comma on `apiKey: process.env.ETHERSCAN_API_KEY,` it works.

Hardhat version 2.7.0
@nomiclabs/hardhat-etherscan: "^2.1.8"

**Comment by alcuadrado** [comment]
Closing as this plugin changed a lot. If this problem is still present with the new version, please open a new issue.

**Comment by JBobznfts** [comment]
hello i am having the same problem when i try to verify it says Error in plugin @nomiclabs/hardhat-etherscan: Please provide an Etherscan API token via hardhat config. For example:  {
  ...
  etherscan: {
    apiKey: {
      rinkeby: 'your API key'
    }
  }
}

See https://etherscan.io/apis


this is the part that saying has the error what am i doing wrong thank you im new to all this       



module.exports = {
  solidity: "0.8.4",
  networks:{
    rinkeby: {
      url: process.env.REACT_APP_RINKEBY_RPC_URL,
      accounts: [process.env.REACT_APP_PRIVATE_KEY]
    },
  },
  etherscan: {
    apikey: process.env.REACT_APP_ETHERSCAN_KEY,
  },
};

**Comment by JBobznfts** [comment]
> module.exports = {
  solidity: "0.8.4",
  networks:{
    rinkeby: {
      url: process.env.REACT_APP_RINKEBY_RPC_URL,
      accounts: [process.env.REACT_APP_PRIVATE_KEY]
    },
  },
  etherscan: {
    apikey: process.env.REACT_APP_ETHERSCAN_KEY,
  },
};

**Comment by JBobznfts** [comment]
module.exports = {
  solidity: "0.8.4",
  networks:{
    rinkeby: {
      url: process.env.REACT_APP_RINKEBY_RPC_URL,
      accounts: [process.env.REACT_APP_PRIVATE_KEY]
    },
  },
  etherscan: {
    apikey: process.env.REACT_APP_ETHERSCAN_KEY,
  },
};
