### ISSUE TITLE
npx hardhat compile Nothing to compile

### ISSUE THREAD

**Issue by herumet** [nomiclabs/hardhat#2142]
npx hardhat compile
Nothing to compile
ｗｈｙ？
`<!--`

Thank you for using Hardhat and taking the time to open an issue!

**Note that this issue tracker is not a support channel.**

- For help with Hardhat and Hardhat network, please use our [Discord server](https://hardhat.org/discord).
- For help with ethers.js, please go to [its Github Discussions](https://github.com/ethers-io/ethers.js/discussions).

If you are reporting a bug, please include reproduction steps. The best way to do this is to include a [Minimal Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example). If you can't do that, then include a link to your repo, and the steps to reproduce the problem. The easiest it is to reproduce your problem, the faster we are going to be able to fix it.

If you are submitting a feature request, please take the time to clearly describe your use case, and not only your proposed solution.

This issue will be automatically assigned to a Hardhat team member. This person will act as the point of contact between you and the team, but won't necessarily fix it nor address it in any way. An issue being assigned does not mean that it's being worked on.

-->

**Comment by fvictorio** [comment]
This means that there are no contracts in your directory, or that they were already compiled.

**Comment by ihorbond** [comment]
I have hardhat.config.js and contracts folder in root. Updated contract multiple times but everytime it's Nothing to compile. I have other projects where I use hardhat no problem but here I'm lost. What could be wrong ? cache file indicates as if there is no files
![image](https://user-images.githubusercontent.com/15573624/168389534-6a04bd49-169f-4724-84e3-9f5e236f54fa.png)

**Comment by boldrack** [comment]
This looks like a fresh issue ..

**Comment by hwale** [comment]
I'm also getting this issue with a fresh advanced sample project in Typescript.

**Comment by ihorbond** [comment]
@hwale @boldrack come into their discord https://discord.com/invite/TETZs2KK4k let's chat there

**Comment by faea726** [comment]
I just create a Typescript project. And get that issue too.
```
mkdir project
cd project
npm init
...
npx hardhat
...
npx hardhat compile
```
Result:
```
Nothing to compile
No need to generate any newer typings.
```

**Comment by haardikk21** [comment]
+1 to reopening this issue. Been seeing that since the version bump across multiple projects. Even freshly created projects cannot be compiled.

**Comment by TheyCallMeCheng** [comment]
Hey everyone, there are at least 2 open issues about this 
One solution is to use WSL with ubuntu if you're on windows. 

Check this one https://github.com/NomicFoundation/hardhat/issues/2712

**Comment by valeshgopal** [comment]
I'm facing the same issue. Changed the version back to 2.9.4 and that doesn't help either

**Comment by dragondyt** [comment]
> 我面临同样的问题。将版本改回 2.9.4 也无济于事

It only needs to rewrite the sol read path in hardhat.config.ts and it will work properly. I think it is because the glob does not recognize the expression under windows

`subtask(
    "compile:solidity:get-source-paths",
    async (_, {config}): Promise<string[]> => {
        const glob = require("glob");
        const files = await util.promisify(glob)("contracts/*.sol", {});
        return files.map(path.normalize);
    }
);`

**Comment by staranger01** [comment]
I am facing the same issue too.

**Comment by iamoracle** [comment]
I am experiencing the same problem here.

**Comment by terminatorec** [comment]
#https://github.com/NomicFoundation/hardhat/issues/2712

**Comment by terminatorec** [comment]
https://github.com/NomicFoundation/hardhat/issues/2712#issuecomment-1126722588

**Comment by angwilson** [comment]
Solved it by installing this package 
npm install glob@7.2.0

**Comment by iaskgithub** [comment]
hardhat is so hard to use,and i will change back to the remix IDE

**Comment by janaka45** [comment]
The major issue with that you haven't created a ***contracts*** directory in your code.Then you can implement sol file in it and run npx hardhat compile..It was worked for me...Thanks.
