### ISSUE TITLE
Time to remove proxy provider?

### ISSUE THREAD

**Issue by molfar** [nomiclabs/hardhat#2147]
https://github.com/nomiclabs/hardhat/blob/56ce15ae74583feae96a92a366c2c19216eaa9df/packages/hardhat-ethers/src/internal/index.ts#L27

**Comment by fvictorio** [comment]
Ha, thanks for the reminder.

@alcuadrado is that comment still relevant? Should we do that?

**Comment by alcuadrado** [comment]
I think the comment is what's outdated. It proceeds the proxy actually.

I think the intention was to remove our wrapper once ethers implemented eip1559, but unfortunately we still need it.
