### ISSUE TITLE
Hardhat and Ethers out of sync?

### ISSUE THREAD

**Issue by Dellybro** [nomiclabs/hardhat#2148]
On the latest version of Ethers: 5.5.2, it seems when running `hardhat compile`, the contract factories inside my typechain folder are extending from ContractFactory from ethers, but when i try to deploy my contracts using hardhat `upgrades.deployProxy` i get errors saying my contracts do not correctly implement `ContractFactory`

EX:

ContractFactory.ts (to make my life easier)
```
import { ethers } from 'hardhat';

enum MyContracts {
  SomeToken = 'SomeToken',
}

export class MyContractFactory {
  // SomeToken
  static getSomeTokenFactory(): Promise<SomeToken__factory> {
    return ethers.getContractFactory(MyContracts.SomeToken) as Promise<SomeToken__factory>;
  }

  static getSomeTokenAt(address: string): Promise<SomeToken> {
    return ethers.getContractAt(MyContracts.SomeToken, address) as Promise<SomeToken>;
  }
}
```

deploy.ts
```
....
    const someToken = (await upgrades.deployProxy(
      await MyContractFactory.getSomeTokenFactory(),
      [`${name} Some Token`, `${symbol}-ST`],
      {
        unsafeAllowCustomTypes: true,
        unsafeAllowLinkedLibraries: true,
      }
    )) as SomeToken;
    await someToken.deployed();
 ....
```

The line `await MyContractFactory.getSomeTokenFactory()` gives me a whole mess of errors

```
Argument of type 'SomeToken__factory' is not assignable to parameter of type 'ContractFactory'.
  The types returned by 'deploy(...)' are incompatible between these types.
    Type 'Promise<SomeToken>' is not assignable to type 'Promise<Contract>'.
      Type 'SomeToken' is not assignable to type 'Contract'.
        The types of 'interface.functions' are incompatible between these types.
          Type '{ "approve(address,uint256)": FunctionFragment; "balanceOf(address)": FunctionFragment; "SomeRepaid(uint256)": FunctionFragment; ... 24 more ...; "transferOwnership(address)": FunctionFragment; }' is not assignable to type '{ [name: string]: FunctionFragment; }'.
            Property '"approve(address,uint256)"' is incompatible with index signature.
              Type 'import("/Users/user/Desktop/rebase/some-contracts/node_modules/@ethersproject/abi/lib/fragments").FunctionFragment' is not assignable to type 'import("/Users/user/Desktop/rebase/some-contracts/node_modules/@ethersproject/contracts/node_modules/@ethersproject/abi/lib/fragments").FunctionFragment'.
                Types of property 'gas' are incompatible.
                  Type 'import("/Users/user/Desktop/rebase/some-contracts/node_modules/@ethersproject/bignumber/lib/bignumber").BigNumber | undefined' is not
```

Dependencies: 

    "@nomiclabs/hardhat-ethers": "^2.0.2",
    "@nomiclabs/hardhat-etherscan": "^2.1.6",
    "@nomiclabs/hardhat-waffle": "^2.0.1",
    "ethers": "^5.5.2",
    "hardhat": "^2.6.5",

**Comment by jrocco2** [comment]
I'm having the same issue with "ethers": "5.4.0"

**Comment by jrocco2** [comment]
I got around it by importing the type ContractFactory

`import type { ContractFactory } from 'ethers';
`

Then casting the result of ethers.getContractFactory() to ContractFactory

` 
  let MyToken = await ethers.getContractFactory("MyToken");
  let myToken = await upgrades.deployProxy(MyToken as ContractFactory, { kind: 'uups' });
`

**Comment by fvictorio** [comment]
Hey @Dellybro, can you create a minimal reproduction example for this problem? If I use the typescript sample project (which includes typechain) and the latest version of ethers, everything seems to work fine.

**Comment by Dellybro** [comment]
Hey guys we can actually just close this, i realized that my packages were completely out of wack, i was using a typechains that was deprecated and many other things. Sorry for leaving this open.

**Comment by fvictorio** [comment]
No problem, thanks for letting us know! You might want to close the issue in ethers's repo too :slightly_smiling_face:

**Comment by Dellybro** [comment]
Good call
