### ISSUE TITLE
Deprecated eth-sig-util

### ISSUE THREAD

**Issue by frangio** [nomiclabs/hardhat#2149]
There's a deprecation message when installing Hardhat:

```
npm WARN deprecated eth-sig-util@2.5.4: Deprecated in favor of '@metamask/eth-sig-util'
```

**Comment by 0xPunkmask** [comment]
did u got the key?

**Comment by 0xPunkmask** [comment]
try this
```npm install eth-sig-util --save```

**Comment by XProject11** [comment]
i fix doing on my project

npm install 
npm install eth-sig-util --save
npm install
