### ISSUE TITLE
Cant deploy a contract with non-default signer while attaching a library at the same time?

### ISSUE THREAD

**Issue by grapevinegizmos** [nomiclabs/hardhat#2150]
I'm not sure if this is a hardhat problem or an ethers problem, but I it seems a bit more on hardhat side based on the error messages.  In brief, the problem is deploying with an alternate signer than account0 while at same time attaching a library in a hardhat test.

Seems like I can either write:
```
       let factory  = await ethers.getContractFactory("MyContract",  {
            libraries: {
                MyLibrary: libaddress
            }
        });
```
or I can write

```
       let factory = await ethers.getContractFactory("MyContract", otherSigner);
```

But I can't do both at the same time, that is include a different signer and also attach a library.
Is there some obvious way?  If I write
 ```
       let factory  = await ethers.getContractFactory("MyContract",  {
            libraries: {
                MyLibrary: libaddress
            }
        }, otherSigner );
```
I get a weird error on the the contract name: `Argument of type 'string' is not assignable to parameter of type 'any[]'`

**Comment by morgansliman** [comment]
Hi @grapevinegizmos - this should be possible using the following code (assuming `otherSigner` is an address):

```javascript
let factory = await ethers.getContractFactory("MyContract", {
  libraries: {
    MyLibrary: libaddress
  },
  signer: await ethers.getSigner(otherSigner)
})
```

Going to close this for now. Feel free to reopen if that code didn't work for you!
