### ISSUE TITLE
Hard 

### ISSUE THREAD

**Issue by coladimeji** [nomiclabs/hardhat#2156]
![hardhat not created bug](https://user-images.githubusercontent.com/32521595/146125004-1ae8fa51-5b79-49ea-b74f-ed67d69d9469.PNG)

**Comment by coladimeji** [comment]
While trying to deploy to test network Hardhat failed to load. see screenshot above

**Comment by coladimeji** [comment]
should remain open

**Comment by jongold** [comment]
You probably don't want to be posting screenshots with your private key! I'm not sure if it's what's causing your bug, but you have a typo -

```diff
- accounts: [ '0x${PRIVATE_KEY}' ]
+ accounts: [ `0x${PRIVATE_KEY}` ]
```

**Comment by coladimeji** [comment]
It’s test environment private key

**Comment by morgansliman** [comment]
Hi @coladimeji - it appears that you're trying to export a hardhat config from a deploy script, which is not a pattern we currently support. [Here's a link to all our current documentation regarding deploying contracts.](https://hardhat.org/guides/deploying.html)

I'm going to close this for now. Feel free to reopen with some more information if I've misunderstood the issue you're having.

Thanks!
