### ISSUE TITLE
How to verify smart contract using Hardhat?

### ISSUE THREAD

**Issue by OliveBounty** [nomiclabs/hardhat#2172]
Hello, hope you are doing well.

I am newbie to use Hardhat.
I always used truffle for building, compiling and deploy smart contract.
But, recently, I noticed that Hardhat is better than Truffle. so that I start to study about Hardhat.

The issue:
I deployed smart contract using hardhat.
But, I hope to verify smart contract using hardhat command.
How??
I saw several blogs and stackoverflow, but it doesn't work.
I would like to get perfect solution...

**Comment by fvictorio** [comment]
https://hardhat.org/plugins/nomiclabs-hardhat-etherscan.html

Please use [our Discord server](https://hardhat.org/discord) if you have more questions.
