### ISSUE TITLE
Typescript type error standalone script.

### ISSUE THREAD

**Issue by StefanoGagliardi** [nomiclabs/hardhat#2175]
I decided to run standalone Typescript script via ts-node, problem is simple:

I use property "ethers" from "hre" and it exists and works, but not exists in type: "HardhatRuntimeEnvironment".

```typescript

import hre from "hardhat";

// Interface from runtime.ts
export interface HardhatRuntimeEnvironment {
  readonly config: HardhatConfig;
  readonly hardhatArguments: HardhatArguments;
  readonly tasks: TasksMap;
  readonly run: RunTaskFunction;
  readonly network: Network;
  readonly artifacts: Artifacts;
}

async function main() {
  await hre.run('compile');
  const NFTMarket = await (hre as any).ethers.getContractFactory("NFTMarket");
  const nftMarket = await NFTMarket.deploy();
  ...
}

```

I saw there other library that re-declare library and merge HardhatRuntimeEnvironment  with eheters:
https://github.com/wighawag/hardhat-deploy-ethers/blob/main/src/internal/type-extensions.ts

```typescript
declare module "hardhat/types/runtime" {
  interface HardhatRuntimeEnvironment {
    // We omit the ethers field because it is redundant.
    ethers: typeof ethers & HardhatEthersHelpers;
  }

  // Beware, adding new types to any hardhat type submodule is not a good practice in a Hardhat plugin.
  // Doing so increases the risk of a type clash with another plugin.
  // Removing any of these three types is a breaking change.
  type Libraries = LibrariesT;
  type FactoryOptions = FactoryOptionsT;
  // tslint:disable-next-line: naming-convention
  type getContractFactory = typeof getContractFactoryT;
}

```

This is doesn't work beacuse there are import and module resolution problem.
So... Why "ethers" there isn't in type "HardhatRuntimeEnvironment" when proprerty de-facto exits?

A fast workaround for preserve type during typescript transpile is follow:
```typescript

import { HardhatEthersHelpers } from "@nomiclabs/hardhat-ethers/dist/src/types";
import { HardhatRuntimeEnvironment } from "hardhat/types";
import hre from "hardhat";

const wrapHre = hre as HardhatRuntimeEnvironment & { ethers: any } & {
  ethers: typeof ethers & HardhatEthersHelpers;
};

const NFTMarket = await wrapHre.ethers.getContractFactory("NFTMarket");

```

Can this anomaly be fixed or is it known and is there a reason?
Thanks in advice

**Comment by kanej** [comment]
I believe the problem here is that the `hardhat cli` is doing extra work over and above `ts-node` to present the correct type for `hre` based on the combined plugins in the `hardhat.config.ts` file.

So on a new typescript sample project an example script `./scripts/example.ts`:

```typescript
import hre from "hardhat";

async function main() {
  await hre.run("compile");

  console.log(hre.ethers);
}

main();
```

Would correctly log if run with `npx hardhat run ./scripts/example.ts`, but would throw an error complaining of "Property 'ethers' does not exist on type 'HardhatRuntimeEnvironment'" if you ran it with `npx ts-node scripts/example.ts`.

My understanding is hardhat expects scripts to be run with `hardhat run` to get full type support.

**Comment by kanej** [comment]
@StefanoGagliardi running the script directly with `ts-node` can be done, see the hardhat docs here:

https://hardhat.org/guides/typescript.html#running-your-tests-and-scripts-directly-with-ts-node

Basically `ts-node` does not scan all the files in a project by default and requires the `--files` flag to get the type information in  those file, so something like the following should work:

```shell
npx ts-node --files scripts/example.ts
```

**Comment by jarrodwatts** [comment]
Using ```npx hardhat run .\scripts\sample-script.ts``` instead of `ts-node` worked for me.

**Comment by crisanlucid** [comment]
how this solution will solve this problem?

![image](https://user-images.githubusercontent.com/340843/162167317-ce25c2d7-a006-4ed9-af51-3996b24be4f2.png)

**Comment by toshiSat** [comment]
> how this solution will solve this problem?
> 
> ![image](https://user-images.githubusercontent.com/340843/162167317-ce25c2d7-a006-4ed9-af51-3996b24be4f2.png)

I'm getting this as well

**Comment by CypElf** [comment]
Any news about this? This issue doesn't seem solved at all at the moment. The only workaround I found is to use `// @ts-ignore`, but it's dirty.
