### ISSUE TITLE
Reportable error while deploying contract to testate

### ISSUE THREAD

**Issue by parthingle** [nomiclabs/hardhat#2185]
<!--

```
Thank you for using Hardhat and taking the time to open an issue!

**Note that this issue tracker is not a support channel.**

- For help with Hardhat and Hardhat network, please use our [Discord server](https://hardhat.org/discord).
- For help with ethers.js, please go to [its Github Discussions](https://github.com/ethers-io/ethers.js/discussions).

If you are reporting a bug, please include reproduction steps. The best way to do this is to include a [Minimal Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example). If you can't do that, then include a link to your repo, and the steps to reproduce the problem. The easiest it is to reproduce your problem, the faster we are going to be able to fix it.

If you are submitting a feature request, please take the time to clearly describe your use case, and not only your proposed solution.

This issue will be automatically assigned to a Hardhat team member. This person will act as the point of contact between you and the team, but won't necessarily fix it nor address it in any way. An issue being assigned does not mean that it's being worked on.

-->

Trying to run this simple contact deploy code 

```
require("@nomiclabs/hardhat-ethers");

async function main() {
    const HelloWorld = await ethers.getContractFactory("HelloWorld");
 
    // Start deployment, returning a promise that resolves to a contract object
    const hello_world = await HelloWorld.deploy("Hello World!");
    console.log("Contract deployed to address:", hello_world.address);
 }
 
 main()
   .then(() => process.exit(0))
   .catch(error => {
     console.error(error);
     process.exit(1);
   });
```


And getting this error

```
/Users/parthingle/Documents/web3/hello-world/node_modules/hardhat/internal/context.js:35
            throw new errors_1.HardhatError(errors_list_1.ERRORS.GENERAL.CONTEXT_NOT_CREATED);
            ^

HardhatError: HH5: HardhatContext is not created.
    at Function.getHardhatContext (/Users/parthingle/Documents/web3/hello-world/node_modules/hardhat/internal/context.js:35:19)
    at extendEnvironment (/Users/parthingle/Documents/web3/hello-world/node_modules/hardhat/internal/core/config/config-env.js:60:42)
    at Object.<anonymous> (/Users/parthingle/Documents/web3/hello-world/node_modules/@nomiclabs/hardhat-ethers/internal/index.js:13:32)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/parthingle/Documents/web3/hello-world/scripts/deploy.js:1:1) {
  parent: undefined,
  errorDescriptor: {
    number: 5,
    message: 'HardhatContext is not created.',
    title: "Hardhat wasn't initialized",
    description: 'Hardhat initialization failed. This is a bug.\n' +
      '\n' +
      'Please [report it](https://github.com/nomiclabs/hardhat/issues/new) to help us improve Hardhat.',
    shouldBeReported: true
  },
  number: 5,
  messageArguments: {},
  _isHardhatError: true
}

Node.js v17.3.0
```



Full Reproduction Steps: https://www.web3.university/article/hello-world-smart-contract

**Comment by feuGeneA** [comment]
How are you invoking the script? (What is your command line?) The doc you're following is missing the info on that step (Step 16). (FYI, I reported that problem to the Web3U creators.) I was able to follow the instructions there, and successfully deploy the contract, using the command line `npx hardhat run scripts/deploy.js`.

Can you share the contents of your project folder?

**Comment by feuGeneA** [comment]
Closing for lack of information. Please feel free to re-open if/when you're able to share more.
