### ISSUE TITLE
Passing in a number for an enum parameter throws an invalid type error

### ISSUE THREAD

**Issue by bgits** [nomiclabs/hardhat#2186]
_Originally posted by @bgits in https://github.com/ethers-io/ethers.js/discussions/2432_

Upon discussion it might be possible hardhat is passing the internalType instead of type in the ethers wrapper.

**Describe the bug**
When attempting to pass an enum to a function accepting an enum type parameter the following error is thrown:
`Error: invalid type (argument="type", value="Test.fruit", code=INVALID_ARGUMENT, version=abi/5.5.0` 

Function being called: https://github.com/bgits/hardhat-enums/blob/main/contracts/Test.sol#L9

Failure point: https://github.com/bgits/hardhat-enums/blob/main/test/Test.ts#L9

**Reproduction steps**
A mock repo can be found here: https://github.com/bgits/hardhat-enums

test case can be run: `npx hardhat test`

**Environment:**

This is run as part of a hardhat development environment. Full project dependencies and configuration can be found in the example repo.

**Search Terms**
code=INVALID_ARGUMENT
invalid type

**Comment by alcuadrado** [comment]
Hey, thanks for the reproduction script, @bgits!

This is not an issue on our side. I left a comment in the ethers discussion with my findings.
