### ISSUE TITLE
BUG in alternative block explorers : FANTOM

### ISSUE THREAD

**Issue by Jmallone** [nomiclabs/hardhat#2189]
When i set 

![image](https://user-images.githubusercontent.com/6977257/147371398-700f0ba1-799f-43c0-b87b-f6092207812f.png)

happens this error:
![image](https://user-images.githubusercontent.com/6977257/147371411-1d79e0ff-101f-4666-a783-6c4ae234253f.png)

**Comment by kanej** [comment]
Hey @Jmallone, the feature to support multiple api keys like 'ftmTestnet' has been merged but not released to npm yet.

The issue https://github.com/nomiclabs/hardhat/issues/1448 tracks the progress of this feature and will be closed with a new release of `hardhat-etherscan` is cut.

**Comment by Jmallone** [comment]
Thanks @kanej  for answering me, 
I'll wait to get out at NPM. :smiley: 

Do you know when they will release?

**Comment by kanej** [comment]
@Jmallone the aim is this week or early next.
