### ISSUE TITLE
Release new version of hardhat-waffle that supports hexEqual

### ISSUE THREAD

**Issue by aberezkin** [nomiclabs/hardhat#2200]
Hi! [This commit](https://github.com/nomiclabs/hardhat/commit/ef1642846e4d68358e7fd538e988e277eeb9eed8) adds support for hexEqual but was not published to npm yet. 

Can you release new version of `@nomiclabs/hardhat-waffle` so we can use hexEqual in our tests?

I get `Invalid Chai property: hexEqual` on 2.0.1 now.

**Comment by sisco0** [comment]
![image](https://user-images.githubusercontent.com/25695302/147711672-4e523677-3fb8-44d4-acbd-b4d90339632e.png)
https://www.npmjs.com/package/@nomiclabs/hardhat-truffle5/v/2.0.3
It seems like this change is already included in v 2.0.3 which is available in the _npm_ with the link I provided above.

**Comment by fvictorio** [comment]
Thanks @aberezkin. I pushed a changeset for that, so next time we make a release the hardhat-waffle plugin will be included.

**Comment by feuGeneA** [comment]
Fixed in [hardhat-waffle v2.0.2](https://github.com/nomiclabs/hardhat/releases/tag/%40nomiclabs%2Fhardhat-waffle%402.0.2)
