### ISSUE TITLE
Cannot verify erc20 contract with proxy

### ISSUE THREAD

**Issue by coeus-crypto** [nomiclabs/hardhat#2207]
Close

**Comment by xieuxaythit** [comment]
Which address were you trying to verify, the proxy or the implementation's address? Can you elaborate the command please?

**Comment by coeus-crypto** [comment]
The implementation address, as the proxy contract is automatically verified.

It's in the example here but to clarify, this is the command I use to verify.

````
npx hardhat verify --network testnet --contract "contracts/XXXXX.sol:XXXXX" 0xCONTRACT_ADDRESS_HERE
```

**Comment by DiogoAbu** [comment]
How are you getting the contract address?
To verifiy the source on etherscan you need the implementation address, which is the one that changes on upgrades.
Here is how I am doing it:

```ts
// Upgrading
const implementation = await upgrades.upgradeProxy(proxyAddress, ContractFactory);
await implementation.deployed();

// This is important
const implementationAddress = await getImplementationAddress(ethers.provider, proxyAddress);

// Wait for Etherscan to catch up (5 blocks), verify, and publish source
await ethers.provider.waitForTransaction(implementation.deployTransaction.hash, 5);
await run('verify:verify', { address: implementationAddress });
```
