### ISSUE TITLE
Hardhat very slow on WSL

### ISSUE THREAD

**Issue by norswap** [nomiclabs/hardhat#2240]
Using version 2.7.1 of hardhat on WSL 2 (Ubuntu), it takes me ~50s~ 23s to run `npx hardhat compile` with only two trivial contracts and no changes.

The overhead is at the CLI level, e.g. running `npx hardhat --help` is also excruciatingly slow. It does not come from `npm` itself (e.g. our linting script is fast).

I tried using both the apt-installed node, and an nvm-installed node, with no differences.

It seems to be an issue specific to WSL, I did not experience the same issue on Windows itself (at least I did not two weeks ago when I last tried).

A detail that might be important is that the files are located on the Windows filesystem (i.e. `/mnt/c/...`). I haven't tried to run things on the linux-native filesystem, but I will do that and report back.

**Comment by norswap** [comment]
Ran it on the linux filesystem, it only takes 8.4s. `time npx hardhat --help` is 7.46s.

**Comment by alcuadrado** [comment]
Hey @norswap, great to see you are using Hardhat! 👋

Can you provide more info about your setup? Windows version, plugins, typescript, and hardhat versions would be great.

**Comment by norswap** [comment]
Hey Patricio 👋 

- Hardhat version: 2.7.1
- Windows version: 11 Pro (build 21996.1)
- Plugins: 
  ```
  import '@nomiclabs/hardhat-waffle'
  import '@typechain/hardhat'
  import 'hardhat-gas-reporter'
  import 'solidity-coverage'
  ```
  (removing all of them does not significantly lower the run time)
- Typescript: 4.5.3, according to `yarn.lock`

**Comment by kanej** [comment]
Slow performance when accessing the windows filesystem from wsl2 seems to be a known tradeoff of (wsl 2). Microsoft advises running from the linx filesystem or sticking with `wsl 1.0` if you are working across os filesystems: https://docs.microsoft.com/en-us/windows/wsl/compare-versions#comparing-features

![image](https://user-images.githubusercontent.com/24030/148917411-0efd80e9-b78e-4fd2-b788-e2ae12e365fe.png)

**Comment by norswap** [comment]
Thanks! You might be right, maybe it's intrinsic and nothing can be done. Was hesitant to come to this conclusion, because 23 sec for `--help` is still very slow (our markdown lint takes ~11s under the same conditions). And the perf on WSL's own partitions (8s) is slow too.

**Comment by alcuadrado** [comment]
The bootstrap is affected by ts-npde, which unfortunately doesn't cache the TS compilation results. You can improve it by enabling ts-node's transpile only mode with an env variable or your package.json.

**Comment by norswap** [comment]
I tried `TS_NODE_TRANSPILE_ONLY=true npx hardhat` and setting the same option [via `tsconfig.json`](https://github.com/TypeStrong/ts-node#via-tsconfigjson-recommended) but it does not significantly speed things up.

**Comment by LukeSamkharadze** [comment]
`WSL 2` user here on linux filesystem 🙋‍♂️

I have no issues using hardhat, your problem might be the working on the Windows side

`npx hardhat --help` takes about 2 seconds.


```
$ time npx hardhat --help

real    0m1.992s   <------
user    0m3.043s
sys     0m0.122s
```

**Comment by nebasuke** [comment]
Commenting for posterity. I had similar issues, which I've now managed to resolve. 

One possible cause of slowness I perceived in using WSL for Hardhat, is when using a VPN. Since Hardhat uses localhost to run the network, when using a VPN, localhost can take a while to resolve. You can address this either by disabling the VPN or taking the steps to change your DNS resolving order to resolve localhost earlier, see here: https://github.com/microsoft/WSL/issues/4901#issuecomment-2323398154
