### ISSUE TITLE
Error HH303: Unrecognized task add-candidate when passing multiple parameters 

### ISSUE THREAD

**Issue by ezeamaka2** [nomiclabs/hardhat#2242]
Here is a sample code of my hardhat task
```
task("add-candidate ", "Set the value of my number")
    .addParam("contract", "The contract address")
    .addParam("candidate", "Add candidate name, party and age")
    .setAction(async (taskArgs) => {
        const mycontractAddress = taskArgs.contract;
        const name = taskArgs.name;
        const party = taskArgs.party;
        const age = taskArgs.age;
        const ElectionContract = await ethers.getContractFactory("Election");

        const accounts = await ethers.getSigners();
        const signer = accounts[0];
        const electionContract = await new ethers.Contract(mycontractAddress, ElectionContract.interface, signer);

        let result = await electionContract.addCandidate(name, party, age);


        console.log("New candiate added with name: " + name);
        console.log("belongs to: " + party);
        console.log("and is: " + age);

    });
```

I am trying to pass the values from the console using:

`npx hardhat add-candidate --contract 0x99cEeCd85483B013CCdd1526A4fC3fc7d67A4421 --name Eze --party PDP --age 31`

Here is the Error I have been recieving

`Error HH303: Unrecognized task add-candidate`

**Comment by kanej** [comment]
Hey @ezeamaka2, I was able to recreate the error with the code above.

The task will be found if you remove the trailing space from the name so 

```javascript
"add-candidate"
```
rather than

```javascript
"add-candidate "
```

**Comment by alcuadrado** [comment]
The task should be defined as `"addCandidate"`, which in the cli gets translated to `add-candidate`.

**Comment by ezeamaka2** [comment]
> Hey @ezeamaka2, I was able to recreate the error with the code above.
> 
> The task will be found if you remove the trailing space from the name so
> 
> ```js
> "add-candidate"
> ```
> 
> rather than
> 
> ```js
> "add-candidate "
> ```

Oh, thanks for pointing it out. Let me try it again

**Comment by ezeamaka2** [comment]
> The task should be defined as `"addCandidate"`, which in the cli gets translated to `add-candidate`.

Really, will also try it out.... Thanks

**Comment by ezeamaka2** [comment]
Thanks for your contributions, I have actually solved the problem. I defined each of the parameters in a single `addParam` function like this

`
    .addParam("name", "Add candidate name")
    .addParam("party", "Add candidate party")
    .addParam("age", "Add candidate age")
`

and passed the values from the CLI like this
`npx hardhat add-candidate --contract 0x99cEeCd85483B013CCdd1526A4fC3fc7d67A4421 --name Eze --party PDP --age 21`

**Comment by ssiri09** [comment]
![Screenshot (476)](https://user-images.githubusercontent.com/103464513/176227388-5cde3ac0-3f65-4fde-bceb-e8d5de53af96.png)
can anyone help me please

**Comment by Chidubemcodes** [comment]
I think maybe you should try reinstalling hardhat

**Comment by KavyaBhalodia** [comment]
use npx hardhat node instead of npx hardhat account
