### ISSUE TITLE
when using different hardhat config of compilers may got CompilerError: Stack too deep  

### ISSUE THREAD

**Issue by chobynleo** [nomiclabs/hardhat#2254]
Hi, when using different hardhat config of compilers may got CompilerError: Stack too deep.

If config:
```
solidity: {
    compilers: [    
          {version: "0.7.6"},
      ],
    settings: {
      optimizer: {
        enabled: true,
        runs: 200,
      }
    },
  },
```
and then got this error:
> CompilerError: Stack too deep when compiling inline assembly: Variable headStart is 1 slot(s) too deep inside the stack.

but config:
```
solidity: {
    version: "0.7.6",
    settings: {
      optimizer: {
        enabled: true,
        runs: 200,
      }
    },
  },
```
Compilation successfully.

I just want to know what's the difference.

Here is my [repo](https://github.com/chobynleo/HardhatCompilerErrorTest) for test.

Thanks！

**Comment by LukeSamkharadze** [comment]
I don't think this config is valid

```JS
solidity: {
    compilers: [    
          {version: "0.7.6"},
      ],
    settings: {
      optimizer: {
        enabled: true,
        runs: 200,
      }
    },
  },
```

Try moving settings into compiler object

```JS
  solidity: {
    compilers: [
      {
        version: "0.6.6",
        settings: {
          optimizer: {
            enabled: true,
            runs: 200,
          },
        },
      },
    ],
  },
```

It seems that when you have array of compilers you have to specify settings for each one of them

**Comment by chobynleo** [comment]
> I don't think this config is valid
> 
> ```js
> solidity: {
>     compilers: [    
>           {version: "0.7.6"},
>       ],
>     settings: {
>       optimizer: {
>         enabled: true,
>         runs: 200,
>       }
>     },
>   },
> ```
> 
> Try moving settings into compiler object
> 
> ```js
>   solidity: {
>     compilers: [
>       {
>         version: "0.7.6",
>         settings: {
>           optimizer: {
>             enabled: true,
>             runs: 200,
>           },
>         },
>       },
>     ],
>   },
> ```
> 
> It seems that when you have array of compilers you have to specify settings for each one of them

Thanks. It works.
I often set this config to compile:
```
solidity: {
    compilers: [   
          {version: "0.4.18"},
          {version: "0.4.24"},
          {version: "0.5.16"},
          {version: "0.6.12"},
          {version: "0.6.6"},
          {version: "0.7.6"},
          {version: "0.8.0"},
          {version: "0.8.4"},
      ],
  },
```
May be I should specify settings for each one of them.

**Comment by LukeSamkharadze** [comment]
Yep, I think so

**Comment by chobynleo** [comment]
> 

Many thanks!
