### ISSUE TITLE
Verify task not found in script

### ISSUE THREAD

**Issue by LukeSamkharadze** [nomiclabs/hardhat#2258]
This is my script and I'm trying to verify my contract from the script, but I get error that `verify` is unrecognized

```TS
import hre, { ethers } from "hardhat";

async function main() {
  console.log("Deploying contract");

  const WBNB = await ethers.getContractFactory("WBNB");
  const wbnb = await WBNB.deploy();
  await wbnb.deployed();

  console.log("Contract deployed to:", wbnb.address);

  console.log("Verifying contract");

  await hre.run(`verify ${wbnb.address}`, { network: hre.network.name }); // <----------
  // await hre.run(`npx hardhat verify --network ${hre.network.name} ${wbnb.address}`);

  console.log("Contract verified");
}

main();
```

```
(node:25143) UnhandledPromiseRejectionWarning: HardhatError: HH303: Unrecognized task verify 0x714d170Cdf99c3326807774A400E738831AeB6A9
    at Environment.run (/home/luke/repos/dx/summitswap-contracts/node_modules/hardhat/src/internal/core/runtime-environment.ts:118:13)
    at main (/home/luke/repos/dx/summitswap-contracts/scripts/deployWBNB.ts:14:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

This is my task list, as you can see I have a `verify` task listed here from [nomiclabs-hardhat-etherscan.](https://hardhat.org/plugins/nomiclabs-hardhat-etherscan.html)
```
> hardhat help

Hardhat version 2.8.2

Usage: hardhat [GLOBAL OPTIONS] <TASK> [TASK OPTIONS]

AVAILABLE TASKS:
  
  ...
  test                  Runs mocha tests
  typechain             Generate Typechain typings for compiled contracts
  verify                Verifies contract on Etherscan

To get help for a specific task run: npx hardhat help [task]
```

I think issue might be that `hardhat` assumes that `verify 0x714d170Cdf99c3326807774A400E738831AeB6A9` is the task name itself. There is no good documentation on how to pass `taskArguments` properly to `hre.run` function, how can I pass address of the contract first and then network?

```TS
/**
 * @type TaskArguments {object-like} - the input arguments for a task.
 *
 * TaskArguments type is set to 'any' because it's interface is dynamic.
 * It's impossible in TypeScript to statically specify a variadic
 * number of fields and at the same time define specific types for\
 * the argument values.
 *
 * For example, we could define:
 * type TaskArguments = Record<string, any>;
 *
 * ...but then, we couldn't narrow the actual argument value's type in compile time,
 * thus we have no other option than forcing it to be just 'any'.
 */
export type TaskArguments = any; // <---------------
```

**Comment by LukeSamkharadze** [comment]
See https://www.npmjs.com/package/@nomiclabs/hardhat-etherscan#complex-arguments

```JS
await hre.run("verify:verify", {
  address: contractAddress,
  constructorArguments: [
    50,
    "a string argument",
    {
      x: 10,
      y: 5,
    },
    "0xabcdef",
  ],
});
```

**Comment by feuGeneA** [comment]
Thanks @LukeSamkharadze !! A detailed and concise report, a follow-up with details for others who end up here, and a self-closure! Bravo!

**Comment by jamesmccomish** [comment]
@feuGeneA in OP you seemed to want to set network, did you find that link above helped with verifying on testnets?

I've been trying to set a field in the arguments object to specify network / etherscan apiKey to verify, but haven't got it working.

(I don't think I'm missing anything in my config file as I can manually verify through command line)

**Comment by LukeSamkharadze** [comment]
@jamesmccomish

`npx hardhat run script.ts --network bscTestnet` should be enough

And `await hre.run("verify:verify", {` will automatically confirm contracts on `bscTestnet`

But you should have correct apiKey for this network in the config

**Comment by jamesmccomish** [comment]
Ah ok that's fine, no need to reproduce - I think I was over complicating the verify task, but I now see how the above works. In the end I can just write a script to preform the logic needed around the verify task and, as you say, call that with the network set. 

cheers!

**Comment by josealonso** [comment]
> See https://www.npmjs.com/package/@nomiclabs/hardhat-etherscan#complex-arguments
> 
> ```js
> await hre.run("verify:verify", {
>   address: contractAddress,
>   constructorArguments: [
>     50,
>     "a string argument",
>     {
>       x: 10,
>       y: 5,
>     },
>     "0xabcdef",
>   ],
> });
> ```

I didn't know how to verify a contract in Typescript. So thanks a lot, @LukeSamkharadze  !!
