### ISSUE TITLE
Error HH604- Hardhat not compatible with Node v17+ 

### ISSUE THREAD

**Issue by adriandelgg** [nomiclabs/hardhat#2274]
After updating the Node v17 Hardhat does not work properly. I've seen on StackOverflow others complaining about the same thing.

Reproduce:
1. Use Node v17+
2. Run `npx hardhat node`
3. Get error message & failure:
`Error HH604: Error running JSON-RPC server: error:0308010C:digital envelope routines::unsupported`

I'm on Node v17.4.0

What's the issue causing this?

**Comment by morgansliman** [comment]
We only ensure compatibility for the latest three LTS versions of NodeJS - currently 12, 14 and 16. Any versions outside these three will not be guaranteed to work as there may exist breaking changes like the one you're experiencing. 

I would suggest using node version ^16.0.0 for your hardhat projects for now as I can't promise we'll be able to prioritize this refactor until node 18.
