### ISSUE TITLE
Coverage started with errors in 2.8.1 when --testfiles is provided.

### ISSUE THREAD

**Issue by Janther** [nomiclabs/hardhat#2276]
Found this when trying to update hardhat for https://github.com/paulrberg/solidity-template 

the command for coverage fails as it can't load the tests files provided.

```
Error in plugin solidity-coverage: Error: Cannot find module './test/types.ts'
Require stack:
- ~/Projects/solidity-template/node_modules/hardhat/node_modules/mocha/lib/mocha.js
- ~/Projects/solidity-template/node_modules/hardhat/node_modules/mocha/index.js
- ~/Projects/solidity-template/node_modules/hardhat/builtin-tasks/test.js
- ~/Projects/solidity-template/node_modules/hardhat/internal/core/tasks/builtin-tasks.js
- ~/Projects/solidity-template/node_modules/hardhat/internal/core/config/config-loading.js
- ~/Projects/solidity-template/node_modules/hardhat/internal/cli/cli.js
```

**Comment by cgewecke** [comment]
@Janther I think this could be an issue at solidity-coverage with the way the testfiles arg is processed. 

I see the error go away if you rewrite the arg in the template's package.json scripts so it doesn't use a relative path prefix, e.g:
```diff
- --testfiles \"./test/**/*.ts\"
+ --testfiles \"test/**/*.ts\" 
```

It's possible this err was being swallowed in 2.7.0, hiding the problem. And 2.8.1 has fixed it.

**Comment by feuGeneA** [comment]
Seems like not an issue with Hardhat? Please close if that seems to be the case to you.

**Comment by Janther** [comment]
if I run it with a not existing folder it runs. Only where there are matching files it fails.

```
--testfiles \"./badfolder/**/*.ts\"
```

Still unsure who's responsible for this issue. Gonna look into what changes happened between 2.8.0 and 2.8.1 but I don't have much middle time right now.

**Comment by cgewecke** [comment]
@feuGeneA IMO this is closable - see [issue comment at solidity-coverage 684][1] which confirms that removing the path prefix resolves. 

Requires a patch at solidity-coverage b/c that's where the task arg is processed. 

[1]: https://github.com/sc-forks/solidity-coverage/issues/684#issuecomment-1017818951

**Comment by Janther** [comment]
Sweet, let's wait on their response for now.
