### ISSUE TITLE
 error TS2305: Module '"hardhat"' has no exported member 'ethers'.

### ISSUE THREAD

**Issue by DedicatedDev** [nomiclabs/hardhat#2291]
Degger configuration in VSCode. 

{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Mocha All",
      "program": "${workspaceFolder}/node_modules/mocha/bin/_mocha",
      "args": [
          "-r",
          "ts-node/register",
          "--timeout",
          "999999",
          "--colors",
          "${workspaceFolder}/test/index.ts",
      ],
      "scripts": {
        "test": "mocha -r ts-node/register test/index.ts"
      },
      "console": "integratedTerminal",
      "internalConsoleOptions": "neverOpen",
      "protocol": "inspector"
  },
  ]
}

hardhat version: 2.8.3

**Comment by DedicatedDev** [comment]
it is only happening with debugger.

**Comment by alcuadrado** [comment]
Hey @DedicatedDev,

You should use `ts-node/register/files` instead. More info here: https://github.com/TypeStrong/ts-node#help-my-types-are-missing

Note that this is not our support forum, but issue tracking. Please use hardhat.org/discord for support instead.

**Comment by DedicatedDev** [comment]
same issue.

**Comment by DedicatedDev** [comment]
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Mocha All",
      "program": "${workspaceFolder}/node_modules/mocha/bin/_mocha",
      "args": [
          "-r",
          "ts-node/register",
          "--timeout",
          "999999",
          "--colors",
          "${workspaceFolder}/test/index.ts",
      ],
      "scripts": {
        "test": "mocha -r ts-node/register/files"
      },
      "console": "integratedTerminal",
      "internalConsoleOptions": "neverOpen",
      "protocol": "inspector",
      "ts-node": {
      "require": ["tsconfig-paths/register"]
      }
  },
  ]
}

**Comment by alcuadrado** [comment]
Please, pay attention to what you just posted, and avoid using this as a support forum.
