### ISSUE TITLE
[Request] Allow CLI arguments to be used when running scripts

### ISSUE THREAD

**Issue by system32uwu** [nomiclabs/hardhat#2292]
# Problem

When trying to run a script using arguments it fails with the following error:

`Error HH308: Unrecognized positional argument Collection1`

# Context

I'm currently working on a game that will use multiple collections of NFTs, but they all share the same smart contract, just deployed with different values.

# Example use case:

Deploy the same contract, but with different values each instance
 `hardhat run --network localhost deploy-token.ts Collection1 C1 10000 `
 `hardhat run --network localhost deploy-token.ts Collection2 C2 5000 `
 `hardhat run --network localhost deploy-token.ts Collection3 C3 100 `

Where Collection{n} is the name, C{n} the symbol and the last number the max supply.

This solves having to manually change hardcoded values in the deploy script each time it needs to be run.

I considered using a task for this but since the template generated uses scripts/deploy.ts to deploy the Greeter contract I'm assuming I should be using the later and not a task.

# Full example (the one I'm currently developing)

```typescript
import { ethers } from 'hardhat'

async function main() {
  // Deploy AQLF
  const AQLF = await ethers.getContractFactory('AquariumLifeForm')
  const aqlf = await AQLF.deploy(
    process.argv[2], // baseURI
    process.argv[3], // Name of collection
    process.argv[4], // Symbol of collection
    process.argv[5], // Mint price
    process.argv[6], // Max mint at once
    process.argv[7], // Amount of tokens reserved
    process.argv[8]  // Max supply of tokens
  )

  await aqlf.deployed()

  console.log(
    'New Aquarium Life Form collection deployed to:',
    aqlf.address
  )
}

// We recommend this pattern to be able to use async/await everywhere
// and properly handle errors.
main().catch((error) => {
  console.error(error)
  process.exitCode = 1
})
```
So I'd need to run this deploy script for every collection we have (+10).

Finally, I tried running the script with node as suggested in the comments of the deploy script, but I'm facing the following error:

`TSError: ⨯ Unable to compile TypeScript:
scripts/deploy-plank.ts:17:27 - error TS2339: Property 'ethers' does not exist on type 'HardhatRuntimeEnvironment'.`

Update: Running this with node but using `require` instead of `import` when importing hardhat works, but I'm assuming we should be able to achieve the same using the `run` command from the hardhat CLI, also, this would mean that I can't run the script using the argument `--network localhost`, so when I try to access to my local node I don't have access to the deployed contracts

I saw #651 but using node removes the ability to use the network argument for the `run` task, the `run` task should just forward all the parameters that it doesn't recognize to the following task / script / command.

**Comment by system32uwu** [comment]
I tried creating a task to deploy our currency since it sounded easier:

`hardhat.config.ts`:

```typescript
task('deploy-plank', 'Deploys $PLANK')
  .addPositionalParam(
    'supply',
    'Initial Supply',
    undefined,
    types.int,
    false
  )
  .addPositionalParam(
    'beneficiary',
    'Address of the beneficiary',
    undefined,
    types.string,
    false
  )
  .setAction(async (taskArgs, hre) => {
    console.log(taskArgs)
    await hre.run('compile')

    const PLANK = await hre.ethers.getContractFactory('Plankton')
    const plank = await PLANK.deploy(process.argv[2], process.argv[3])

    await plank.deployed()

    console.log('$PLANK deployed to:', plank.address)
    console.log(process.argv.join(', '))
  })
```

so then I run `yarn hardhat` to register the task

and finally running `yarn hardhat run deploy-plank 20000000 0x8626f6940e2eb28930efb4cef49b2d1f2c9c1199` should work, but I'm getting: `Error HH308: Unrecognized positional argument 20000000`

Which is weird, because when I check for help of this task using `yarn hardhat help deploy-plank` I get:

```
Usage: hardhat [GLOBAL OPTIONS] deploy-plank supply beneficiary

POSITIONAL ARGUMENTS:

  supply        Initial Supply 
  beneficiary   Address of the beneficiary 

deploy-plank: Deploys $PLANK
```

Not sure what I'm doing wrong, but it seems that creating a dedicated task will be the solution for my use case, any help is much appreciated

**Comment by impguard** [comment]
Run it directly

```
npx hardhat deploy-plank ...
```

**Comment by system32uwu** [comment]
Oh okay that works for running the task, sorry I mixed the commands, thank you for the clarification there.

I'd close but maybe this should be either be covered in the documentation (use tasks if you need to use arguments) or otherwise implemented (for running scripts with arguments I mean)

**Comment by impguard** [comment]
```
Hardhat scripts are useful for simple things that don't take user arguments, and for integrating with external tools that aren't well suited for the Hardhat CLI, like a Node.js debugger.

If you want to automate more complex things, and receive user arguments, you can learn how to create your own tasks here.
```

It's bolded directly at the very top of the docs for scripts.

**Comment by system32uwu** [comment]
Yeah I checked again and I don't know how I missed the TIP that mentions user arguments, my bad. Thank you for your time!

**Comment by excalq** [comment]
Since scripts are much more portable than tasks, it would be great to have the option of using arguments.

One such use case would be a Hardhat user and a JS client sharing a script. Having Hardhat automatically interpret Typescript is a nice feature as well, versus standalone scripting.
