### ISSUE TITLE
If contract deployed to localhost (for testing), can I use testnet contract addresses?

### ISSUE THREAD

**Issue by adminoid** [nomiclabs/hardhat#2303]
Hello! My contract should interacts with BUSD and USDT contracts, but for testing I want use only localhost network. It's possible interactions with 3rd party contracts like as BUSD and USDT?
Thank you!

**Comment by alcuadrado** [comment]
Hi there, and thanks for using Hardhat!

We don't use Github issues for support about how to use it, but exclusively for bugs and feature requests. If you need help, please use [our Discord server](https://hardhat.org/discord) instead.

Anyway, take a look at this: https://hardhat.org/hardhat-network/guides/mainnet-forking.html
