### ISSUE TITLE
unknown account when test running with frontend

### ISSUE THREAD

**Issue by kajvan** [nomiclabs/hardhat#2324]
i am trying to test run the smart contract with alchemy but when i run it i get this error

`Uncaught (in promise) Error: unknown account #0 (operation="getAddress", code=UNSUPPORTED_OPERATION, version=providers/5.5.2) inder.ts:225`

how can i fix this

**Comment by feuGeneA** [comment]
Thank you for using Hardhat. GitHub Issues are intended to be used only for known or suspected problems or bugs with Hardhat.  For questions or other help, please use either [our Discord server](https://hardhat.org/discord) or [the GitHub Discussions feature](https://github.com/nomiclabs/hardhat/discussions/) instead.
