### ISSUE TITLE
hardhat-etherscan with TS cannot specify apiKey as object

### ISSUE THREAD

**Issue by rlogiacco** [nomiclabs/hardhat#2327]
In hardhat.config.ts I cannot specify the etherscan `apiKey` parameter as an object, thus I'm unable to use one config for multiple evms.

```
hardhat.config.ts:78:5 - error TS2322: Type '{ mainnet: string | undefined; rinkeby: string | undefined; polygon: string | undefined; polygonMumbai: string | undefined; bsc: string | undefined; bscTestnet: string | undefined; }' is not assignable to type 'string'
```

Excerpt from config:

```
  etherscan: {
    apiKey: {
      mainnet: process.env.ETHERSCAN_API_KEY,
      rinkeby: process.env.ETHERSCAN_API_KEY,
      polygon: process.env.POLYGONSCAN_API_KEY,
      polygonMumbai: process.env.POLYGONSCAN_API_KEY,
      bsc: process.env.BSCSCAN_API_KEY,
      bscTestnet: process.env.BSCSCAN_API_KEY,
    }
  }
```

My current workaround is to just manually swap in and out keys depending on the chain I'm aiming for:
```
  etherscan: {
    //apiKey: process.env.ETHERSCAN_API_KEY
    apiKey: process.env.POLYGONSCAN_API_KEY
    //apiKey: process.env.BSCSCAN_API_KEY
  },
```

**Comment by kanej** [comment]
Hey @rlogiacco, thanks for the feedback.

The multiple evms feature is available in `@nomiclabs/hardhat-etherscan` version `3.0.0` and later. Can you confirm the version you are using?

**Comment by rlogiacco** [comment]
No, I am not. Updating now.

Apologies for the bother.

**Comment by chubidursel** [comment]
Type '{ apiKey: string; }' is not assignable to type 'NetworkUserConfig | undefined'.
  Object literal may only specify known properties, and 'apiKey' does not exist in type 'NetworkUserConfig'

I updated the last version of this lab, and still have problem, does anyone know how to solve it? Thanks
