### ISSUE TITLE
'plugins' does not exist in HardhatUserConfig

### ISSUE THREAD

**Issue by Dentrax** [nomiclabs/hardhat#2339]
I was trying to implement [solidity-coverage](https://www.npmjs.com/package/solidity-coverage) plugin in my `hardhat.config.ts` file. Documentation used the following example:
```ts
module.exports = {
  networks: {...},
  plugins: ["solidity-coverage"]
}
```

But I didn't find a `plugins` field in the `HardhatUserConfig` struct:
```ts
import { HardhatUserConfig } from "hardhat/config";

const config: HardhatUserConfig = {
  solidity: {
    version: "0.8.9",
  },
  plugins: ["solidity-coverage"],
};

export default config;
```

Any ideas here? Is `plugins` field removed? I couldn't see a `plugin` field the in the [config.ts](https://github.com/nomiclabs/hardhat/blob/master/packages/hardhat-core/src/types/config.ts).

**Comment by alcuadrado** [comment]
You were looking at Truffle's docs. To use it with hardhat you should add `import "solidity-coverage";`

**Comment by Dentrax** [comment]
> You were looking at Truffle's docs. To use it with hardhat you should add `import "solidity-coverage";`

Thanks but already imported.
