### ISSUE TITLE
Unable to verify, and verify-error-suggestion different from the docs

### ISSUE THREAD

**Issue by dellwatson** [nomiclabs/hardhat#2351]
Hello I have write the issue on discord multiple times, but no one respond. 
I had deployed  the contract and it's working on rinkeby but have problem for verifying with hardhat;

```js
require("@nomiclabs/hardhat-waffle");
require("dotenv").config();
require("@nomiclabs/hardhat-etherscan");

const rinkebyUrl = process.env.ALCHEMY_RINKEBY_URL
  ? process.env.ALCHEMY_RINKEBY_URL
  : "";

module.exports = {
  solidity: "0.8.3",
  networks: {
    localhost: {
      url: "http://localhost:8545",
    },
    rinkeby: {
      url: rinkebyUrl,
      accounts:
        process.env.ACCOUNT_KEY !== undefined ? [process.env.ACCOUNT_KEY] : [],
    },
    etherscan: {
      apiKey: {
        rinkeby: process.env.ETHER_API,
      },
    },
  },
};
```
or   as
```js
    etherscan: {
      apiKey:  process.env.ETHER_API,
   },
```

but none is working if i run `npx hardhat verify --network rinkeby DEPLOYED_CONTRACT_ADDRESS`
```error
Error HH8: There's one or more errors in your config file:
  * Invalid value undefined for HardhatConfig.networks.etherscan.url - Expected a value of type string.
 ```
 
 
and because of the error code, I add 
```js
    etherscan: {
      url: rinkebyUrl,
      ...
   },
```
 but it's not working too. why would etherscan require url in first place too is weird because it's not even mentioned in the docs too

**Comment by dellwatson** [comment]
I misplace the etherscan inside networks, no wonder I can't believe it doesn't work this time

**Comment by steventraykovski** [comment]
Made the exact same error, thanks for sharing this!

**Comment by douglasmoraisdev** [comment]
I did the same. Thanks for sharing!

**Comment by byte14** [comment]
Hell yeah! did the same thing!!! Thank you for sharing this.

**Comment by rohanA6** [comment]
it worked thanks !

**Comment by DrBrok** [comment]
same here hhhhh

**Comment by DrBrok** [comment]
the same here hhh, thanks!!!

**Comment by bill-noto** [comment]
Lolll, me too! Took two hours to finally find this answer pointing this easy to miss mistake out, thanks a lot!!
