### ISSUE TITLE
variable is not change.

### ISSUE THREAD

**Issue by DedicatedDev** [nomiclabs/hardhat#2382]
"""
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.7;
import "hardhat/console.sol";
contract Delegate {

    address public owner;

    constructor(address _owner)  {
        owner = _owner;
    }

    function pwn() public {
        owner = address(msg.sender);
        console.log("owner:=>",owner);
    }
}

contract Delegation {
    address public owner;
    Delegate private delegate;
    constructor(address _delegateAddress) {
        delegate = Delegate(_delegateAddress);
        owner = msg.sender;
    }

    fallback() external {
        console.log("Fallback is Calling");
        (bool result,) = address(delegate).delegatecall(msg.data);
        if (result) {
            this;
        }
        console.log("CurrentOwner:=>", owner);
    }
}
"""

Here is my contract to  get ownership by fallback function. 
Here is test script. 
"""
import { SignerWithAddress } from "@nomiclabs/hardhat-ethers/signers"
import { expect } from "chai"
import { time } from "console"
import { keccak256 } from "ethers/lib/utils"
import { ethers } from "hardhat"
import { Delegate, Delegate__factory, Delegation, Delegation__factory } from "../typechain"

describe("Delegation",async()=>{
    let DelegateFactory:Delegate__factory
    let delegate:Delegate
    let DelegationFactory:Delegation__factory
    let delegation:Delegation
    let accounts:SignerWithAddress[]

    before(async()=>{
        accounts = await ethers.getSigners()
        DelegateFactory = await ethers.getContractFactory("Delegate")
        delegate = await DelegateFactory.deploy(accounts[0].address)
        await delegate.deployed()
        console.log("Deployed Owner",await delegate.owner())

        DelegationFactory = await ethers.getContractFactory("Delegation")
        delegation = await DelegationFactory.deploy(delegate.address)
        await delegation.deployed()

    })

    it("Delegation", async()=>{
        let tx = await accounts[1].sendTransaction({
            from:accounts[1].address,
            to: delegation.address,
            data:ethers.utils.solidityKeccak256(['string'],["pwn()"]),
        })
        

        const owner = await delegation.owner()

        console.log(owner)
        //expect(owner).to.equal(accounts[1].address)
    })
})
"""

console result shows owner value is changed already 
but in test script  await delegation.owner() function still return original value. 
so I've defined getOwner function on contract like this. 
"""
 function getOwner() external view returns(address) {
        return owner;
    }
"""

if I call this function, it is returning correct changed value. 
not sure why public variable call does not return correct value. 

Thank you.

**Comment by webdevabhijit** [comment]
I have tested your contract locally. Public variable owner call returned the changed value. Here see the below output.
```
Delegation
Deployed Owner 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
Fallback is Calling
owner:=> 0x70997970c51812dc3a010c7d01b50e0d17dc79c8
CurrentOwner:=> 0x70997970c51812dc3a010c7d01b50e0d17dc79c8
0x70997970C51812dc3A010C7d01b50e0d17dc79C8
    √ Delegation (97ms)


  1 passing (973ms)
```

**Comment by DedicatedDev** [comment]
now it is working for me. I guess looking there are delay. 
Sometimes, if I click npx run test, I'm seeing not updated result. 
Thank you.
