### ISSUE TITLE
Deploy contract to a different address. 

### ISSUE THREAD

**Issue by nandhini-ecrubit** [nomiclabs/hardhat#2383]
Hi, is it possible to create and deploy a contract to a different wallet address. Means, by passing a specific address to the constructor, and deploying to that address instead of `msg.sender' address. 
I can do that by adding private-key in the config file. But is there any way to do this only with the wallet address

**Comment by alcuadrado** [comment]
Hi there, and thanks for using Hardhat!

We don't use Github issues for support about how to use it, but exclusively for bugs and feature requests. If you need help, please use [our Discord server](https://hardhat.org/discord) instead.

You can set the code of an address with `hardhat_setCode` though. Take a look at Hardhat Network's reference docs.
