### ISSUE TITLE
Improve error handling when trying to use a global installation with ts

### ISSUE THREAD

**Issue by alcuadrado** [nomiclabs/hardhat#351]
We should restrict typescript support to local installations. Writing your config/tests/scripts requires importing Buidler as a library, and that's not possible in node if Buidler is installed globally.

There are multiple small changes that should be done:

* If Buidler is installed globally and we find a ts config, we should print an error explaining that to use typescript Buidler has to be installed locally.

* If Buidler is installed locally, and we find a ts config, but `ts-node` or `typescript` aren't installed, we should print an error directing the user to install them.

* If Buidler is installed globally and a user tries to `buidler run` a typescript script, we should print an error explaining that to use typescript Buidler has to be installed locally.

* If Buidler is installed globally we detect tests written in ts, we should print an error explaining that to use typescript Buidler has to be installed locally.

All of these errors have to link to the typescript support documentation once #346 is merged.

**Comment by fvictorio** [comment]
I think this is not longer valid. We don't allow using hardhat globally, so the only remaining point is:

> If Buidler is installed globally and a user tries to buidler run a typescript script, we should print an error explaining that to use typescript Buidler has to be installed locally.

And that seems to be handled correctly now:

```
Error HH14: Your Hardhat project uses typescript, but it's not installed.

Please run: npm install --save-dev typescript
```
