### ISSUE TITLE
Linking contract fails

### ISSUE THREAD

**Issue by pizzarob** [nomiclabs/hardhat#384]
Hey there. Really excited to get stack traces when testing my contracts. I've run into an issue. I was using truffle and when switching to buidler I get `Error: ContractName link failed`

I do this before my tests:

```js
const lib = await MyLib.new();
await MyContract.link('MyLib', lib.address);
await MyContract.new();
```

Is this the correct way to link a library before deploying with buidler?

**Comment by cgewecke** [comment]
@pizza-r0b 

Does passing `link` the deployed lib instance work?  

(There's an example using truffle's metacoin [here](https://github.com/cgewecke/eth-gas-reporter/blob/master/mock/buidler-metacoinjs-template.js#L7-L10))

```javascript
const lib = await ConvertLib.new();
MetaCoin.link(lib);
await MetaCoin.new();
```

**Comment by alcuadrado** [comment]
Hey @pizza-r0b,

As @cgewecke pointed out, in Buidler, you need to link contracts using library instances.

You should be getting an error message that indicates what to do though. Can you post the steps to reproduce this, please? Thanks!

**Comment by pizza-r0b** [comment]
Hey using the library instance fixes it. Unfortunately I don't get stack traces. I run with --verbose and see 

```
buidler:core:buidler-evm:node Solidity stack traces disabled: SolidityTracer failed to be initialized. Please report this to help us improve Buidler.

buidler:core:buidler-evm:node  Error: Failed to compute the selector one or more implementations of MyLib#remove. BuidlerEVM can automatically fix this problem if you don't use function overloading.
```

Unfortunately it would be quite a lot of work the refactor not to use function overloading.

**Comment by alcuadrado** [comment]
Do you have a link to that library? Computing selectors is mostly problematic if you are using the abi encoder v2.

**Comment by pizza-r0b** [comment]
It's in a private repo 👻. I'm not using abi encoder v2.  I have overloaded functions like:

```
function remove(KeyedMapIdToAddress storage map, uint id) public returns (uint) {}

function remove(KeyedMapAddressToIdToBool storage map, address fromAddress, uint toId) public returns (uint) {}
```

**Comment by pizza-r0b** [comment]
@alcuadrado any way to debug this without giving you access to the repo?

**Comment by alcuadrado** [comment]
Can you give me more info about `KeyedMapAddressToIdToBool` and `KeyedMapIdToAddress`? If I get to compile a contract with the exact same function signatures, I'll be able to debug it.

**Comment by pizza-r0b** [comment]
@alcuadrado Sure. These structs and functions exist in a library and then I am linking and using the library in a contract 

```
  struct KeyedMapAddressToBool {
    mapping(address => bool) data;
    mapping(address => uint) indices;
    address[] addresses;
    mapping(address => bool) exists;
  }

  struct KeyedMapIdToBool {
    mapping(uint => bool) data;
    mapping(uint => uint) indices;
    uint[] ids;
    mapping(uint => bool) exists;
  }

  struct KeyedMapIdToIdToBool {
    mapping(uint => KeyedMapIdToBool) data;
    mapping(uint => uint) indices;
    uint[] ids;
    mapping(uint => bool) exists;
  }
```

The removal functions are just utility functions the library provides to remove values from the structs.

**Comment by fvictorio** [comment]
Hi @pizzarob. I'm cleaning up old issues so I'm going to close this, but feel free to re-open if this is still a problem.
