### ISSUE TITLE
Add empty networks to compilation

### ISSUE THREAD

**Issue by okwme** [nomiclabs/hardhat#386]
Realized this problem when using https://github.com/gnosis/util-contracts to `extract-network` and `inject-network`. They expect a truffle formatted artifact and so expect each contract to have a network attribute even if it is empty.

It seems that when buidler compiles it doesn't not include an empty network object. I've been injecting deployed contract networks manually, but lots of contracts aren't deployed directly. That means they have no network object and gnosis's tool throws an error when they are encountered.

It's an easy fix in the Gnosis tool, but if buidler is actually trying to mimic the truffle artifact then it should actually just include an empty network object the way truffle does.

**Comment by alcuadrado** [comment]
I'm more inclined to make the artifacts generation an internal task, so users can override it as they wish.

Maybe we could even override it in the truffle plugins to add that empty object. But I don't know how confusing that empty object may be to other users.

**Comment by fvictorio** [comment]
Closing this since I don't think we'll do something like that soon and, in any case, it can be done via subtasks overriding.
