### ISSUE TITLE
[buidler-truffle] artifacts.require should work with contracts from npm modules

### ISSUE THREAD

**Issue by alcuadrado** [nomiclabs/hardhat#396]
Truffle's `artifacts.require` lets you pass an npm module's Solidity file. This doesn't work on Buidler, and it should.

An example of a project using this feature: https://github.com/ensdomains/resolvers/blob/23454aff68f713a74c3a08e8d491137a32639b9f/test/TestPublicResolver.js#L1

**Comment by fvictorio** [comment]
Closing in favor of #1040.
