### ISSUE TITLE
Preventing abstract contract deployments

### ISSUE THREAD

**Issue by alcuadrado** [nomiclabs/hardhat#397]
Currently, Buidler lets you deploy an abstract contract. This results in an empty bytecode being deployed.

We should detect this situation, prevent it, and print a clear error message.

**Comment by minton1** [comment]
update: 

Super annoying issue: accidentally marked a contract as abstract in solidity, then instantiated it with   
const factory = await ethers.getContractFactory("MockERC20");
let erc20: ERC20 = (await factory.deploy(initialHolder, initialTokens, name, symbol)) as ERC20;
(which was allowed!)

then called balanceOf on it and got the error message: "Error: call exception (address="0xf4e77E5Da47AC3125140c470c71cBca77B5c638c", method="balanceOf(address)", args=["0x2fFd013AaA7B5a7DA93336C2251075202b33FB2B"], version=4.0.47)"

took me way longer than I'd like to admit to figure out..

takeaway is should there be an earlier warning for instantiating an abstract contract?


```
macosx 10.15.4
node v11.15.0
{
    "dependencies": {
      "@nomiclabs/buidler": "^1.3.3",
      "@nomiclabs/buidler-ethers": "^1.3.3",
      "@nomiclabs/buidler-etherscan": "^1.3.3",
      "@nomiclabs/buidler-truffle5": "^1.3.3",
      "@nomiclabs/buidler-waffle": "1.3.4",
      "@nomiclabs/buidler-web3": "^1.3.3",
      "@openzeppelin/contracts": "^3.0.1",
      "@studydefi/money-legos": "^2.2.1",
      "@types/chai": "^4.2.11",
      "@types/mocha": "^7.0.2",
      "@types/node": "^14.0.1",
      "@uniswap/v2-core": "^1.0.0",
      "@uniswap/v2-periphery": "^1.0.0-beta.0",
      "buidler-typechain": "^0.0.5",
      "chai": "^4.2.0",
      "ethereum-waffle": "2.5.1",
      "ethers": "^4.0.23",
      "lodash": "^4.17.15",
      "solidity-cli": "^1.0.3",
      "solidity-coverage": "^0.7.5",
      "ts-generator": "^0.0.8",
      "ts-node": "^8.10.1",
      "typechain": "^1.0.3",
      "typechain-target-ethers": "^1.0.4",
      "typechain-target-truffle": "^1.0.2",
      "typechain-target-web3-v1": "^1.0.4",
      "typescript": "^3.9.2",
      "web3": "^1.2.7"
    }
```

**Comment by alcuadrado** [comment]
I'm closing this issue as we now check that contracts are not abstract when creating ether's `ContractFactory`'s, which were the main source of confusion.
