### ISSUE TITLE
[buidler-ganache] Add istanbul support and custom ganache options

### ISSUE THREAD

**Issue by sobolev-igor** [nomiclabs/hardhat#412]
Hi, everyone! 

I cannot use `buidler-ganache` package with Solidity 0.6.0 as it does not support istanbul opcodes. 

Also, I would like to use custom ganache options (such as `mnemonic`, `fork`, `forkBlockNumber`), but `BuidlerConfig` does not support it.

**Comment by alcuadrado** [comment]
Hi @sobolev-igor, thanks for opening this issue.

You should be able to set any ganache option in `networks.ganache`. Did you try that? Are you using a typescript-based config?

Regarding Istanbul, it is still beta in `ganache-core`, we should probably update the plugin to that version, but it's not clear if it is ready for production. I'll investigate further and update here.

**Comment by sobolev-igor** [comment]
@alcuadrado, thanks for the quick response!

Yes, my config is of `BuidlerConfig` type and `networks.ganache` should be of `NetworkConfig` type. So, after I've added extra options in `networks.ganache`, TypeScript could not compile the config.

**Comment by fvictorio** [comment]
Closing this in favor of #518 which has a more detailed discussion.
