### ISSUE TITLE
Ability to run buidler-evm as a standalone provider (outside of buidler projects)

### ISSUE THREAD

**Issue by wighawag** [nomiclabs/hardhat#430]
builder-evm requires to have some specific information from the compilation process but this should be possible to let user provide it.
For example when instantiating buidler-evm user could give the input/output of solc (or even the metadata) so that buidler-evm get all the info needed to run and provide debugging info

**Comment by alcuadrado** [comment]
You can now run [`Buidler EVM as a JSON-RPC server`](https://github.com/nomiclabs/buidler/releases/tag/v1.2.0), and connect to it from any application. You still need to compile with Buidler if you want all of its functionality.

**Comment by fvictorio** [comment]
Closing this. Notice that we also have the (undocumented?) `hardhat_addCompilationResult` RPC method.
