### ISSUE TITLE
`usePlugin` throws a cryptic error if the plugin's `main` doesn't exist

### ISSUE THREAD

**Issue by alcuadrado** [nomiclabs/hardhat#432]
`usePlugin` internally uses `require`, and `require` follows Node's resolution rules, including looking at `pkg.main`.

When `pkg.main` is available, but the file it points to doesn't exist (e.g. it's wrong, or you forgot to compile) it throws a cryptic error complaining that the package doesn't exits, when it does.

We should detect this case and improve it.

**Comment by fvictorio** [comment]
The error is helpful enough now that `usePlugin` doesn't exist anymore:

```
An unexpected error occurred:

Error: Cannot find module '/tmp/npmproject-8/node_modules/@nomiclabs/hardhat-truffle5/dist/src/indexx.js'. Please verify that the package.json has a valid "main" entry
```
