### ISSUE TITLE
[buidler-etherscan] Verify the contract deployed bytecode before publishing sources

### ISSUE THREAD

**Issue by canepat** [nomiclabs/hardhat#441]
As discussed with @alcuadrado, the `verify-contract` task could verify the compiled bytecode against the deployed bytecode when publishing sources on Etherscan for improved reliability.

This can be achieved relying on the `eth_getCode` API to obtain the deployed bytecode and performing a linear search for matching local bytecode, thus getting rid of the `contractName` task parameter altogether.

**Comment by canepat** [comment]
I've done a quick analysis, it seems that the changes can be restricted to the `index.ts` file where:
- the deployed bytecode can be retrieved using `ethers` Provider API
- the local bytecode can be accessed using the `Artifact` returned by the `readArtifact` function

Then a check can be added to raise a `BuidlerPluginError` if they don't match.

Getting rid of the `contractName` parameter can be achieved by:
- reading the compiler output from Buidler cache (should we add an internal task `GET_COMPILER_OUTPUT`?)
- performing a linear search matching the bytecode to extract the full contract name

**Comment by alcuadrado** [comment]
This has already been implemented.
