### ISSUE TITLE
[buidler-etherscan] Verify the Solc version in contract deployed bytecode

### ISSUE THREAD

**Issue by canepat** [nomiclabs/hardhat#442]
As discussed with @alcuadrado, the `verify-contract` task could verify the configured Solc version used by Buidler to compile bytecode against the Solc version embedded in deployed bytecode before publishing sources on Etherscan, making the contract verification even more reliable.

This improvement can be accomplished thanks to an interesting feature added to the Solc compiler since version 0.5.15: the [CBOR-encoding of the Solc compiler version in the contract bytecode](https://solidity.readthedocs.io/en/v0.5.15/metadata.html#encoding-of-the-metadata-hash-in-the-bytecode).

**Comment by canepat** [comment]
In order to implement these changes we need a [CBOR](https://cbor.io/) parser to decode the metadata included in contract bytecode: as a starting point, we can evaluate the `cbor-js` library and then add it as Buidler dependency.

Then, assuming the changes required by issue #441 are already in place, we can extract the metadata section from deployed bytecode, decode it using `cbor-js` and check the extracted `solc` version against the one resolved in Buidler configuration available in `bre.config.solc`.

**Comment by alcuadrado** [comment]
This has already been implemented. Thanks for all your work with this plugin, @canepat.
