### ISSUE TITLE
Deploy and verify contracts all in once

### ISSUE THREAD

**Issue by canepat** [nomiclabs/hardhat#443]
It would be nice to have a mechanism for automatically publishing sources when deploying contracts on testnet/mainnet.

This is not trivial because Buidler supports pretty much any library (web3, truffle-contract, ethers...) for use in the deployment scripts.

IMHO a simple Buidler API for verifying a contract just after its deployment in Buidler scripts could be sufficient.

**Comment by fvictorio** [comment]
Hi @canepat. I'm cleaning up old issues so I'm going to close this since I don't think something like this is going to be part of hardhat core in the foreseeable future.
