### ISSUE TITLE
Failing tests and performance regression when switching from ganache-core to buidler

### ISSUE THREAD

**Issue by HenryNguyen5** [nomiclabs/hardhat#470]
# Problem
During the process of swapping over form ganache-core to buidler, we have noticed two things:
1. Some of our test suite that should be passing (tested against ganache, geth, parity) is now failing.
2. Tests now take 2-3 times slower to run
A draft pull request has been opened [here](https://github.com/smartcontractkit/chainlink/pull/2427) for easy diffing.

# Steps to reproduce
1. Clone the chainlink repository:
```sh
git clone git@github.com:smartcontractkit/chainlink.git
```
2. Checkout buidler branch
```sh
git checkout feature/buidler
```
3. Install dependencies
```sh
yarn
yarn setup:contracts
```
4. Run tests
```sh
yarn workspace @chainlink/contracts test
```
5. Observe failing tests, and the test time.
6. Checkout the commit before the buidler conversion
```sh
git checkout HEAD^
```
7. Repeat steps 3-4
8. Observe passing tests and faster test time.

**Comment by fvictorio** [comment]
Hi @HenryNguyen5. Sorry for never responding to this. I'm cleaning up old issues so I'm going to close this, since it probably doesn't make sense to look into it now.
