### ISSUE TITLE
ethers v5 support

### ISSUE THREAD

**Issue by pcowgill** [nomiclabs/hardhat#481]
For context, see this related issue in the Waffle repo https://github.com/EthWorks/Waffle/issues/162

**Comment by pcowgill** [comment]
@alcuadrado Any thoughts on a timeline that would make sense for this? Thanks!

**Comment by alcuadrado** [comment]
Hey @pcowgill,

We are still planning how to add support for this and when. Should we release a new plugin? Should it be a new major of the same one?

In the meantime, you can use this plugin https://github.com/wighawag/buidler-ethers-v5

We may as well just make that one the official ethers v5 plugin.

**Comment by pcowgill** [comment]
@alcuadrado Thanks for the update!

I would imagine that users will be on a mixture of ethers 4 and ethers 5 for a while. I think releasing a new major of the same plugin but introducing a new plugin for continued ethers v4 support is a good option, even though that means some more effort required.

**Comment by pedrouid** [comment]
I think this could be added to the BuilderConfig similarly to how you select the `solc` version.

```typescript
import { BuidlerConfig } from "@nomiclabs/buidler/config";

const config: BuidlerConfig = {
  ethers: {
    version: "5.0.0-beta.183",
  },
};
``

You could check for the major version to select the ethers version to be used by buidler

**Comment by alcuadrado** [comment]
That's an interesting idea, @pedrouid. I'm not completely sure if it is feasible, as we are now using npm to install ethers, so we get a single version of it. The reason we can do that with solc, is that we download it manually, as it's just a blob.

**Comment by pedrouid** [comment]
Well what I was suggesting would be to support both interfaces and the configuration would switch between the two interfaces

Alternatively you could try to evaluate the version yourselves and switch between interfaces automatically (without requiring user configuration)

**Comment by pedrouid** [comment]
Another suggestion would be to maintain temporarily two versions of buidler that each support a different version of ethers

**Comment by pedrouid** [comment]
@pcowgill you can now use ethers v5 with @nomiclabs/buidler-ethers@next and  @nomiclabs/buidler-waffle@next 🎉

**Comment by pcowgill** [comment]
> @pcowgill you can now use ethers v5 with @nomiclabs/buidler-ethers@next and  @nomiclabs/buidler-waffle@next 🎉 

@pedrouid Awesome, thanks for the heads up!
