### ISSUE TITLE
more flexibility for location of 3rd party solidity libraries

### ISSUE THREAD

**Issue by pyggie** [nomiclabs/hardhat#504]
Some 3rd party libraries are not distributed via `npm install ...`. It can be difficult to install these in a way that `npx buidler compile` can find them.

An example is `ds-math` from https://github.com/dapphub/ds-math (this is the Maker project's safe math library). The library consists of a single solidity file, `math.sol`, which is easy enough to just copy into the `contracts` directory as expected by Buidler. But it would preferable to refer to the file in its library location, using a solidity import along these lines:

```import "ds-math/math.sol";```

The recommended installation method of ds-math is to clone the git repository, or include it as a submodule in your own git project. Either way, the advice is to add a path mapping to the `solc` compiler command, something like `ds-math=lib/ds-math/src`.

I may be overlooking a good way to handle this sort of import in Buidler.

**Comment by fvictorio** [comment]
Closing this since we support relative imports outside the `contracts` directory now.
