### ISSUE TITLE
ERC20.sol treated as a local one

### ISSUE THREAD

**Issue by dipeshsukhani** [nomiclabs/hardhat#505]
Error BDLR402: File /Users/..../node_modules/@openzeppelin/contracts/token/ERC20/ERC20.sol belongs to a library but was treated as a local one.

**Comment by alcuadrado** [comment]
Hey @dipeshsukhani,

Do you have a link to a project to reproduce this problem?

**Comment by dipeshsukhani** [comment]
oops, I do not.  I moved away to doing something else then.  Sorry :(
