### ISSUE TITLE
Follow XDG_BASEDIR specification for global config on Linux

### ISSUE THREAD

**Issue by paxthemax** [nomiclabs/hardhat#536]
Buidler CLI stores global (user level) config in the users `$HOME` directory (`~/.buidler/config.json`).

I would propose that the config file be moved as [per the XDG basedir specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html). To ensure backwards compatibility, the config file should be sourced:

- From `$HOME/.buidler/config.json`, if the file exists
- From `$XDG_CONFIG_HOME\buidler\config.json`, if the env variable is set
- From `$HOME\.config\buidler\config.json` otherwise.

This follows the spec (keeps the user homedir clean) and retains backward compatibility.

Bear in mind that this does not solve compatibility with Windows.

**Comment by fvictorio** [comment]
Closing this since we use [env-paths](https://github.com/sindresorhus/env-paths) now, that (I think) handles this correctly.
