### ISSUE TITLE
"builder compile" sometimes skips compilation - claiming everything is up to date.

### ISSUE THREAD

**Issue by drortirosh** [nomiclabs/hardhat#552]
Sometimes, `buildler compile` doesn't compile, and thinks everything is OK.
Here's a repro (though there are cases where it doesn't compile even without removing the artifacts)
```
git clone https://github.com/opengsn/gsn-with-ethers.git && cd gsn-with-ethers
$ yarn install --ignore-optional
...
✨  Done in 26.52s.
$ bdl compile
Compiling...
Downloading compiler version 0.5.16
Compiled 6 contracts successfully
```
^^^ (first compilation went OK)
```
$ bdl compile
All contracts have already been compiled, skipping compilation.
```
^^^ (cache up to date. OK)
```
$ rm -rf artifacts/
$ bdl compile
All contracts have already been compiled, skipping compilation.
```
## ^^^ ERROR: should compile if no artifacts.
```
 $ touch contracts/*
$ bdl compile
Compiling...
Compiled 6 contracts successfully
```
^^^ after touch - OK

**Comment by alcuadrado** [comment]
Sorry we haven't got into this yet, @drortirosh .

This bug is more common than I originally thought. For example: https://github.com/sc-forks/solidity-coverage/issues/474#issuecomment-655067859

**Comment by drortirosh** [comment]
Suggestion: to determine if build is up-to-date:
- create a list of configuration files, source, and output folders.
- hash all files (including recursively all current files in source, dest)
- put this hash in output folder
- whenever rebuilding, perform the above hash again - and verify it matches previous hash.
- any change to source (or ouputs) will cause rebuild..

**Comment by fvictorio** [comment]
I'm closing this since we've completely changed our compilation pipeline since this was reported. Please re-open if this is still an issue.
