### ISSUE TITLE
Compilation tasks overhaul

### ISSUE THREAD

**Issue by alcuadrado** [nomiclabs/hardhat#553]
Buidler compilation tasks need to be redesigned to support multiple Solidity versions natively. We want to take this opportunity to gather feedback and ideas from the community and add other improvements.

These are some of the ideas that different members of the community have mentioned:

1. Support multiple Solidity versions
2. Support multiple programming languages
3. Let users set any solc config
4. Per-network solc config
5. Let the users customize the artifact format
6. Make the compilation output overridable
7. Add a quiet compilation mode

I wouldn't focus on how to make this change backward compatible for now, but rather on how to modularize the tasks and how to redesign the compilation config.

/cc @wighawag @fvictorio @ajsantander @justinjmoses @cgewecke

**Comment by cgewecke** [comment]
Re 6/7 - initial thoughts about these were just to split [the code in this area][1] into
```
TASK_COMPILE_REPORT_INPUT: { input }
TASK_COMPILE_REPORT_OUTPUT: { output }
```

Idk. As a side-note, asked chriseth last week about whether Solidity's [colorized pretty printing][2] (available for the native compiler) will be extended to include JSON-IO and he said: *no*.  

So if someone wanted to write a formatter like this, it might be worthwhile.

<img width="924" alt="31265840-4c3e9d3e-aa47-11e7-90f2-070af4227aca" src="https://user-images.githubusercontent.com/7332026/81322199-77ca1980-9048-11ea-9919-4fe7677ad238.png">



[1]: https://github.com/nomiclabs/buidler/blob/d6e897c61730bd5b4a9ca1ae00df8aa65401ea75/packages/buidler-core/src/builtin-tasks/compile.ts#L131-L162
[2]: https://github.com/ethereum/solidity/pull/5511

**Comment by bohendo** [comment]
It's important to us over at https://github.com/connext/indra to be able to specify metadata options, we're looking forward to task 3 in particular: "Let users set any solc config"

**Comment by justinjmoses** [comment]
For us (https://github.com/Synthetixio/synthetix/tree/develop), while 1) is the most important, we currently handle this with a separate buidler config quite easily. 3) would most definitely be helpful for extensibility. 5) would be great for us to reuse and rely on the artifact format more fully. 

Additionally, our custom build script does two things that we like to port to buidler eventually:
1. We can set the optimization runs per target, as we compile each target separately 
2. Because of separate compilation, we can skip targets on compile if they haven't changed (though this really requires keeping ASTs of each source and figuring out if any of its deps have changed, which we don't currently do).

Finally, as @cgewecke mentioned, I do think better compiler output is critical if we want more devs to simply chose buidler as a default.

**Comment by pcowgill** [comment]
My use case for this falls in category #1. I'm creating a package that compiles different 3rd-party contracts which often are on various older Solidity versions and that also compiles some local contracts that might as well be using the latest Solidity version.

**Comment by wighawag** [comment]
Having multiple source path would be useful too, see : https://github.com/nomiclabs/buidler/issues/520

**Comment by alcuadrado** [comment]
Hey @justinjmoses,

Can you tell us more about what you mean by `target` in your comment? Is it each solc version? Or do you have different targets with the same version?

---

Also, to be clear, we are also working on improving recompilations, so that Buidler only recompiles what's actually needed. Currently, it recompiles everything every time.

**Comment by justinjmoses** [comment]
By `target` I mean `contract`. We have different optimization runs for some specific contracts, and use a default otherwise.

**Comment by alcuadrado** [comment]
That's really interesting, @justinjmoses. Where can I see how you define these per-contract settings?

**Comment by justinjmoses** [comment]
Well right now we do it with our custom build script for deployment: https://github.com/Synthetixio/synthetix/blob/master/publish/src/commands/build.js#L108-L133

**Comment by alcuadrado** [comment]
We've been working on some ideas and including everyone with @fvictorio.

This is a preliminary version of how this would work, and how the config would look like.

```js
// 1. Everything will be compiled with 0.5.5 and 0.6.1 as defined in
// the compilersarray.
//
// 2. If there's a file which can't be compiled with 0.5.5 nor 0.6.1, 
// the compilation process will fail.
//
// 3. If a file can be compiled with either version it will be compiled
// using the max possible version.
//
// 4. The file contracts/Fool.sol will be compiled using 0.5.5 with 
// different settings.
//
// 5. The final version would have less-verbose ways to set it up.
"solidity": {
  "compilers": [
     { 
        "version": "0.5.5",
        "settings": {
          "optimizer": { "enabled": false}
        }
     },
     { 
        "version": "0.6.1",
        "settings": {
          "optimizer": { "enabled": true}
        }
     }
  ],
  "overrides": {
    "contracts/Foo.sol": {
       "version": "0.5.5"
       "settings": {
          "optimizer": { "enabled": true, runs: 1000 }
       }
    }
  }
}
```

Would something like this cover your use-case, @justinjmoses ?

**Comment by pcowgill** [comment]
This would work well for my use case!

**Comment by justinjmoses** [comment]
Yeah that looks like it'd work.

Would the overrides also accept relative file paths? That way I could have `"contracts"` compile with 0.5.16 and `"legacy"` compile with 0.4.25

**Comment by alcuadrado** [comment]
You can think of it as each file being compile with the max solc version that its pragma and its dependencies' pragmas allow, between the versions you set up in your config. The actual implementation will be more complex as to minimize the number of compilations, but that's the easiest way to think about it.

If you have a file/contract that requires something different, you can use the `overrides` section.

If you don't set up any solc version (not recommended), all the published versions would be included in the process of choosing one.

**Comment by Anyhowclick** [comment]
Chiming in for Kyber (https://github.com/KyberNetwork/smart-contracts), as some have mentioned, (1) is most important for us as we want to ensure that whatever SCs we churn out is backwards-compatible with previous versions. (2), (3) and (6) is great for compostability (Eg. people building on Uniswap, Synthetix, Kyber, 0x, YFI etc.).

Based on the preliminary version, I see that we'd be able to specify the no. of optimiser runs per contract, which is an awesome feature to have! Different contracts have different sizes, and hence we'd like to optimise each one as much as possible.

Very excited for this!!

**Comment by alcuadrado** [comment]
Hey @K-Ho. This is something we are also considering.

Also, about per-network solc config: we won't include this in the initial version but will make sure that it can be implemented by overriding an internal builder task, and that we can eventually add it without a breaking change.

**Comment by alcuadrado** [comment]
@K-Ho Would a path to the solc json be enough? 

Something like:

```js
     { 
        "version": "0.5.5",
        "solcJs": "./custom-compilers/solidity-ovm-0.5.5.json",
        "settings": {
          "optimizer": { "enabled": false}
        }
     },
```

**Comment by K-Ho** [comment]
@alcuadrado - that would definitely be sufficient! Ideally, the compiler version would be able to be set to anything that waffle/truffle also allows 😊

**Comment by pcowgill** [comment]
I agree that being able to use this with the OVM's solc wrapper is helpful.

**Comment by alcuadrado** [comment]
Those would be available in the default configuration, @gtrepta

**Comment by gtrepta** [comment]
@alcuadrado When I run `buidler compile` in the sample project, the jsons in the `artifacts` folder don't contain any source mappings, just the bytecodes, abi, etc. Are you saying there is a way to configure buidler currently to write those fields out into the artifacts?

**Comment by alcuadrado** [comment]
Oh, I was talking about the upcoming release.

In the current version you can find those things in the cache directory.

**Comment by shalzz** [comment]
Hi, 

Are there plans to support using native distribution provided solc compiler or using a docker image with solc instead of just using the solc-js compiler?
Much like the one already supported by truffle: https://github.com/trufflesuite/truffle/releases/tag/v5.0.0#user-content-what-s-new-in-truffle-v5-truffle-compile-solidity-use-docker-or-native-solc

**Comment by alcuadrado** [comment]
Hi @shalzz. 

Our next release will use the native version of solc by default.

**Comment by fvictorio** [comment]
I think we can close this issue now?

Thanks to everyone for your input :smiling_face_with_three_hearts: If anyone is curious about how compilation works now, you can read about it [here](https://hardhat.org/guides/compile-contracts.html)
