### ISSUE TITLE
Replace all mocha.opts with .mocharc.json files

### ISSUE THREAD

**Issue by alcuadrado** [nomiclabs/hardhat#568]
We upgraded mocha to its latest version in #566, and `mocha.opts` is deprecated now. We should replace those with their equivalent `.mocharc.json`s.

**Comment by frangio** [comment]
I think this should have been closed by https://github.com/nomiclabs/hardhat/pull/847 but wasn't.

**Comment by alcuadrado** [comment]
You are right. Thanks, @frangio
