### ISSUE TITLE
Feature Request: create contracts at arbitrary address by bypassing create & create2 rules

### ISSUE THREAD

**Issue by thegostep** [nomiclabs/hardhat#574]
This would allow for testing smart contracts which use hardcoded address references

**Comment by alcuadrado** [comment]
What would this look like? Do you have anything in mind?

**Comment by alcuadrado** [comment]
Btw, if you are trying to deploy a contract into the same address in every network, you can use this technique: https://medium.com/@weka/how-to-send-ether-to-11-440-people-187e332566b7

It's used by a few EIPs and GSN.

**Comment by thegostep** [comment]
The goal is to deploy a mock of a 3rd party contract locally at the same
address as it is deployed on mainnet.

**Comment by fvictorio** [comment]
I think this will be doable with the new `hardhat_setCode` RPC method added in #1435?

Closing this for now, please re-open if that's not a proper solution.
