### ISSUE TITLE
Feature Request: allow sending transactions from account without access to private key

### ISSUE THREAD

**Issue by thegostep** [nomiclabs/hardhat#575]
This would match ganache's feature of unlocked accounts

**Comment by alcuadrado** [comment]
Thanks for the suggestion, @thegostep. We are going to build this feature soon.

**Comment by fvictorio** [comment]
This was implemented as the `hardhat_impersonateAccount` RPC method.

**Comment by hahahihiho** [comment]
But it looks it doesn't work correctly.

```
await hardhat.ethers.provider.send("hardhat_impersonateAccount",[address])
const signer = await hardhat.ethers.getSigner(address);
```

I sent tx on the hardhat node by the 'signer', but it is not working correctly.
It looks like it could be work by setting the hardhat.config.js but I couldn't find docs..

**Comment by fvictorio** [comment]
@hahahihiho you'll have to give us some reproduction steps, or at least tell us which error you're getting because that snippet looks correct.

**Comment by hahahihiho** [comment]
This is what I tested.
1. run hardhat node `npx hardhat node`
2. request 'impersonatedAccount' to provider 
```js
await hre.network.provider.request({
  method: "hardhat_impersonateAccount",
  params: [unregistered_account],
});
```
4. send ether to unregistered_account
```js
const signer = new ethers.Wallet(pk,provider)
signer.sendTransaction({
  to : unregistered_account,
  value : ethers.constants.WeiPerEther
})
```
5. make tx by unregistered_account
```js
const signer = await ethers.getSigner(unregistered_account)
signer.sendTransaction({
  to : known_address,
  value : ethers.constants.One
})
```

But it throws an error, I tried many other ways, but I couldn't find a way how to manually handle.
I referred to official document "https://hardhat.org/hardhat-network/reference/#hardhat-impersonateaccount"


This is what I really want to know
- run node at 8546 port `npx hardhat node --port 8546`
1. How to send a hardhat_impersonateAccount request to the specific local hardhat node
2. How to get the unregistered_signer from the node.
3. send tx by unregistered_signer

**Comment by hahahihiho** [comment]
I solved the issue by the below code
```js
const provider = new ethers.provider.JsonRpcProvider("http://127.0.0.1:8546");
await provider.send("hardhat_impersonateAccount",[unregistered_account])
```

**Comment by hahahihiho** [comment]
FYI, 
I thought those providers are same, but sometimes they work differently.
```
const provider1 = new ethers.providers.JsonRpcProvider("http://127.0.0.1:8545");
const provider2 = hre.ethers.provider;
```

if you use `npx hardhat test --network localhost`(localhost is defined in hardhat.config)
(I didn't test `hardhat script ~~` but it might be working same)
then you can use hardhat request without any issue.

```
await hre.network.provider.request({
    method: "hardhat_impersonateAccount",
    params: [unregistered_account],
});
```
