### ISSUE TITLE
Feature Request: add method for fast forwarding an account nonce

### ISSUE THREAD

**Issue by thegostep** [nomiclabs/hardhat#576]
This is useful for testing contracts that rely on contract or EOA nonce

**Comment by alcuadrado** [comment]
Can you give more info about what this would be used for? Do you use this somehow now? Maybe with ganache?

**Comment by thegostep** [comment]
I use this to generate deterministic contract addresses with regular create.

This could be replaced by implementation of #574

**Comment by fvictorio** [comment]
#1435 added the `hardhat_setNonce` method that should let users do this. It's not released yet, but it will be next week.

**Comment by fvictorio** [comment]
We just released Hardhat [2.4.0](https://github.com/nomiclabs/hardhat/releases/tag/hardhat-core-v2.4.0), which includes the `hardhat_setNonce` RPC method.
