### ISSUE TITLE
"ethers" and "waffle" not available in global scope in console

### ISSUE THREAD

**Issue by paulrberg** [nomiclabs/hardhat#602]
## Description

In spite of what the [docs](https://buidler.dev/guides/buidler-console.html#using-the-buidler-console) say, the "ethers" and "waffle" objects are not available in the global scope when I do:

```sh
yarn buidler console
```

I suspect that this is caused by TypeScript, but I'm not sure how exactly. I created a repository that reproduces the issue:

https://github.com/paulrberg/buidler-console-bug

## Environment

+ @nomiclabs/buidler@1.3.3
+ @nomiclabs-ethers/buidler@1.3.3
+ @nomiclabs-waffle/buidler@1.3.3
+ node@12.16.3
+ macOS@10.15.4

**Comment by fvictorio** [comment]
I'm pretty sure this is not the case anymore :sweat_smile: Please re-open if it is.

**Comment by paulrberg** [comment]
Yeah it works now! Thanks for updating this.
