### ISSUE TITLE
Feature Request: verify contracts with buidler-etherscan in scripts

### ISSUE THREAD

**Issue by thegostep** [nomiclabs/hardhat#607]

**Comment by alcuadrado** [comment]
Hey @thegostep,

You can run any task from your scripts. You just have to do 

```js
await run("task-name", {param1: 123, param2: "asd"})
```

You can import the `run` function explicitly from `@nomiclabs/buidler`.

**Comment by fvictorio** [comment]
@thegostep does this work for you? Or do you need to do something around verification that can't be done this way?

**Comment by thegostep** [comment]
Thanks guys - I missed this initially.

Here is the error I get. It would be useful to add documentation on how to use this.

![image](https://user-images.githubusercontent.com/15959632/87595446-697d2700-c6a3-11ea-8ddd-c1b968589f42.png)
![image](https://user-images.githubusercontent.com/15959632/87595486-79950680-c6a3-11ea-9b1d-61fdb20b9de8.png)

**Comment by thegostep** [comment]
Would be neat to be able to simply give the deploy tx and contract name and get the whole thing verified

**Comment by thegostep** [comment]
running into issues with nested array parameters

![image](https://user-images.githubusercontent.com/15959632/87606339-96cfd200-c6af-11ea-849c-6efc223c078e.png)

**Comment by scnale** [comment]
This has been added in #1114. It is present in the latest v2.1.1 release. Look at the [subtask API](https://github.com/nomiclabs/hardhat/tree/6cbdaf84795e0c602287eeb019feb332ccbd3ba0/packages/hardhat-etherscan#using-programmatically) for more details.
