### ISSUE TITLE
Unable to link libraries with Buidler (and other issues with Waffle)

### ISSUE THREAD

**Issue by boyuanx** [nomiclabs/hardhat#611]
I'm trying to link libraries for my contract and I cannot find a way to do it with Buidler. I find myself resorting to using Waffle's native methods but the problem is, compiled JSONs generated by Buidler are incompatible with Waffle. In other words, Buidler and Waffle generate different JSONs from the same Solidity source file. Here is the main difference (the missing "evm" breaks compatibility with Waffle as it's no longer recognized as a LinkableContract):

From Waffle:
```
"evm": {
    "bytecode": {
      "linkReferences": {
        "contracts/external/AddressSet.sol": {
```

From Buidler:
```
"bytecode": 
" *all the bytecode* "
"linkReferences": {
    "contracts/external/AddressSet.sol": {
```

Also, Waffle instructs me to link by doing:
```
import MyLibrary from "build/MyLibrary.json";
import LibraryConsumer from "build/LibraryConsumer.json";
myLibrary = await deployContract(wallet, MyLibrary, []);
link(LibraryConsumer, 'contracts/MyLibrary.sol:MyLibrary', myLibrary.address);
libraryConsumer = await deployContract(wallet, LibraryConsumer, []);
```
which is completely different from how Buidler handles things.

I can't seem to find a way around this. Does anyone have any insights as to how to link libraries using Buidler?

**Comment by alcuadrado** [comment]
Thanks for reporting this @boyuanx.

It seems to be a serious limitation of the buidler-ethers-waffle setup, so we'll address it soon.

**Comment by boyuanx** [comment]
Thank you for the information, @alcuadrado. I just switched over from web3 + Truffle and it’s a shame because I’m really liking Buidler + ethers + Waffle.

**Comment by alcuadrado** [comment]
This is going to be addressed soon, but in the meantime, this is a workaround you can use:

```js
const { ethers, config } = require("@nomiclabs/buidler");
const { readArtifact } = require("@nomiclabs/buidler/plugins");

async function main() {
  const Library = await ethers.getContractFactory("Library");
  const library = await Library.deploy();
  await library.deployed();

  const cArtifact = await readArtifact(config.paths.artifacts, "Contract");
  const linkedBytecode = linkBytecode(cArtifact, { Library: library.address });
  const Contract = await ethers.getContractFactory(
    cArtifact.abi,
    linkedBytecode
  );

  const contract = await Contract.deploy();
  await contract.deployed();

  console.log("Contract address:", contract.address);
}

function linkBytecode(artifact, libraries) {
  let bytecode = artifact.bytecode;

  for (const [fileName, fileReferences] of Object.entries(
    artifact.linkReferences
  )) {
    for (const [libName, fixups] of Object.entries(fileReferences)) {
      const addr = libraries[libName];
      if (addr === undefined) {
        continue;
      }

      for (const fixup of fixups) {
        bytecode =
          bytecode.substr(0, 2 + fixup.start * 2) +
          addr.substr(2) +
          bytecode.substr(2 + (fixup.start + fixup.length) * 2);
      }
    }
  }

  return bytecode;
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
```

**Comment by fvictorio** [comment]
@alcuadrado we can close this, right?

For anyone reading this, you can now link libraries with the ethers plugin. Read [this](https://hardhat.org/plugins/nomiclabs-hardhat-ethers.html#library-linking) to learn how.
