### ISSUE TITLE
Feature Request: allow to pass mnemonic for buidler network config

### ISSUE THREAD

**Issue by wighawag** [nomiclabs/hardhat#621]
Currently buidler network need to be provided a set of private key with balances.
For cases where we want to have the buidlerevm run with a mnemonic based accounts (like when running `buidler node` with a test metamask account, we need to convert such mnemonic into private keys in the buidlerc.config first

I suggest the following types to allow passing a mnemonic for buidlerevm network too
```
export interface BuidlerNetworkConfig extends CommonNetworkConfig {
  accounts?: BuidlerNetworkAccount[] | BuidlerNetworkHDAccountsConfig;
  ...
}

export interface BuidlerNetworkHDAccountsConfig extends HDAccountsConfig {
  balance: string;
}
```

**Comment by alcuadrado** [comment]
I really want to add this feature. We just have to figure out how to do it without breaking people's code.

We can do something like this:
1. Add a new field for HD accounts.
2. Validate that `accounts` and HD accounts aren't used at the same time.
3. If HD accounts are being used, populate `accounts` with the result fo deriving them.

**Comment by wighawag** [comment]
ok, let's have that new fields also present on HttpNetworkConfig to help using the same variable across networks.

like: 

```
const hdAccounts = ...
const config = {
  networks: {
    buidlerevm: {
      hdAccounts
    }
    rinkeby: {
      url: 'https://rinkeby.infura.io/v3/' + process.env.INFURA_TOKEN,
      hdAccounts
    }
  }
};
```

**Comment by fvictorio** [comment]
Wouldn't `hdAccounts` be too similar to the [HD Wallet Config](https://buidler.dev/config/#hd-wallet-config) for JSON-RPC based networks?

And slightly off-topic bug: I found a little confusing the fact that `accounts` has different types for different networks. I think (though I'm not 100% sure) that it would be better to have a single type and check for invalid configurations in runtime (and it seems to me this can be done without breaking changes?).

**Comment by alcuadrado** [comment]
The problem is that someone may have code that assumes that `config.networks.buidlerevm.accounts` is an array of strings.

**Comment by fvictorio** [comment]
Couldn't you make something like this (admittedly a bit too complex)?

- `"remote"`: what it does right now (but might not make sense for Buidler EVM, or maybe it would use some default accounts?
- `"string"` (except `"remote"`): shortcut for using a mnemonic
- `string[]`: array of private keys
- `Array<{privateKey, balance}>`: same as now; only makes sense for Buidler EVM
- `object`: mnemonic configuration

I might be missing something huge here though :sweat_smile:

**Comment by wighawag** [comment]
fixed in hardhat
