### ISSUE TITLE
ContractsIdentifier failed to be initialized for overloaded function

### ISSUE THREAD

**Issue by gorgos** [nomiclabs/hardhat#644]
With an overloaded function using `ABIEncoderV2` and passing a struct ([see example](https://ethereum.stackexchange.com/questions/84117/how-to-call-an-overloaded-function-in-truffle-with-abiencoderv2.)), I get the error:

```
buidler:core:buidler-evm:node Buidler EVM tracing disabled: ContractsIdentifier failed to be initialized. Please report this to help us improve Buidler.
 Error: Failed to compute the selector one or more implementations of MyContract#init. BuidlerEVM can automatically fix this problem if you don't use function overloading.
```

Version: `1.3.0-rc.0`, apologies if it's already fixed in the latest version.

**Comment by gorgos** [comment]
@alcuadrado Sorry, I forgot to add the link to the example: https://ethereum.stackexchange.com/questions/84117/how-to-call-an-overloaded-function-in-truffle-with-abiencoderv2.

I will check with `1.3.6` next week and report back.

**Comment by gorgos** [comment]
@alcuadrado Issue still exists with `1.3.6`.

**Comment by alcuadrado** [comment]
Thanks for confirming this @gorgos. Do you have a link to a repo to reproduce this?

**Comment by gorgos** [comment]
@alcuadrado https://github.com/gorgos/buidler-error-example

**Comment by fvictorio** [comment]
Hey @gorgos, I'm cleaning up old issues so I'm going to close this one. Please re-open if this issue is still valid.
