### ISSUE TITLE
Trying to import a Solidity file with its URL results in a confusing error message

### ISSUE THREAD

**Issue by alcuadrado** [nomiclabs/hardhat#649]
When this happens, Buidler just tells you that the library 'http' is not installed.

We should detect this and show a better error message.

**Comment by fvictorio** [comment]
We have a nice error now :smiling_face_with_three_hearts:

```
Error HH406: Invalid import http://example.com/FooBar.sol from contracts/Foo.sol. Hardhat doesn't support imports via http.
```

**Comment by 3h4x** [comment]
@fvictorio Will it ever support import via http?

**Comment by alcuadrado** [comment]
It was discussed in #557

**Comment by aifeelit** [comment]
Hardhat doesn't support to import from `http`

**Comment by aifeelit** [comment]
We need to install `openzeppelin/contract` and import associated sol from it
