### ISSUE TITLE
Run script with arguments

### ISSUE THREAD

**Issue by xuhcc** [nomiclabs/hardhat#651]
I'm trying to run a script with an argument, but buidler fails to do that:

```
$ buidler run scripts/myScript.ts 1234
Error BDLR308: Unrecognized positional argument 1234
```

Buidler version: 1.3.5

**Comment by alcuadrado** [comment]
This is really interesting. TBH, I never thought about it. 

How would you expect to receive those arguments in your script?

**Comment by xuhcc** [comment]
In the script I do several contract calls and display results. I think I can simply use `process.argv`.

**Comment by alcuadrado** [comment]
As a workaround, if you import the Buidler Runtime Environment explicitly in your scripts, you can just run them with `node path/to/script.js`.

**Comment by fvictorio** [comment]
Closing this since I'm not sure there's something we can do. If someone is interested in this subject, please read [this Ethereum Stack Exchange question](https://ethereum.stackexchange.com/questions/83656/where-does-the-line-blur-between-a-task-and-a-script-in-hardhat).
