### ISSUE TITLE
Feature Request : putContractStorage / getContractStorage for GodMode

### ISSUE THREAD

**Issue by wighawag** [nomiclabs/hardhat#671]
It would be great to have the following extra rpc method: 
`putContractStorage` and `getContractStorage`
that would allow to override the code and data content of an address like in ganache GodMode : 
 https://github.com/martinetlee/godmode-ganache-core/commit/08fb5d05717f501b7fa813be9b2bc1979e3fa542

**Comment by fvictorio** [comment]
Done in #1435! (Not released yet though)
