### ISSUE TITLE
Problems when importing contracts from their own package using it's package name

### ISSUE THREAD

**Issue by alcuadrado** [nomiclabs/hardhat#689]
If your buidler project is also an npm project, you can get a very confusing error if you try importing your own contracts with their package name.

For example, if your npm project name is `p`, and you import something with `p/contract/a.sol`, Buidler will resolve that import, but won't use `p/contract/a.sol` as the file's global name in the solc json input. It will use `contract/a.sol` instead. This will lead to the compilation failing within solc, with a really confusing error about a callback not being provided.

**Comment by fvictorio** [comment]
What should be the behavior here? To forbid importing a contact that way and log a proper error, or to use the correct global name?

**Comment by alcuadrado** [comment]
I'm not really sure yet. If you are using Buidler with a global installation, your buidler project may not be an npm project, so I'm somewhat inclined to forbidding it.

**Comment by alcuadrado** [comment]
After trying to reproduce this in an npm project, I realized that this problem is only present if you are using yarn workspaces.

A minimal reproduction project would look like this:
```
.
├── package.json
└── project
    ├── buidler.config.js
    ├── contracts
    │   └── c.sol
    └── package.json
```

Where the root's `package.json` just declares that `project` is a workspace, `project`'s  `package.json` name is `project`, and `c.sol` imports `project/contracts/c.sol`.

yarn workspaces creates symlinks of every project/workspace in the root's `node_modules`, so buidler does find `project/contracts/c.sol` while resolving this dependency, despite it not being declared in not being really installed.

**Comment by fvictorio** [comment]
Closing in favor of #1500, also opened by @alcuadrado
