### ISSUE TITLE
Feature Request: ability to enable / disable logging on the provider

### ISSUE THREAD

**Issue by wighawag** [nomiclabs/hardhat#730]
For buidler-deploy, I need a way to have the log disabled to start with but enable it later.

see : https://github.com/wighawag/buidler-deploy/blob/ef748edd0411a5f9fffaf27639ff9af14baf1c10/src/index.ts#L374-L377

Currently to do that I need to set internal member.

**Comment by wighawag** [comment]
This is not easily doable with hardhat

**Comment by alcuadrado** [comment]
Is that not meant to be a now? @wighawag

**Comment by wighawag** [comment]
yes, oups :D
