### ISSUE TITLE
[buidler-ganache] Getting private keys

### ISSUE THREAD

**Issue by xuhcc** [nomiclabs/hardhat#759]
If I run tests with `buidler-ganache` and call `wallet.provider.getWallets()` , the tests are failing with this error:

```
Error: This method only works with Buidler EVM.
You can use `await bre.ethers.signers()` in other networks.
```

Then how one can reveal private keys? 

According to [documentation](https://buidler.dev/plugins/nomiclabs-buidler-ganache.html#configuration) the `accounts` option is not supported. Is there a reason for that?

**Comment by alcuadrado** [comment]
The `accounts` settings clashes with Buidler's networks `accounts` field, that's the reason.

You can set Ganache to run in a deterministic mode, which always uses the same private keys.
