### ISSUE TITLE
 Uncaught RuntimeError: abort when running test

### ISSUE THREAD

**Issue by hkalodner** [nomiclabs/hardhat#789]
The following code triggers an issue when using a combination of `chai-as-promised`, the explicit inclusion of `ethereum-waffle` and the use of solidity `selfdestruct`.

I'll include code for the issue and the failure below, but I've also created a simple repo that displays the problem at https://github.com/hkalodner/buidler-issue/

I resolved the issue by removing the explicit call to `use(solidity)`, but I suspect there may be some more core issue based on the mysterious way the error is occurring (removing the `selfdestruct` or the use of `chai-as-promised` also fixed the issue`).

```solidity
pragma solidity ^0.5.11;

contract Test {

    string public constant test = "test";

    function shutdown() external {
        selfdestruct(msg.sender);
    }
}
```

```javascript
const { expect, use } = require('chai')
const chaiAsPromised = require("chai-as-promised")
const { solidity } = require('ethereum-waffle')

use(chaiAsPromised)
use(solidity)

describe('Test', () => {
  it('test should succeed', async function () {
    const Test = await ethers.getContractFactory('Test')
    const test = await Test.deploy()
    await test.deployed()
    await expect(test.test()).to.eventually.equal("test")
    await test.shutdown()
  })
})
```

I get the following error when running the test against in internal node `yarn buidler test`, but not when running against an external node `yarn buidler --network localhost test`

 `Uncaught RuntimeError: abort(Error: call revert exception (method="test()", errorSignature=null, errorArgs=[null], reason=null, code=CALL_EXCEPTION, version=abi/5.0.5)). Build with -s ASSERTIONS=1 for more info.`

**Comment by alcuadrado** [comment]
Hey @hkalodner 

Thanks for the detailed report.

Can you tell us more about your setup? Which OS and node version are you using?
