### ISSUE TITLE
BuidlerPluginError: contract has already been linked (truffle plugin)

### ISSUE THREAD

**Issue by EndymionJkb** [nomiclabs/hardhat#797]
I have a contract that links a library. This works in truffle:
1) run "yarn testrpc" to start a local Ganache network
2) run "yarn test" to run truffle tests - everything works

"npx buidler test" fails with the error message above. Following the docs, I replicated the truffle migrations with test/truffle-fixture.js - deploying the library, then linking, then deploying the main contract.

The first test runs, so the basics work. The second test fails, saying it was already linked. So somehow it was not cleaned up properly.

https://github.com/EndymionJkb/buidler-test has the code.

**Comment by JGcarv** [comment]
Hi! I'm also facing this issue! 

Is there a workaround in place or a fix?

Thank you!

**Comment by ducquangkstn** [comment]
I see that in `Math` library, there are external function 
https://github.com/EndymionJkb/buidler-test/blob/master/contracts/Math.sol#L5

So the compile will think this library is an external library.
If you want the library is in the `TestContract`, you should change these function into internal

**Comment by fvictorio** [comment]
Hi everyone, just checking if this issue is still valid. Does it happen if you upgrade to hardhat? (We might backport fixes to buidler if it's really necessary, but it might take some time.)

**Comment by EndymionJkb** [comment]
I'm on a different code base now, and have upgraded to hardhat - so for me
this is no longer a blocking issue. Thanks for following up!

**Comment by fvictorio** [comment]
Thanks @EndymionJkb. I'm going to close this then. If someone runs into this problem when using the latest hardhat version, please let us know.

**Comment by JGcarv** [comment]
This actually still happens. I found a dirty workaround.

Sorry for the late reply!

**Comment by fvictorio** [comment]
Does it happen to you in the latest version of Hardhat? If it does and you have reproduction steps, please let us know!

**Comment by JGcarv** [comment]
I was running v2.0.4 and was still hapenning. I'll update it and let you know.
