### ISSUE TITLE
[buidler-solhint] solhint as peerDependency

### ISSUE THREAD

**Issue by cruzdanilo** [nomiclabs/hardhat#799]
use `solhint` as a `peerDependency`, allowing users to choose between incompatible versions, ex: 2.x vs 3.x
currently `buidler-solhint` uses `"solhint": "^2.0.0"` as a dependency.

**Comment by alcuadrado** [comment]
Hey @cruzdanilo, thanks for opening this issue. We should update this plugin to 3.x.

Setting a dependency as peer doesn't mean that you can choose a different major version than what's been specified. The semantics of peerDependencies is different, and they are now installed automatically by npm7.

We will update the plugin to 3.x asap.

**Comment by fvictorio** [comment]
Issue to upgrade solhint: https://github.com/nomiclabs/hardhat/issues/654
