### ISSUE TITLE
[builder-etherscan]: compiled contracts included in verification

### ISSUE THREAD

**Issue by abcoathup** [nomiclabs/hardhat#804]
When verifying with buidler-etherscan plugin, other compiled (unrelated) contracts are also included in the verification.  

The following simple example is a project with two contracts, where A is deployed to a public testnet and then verified.  

```
$ npx buidler verify --network kovan 0xBc2bfE23f7Cd054283A51Fe64f5b3D69d2CBeCa9
Compiling...
Successfully submitted source code for contract
contracts/A.sol:A at 0xBc2bfE23f7Cd054283A51Fe64f5b3D69d2CBeCa9
for verification on etherscan. Waiting for verification result...
Successfully verified contract on etherscan
```

The verified contract on Etherscan shows both A and B files.

https://kovan.etherscan.io/address/0xBc2bfE23f7Cd054283A51Fe64f5b3D69d2CBeCa9#code

## A.sol
```solidity
// contracts/A.sol
// SPDX-License-Identifier: MIT
pragma solidity ^0.6.0;

contract A {
    uint256 private _value;

    function doStuff(uint256 value) public {
        _value = value;
    }
}
```

## B.sol
```solidity
// contracts/B.sol
// SPDX-License-Identifier: MIT
pragma solidity ^0.6.0;

contract B {
    bool private _value;

    function doStuff(bool value) public {
        _value = value;
    }
}
```

**Comment by alcuadrado** [comment]
Thanks for reporting this, @abcoathup!

Unfortunately, we have to upload all of the contracts atm, as there's [a bug in solc](https://github.com/ethereum/solidity/issues/9573) that can prevent the contracts from verifying otherwise.

The good news is that we are about to ship a new compilation pipeline, that is aware of this bug, and will let us prune the unrelated contracts when we are sure that it won't cause any problems.

**Comment by mudgen** [comment]
I have the same problem. @alcuadrado Any news about this?

**Comment by mudgen** [comment]
@alcuadrado According to the solc issue about this,  this problem exists for solc before 0.7.0.   I am using solc 0.7.3 so I shouldn't have this problem.

So can `builder-etherscan` be updated to allow my 0.7.3 code to be verified without including disrelated contracts?

**Comment by dexcell** [comment]
@alcuadrado 
Any update on this? Hope this will be fixed soon. since mock doesn't need to be uploaded and verified.

@mudgen 
i tried it with 0.7.3 solc, not working, still all contracts uploaded and verified.

**Comment by alcuadrado** [comment]
We are about to publish the biggest release of Buidler so far. We'll get back to this once that's done.

**Comment by mudgen** [comment]
@alcuadrado That seems exciting.  I look forward to reading and using the big release coming out soon. Is it getting published this week?

**Comment by alcuadrado** [comment]
Yep. This week 🚀

**Comment by dexcell** [comment]
Wow thank you

**Comment by PaulRBerg** [comment]
Hey @alcuadrado, it looks like the repo has just been renamed to `hardhat`. First off, congrats! This seems to be a big milestone.

Has this bug been addresses in the latest version? Or is it still pending?

**Comment by fvictorio** [comment]
Not yet! But with the changes in this release, tackling this issue should be possible :smile:

**Comment by dexcell** [comment]
Thank God it was renamed to hardhat, would be more easier to type on command line and more easier google search for issues.

**Comment by mudgen** [comment]
> Not yet! But with the changes in this release, tackling this issue should be possible 😄

Great.  Is it going to be tackled soon?

**Comment by PaulRBerg** [comment]
As an interim solution, it looks like we could use [solt][1]. It's compatible with any development framework and it's using the same trick as hardhat-etherscan, that is, Solidity's standard json format.

[1]: https://blog.jubb.xyz/post/solt-release/

**Comment by alcuadrado** [comment]
FYI: We are already working on this, and a fix should be available in a couple of days.

**Comment by alcuadrado** [comment]
We just released a new version of the plugin which improves on this as far as it can be done. Take a look at this comment for more info: https://github.com/nomiclabs/hardhat/issues/670#issuecomment-737420415

**Comment by Skyge** [comment]
@abcoathup Hi, have you tried to verify again with the new release, I meet another problem and now can not verify contract, error message:
```
TypeError: Cannot read property 'contracts' of undefined
    at SimpleTaskDefinition.verify (/Users/ERC20-Token/node_modules/@nomiclabs/hardhat-etherscan/src/index.ts:281:25)
```
My package version is `"@nomiclabs/hardhat-etherscan": "^2.1.0",`

**Comment by alcuadrado** [comment]
Try upgrading hardhat.

**Comment by Skyge** [comment]
Yeah, you are right, all is fine now, thanks a lot!
