### ISSUE TITLE
Transaction out of gas on deployment

### ISSUE THREAD

**Issue by michaelcohen716** [nomiclabs/hardhat#816]
- Contract deploys successfully to Ropsten
- buidler-contract-sizer prints out 16.8 kb for contract size (well within limit)...but removing one function (0.2 kb) somehow allows the contract to deploy again succcessfully. 

Seems like there's some gas/size threshold being reached but not sure why because the contract is well under the bytecode limit

**Comment by alcuadrado** [comment]
Hey @michaelcohen716

Can you provide more information so that we can reproduce it?
