### ISSUE TITLE
connecting geth console to buidler

### ISSUE THREAD

**Issue by jboadas** [nomiclabs/hardhat#828]
geth attach http://127.0.0.1:8545

Gives this error:
`Fatal: Failed to start the JavaScript console: api modules: Method rpc_modules not found`
And on Buidler console we got:
`rpc_modules - Method not supported`

There is a way we can connect geth console to buidler?

**Comment by alcuadrado** [comment]
Hey @jboadas,

I don't know. You should disable that check in geth, which not sure if it's possible.

**Comment by jboadas** [comment]
Found a workaround to connect, but doesn't seems to be working.

Started `ganache-cli`
Connected the `geth` console to the `ganache-cli` instance
shut down `ganache-cli`
start `npx buidler node`

I can see the transactions on buidler, but they seem to be doing nothing.

**Comment by fvictorio** [comment]
Just out of curiosity, why are you trying to connect the geth console? Is there something you can do that way that you can't with `buidler console`?

That doesn't mean that it's OK for geth to not work with buidler, it's just to see if there's a missing feature in buidler's console.

**Comment by jboadas** [comment]
Good point, is just because I have some files with geth console commands that mechanically I use to play with my contracts.
I will take a look to the `buidler console`
Thanks for mention this.
