### ISSUE TITLE
Error: tx has a higher gas limit than the block

### ISSUE THREAD

**Issue by Ramarti** [nomiclabs/hardhat#851]
Hello! I just installed buidler and I'm following the website instructions (sample project without any modification on my side).

Just run the test command and got this.

```
  1) Greeter
       Should return the new greeting once it's changed:
     Error: tx has a higher gas limit than the block

```

```
"devDependencies": {
    "@nomiclabs/buidler": "^1.4.7",
    "@nomiclabs/buidler-ethers": "^2.0.0",
    "@nomiclabs/buidler-waffle": "^2.1.0",
    "chai": "^4.2.0",
    "ethereum-waffle": "^3.1.1",
    "ethers": "^5.0.15"
  }
```

Anything extra configuration needed? If that's the case, it should be already there / on the website IMHO

Thanks!

**Comment by jessebmiller** [comment]
Happening to me too! Seems to have started happening recently

**Comment by jessebmiller** [comment]
@Ramarti Looks like following the instructions here https://buidler.dev/guides/ganache-tests.html might be a decent temporary work around.

**Comment by alcuadrado** [comment]
Thanks for reporting this. The latest version of ethers introduced a small change that broke our plugin. We already reported this upstream, and will be resolved asap.

**Comment by alcuadrado** [comment]
I just released a temporal hotfix. Please upgrade `@nomiclabs/buidler-ethers` to `2.0.2` to be able to use Buidler while we implement a proper fix.

The only negative impact of the hotfix is that transactions can't use the entire block gas limit for now. If you are being affected by this, you can work around it by adding the `blockGasLimit` and `gas` fields to the `buidlerevm` network, making sure that `blockGasLimit` is at least 1M higher than `gas`.

**Comment by alcuadrado** [comment]
For more information, please see [the release page](https://github.com/nomiclabs/buidler/releases/tag/buidler-ethers-v2.0.2).

**Comment by fvictorio** [comment]
I'm gonna assume this is fixed. Please re-open if it's not.
