### ISSUE TITLE
buidler should provide a mechanism to transform solcInput

### ISSUE THREAD

**Issue by wighawag** [nomiclabs/hardhat#864]
It seems buidler is reading the solidity source from disk for a specific file multiple time, when this file is imported by other file. 
This pose problem because for preprocessor as there is no easy way to transform such file,

my plugin [buidler-preprocessor](https://github.com/wighawag/buidler-preprocessor) use an override of TASK_COMPILE_GET_RESOLVED_SOURCES but this is not sufficient as import will fetch the source file again (see `resolver.resolveImport` in `dependencyGraph.ts` (https://github.com/nomiclabs/buidler/blob/27cc18e197067fad18fcb81b53dbaea7905b50a7/packages/buidler-core/src/internal/solidity/dependencyGraph.ts#L47) ), and this time the preprocessor has no chance of being executed (issue : https://github.com/wighawag/buidler-preprocessor/issues/4)

Could you reuse the already resolved files so even when doing resolver.resolveImport it can first check the already resolvedFiles 
but I guess this would not be sufficient as I might want to overwrite external import too
I guess the best would be to provide a hook to transform the solcInput after all dependencies are resolved the preprocessor can act on it afterward

**Comment by alcuadrado** [comment]
Hey Ronan, thanks for opening this issue. This is already fixed in the 2.0 branch :)

And actually, we updated solidity-coverage to pre-process files in process in a single place, and it works great.

**Comment by wighawag** [comment]
Excellent, looking forward to it!

**Comment by wighawag** [comment]
this is now easily doable in hardhat, I am using it for https://github.com/wighawag/hardhat-preprocessor
