### ISSUE TITLE
Buidler install fails when initializing for preexisting repository

### ISSUE THREAD

**Issue by ncitron** [nomiclabs/hardhat#869]
I was able to install buidler for my project when it was originally empty. When I take this same project and upload it to GitHub, and clone it to a new folder. Running:
`npm install`
or
`npm install -g --save-dev @nomiclabs/buidler`
I get this error:
```
npm ERR! code ENOLOCAL
npm ERR! Could not install from "node_modules/ganache-core/node_modules/web3-provider-engine/node_modules/eth-sig-util/ethereumjs-abi@git+https:/github.com/ethereumjs/ethereumjs-abi.git" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/noahcitron/.npm/_logs/2020-10-11T07_19_04_379Z-debug.log
```

**Comment by ncitron** [comment]
Upon further investigation, it appears that this issue can be mitigated by deleting `package-lock.json`, then running `npm install`. Not quite sure why this would be the case...

**Comment by alcuadrado** [comment]
Do you still have access to that `package-lock`? Do you mind sharing it with us? Thanks!

**Comment by ncitron** [comment]
Of course. Feel free to check out the repository here [https://github.com/ncitron/synthetix_limit_orders](https://github.com/ncitron/synthetix_limit_orders).

 Also, I think there may be a problem with the `timeout` setting in networks. I have increased mine to 120,000, but I still get `Error: Timeout of 20000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/noahcitron/Developer/crypto/snx_limit/test/test.js)`. Should I open a new issue about it?

**Comment by alcuadrado** [comment]
Thee's two different timeouts. A network related one, and a mocha one. Try also increasing the one from mocha.

```
module.exports: {
  mocha: {
    timeout: 100000
  }
}
```

**Comment by fvictorio** [comment]
Hey @ncitron, I'm cleaning up old issues so I'm going to close this one, but feel free to re-open if there's something to do on our side here.
