### ISSUE TITLE
Buidler fails to recognize TypeScript setup in yarn (v1) workspace

### ISSUE THREAD

**Issue by lepidotteri** [nomiclabs/hardhat#871]
While we are aware of incompatibilities between Buidler and Yarn v2 (Berry) and the workarounds currently available, as documented here #586; I would also like to report the issues I have been experiencing with the Buidler TypeScript sample project setup in a monorepo environment with Yarn v1 as package manager.

Essentially, it boils down to the following: if the ts-node and typescript packages are installed at the workspace node_modules level, then the Buidler project (in the same workspace) will fail to detect the TypeScript setup and instead launch the wizard again. When ts-node and typescript are installed at the root level, then Buidler works fine.

I would like to take the chance to exort Nomic Labs to improve support for Yarn and extend it to Berry as well

![zzzzzzx](https://user-images.githubusercontent.com/45174270/95778826-314cab00-0cc9-11eb-8efd-bf1e9f881222.JPG)

**Comment by alcuadrado** [comment]
Hey @lepidotteri!

Thanks for opening this issue. We fixed the typescript support a few versions ago, and now works in yarn workspaces. I just tried it with this project structure and worked.

```
.
├── node_modules
│   ├── @nomiclabs
│   │   ├── buidler
│   │   └── ...
│   ├── ...
│   ├── ts-node
│   │   ├── L...
│   ├── ...
│   ├── typescript
│   │   ├── ...
│   ├── ...
├── package.json
├── packages
│   ├── contracts // Running yarn buidler from this folder
│   │   ├── buidler.config.ts
│   │   ├── node_modules // THIS IS EMPTY
│   │   └── package.json
│   └── something
│       ├── node_modules // THIS IS EMPTY
│       └── package.json
└── yarn.lock
```

Am I missing something?

Regarding Berry, we'll be in a much better position to properly support it in our next major version. It's coming out really soon.

**Comment by lepidotteri** [comment]
Hi @alcuadrado ,

Thank you for the prompt reply, I welcome that you officially fixed incompatibilities among typescript, yarn and Buidler and can confirm that your project structure works just fine, as I had pointed out myself here: 
> When ts-node and typescript are installed at the root level, then Buidler works fine.

Aside from that,
> Am I missing something?

In a way yes, I originally opened this issue to report the fact that we are currently unable to get a working yarn + typescript setup for Buidler if the TS libs are installed at the package level; shouldn't we have that option and flexibility as well?

> Regarding Berry, we'll be in a much better position to properly support it in our next major version. It's coming out really soon.

Well this is very encouraging news then, thank you

**Comment by alcuadrado** [comment]
> if the TS libs are installed at the package level; shouldn't we have that option and flexibility as well?

Can you show me an example of how this would look? I'm not following.

**Comment by lepidotteri** [comment]
> Can you show me an example of how this would look? I'm not following.

Simply, when ts-node and typescript libs are installed in any of the node_modules folders at the workspace/package level (same level where buidler.config.ts is located as well), then Buidler will fail to detect the TS setup.

Let me know if you need screenshots, I have two projects structures I had readied to reproduce the "issue", and btw, this is also how I came to spot it the first time; these projects were pretty much forks, with the exception that in one of the other packages were installed typescript and ts-node as well (due to the workspace being a Svelte + TS sample app); so Yarn identified the presence of typescript and ts-node in two workspaces and correctly moved it at the root node_modules to avoid deps duplicates within the packages; hence Buidler recognized the TS setup for that project and worked just fine

**Comment by alcuadrado** [comment]
> Simply, when ts-node and typescript libs are installed in any of the node_modules folders at the workspace/package level (same level where buidler.config.ts is located as well), then Buidler will fail to detect the TS setup.

Do you mean in packages that are not your buidler project? Why would it detect that? I think there's something missing in your explanation, so an output of `tree` or a screanshot would be useful.

**Comment by lepidotteri** [comment]
I will close this for now @alcuadrado, sorry for not finding time to provide you with all relevant screenshots; the problem doesn't seem to be there with Hardhat and Yarn v1.

If you can update us on support for Berry meanwhile.

Thank you very much for your support

**Comment by alcuadrado** [comment]
I'm glad it's fixed.

I tried running Hardhat with Berry, but there are multiple dependencies that fail. Hardhat now doesn't rely on a node_modules, but a few dependencies have their dependencies incorrectly declared :(
