### ISSUE TITLE
Running a Buidler EVM HTTP server programmatically

### ISSUE THREAD

**Issue by Mrtenz** [nomiclabs/hardhat#872]
In order to test the HTTP JSONRPC functionality of my code, I'm looking to run a Buidler EVM server (like `buidler node`) programmatically. After looking at the source code for a bit, it seems I can use something like this:

```ts
import buidler from '@nomiclabs/buidler';
import { JsonRpcServer } from '@nomiclabs/buidler/internal/buidler-evm/jsonrpc/server';

const server = new JsonRpcServer({
  hostname: '127.0.0.1',
  port: 8545,
  provider: buidler.network.provider
});
```

But I assume this is not a public API. It would be nice if there was a better way to do something like this.

**Comment by alcuadrado** [comment]
You can also do:

```ts
import buidler from '@nomiclabs/buidler';
/// ...
await buidler.run("node")
```

**Comment by Mrtenz** [comment]
Thank you for the quick reply. I tried that, but there's two problems:

1. It adds a bunch of output to the console, which I'd like to avoid.
2. I can't seem to find a way to stop the server. I'm running this in combination with Jest's `beforeAll` and `afterAll` to automatically run and stop the server.

**Comment by alcuadrado** [comment]
I think you'd be better avoiding the HTTP layer if you are using this from jest. You can just use an in-memory provider with:

```
import buidler from '@nomiclabs/buidler';
/// ...
await buidler.network.provider.send("eth_accounts");
```

**Comment by Mrtenz** [comment]
[The code I'm trying to test sends an HTTP JSONRPC call](https://github.com/FindETH/networks/blob/63894c0f653552d14c833fb47c9bdeb54b50310b/src/jsonrpc/api.ts#L22), so I cannot use the Web3-like provider. Essentially I'm using Buidler just for the EVM (since Ganache was causing issues, and in general the Buidler EVM seems to be a lot faster).

**Comment by alcuadrado** [comment]
I see. I think you should probably use a subprocess for now.

**Comment by fvictorio** [comment]
This can be done with the `TASK_NODE_CREATE_SERVER` subtask:

```js
const taskNames = require("hardhat/builtin-tasks/task-names");

async function main() {
  const server = await hre.run(taskNames.TASK_NODE_CREATE_SERVER, {
    hostname: "localhost",
    port: 8545,
    provider: hre.network.provider
  });

  await server.listen();

  await server.waitUntilClosed();
}

main()
  .then(() => process.exit(0))
  .catch(error => {
    console.error(error);
    process.exit(1);
  });
```
