### ISSUE TITLE
Compiling 0.5.* .sol libraries in scaffold-eth

### ISSUE THREAD

**Issue by akerbabber** [nomiclabs/hardhat#873]
When I try to deploy my scaffold-eth project i get:

`@gnosis.pm/conditional-tokens-contracts/contracts/CTHelpers.sol:1:1: ParserError: Source file requires different compiler version (current compiler is 0.6.6+commit.6c089d02.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity ^0.5.1;`

I tried to follow the instructions to get a new buidler.config.js for solidity 0.5 files but when i try to compile it by:

`$ npx buidler compile --config buidler.config.5.js`
i get
`Error BDLR402: File /home/akerbabber/Documents/GitHub/ConditionalToken/packages/buidler/node_modules/@gnosis.pm/conditional-tokens-contracts/contracts/ConditionalTokens.sol belongs to a library but was treated as a local one.`

**Comment by fvictorio** [comment]
Can you share your `buidler.config.5.js` file?

**Comment by fvictorio** [comment]
That doesn't make sense to me. It seems like you have contracts that use solidity `^0.6.0` but you want to import the Gnosis's contracts that use `0.5.15`. That's not possible at the compiler level: if a file imports another, they need to be compiled with the same solc version.

Put another way, if you are using contracts that have a `^0.5.1` pragma, then the contracts that import them need to use that same pragma (or superior but compatible, like `0.5.5`). There's no way around that :worried:
