### ISSUE TITLE
Unrecognized failure on ethers.utils.parseEther

### ISSUE THREAD

**Issue by isaacdchan** [nomiclabs/hardhat#907]
Was writing a test when I accidentally passed "0.000" into parseEther. Was hit with the following error:

`     Error: Transaction reverted for an unrecognized reason. Please report this to help us improve Buidler.
      at Bounty.setReward (contracts/Bounty.sol:76)
      at process._tickCallback (internal/process/next_tick.js:68:7)`

Same behavior when "0" is passed.

**Comment by fvictorio** [comment]
Hi @isaacdchan. Sorry for not responding before. I'm cleaning up old issues so I'm going to close this one (it's very likely that later improvements to our error detection code have fixed this, but feel free to re-open if that's not the case).
