### ISSUE TITLE
solc 0.7.4 file import callback not supported error

### ISSUE THREAD

**Issue by gitpusha** [nomiclabs/hardhat#916]
I reported this bug to @alcuadrado already: 

In the new solidity 0.7 versions, you are not supposed to give the constructor a visibility modifier. However, when I remove the visibility modifier I get this weird `File import callback not supported bug` for one of my contracts, whereas when I give it a visibility modifier the problem is not there.

Steps to reproduce:

buidler version: 1.4.7
solc: 0.7.4
"@gelatonetwork/core": "1.0.0"

Try to compile this code: 

```solidity
// "SPDX-License-Identifier: UNLICENSED"
pragma solidity 0.7.4;
pragma experimental ABIEncoderV2;

/// yarn add -D @gelatonetwork/core v1.0.0
import {
    GelatoProviderModuleStandard
} from "@gelatonetwork/core/contracts/provider_modules/GelatoProviderModuleStandard.sol";

contract ProviderModuleDSA is GelatoProviderModuleStandard {
    // add/remove `public` for file import bug appear/disappear
    constructor() {}
}
```

However, when I change the import statement to be on one line: 

`import {GelatoProviderModuleStandard} from "@gelatonetwork/core/contracts/provider_modules/GelatoProviderModuleStandard.sol";`

it all works as it should. 

However, I am using `prettier-solidity-plugin` which auto-formats long import statements to be multi-line.

So must be something about the Parser buidler is using.

**Comment by gitpusha** [comment]
Seems to have been resolved with new `hardhat` versions.

**Comment by cameel** [comment]
The error you're getting basically means that solc did find the file you're importing in the input from Hardhat. It's either under wrong path or not present at all. I would guess that a parsing file results in file being skipped for some reason.

BTW, regarding the meaning of the weird error message. solc lets you provide a callback that is used to look up missing files. If a file has not been provided to the compiler in the JSON input the compiler invokes the callback. The default callback just tries to load the file from disk. You can also use this system to do fancy things like loading files directly from URLs, etc. Hardhat apparently does not provide such callback and the compiler is just pointing that out. I see a lot of confusion related to this message and I think we should change it to something more self-explanatory in the compiler. The callback is just a minor point and the message should focus on the fact that the file was not present in the input could not be looked up.

**Comment by alcuadrado** [comment]
Hey @cameel, thanks for your explanation.

The way hardhat works is by resolving all dependencies locally and then calling native solc using the standard json input. The reason this bug was present was that our dependencies resolution was somehow broken and the json was incomplete.

I completely agree that the error message is misleading. The error is that a file is missing, the callback is just an unrelated option.

I'm closing this issue as it has been solved. Please if anyone is getting a similar error, open a new one.
