### ISSUE TITLE
mainnet network forking performance

### ISSUE THREAD

**Issue by cruzdanilo** [nomiclabs/hardhat#944]
first of all, great work on hardhat, people. i migrated my projects and i am loving it <3
the mainnet forking on hardhat network is particularly amazing!
while migrating from ganache i noticed that my test cases are taking roughly twice the time, maybe a little more.
i checked geth logs and saw that hardhat was making less rpc calls, but they seem to be sequential, while ganache makes more requests, particularly a lot of `eth_getTransactionCount` right at the beginning, but they seem to be in parallel, some of them returning not ordered (by `reqid`).
is there some kind of optimization that can be done in this regard?

**Comment by fvictorio** [comment]
Hi @cruzdanilo. Sorry for not responding before. I'm cleaning up old issues so I'm going to close this one. (We already parallelize several of our remote RPC calls and, while there's probably room for improvement, I think we are already on the diminishing returns zone so I doubt we'll work on this anytime soon).
