### ISSUE TITLE
[hardhat-etherscan] Programatically pass complex arguments to verify task

### ISSUE THREAD

**Issue by dexcell** [nomiclabs/hardhat#945]
How to verify if my contract constructor has array params?

Let say i have a contract that have constructor accepting 2 params, string and array

````
constructor(string memory param1, address[] memory param2) public {
}
````

I want to verify it using etherscan verify plugin. 

Tried code below it doesn't work.
````
const bre = require("@nomiclabs/buidler");
await bre.run('verify', {
        address: '0xXXXXXX,
        constructorArguments: ['Some params', ['test']],
    });
````
This will result in error `Invalid value  for argument constructorArguments of type string`.

**Comment by dexcell** [comment]
Seems the only way to do it now is using command line with arguments.js, i wish that i can deploy and verify automatically using code.

**Comment by fvictorio** [comment]
You should be able to do it!

In a script, you can do something like this:

```js
await hre.run("verify", {
  address: yourContractAddress,
  constructorArgs: pathToYourArgsFile
})
```

I haven't tested it so there might be some mistake, but it's just to show the idea. Does that work for you?

**Comment by dexcell** [comment]
@fvictorio Yeah i think it would work, but it would be nice if we can do complicated args without having to create another separate js file.

The obvious use case would be, when i write my deploy script, 
i save the deployed address into a variable,
Then i can run hre verify, with that deployed address variable and that same parameters variable that i use to deploy.

So imagine i can run like `npm run deploy:ropsten` then it will deploy contract to ropsten and verify it automatically.

**Comment by fvictorio** [comment]
Yeah, that makes a lot of sense. @alcuadrado what do you think? We could add a subtask for this.

**Comment by dexcell** [comment]
Yeah, i think it's needed, so we can deploy and verify as smooth as butter. Even at the beginning my impression was etherscan plugin was designed to do that, i thought i miss something at the beginning.

**Comment by alcuadrado** [comment]
That's a valid point. Let's reopen this issue so we can come back to this later.
