### ISSUE TITLE
Not resolving types in Lerna repo

### ISSUE THREAD

**Issue by RobertoSnap** [nomiclabs/hardhat#946]
Haveing problem getting types from a plugin into a hardhat project locally. 

# Enviroment
* "hardhat": "^2.0.0",
* Its a Lerna repo. I have two packages. A demo and a plugin. 
* In plugin i decleared https://github.com/symfoni/buidler-plugins/blob/hardhat/packages/hardhat-react/src/type-extensions.ts
* Set the default in index https://github.com/symfoni/buidler-plugins/blob/hardhat/packages/hardhat-react/src/index.ts
*Decleared it as dep i demo (it has successful symlink with Lerna)
* imported the module in hardhat.config.ts, but it gives me type error https://github.com/symfoni/buidler-plugins/blob/hardhat/packages/hardhat-demo/hardhat.config.ts
* I have not done anything with tsconfig.json, maybe i should?
* Im also running watch to compile the src and types for the local package import

![image](https://user-images.githubusercontent.com/4772930/96998129-3d3f3500-1533-11eb-908e-e1cdfcda2d4d.png)

# Maybe cause

When i run `npx hardhat`from the hardhat-demo package i get this error:

```bash
npx hardhat
An unexpected error occurred:

Error: Cannot find module './type-extensions.ts'
Require stack:
- /Users/robin/code/buidler-plugins/packages/hardhat-react/dist/src/index.js
- /Users/robin/code/buidler-plugins/packages/hardhat-demo/hardhat.config.ts
- /Users/robin/code/buidler-plugins/packages/hardhat-demo/node_modules/hardhat/internal/core/config/config-loading.js
- /Users/robin/code/buidler-plugins/packages/hardhat-demo/node_modules/hardhat/internal/cli/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/robin/code/buidler-plugins/packages/hardhat-react/src/index.ts:7:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/robin/code/buidler-plugins/packages/hardhat-react/dist/src/index.js',
    '/Users/robin/code/buidler-plugins/packages/hardhat-demo/hardhat.config.ts',
    '/Users/robin/code/buidler-plugins/packages/hardhat-demo/node_modules/hardhat/internal/core/config/config-loading.js',
    '/Users/robin/code/buidler-plugins/packages/hardhat-demo/node_modules/hardhat/internal/cli/cli.js'
  ]
}
```

But .ts file is not there, i assume it should be looking for the .d.ts file instead?

![image](https://user-images.githubusercontent.com/4772930/96998310-8a230b80-1533-11eb-8d4d-afc9e257dfbc.png)

**Comment by RobertoSnap** [comment]
Seems that this resolved it, but thb i don't know if it's right or the implications.

**Comment by alcuadrado** [comment]
Thanks for the detailed report, @RobertoSnap ! And good catch!

TS can be scary sometimes 😬
