### ISSUE TITLE
[hardhat-ethers] `getContractAt` doesn't work for unlinked contracts

### ISSUE THREAD

**Issue by scnale** [nomiclabs/hardhat#950]
Calling the `getContractAt` helper currently fails if the contract needs library linking.

```js
const token = await ethers.getContractAt("Token", address);
```

This can be worked around like this for now:
```js
const tokenArtifact = await artifacts.readArtifact("Token");
const token = new ethers.Contract(address, tokenArtifact.abi, ethers.provider);
```

**Comment by krasi-georgiev** [comment]
+1 , Spend quite a bit if time trying to make this work with `getContractAt`. 

Is this a bug or by design?

**Comment by krasi-georgiev** [comment]
OTOH it would be quite usefull to get the ABI by the contract address instead of having to keep a copy of the artifacts. My idea is to create docker container with some deployed contracts and run some tests against is. A new container for each test.

**Comment by scnale** [comment]
> OTOH it would be quite useful to get the ABI by the contract address instead of having to keep a copy of the artifacts. My idea is to create docker container with some deployed contracts and run some tests against is. A new container for each test.

@krasi-georgiev That sounds interesting. Would you be willing to open an issue explaining a bit more your use case?

**Comment by krasi-georgiev** [comment]
Sure will do. I am now also exploring using geth to run a local node and deploy all contracts as the app I will be writing the e2e tests is in golang so it will be easier to use a single language for everything.

**Comment by SamSteele01** [comment]
+1
