### ISSUE TITLE
changed to solcConfig in TASK_COMPILE_SOLIDITY_GET_COMPILER_INPUT not considered for cache

### ISSUE THREAD

**Issue by wighawag** [nomiclabs/hardhat#955]
Plugin that override TASK_COMPILE_SOLIDITY_GET_COMPILER_INPUT to change the solcInput have the issue that hardhat will recompile the contract every time., see for example : https://github.com/wighawag/hardhat-deploy/issues/50

this is because hardhat use the version of solcInput before the call to TASK_COMPILE_SOLIDITY_GET_COMPILER_INPUT and so the cache never matches

**Comment by fvictorio** [comment]
Ideally that subtask shouldn't be overriden. Can you check [this comment](https://github.com/nomiclabs/hardhat/blob/23b045015bb805c17dad769d35a42a7724022bbf/packages/hardhat-core/src/builtin-tasks/compile.ts#L171) to see if you could override that subtask instead?.

**Comment by wighawag** [comment]
ah, yes I remember seeing that comment for my preprocessor plugin.

But maybe I should simply use `extendConfig` as this would have the same effect for my use case. unless I am missing something
