### ISSUE TITLE
Compiling artifacts from outside contracts folder

### ISSUE THREAD

**Issue by elenadimitrova** [nomiclabs/hardhat#959]
Is it possible for the configuration to specify overrides for locations outside the `./contracts` folder? We have a number of contracts in various folders at the project root level with different compilation settings solution is https://github.com/argentlabs/argent-contracts. Compiling with the following configuration does not produce anything different than without the `overrides`.

Additionally, since you advice the optimiser is disabled for testing, how can we specify network specific settings for the compiler? i.e. turn optimiser off for development and turn it on for ropsten and mainnet deployments.

```
require("@nomiclabs/hardhat-waffle");

// This is a sample Hardhat task. To learn how to create your own go to
// https://hardhat.org/guides/create-task.html
task("accounts", "Prints the list of accounts", async () => {
  const accounts = await ethers.getSigners();

  for (const account of accounts) {
    console.log(account.address);
  }
});

// You need to export an object to set up your config
// Go to https://hardhat.org/config/ to learn more

/**
 * @type import('hardhat/config').HardhatUserConfig
 */
module.exports = {
  solidity: {
    compilers: [
      {
        version: "0.5.4",
        settings: {
          optimizer: {
              enabled: true,
              runs: 200,
          }
        }
      },
      {
        version: "0.6.12",
        settings: {
          optimizer: {
              enabled: true,
              runs: 999,
          }
        }
      }
    ],
    overrides: {
      "./contracts-legacy/v1.3.0/": {
        version: "0.5.4",
        settings: {
          optimizer: {
              enabled: true,
              runs: 999,
          }
        }
      },
      "./contracts-legacy/v1.6.0/": {
        version: "0.5.4",
        settings: {
          optimizer: {
              enabled: true,
              runs: 999,
          }
        }
      },
      "./contracts-test": {
        version: "0.6.12",
        settings: {
          optimizer: {
              enabled: true,
              runs: 999,
          }
        }
      },
      "./contracts/infrastructure_0.5": {
        version: "0.5.4",
        settings: {
          optimizer: {
              enabled: true,
              runs: 999,
          }
        }
      },
      "./contracts/infrastructure": {
        version: "0.6.12",
        settings: {
          optimizer: {
              enabled: true,
              runs: 999,
          }
        }
      },
      "./lib": {
        version: "0.5.4",
        settings: {
          optimizer: {
              enabled: true,
              runs: 200,
          }
        }
      },
      "./contracts/modules": {
        version: "0.6.12",
        settings: {
          optimizer: {
              enabled: true,
              runs: 999,
          }
        }
      },
      "./contracts/wallet": {
        version: "0.6.12",
        settings: {
          optimizer: {
              enabled: true,
              runs: 999,
          }
        }
      }
    }
  }
};

```

**Comment by fvictorio** [comment]
Hi @elenadimitrova! There's probably some way around this if you override a task, but before getting into that, is it too disruptive for your project to just have everything inside a `contracts` directory, with subdirectories like `main`, `legacy`, `test`? That should make everything work fine, you would only need to adapt some overrides.

If you can't or don't want to do that, you can try overriding the `TASK_COMPILE_SOLIDITY_GET_SOURCE_PATHS`, and making it get the solidity files from those directories. I haven't tried this, but it should look like this:

```js
subtask(
  TASK_COMPILE_SOLIDITY_GET_SOURCE_PATHS,
  async (_, { config }) => {
    const mainContracts = await glob(path.join(config.paths.root, "contracts/**/*.sol"));
    const testContracts = await glob(path.join(config.paths.root, "test/**/*.sol"));
    // and so on

    return [
      ...mainContracts,
      ...testContracts,
      // and so on
    ].map(path.normalize); // not sure if normalize is needed here
  }
);
```

**Comment by elenadimitrova** [comment]
The reason to keep those separate is selective compilation when we need purely the Argent code compiled, without the test or legacy contracts which generate duplicate contract artefacts, e.g. there is a `WalletFactory` in `contracts` as well as `contracts-legacy` locations. Historically some tools auto compile `contracts` assuming it's that easy to compile a project, in our case it is not, as we're running different contracts on different versions of solidity with different optimiser settings.  
On that topic do you know what will happen with a test, trying to `artifacts.require("WalletFactory");` from the example above using the `@nomiclabs/hardhat-truffle5` plug in or without it for that matter?

**Comment by alcuadrado** [comment]
> On that topic do you know what will happen with a test, trying to `artifacts.require("WalletFactory");` from the example above using the `@nomiclabs/hardhat-truffle5` plug in?

That should work. If the name `WalletFactory` is not unique you'll get an error though, which will explain which options you have. All you need to fix those si copy & paste a string.

The `@nomiclabs/hardhat-truffle5` plugin already does something really similar: https://github.com/nomiclabs/hardhat/blob/master/packages/hardhat-truffle5/src/index.ts#L159-L166

Finally, note that overrides are not relative paths, but contract source names. That's, for example `contract/subdir/file.sol`, and not `contract/subdir/file.sol`. You can't use dirnames either, at least not for now.

**Comment by alcuadrado** [comment]
Hey @elenadimitrova, I just noticed that my last comment was wrong. It's fixed now. Let us know if you could set up Hardhat, or need extra help.

**Comment by elenadimitrova** [comment]
@alcuadrado I haven't been able to get `hardhat` to compile as I want unfortunately. `truffle` is currently closer to what I need although still lacking one last requirement discussed here: https://github.com/trufflesuite/truffle/issues/2021#issuecomment-664883908 https://github.com/trufflesuite/truffle/issues/3436#issuecomment-719538391

**Comment by fvictorio** [comment]
Closing this for now, since it can be done via subtasks overriding.

**Comment by moda20** [comment]
is there a way to add the subtask automatically, most of the time we have contracts in node_modules to import.

**Comment by fvictorio** [comment]
@moda20 please use [our Discord server](https://hardhat.org/discord) for questions like that.
