### ISSUE TITLE
invalid opcode bug on buidler-ganache - but not with hardhat

### ISSUE THREAD

**Issue by gitpusha** [nomiclabs/hardhat#960]
I am just leaving this here in case you are interested:

So back when hardhat didnt ship yet I got an `invalid opcode` bug on buidler-ganache in forkmode for this code and especially for the [gelatoCore.unstakeExecutor()](https://github.com/gelatodigital/gelato-network/blob/master/contracts/gelato_core/GelatoExecutors.sol#L32) method. I believe the bug must have to do with the `Address.sendValue` method from OpenZeppelin. I think `buidler-ganache` gave me an `invalid opcode` for calls to that method elsewhere too.

```javascript
// running `npx buidler run` automatically makes use of buidler-waffle plugin
// => only dependency we need is "chai"
const bre = require("@nomiclabs/buidler");
const { ethers } = bre;
const GelatoCoreLib = require("@gelatonetwork/core");
const { sleep } = GelatoCoreLib;

(async function main() {
  if (bre.network.name !== "ganache") {
    console.error("Test Suite is meant to be run on ganache only");
    process.exit(1);
  }
  // ===== GELATO LOCAL SETUP ==================
  const gelatoCore = await ethers.getContractAt(
    GelatoCoreLib.GelatoCore.abi,
    bre.network.config.GelatoCore
  );

  // DEBUG: buidler-ganache INVALID OPCODE bug

  await gelatoCore.stakeExecutor({ value: ethers.utils.parseEther("2") });

  await gelatoCore.unstakeExecutor();

  await sleep(20000);

  // DEBUG END
})();
```

Back then I talked to @alcuadrado and we assumed that it might be a ganache related bug.

So today I went back and tested the same code on hardhat:

```javascript
// running `npx hardhat run` automatically makes use of buidler-waffle plugin
const hre = require("hardhat");
const { ethers } = hre;
const GelatoCoreLib = require("@gelatonetwork/core");
const { sleep } = GelatoCoreLib;

(async function main() {
  if (hre.network.name !== "hardhat") {
    console.error("Test Suite is meant to be run on hardhat only");
    process.exit(1);
  }
  // ===== GELATO LOCAL SETUP ==================
  const gelatoCore = await ethers.getContractAt(
    GelatoCoreLib.GelatoCore.abi,
    hre.network.config.GelatoCore
  );

  // DEBUG: buidler-ganache INVALID OPCODE bug

  // NO BUG on hardhat

  await gelatoCore.stakeExecutor({ value: ethers.utils.parseEther("2") });

  await gelatoCore.unstakeExecutor();

  await sleep(20000);

  // DEBUG END
})();
```

**And indeed, no `invalid opcode` bug was thrown for the [gelatoCore.unstakeExecutor()](https://github.com/gelatodigital/gelato-network/blob/6950d08229dc0a1ef25dc65dd40291bef3be09d9/contracts/gelato_core/GelatoExecutors.sol#L32) method.** 

**Yeaah! Hardhat is great!**

**Comment by fvictorio** [comment]
I don't understand if this issue is still valid. I'm going to tentatively close it, but please re-open if you think there's still a problem.

**Comment by gitpusha** [comment]
This was fixed with the release of hardhat! 

who still uses ganache anyway lol
