### ISSUE TITLE
npx hardhat compile does not recompile when optimzer settings are changed

### ISSUE THREAD

**Issue by gitpusha** [nomiclabs/hardhat#961]
As reported to @alcuadrado I noticed that `npx hardhat compile` does not seem to recompile even if `optimizer` settings change. 

I use this solidity config: 

```javascript 
  solidity: {
    version: "0.7.4",
    optimizer: {enabled: process.env.DEBUG ? false : true},
  },
```

And I have these sripts in my `package.json`. 

```json
    "compile": "npx hardhat compile",
    "test": "yarn compile --force && npx hardhat test",
    "debug": "DEBUG=true yarn compile --force && npx hardhat test"
```

I had to add the `yarn compile --force` to my `test` and `debug` test scripts because `hardhat` would not recognize that I toggled the `solidity.optimizer` settings with `DEBUG=true`. 

**The simplest steps to reproduce the bug:**

1. `DEBUG=true npx hardhat compile` 
2. `npx hardhat compile` 

Without DEBUG (so with optimizer enabled) it says `Nothing to compile` even though I toggled the optimizer to be enabled no by NOT passing DEBUG=true.

**Comment by fvictorio** [comment]
Hey @gitpusha, to configure the optimizer you have to do:

```
  solidity: {
    version: "0.7.4",
    settings: {
      optimizer: {enabled: process.env.DEBUG ? false : true},
    }
  }
```

that's why is not recognizing the change :sweat_smile:

**Comment by gitpusha** [comment]
Ah I missed that part in the docs. thank you and sorry!

**Comment by gitpusha** [comment]
Reopening with a new but somewhat related question:

I noticed that this happens on consecutive `npx hardhat compile` runs with settings.optimizer enabled:

![image](https://user-images.githubusercontent.com/36712489/97875833-41313b00-1d1b-11eb-9432-a04a8d44c263.png)

So first it compiles all 44 files and then when I expected it to say `Nothing to compile` it actually compiles 41 files. Do you know why this is the case? 

When I toggle off the optimizer it also has unexpected results for me: 
![image](https://user-images.githubusercontent.com/36712489/97875947-6b82f880-1d1b-11eb-8233-e18c69632094.png)

First it recompiles all 44 files because the optimizer has now been switched off (yeah!!). 

However, on the second run I expect it to tell me `Nothing to compile` but it compiles 2 files. 

![image](https://user-images.githubusercontent.com/36712489/97876025-87869a00-1d1b-11eb-8f6b-0b2136897dfb.png)

**Comment by alcuadrado** [comment]
That's interesting! Can you point us to the repo and steps to reproduce this?

**Comment by gitpusha** [comment]
@alcuadrado and @fvictorio - I seem to have found the cause.

So I `renamed` the `filename` of one of my contracts. But only the capitalization which is not tracked as a filename change in my `git` . 

This actually caused some trouble elsewhere. 

Now when I explicity told my `git` about the filename change 

( `git mv -f OldFileNameCase newfilenamecase` ) 

It also removed the redundant compilation issue. 

So this contract filename case insensitivity issue also seems to have had its effect on `npx hardhat compile`.

**Comment by fvictorio** [comment]
That's very strange, hardhat doesn't use any information from git :/

**Comment by alcuadrado** [comment]
Maybe we should be looking at other file attributes for the cache. Which file system are you using, @gitpusha ?

**Comment by gitpusha** [comment]
I am on `macOS Catalina 10.15.7`

**Comment by alcuadrado** [comment]
I think it may be the same issue as this: https://github.com/aragon/govern/issues/186

**Comment by UncleGrandpa925** [comment]
> @alcuadrado and @fvictorio - I seem to have found the cause.
> 
> So I `renamed` the `filename` of one of my contracts. But only the capitalization which is not tracked as a filename change in my `git` .
> 
> This actually caused some trouble elsewhere.
> 
> Now when I explicity told my `git` about the filename change
> 
> ( `git mv -f OldFileNameCase newfilenamecase` )
> 
> It also removed the redundant compilation issue.
> 
> So this contract filename case insensitivity issue also seems to have had its effect on `npx hardhat compile`.

I'm encountering the very same issue where hardhat fails to use the cache. But strangely when I do a fresh clone of the repo then it can cache normally again. I'm using hardhat v2.0.8

**Comment by fvictorio** [comment]
I think this was fixed when we moved to hashes instead of timestamps? But if someone still has this issue and has reproduction steps, please re-open.
