### ISSUE TITLE
Error from buidler after migrating to hardhat

### ISSUE THREAD

**Issue by gigamesh** [nomiclabs/hardhat#963]
Thanks for the awesome tools!

I followed the migration guide, and even though I no longer have any mentions of buidler, I'm still getting this error:

```
hardhat --network localhost deploy --watch "--export" "../web/src/contracts.json"

An unexpected error occurred:

Error: Cannot find module '@nomiclabs/buidler/internal/core/providers/construction'
Require stack:
- /Users/matthewmasurka/code-projects/creaton/contracts/node_modules/solidity-coverage/plugins/resources/buidler.utils.js
- /Users/matthewmasurka/code-projects/creaton/contracts/node_modules/solidity-coverage/plugins/buidler.plugin.js
- /Users/matthewmasurka/code-projects/creaton/contracts/hardhat.config.js
- /Users/matthewmasurka/code-projects/creaton/contracts/node_modules/hardhat/internal/core/config/config-loading.js
- /Users/matthewmasurka/code-projects/creaton/contracts/node_modules/hardhat/internal/cli/cli.js
```

I've tried wiping package-lock.json & node_modules & reinstalling, but no luck. Any ideas?

**Comment by alcuadrado** [comment]
Hey @gigamesh,

You are importing the `solidity-coverage` plugin, which is being migrated at the moment. It will be available for Hardhat toon.

**Comment by gigamesh** [comment]
Thanks - sorry should have done more digging. 

For anyone who runs into the same issue: 
https://github.com/sc-forks/solidity-coverage/issues/541
