### ISSUE TITLE
hardhat test exits with status code 0 when tests fail

### ISSUE THREAD

**Issue by alcuadrado** [nomiclabs/hardhat#975]
Shalzz reported on discord that `hardhat test` always exists with status code 0, even if tests fail. Here's a link to an instance of this problem: https://github.com/unipeer/unipeer/runs/1333222680

**Comment by cgewecke** [comment]
Believe this is close-able thanks to @fvictorio's PR at hh-gasreporter (ref above)

**Comment by alcuadrado** [comment]
Awesome, thanks, @cgewecke!
