### ISSUE TITLE
How do configure hardhat to work nicely with '@openzeppelin/test-environment'?

### ISSUE THREAD

**Issue by amanusk** [nomiclabs/hardhat#982]
After installing `@openzeppelin/test-environment'` in the sample project, I am trying to run the following basic test:
```
const { accounts, contract } = require('@openzeppelin/test-environment');
const [owner] = accounts;

const { expect } = require('chai');

const MyContract = contract.fromArtifact('Greeter');
```

I try to run with `npx hardhat test` and get
```
{ Error: /Users/amanusk/Code/Solidity/sample/build/contracts/Greeter.json: ENOENT: no such file or directory, open '/Users/amanusk/Code/Solidity/sample/build/contracts/Greeter.json'
```

It seems I need to configure it somehow to search for the artifacts in the correct dir. Perhaps the dir structure is not what is expected

Adding the configuration
```
paths: {
    artifacts: './build/contracts',
  },
```
In hardhat.config.js also gives a similar error

**Comment by fvictorio** [comment]
It seems like the artifacts convention that `@openzeppelin/test-environment` follows is the same as the one in truffle (and similar to the one used by buidler before). That is not the case in Hardhat (you can read about that [here](https://hardhat.org/guides/compile-contracts.html#artifacts)).

From what I see in [their API](https://docs.openzeppelin.com/test-environment/0.1/api#contract), one alternative is doing this:

```javascript
const GreeterArtifact = artifacts.readArtifactSync("Greeter")
const Greeter = contract.fromABI(GreeterArtifact.abi)
```

I haven't tested it, but maybe that works. There's also a chance that you need to pass `GreeterArtifact.bytecode` or `GreeterArtifact.deployedBytecode` as the second argument, I'm not sure.

**Comment by fvictorio** [comment]
@amanusk I will close this for the time being, but please re-open if there's something we should do on our side.

**Comment by amanusk** [comment]
Thanks @fvictorio.
Indeed the problem manifested when I was trying to migrate from `buidler` to `hardhat`. Most of the migration when seamlessly, with this as the most notable exception.

I didn't try your solution, but I was able to get around the issue by installing `@nomiclabs/hardhat-truffle5`, and using the truffle syntax.
For reference, the substituted lines are commented out
``` solidity 
//const { accounts } = require('@openzeppelin/test-environment');

//const MyContract = contract.fromArtifact('Greeter');
const Greeter = artifacts.require('Greeter');

const { expect } = require('chai');

//describe('Greeter test', function () {
contract('Greeter', (accounts) => {
  it('Is able to compute hash', async () => {
    const [owner] = accounts;
    const greeter = await Greeter.new('Hello, world!', {
      from: owner,
    });
    expect(await greeter.greet()).to.equal('Hello, world!');
  });
});
``` 

This is not a full solution to working with the openzenppelin test-environment, but other integrations such as  `@openzeppelin/test-helpers` work OK.

I'll reopen if I'll find a fix or need something specific from `@openzeppelin/test-environment` that I can't do without :) 

Appricate the answer

**Comment by errmac-v** [comment]
This works for me.

```javascript
const CoinArtifact = artifacts.readArtifactSync('Coin');
const Coin = contract.fromABI(CoinArtifact.abi, CoinArtifact.bytecode);
```
