### ISSUE TITLE
HardhatNetworkProvider._send() rejects null `from` value

### ISSUE THREAD

**Issue by pyggie** [nomiclabs/hardhat#985]
HardhatNetworkProvider._send(method,params) rejects a null value for params[0].from. It accepts an undefined value. I noticed this while writing an adapter for the dydx Solo package, which seems to make calls with from=null.

**Comment by fvictorio** [comment]
I'm not sure about this. The [spec](https://eth.wiki/json-rpc/API) says that the `from` param in `eth_sendTransaction` is:

> from: DATA, 20 Bytes - The address the transaction is send from.

Although, to be fair, it doesn't say it's optional and we accept undefined.

@alcuadrado wdyt?
