### ISSUE TITLE
bug: incorrectly detects directories with a leading `.` as "relative"

### ISSUE THREAD

**Issue by fubhy** [nomiclabs/hardhat#995]
Currently it's impossible to put the `sources` path at a directory like `./.coverage/contracts` (I am working on a new code coverage instrumentation tool and want to place the instrumented code in a `dot-prefixed` tmp directory inside of the cache dir and then redirect the `compile` task to that directory).

**Comment by alcuadrado** [comment]
Thanks for reporting this, @fubhy.

You may want to take a look at [this PR](https://github.com/sc-forks/solidity-coverage/pull/540), where we instrument the code right before compiling it.

**Comment by fubhy** [comment]
Yeah I do that similarly but I run the code in a parallelized Jest environment (outside of hardhat tasks) for performance reasons, hence I need to drop the files somewhere for all sub-processes to read from.

**Comment by fvictorio** [comment]
I'm not sure I understand the issue though. A path that starts with `.` _is_ relative, isn't it?

**Comment by fvictorio** [comment]
Oh, I see now. You are getting an error like this?

```
Error HH1001: Invalid source name .contracts/Foo.sol. Expected source name but found an absolute path.
```

If that's the case, I agree we should consider this a bug.

**Comment by fubhy** [comment]
> Oh, I see now. You are getting an error like this?
> 
> ```
> Error HH1001: Invalid source name .contracts/Foo.sol. Expected source name but found an absolute path.
> ```
> 
> If that's the case, I agree we should consider this a bug.

Yes exactly. It currently just checks if the first character is a `.`. It should whether it's `./` or JUST `.`. So something like `path.startsWith('./') || path.startsWith('../') || path === '.'`
