### ISSUE TITLE
bug: resolving `hardhat/console.log` fails if there's a directory named `hardhat` in scope

### ISSUE THREAD

**Issue by fubhy** [nomiclabs/hardhat#998]
If e.g. you have a `hardhat` directory at the root of your project, you can't import `hardhat/console.log` anymore. It just stops looking for the file. Node module resolution would continue the path lookup scheme by further walking up the directory tree (also looking into all parent `node_modules/` directories along the way). I think hardhat import resolution should follow that same behavior.

**Comment by fvictorio** [comment]
Can confirm, thanks @fubhy!
